### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by profigriller** [dresden-elektronik/deconz-rest-plugin#5033] opened 2021-06-18 17:58 UTC
## Device

    Product name: PARKSIDE Smart Watering Timer PSBZS A1
    Manufacturer: _TZE200_htnnfasr
    Model identifier: TS0601.
    Device type :
        Other: Smart watering timer

## Screenshots

Device seems to work but does not update status

![grafik](https://user-images.githubusercontent.com/12680457/122599705-10fe9880-d06f-11eb-93e5-7e033e788a88.png)

### Basic

![grafik](https://user-images.githubusercontent.com/12680457/122599606-ef9dac80-d06e-11eb-9d4c-38cc4822333f.png)

### Identify
![grafik](https://user-images.githubusercontent.com/12680457/122599655-00e6b900-d06f-11eb-9906-b9a3518e7b91.png)

### Groups
![grafik](https://user-images.githubusercontent.com/12680457/122599741-1c51c400-d06f-11eb-9073-b3af6894cd3d.png)
![grafik](https://user-images.githubusercontent.com/12680457/122599785-2c69a380-d06f-11eb-8d5e-7fb118ebfcdf.png)

### Scenes
![grafik](https://user-images.githubusercontent.com/12680457/122599817-368ba200-d06f-11eb-899b-c91c19550f40.png)
![grafik](https://user-images.githubusercontent.com/12680457/122599822-3a1f2900-d06f-11eb-9777-433e48dd555f.png)
![grafik](https://user-images.githubusercontent.com/12680457/122599834-3e4b4680-d06f-11eb-8678-f7b5ba02694d.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/12680457/122599844-42776400-d06f-11eb-85dc-745016244506.png)
![grafik](https://user-images.githubusercontent.com/12680457/122599854-46a38180-d06f-11eb-8cbb-ba670754c454.png)

### Other clusters that are not mentioned above
![grafik](https://user-images.githubusercontent.com/12680457/122599887-53c07080-d06f-11eb-8b58-35092eba690e.png)
![grafik](https://user-images.githubusercontent.com/12680457/122599918-5d49d880-d06f-11eb-9b0c-66d24a77da08.png)
![grafik](https://user-images.githubusercontent.com/12680457/122599935-633fb980-d06f-11eb-803f-153e7bf5c509.png)

**Comment by SwoopX** [comment] 2021-06-18 18:30
Duplicate of #4958

**Closed by SwoopX** 2021-06-18 18:30 UTC
Labels: Device Request, Duplicate
