### ISSUE TITLE
Pairing HUE Smart Button

### ISSUE THREAD

**Issue by vantino** [dresden-elektronik/deconz-rest-plugin#2436] opened 2020-02-11 10:13 UTC
Ciao

I'm struggeling to pair the phillips smart button on my current deconz version 2.05.66 running on a pi3.

Does the 2.05.66 know that new device?
The device reset works, but is not being recogniced. 

Apreciate a any help.

Thanks
Vantino

**Comment by carpii** [comment] 2020-02-27 19:32
Duplicate of #2077

**Comment by Mimiix** [comment] 2020-06-05 11:19
As @carpii said, its a duplicate. #close

**Closed by Mimiix** 2020-06-05 11:19 UTC
