### ISSUE TITLE
Linkind water leak sensor

### ISSUE THREAD

**Issue by nmr94** [dresden-elektronik/deconz-rest-plugin#6177] opened 2022-07-06 22:59 UTC
Requesting support for this device. thanks!

## Device type :
Sensor: Leak sensor

### Basic
![134370727-109bc232-1ce5-4ae0-bd84-c274de67df1f](https://user-images.githubusercontent.com/85526412/177656821-04afdea2-7192-44d0-9564-45e92b454928.png)

### Identify
![134370836-fecd2c07-a282-4448-a13f-833f77bee7ce](https://user-images.githubusercontent.com/85526412/177656844-cbeb4e4d-804b-44ec-a3c1-038bd9fa2e28.png)

### Alarms
NA

### Device Temperature
NA

### Groups
na

### Scenes
na

### On/Off
na

### Level Control
na

### Color Control
na

### Simple Metering
na

### Diagnostics
![134372234-068a51a1-9ab6-4de7-bcdb-0188dc0659d9](https://user-images.githubusercontent.com/85526412/177656884-4c22f0bf-d1ed-497b-b084-f070d0f802c7.png)

### Other clusters that are not mentioned above
![134371840-291144e5-6ce5-4399-9c5c-b33f5422f58b](https://user-images.githubusercontent.com/85526412/177656974-ed861304-6000-4c89-a962-6b02cb4cdf54.png)
![134372564-409c9784-0e5c-48a7-97d4-2c009d292ae4](https://user-images.githubusercontent.com/85526412/177656977-2c4d82a6-2ac6-416b-8191-e076a2ca18e8.png)
![134372080-067105d2-7e03-4baf-8dae-9f35cbf24d13](https://user-images.githubusercontent.com/85526412/177656978-074d24a3-561e-48c1-b308-abd027b1f31d.png)
![134371986-ec13009c-d741-4d2a-8483-97d75e2d49a0](https://user-images.githubusercontent.com/85526412/177656981-85fbc0bb-975f-4115-9e4e-0d35eaad7973.png)
![134371447-1cacf4de-a1ae-4b28-87b2-bb430c7d3e6f](https://user-images.githubusercontent.com/85526412/177656982-dfa6d231-17fa-4bab-ab6d-0efdc97b1810.png)

**Comment by Mimiix** [comment] 2022-07-07 04:47
Closing as  this is a duplicate of #5317

**Closed by Mimiix** 2022-07-07 04:47 UTC
Labels: Device Request
