### ISSUE TITLE
[Device Support Request] Mi Smart Plug (add Wattmeter)

### ISSUE THREAD

**Issue by Ridchi1980** [dresden-elektronik/deconz-rest-plugin#2653] opened 2020-04-04 18:42 UTC
Hello, can someone incorporate the output for power in watts and the consumption in kwh?
I can connect the Smart Plug, but only switch on / off.

![grafik](https://user-images.githubusercontent.com/50925972/78458757-106d2280-76b4-11ea-9f3a-39434bf297a0.png)

01 HA : 0000 BASIC
![grafik](https://user-images.githubusercontent.com/50925972/78458815-925d4b80-76b4-11ea-94ee-2f34d33a27e3.png)

15 HA : 000C  --> Present value = Watt
![grafik](https://user-images.githubusercontent.com/50925972/78458772-3abee000-76b4-11ea-944a-359f391ce44a.png)

16 HA:  000C  --> Present value = kwh
![grafik](https://user-images.githubusercontent.com/50925972/78458794-6772f780-76b4-11ea-8ee2-b66800860493.png)

thanks Ridchi

**Comment by SwoopX** [comment] 2020-04-04 18:57
Duplicate of #2583.

**Closed** 2020-04-04 20:29 UTC
