### ISSUE TITLE
BW-SHP15 _TZ3000_mraovvmm suddenly stopped measuring

### ISSUE THREAD

**Issue by SebLz** [dresden-elektronik/deconz-rest-plugin#6352] opened 2022-09-24 20:15 UTC
## Describe the bug
After about 6 monthes of good services, one of my BW-SHP15 plug stopped measuring power and consumption. The consumption counter is not increasing anymore, power and voltage are always 0 even though the plug itself correctly delivers power to the load (I've been using it to charge an hybrid car (2000+ W under load)). I tried to unpair, then pair again with no effect. Could this be a hardware issue ?

## Screenshots

![image](https://user-images.githubusercontent.com/190146/192116568-397a015c-2525-4fbf-85ad-ba45713417b7.png)
![image](https://user-images.githubusercontent.com/190146/192116578-95910036-2ef4-4f55-a331-423f4bb9fd68.png)
![image](https://user-images.githubusercontent.com/190146/192116591-4d6d9266-c727-43db-b8ea-f1ceda83923c.png)

## Environment

 - Host system: NUC
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: (26720700)
 - deCONZ version: (2.18.02)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes)
 - Is there any other USB or serial devices connected to the host system? Yes bluetooth gongle

**Comment by Mimiix** [comment] 2022-09-24 20:48
Hi,

Do you have more of these which also have the same manufacturer name?

**Comment by SebLz** [comment] 2022-09-24 20:52
> 

Hello, yes I have 3 others that still work fine

**Comment by Mimiix** [comment] 2022-09-25 08:33
Hi,

In that case I am closing this issue as this is not a bug report as described in #5113. Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-09-25 08:33 UTC
Labels: Bug report
