### ISSUE TITLE
IKEA Styrbar remote control - left and right buttons don't work

### ISSUE THREAD

**Issue by adrspa** [dresden-elektronik/deconz-rest-plugin#6980] opened 2023-05-15 21:16 UTC
Setup
ConBee 2 connected to RPi 4 running HA
IKEA Strybar running 2.4.5 FW
Deconz v2.21.2
HA 2023.5.3
Supervisor 2023.04.1
Operating System 10.1

Issue
IKEA Styrbar remote control can be paired in Phoscon and is visible in deconz, but only the dim up and dim down buttons work. The left and right buttons don't generate any events, even directly in deconz. 

![Skärmklipp](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12691848/cb7b2759-5756-4b45-9c97-dcdd7b7b365f)

Any help would be greatly appreciated!

Best regards,
Adrian

**Comment by BabaIsYou** [comment] 2023-05-15 22:58
Seem duplicate of #6761

**Comment by Mimiix** [comment] 2023-05-16 04:04
Yep, and template not used.

Closing.

**Closed by Mimiix** 2023-05-16 04:04 UTC

**Comment by adrspa** [comment] 2023-05-16 18:30
Hi,

Sorry for not following the template. Wasn't aware there was one as this was my first post in this forum. I'll take a look at #6761, thanks.

Best regards,
Adrian
