### ISSUE TITLE
IKEA Tradfri Shortcut Button E1812

### ISSUE THREAD

**Issue by Zehir** [dresden-elektronik/deconz-rest-plugin#4068] opened 2020-12-31 13:10 UTC
## Device

- Product name: Tradfri Shortcut Button E1812
- Manufacturer: IKEA of Sweden
- Model identifier: TRADFRI SHORTCUT Button
- Device type : 
  - Switch
- [Product detail](https://www.ikea.com/dk/da/p/tradfri-genvejskontakt-hvid-40356381/)

## Screenshots

Edit : I clicked read on each tab but most of the values are still at 0.

![image](https://user-images.githubusercontent.com/845225/103411542-e5dfc580-4b70-11eb-8275-a66a71b20dd8.png)
![image](https://user-images.githubusercontent.com/845225/103411564-fa23c280-4b70-11eb-994b-ef0c40d6d07f.png)
![image](https://user-images.githubusercontent.com/845225/103411582-0e67bf80-4b71-11eb-94b8-f2f6d5628b77.png)
![image](https://user-images.githubusercontent.com/845225/103411586-158ecd80-4b71-11eb-9b88-4ba37631850a.png)
![image](https://user-images.githubusercontent.com/845225/103411591-1cb5db80-4b71-11eb-9bf0-5c4318c0e42c.png)
![image](https://user-images.githubusercontent.com/845225/103411594-23445300-4b71-11eb-8047-3ec43021772e.png)
![image](https://user-images.githubusercontent.com/845225/103411609-2d665180-4b71-11eb-9769-128f0b37ffca.png)
![image](https://user-images.githubusercontent.com/845225/103411618-3525f600-4b71-11eb-85b9-570a0285ee41.png)

**Comment by Mimiix** [comment] 2020-12-31 13:18
Closed. Duplicate of #3373

**Closed by Mimiix** 2020-12-31 13:18 UTC
Labels: Device Request

**Comment by Zehir** [comment] 2020-12-31 13:26
Duplicate of #3495
