### ISSUE TITLE
Bindings - Documentation?

### ISSUE THREAD

**Issue by xxLeoxx93** [dresden-elektronik/deconz-rest-plugin#6006] opened 2022-05-02 19:09 UTC
## Describe the bug
Hey all,

I'm trying to bind my Fyrtur remote with the with the blind unsing the "Bind Dropbox".
From my understanding this should make the remote work as it was shipped.
But no matter what I bind - there's no reaction and no indication if it worked or not (or why not).
Undforunatly the documentation for this is not even one page long so I don't know how to debug this.

Is there anyone using the blinds without these issues? As of now there are pretty much unusable for me.
Thanks!

## Steps to reproduce the behavior
Try follow the documentation on the bindings and you'll see :)

## Expected behavior
A somewhat complete documentation of how the binding works.

## Screenshots
![image](https://user-images.githubusercontent.com/61089790/166309424-30c90eff-bbdb-4ef9-b0be-7e32f4d03bb1.png)

I tried to drag the 0006 ON/Off field from the switch to the source and the "0102 Window Covering" as a destionation - > No reaction at all...

## Environment
 - Host system: Raspberry Pi
 - Running method:  Docker container
 - Firmware version: 26720700
 - deCONZ version: 2.15.03 / 21.4.2022
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
None.
## Additional context
None.

**Comment by Mimiix** [comment] 2022-05-02 20:05
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Feel free to open an topic on the forum.

Kind regards,

**Closed by Mimiix** 2022-05-02 20:05 UTC
Labels: Bug report
