### ISSUE TITLE
Require API returns unauthorized user

### ISSUE THREAD

**Issue by adisdelalic** [dresden-elektronik/deconz-rest-plugin#4063] opened 2020-12-30 14:36 UTC
Hi

Require API has been working for some time. Now I reinstalled my raspberry pi including deconz.

Now, Require API for my raspbee shield and body raw as here : {"devicetype" : "Raspi II"} returns the error below
{
"error": {
"address": "/",
"description": "unauthorized user",
"type": 1
}

## Steps to reproduce the behavior
1. postman 192.168.0.37:8000/api and raw body {"devicetype" : "Raspi II"}
2. click on enter / send
3. down to response
4. observe 

## Expected behavior
that response returns API key

## Screenshots
![image](https://user-images.githubusercontent.com/40169917/103357820-61c80800-4ab4-11eb-9546-691498bb0001.png)

## Environment
Firmware 26610700

 - Host system: Raspberry Pi 
 - Running method: Raspbian / Open HAB deCONZ Add-on 
 - Firmware version: 26610700
 - deCONZ version: 2.07.01 / 08/12/2020
 - Device: (RaspBee II)
 - No cable
 - No USB

**Comment by Mimiix** [comment] 2020-12-30 15:52
This is not a bug report, but a user question. Please follow the templates and use them correctly. 

Clearly you are not following the documentation: https://dresden-elektronik.github.io/deconz-rest-doc/getting_started/

You are doing a get request, but the documentation shows you have to do a post.

Closing.

**Closed by Mimiix** 2020-12-30 15:52 UTC
Labels: User Question
