### ISSUE TITLE
IKEA SYMFONISK sound remote gen2 not pairing

### ISSUE THREAD

**Issue by Recte** [dresden-elektronik/deconz-rest-plugin#7163] opened 2023-08-12 19:17 UTC
## Describe the bug
I've seen some (development) activity in the SYMFONISK Gen2 and seen it in the [change log at 2023-03-17, TikTak beta](https://phoscon.de/en/changelog/). I however don't see it in the [Supported Devices](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices). I tried to pair my brand new ones as a 'Tradfri' remote control and as dimmer, but without success. My gateway is running on version 2.22.02 and firmware 26720700.

Since all issues are closed, but I do see some confusing messages in the thread below them, I wonder if the SYMFONISK Gen2 is yet supported or not. If supported, is there a special approach to get them paired?

## Steps to reproduce the behavior
  1. Physically turn off/unplug IKEA devices (Bulbs and Power Outlets) close to the Conbee2 stick, since the SYMFONISK Gen2 tends to pair with that device. If that happens, it's unavailable in Phoscon and you have to pair it again.
  2. Click within HomeAssistant on deConz and choose  Phoscon.
  3. Click on the hamburger menu at the left top and pick Switches under Devices
  4. Click add new switch and choose IKEA
  I tried 'Remote control' and 'Dimmer' holding the SYMFONISK Gen2 very close to the dongle.

When it connects to a bulb or outlet, the led lights up and flashes shortly. While holding it next to the Conbee2 dongle, it does nothing.

## Expected behavior
  I'd expect it to light up and flash, resulting in a new switch in the list of switches in Phoscon.

### Phoscon 
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26491601/5b67ed0c-dc89-4475-920b-7aab6b076fb3)

### deCONZ
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26491601/5603f0bb-5a4d-45c6-b97b-b9c45de1829a)

 - Host system: Raspberry Pi 4 8GB
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26720700
 - deCONZ version: 2.22.2
 - Device: ConBee II
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system?
 Yes, USB3 SSD which cannot be removed since it's the boot-disk, but there is no general issue. Other stuff works fine.

## deCONZ Logs
Let me know if relevant

**Comment by Mimiix** [comment] 2023-08-12 19:36
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Please use the forums for this request.

Kind regards,
Dennis

**Closed by Mimiix** 2023-08-12 19:36 UTC
Labels: Bug report
