### ISSUE TITLE
device state timeout ignored in state 3

### ISSUE THREAD

**Issue by adrianmihalko** [dresden-elektronik/deconz-rest-plugin#5723] opened 2022-01-28 16:57 UTC
## Describe the bug

In log I have full of warning device state timeout ignored in state 3. I have not found any information about this.

```
16:41:05:641 DEV Tick.Init: booted after 8000 seconds
16:41:07:188 Device firmware version 0x26660700 ConBee II
16:41:07:191 unlocked max nodes: 512
16:41:07:246 Device protocol version: 0x010C
16:41:07:300 Current channel 15
16:41:07:314 CTRL ANT_CTRL 0x03
16:41:07:337 Device protocol version: 0x010C
16:41:07:389 CTRL ANT_CTRL 0x03
[16:41:07] INFO: Successfully send discovery information to Home Assistant.
16:41:12:649 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26720700.bin.GCF
16:41:12:649 GW firmware version is up to date: 0x26720700
16:41:17:324 device state timeout ignored in state 3
16:41:31:740 Bind response success for 0x000d6ffffe9e108f ep: 0x01 cluster: 0x0000
16:41:31:839 ZCL configure reporting rsp seq: 1 0x000D6FFFFE9E108F for ep: 0x01 cluster: 0x0000 attr: 0x4000 status: 0x00
16:41:35:156 device state timeout ignored in state 3
16:41:35:316 device state timeout ignored in state 3
16:41:35:476 device state timeout ignored in state 3
16:41:35:636 device state timeout ignored in state 3
16:41:35:797 device state timeout ignored in state 3
16:41:35:956 device state timeout ignored in state 3
6:41:52:149 ZCL attribute report 0x00158D0001643EB2 for cluster: 0x0400, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
16:41:52:157 ZCL attribute report 0x00158D0001643EB2 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
16:41:52:648 Set sensor check interval to 100 milliseconds
16:41:52:741 Bind response success for 0x000d6ffffe9e108f ep: 0x01 cluster: 0x0000
16:41:55:733 device state timeout ignored in state 3
16:41:56:665 Device TTL 1358 s flags: 0x7
...
16:49:43:508 ZCL attribute report 0x00158D00027D8E39 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
16:49:43:508 0x00158D00027D8E39 extract Xiaomi special attribute 0xFF01
16:49:43:509 	01 battery 3045 (0x0BE5)
16:49:43:509 	03 Device temperature 27 °C
16:49:43:509 	04 unknown 17320 (0x43A8)
16:49:43:509 	05 RSSI dB (?) 1194 (0x04AA)
16:49:43:509 	06 LQI (?) 4294967296 (0x0100000000)
16:49:43:509 	0a Parent NWK 0 (0x0000)
16:49:43:510 	97 unknown 0 (0x0000)
16:49:43:510 	98 unknown 0 (0x0000)
16:49:43:510 	99 unknown 0 (0x0000)
16:49:43:510 	9a unknown 4 (0x0004)
16:49:47:228 device state timeout ignored in state 3
16:49:47:388 device state timeout ignored in state 3
16:49:47:549 device state timeout ignored in state 3
16:49:47:709 device state timeout ignored in state 3
16:49:47:868 device state timeout ignored in state 3
16:49:48:028 device state timeout ignored in state 3
16:49:56:663 Device TTL 877 s flags: 0x7
16:49:57:282 ZCL attribute report 0x00158D0001643EB2 for cluster: 0x0400, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
16:49:57:290 ZCL attribute report 0x00158D0001643EB2 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
16:49:57:661 Set sensor check interval to 100 milliseconds
16:50:08:228 device state timeout ignored in state 3
16:50:56:228 device state timeout ignored in state 3
16:50:56:669 Device TTL 817 s flags: 0x7
...
17:41:04:420 device state timeout ignored in state 3
17:41:04:580 device state timeout ignored in state 3
17:41:06:161 ZCL attribute report 0x00158D0001643EB2 for cluster: 0x0400, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
17:41:06:176 ZCL attribute report 0x00158D0001643EB2 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
17:41:12:685 Device TTL 2780 s flags: 0x7
17:41:17:272 device state timeout ignored in state 3
17:41:20:317 device state timeout ignored in state 3
17:41:36:732 device state timeout ignored in state 3
17:41:39:732 device state timeout ignored in state 3
```

## Environment

<img width="755" alt="Screenshot 2022-01-28 at 17 47 41" src="https://user-images.githubusercontent.com/733361/151587569-d03d43ce-adf3-4d27-80a6-0e6dc10c07f0.png">

<img width="831" alt="Screenshot 2022-01-28 at 17 47 21" src="https://user-images.githubusercontent.com/733361/151587529-ac3dd58c-7a92-4a91-83c0-e5736cd05b21.png">

 - Host system: PC
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26720700)
 - deCONZ version: (2.13.4)
 - Device:ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment] 2022-01-28 17:09
Hi,

As this is not a bug report as described in #5113, I am closing this issue.

Feel free to open an topic on the forum.

Kind regards
Dennis

**Closed by Mimiix** 2022-01-28 17:09 UTC
Labels: Bug report
