### ISSUE TITLE
Add touchlink support on conbee II

### ISSUE THREAD

**Issue by zoic21** [dresden-elektronik/deconz-rest-plugin#3485] opened 2020-10-23 12:18 UTC
## Feature request type

 Can you add touchlink support on conbee II like conbee I ?

## Description

In conbee I we can make reset off touchlink device but it's not possible on conbee II, can you re-add this feature ?

**Comment by MattWestb** [comment] 2020-10-23 12:25
Please also for RaspBee II need this funktion for working with lights and the great working old web app.

**Comment by Larsn1** [comment] 2020-10-24 08:04
That would be great

**Comment by JakobTewes** [comment] 2021-01-07 21:34
would love that too ;-)

**Comment by JakobTewes** [comment] 2021-01-07 21:42
Found [this issue](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/337), in which someone states, that LivingColors or TouchLink inclusion is not possible.
Seems to have something to do with philips proprietary protocol and missing encryption keys...

**Comment by srtxema** [comment] 2021-01-13 12:47
+1

**Comment by manup** [comment] 2021-01-14 18:17
The Touchlink support for ConBee II / RaspBee II is on the back log, it doesn't have a priority and ETA yet since we currently focus on fixing and improving other parts which are considered more urgent.

Touchlink is mostly useful for Hue mains powered devices since these don't provide a reset sequence. As workaround the Hue Dimmer switch can be used to send the reset command — this has also the benefit of being mobile, so the light doesn't need to be near the gateway.

**Comment by SteGe88** [comment] 2021-01-28 14:21
+1 went through a lot of trouble to get my Living Color connected to mijn ConBee II, before I saw that the touchlink function is not working on the Conbee II.

**Comment by klodeckl** [comment] 2021-01-30 22:45
+1

I have this plug: https://www.amazon.de/Philips-6916531PH-Living-Whites-Leuchten-Adapter/dp/B005ER7MX2
I think it also uses touchlink, right?
I want to buy a Conbee 2, but need that feature.
Do I also need it for Phlips Hue Iris and Bloom?

**Comment by Smanar** [comment] 2021-01-31 09:38
IDK for this device, but for me, if you have philips stuff, the only method that work at 100% is the touchlink feature, but you can too just buy a philips remote to do that.

**Comment by JT089** [comment] 2021-01-31 09:45
@Smanar, did you get (for example the wallplug, @klodeckl mentioned) the „pre-hue“ stuff to work with phoscon via touchlink remote? jow did you include the remote?

**Comment by ebaauw** [comment] 2021-01-31 09:56
You guys are mixing two things: touchlink search/reset vs touchlink linking.
- Touchlink reset, as the name suggests factory-resets a Zigbee device over touchlink.  This is supported by deCONZ, and by the REST API plugin for the RaspBee and ConBee.  As Manuel indicates, it’s on the backlog to add support for the RaspBee II and ConBee II.  I wouldn’t expect support in Phoscon before that;
- The first-generation pre-Hue Philips Living Color and Living White devices don’t support Zigbee ZLL nor ZHA in full.  Note that these devices are over 10 years old; this does **not** apply to any Hue-branded version.  In particular, they don’t support joining a Zigbee network the regular way.  They could be touchlink-paired to the Hue bridge, using the included remote, similar to how the Trådfri hub needs a controller to pair lights.  deCONZ does **not** support touchlink pairing, and afaik there are no plans to change that.

**Comment by Smanar** [comment] 2021-01-31 12:29
>The first-generation pre-Hue Philips Living Color and Living White devices don’t support Zigbee ZLL nor ZHA in full. Note that these devices are over 10 years old; this does not apply to any Hue-branded version. In particular, they don’t support joining a Zigbee network the regular way. They could be touchlink-paired to the Hue bridge, using the included remote, similar to how the Trådfri hub needs a controller to pair lights. deCONZ does not support touchlink pairing, and afaik there are no plans to change that.

Right, sorry I m reading the manual of the plug, nothing about the touchlink RESET, reproducible with the philips remote.

**Comment by readych** [comment] 2021-02-05 13:09
+1

**Comment by cskowronnek** [comment] 2021-03-06 15:56
+1

**Comment by systemcrash** [comment] 2021-03-26 16:09
+1 pretty pleazzzeeeee 

> The Touchlink support for ConBee II / RaspBee II is on the back log, it doesn't have a priority and ETA yet since we currently focus on fixing and improving other parts which are considered more urgent.
> 
> Touchlink is mostly useful for Hue mains powered devices since these don't provide a reset sequence. As workaround the Hue Dimmer switch can be used to send the reset command — this has also the benefit of being mobile, so the light doesn't need to be near the gateway.

Hmm - if I cannot connect my Hue device to the ConBee2 in the first place, it seems that a reset sequence is more important than other functionality. Don't have a Hue Dimmer at hand... ☹️ 

Arrived here via [old forum thread](https://community.smartthings.com/t/dr-hue-is-in-and-the-bulbs-are-back-reset-hue-bulbs-to-factory/9856/7). I assumed that if the first iteration of the devices had this, then surely the second iteration would.


Is this touchlink process the same as this?:

https://www.nxp.com/docs/en/user-guide/JN-UG-3115.pdf#G17.1050870

**Comment by systemcrash** [comment] 2021-03-26 16:10
Or wait - is Touchlink init just a command sequence for the CB2?

**Comment by Dreaming-Codes** [comment] 2021-07-21 22:34
I would absolutely love that

**Comment by systemcrash** [comment] 2021-08-16 22:40
Arrived here again and see that I already wrote on this issue 😆 

But, please, being able to reset one's lights is important, no?

**Comment by Mimiix** [comment] 2021-08-17 11:53
https://forum.phoscon.de/t/feature-request-touchlink-support-on-conbee-ii/340

Created a feature request on it for the forum :)

**Comment by systemcrash** [comment] 2021-08-18 15:26
@Mimiix - could you ask that the request is to implement in the conbee2 firmware, as a start. The CB2 are in use all over the place outside of deconz stuff, so I don't mind testing and using without waiting for it to be implemented elsewhere.

**Comment by systemcrash** [comment] 2022-01-19 20:56
Any update on this feature request?

**Comment by Superzite** [comment] 2022-02-14 18:58
any update ?

**Comment by mcsrobert** [comment] 2022-05-07 14:02
I also want this feature for my ConBee II.

**Comment by Et3rnel** [comment] 2022-08-19 14:14
I also would like to reset my Philips devices with Touchlink reset from my ConBee 2 ! 🙏🏻
Any progess on this feature request ?

**Comment by dave-sausages** [comment] 2022-09-10 16:03
+1 for the feature request

**Comment by Bejjje** [comment] 2022-09-23 11:07
Give us please

**Comment by cedricnet** [comment] 2022-12-22 23:12
Would be quite interested in the touchlink feature on raspbee II, useful for old philips living colors lamps.

**Comment by Smanar** [comment] 2022-12-23 17:01
No return on my side, faster to use the remote for that for the moment.

**Comment by bitfl0wer** [comment] 2023-10-10 20:19
> Would be quite interested in the touchlink feature on raspbee II, useful for old philips living colors lamps.
> 
> Is there any ETA now?

Afaik this exists on the RaspBee 2.

**Comment by systemcrash** [comment] 2024-04-04 13:15
*sigh*

**Comment by cedricnet** [comment] 2024-04-05 16:25
I bought a raspbee II and I can’t neither command old Philips living Colors
with it :-(

**Comment by Smanar** [comment] 2024-04-05 17:37
The remote is not working to reset them ?

**Comment by systemcrash** [comment] 2024-04-05 17:38
What remote 😉

**Comment by ebaauw** [comment] 2024-04-06 08:07
deCONZ doesn’t support device pairing over touchlink, not even on the original RaspBee and ConBee.  The old, pre-Hue Philips Living Colors (and Living White) lights and remotes do not work, and will not work with deCONZ.

deCONZ does support device discovery and reset over touchlink, but only on the original RaspBee and ConBee, as later devices lack firmware support for this.  This is an ancient feature, exposed only through the old web app.  Note that this feature is only useful, if the device is close enough (< 2m) to the RaspBee or ConBee.  You might need to power the Raspberry Pi with the RaspBee from a power bank, or use a 5m USB extension cable for the ConBee.

Note that not all devices support reset over touchlink.  And if they do, only for a short period after powering on.  I’ve only ever needed this for Hue lights, since they cannot be reset through some power on sequence.
You can issue a reset over touchlink, using a Hue dimmer switch.  Hold the On/Off and Hue buttons (On and Off buttons on the old model) for 10s, with the dimmer close (< 10cm) to the light.  Be patient and continue to hold when the light starts reacting, until it remains steady at full brightness.

**Comment by systemcrash** [comment] 2024-04-06 17:32
Yep, and that's what people in this thread are asking for in the conbee 2 firmware, likely because they don't have those remotes. I haven't.

**Comment by Mimiix** [comment] 2024-04-08 11:37
Hi guys,

I am closing the issue here, as we stopped collecting Feature requests on the Github and moved those to the forums (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5113). 

The forum version can be found here, with a response of Manup: https://forum.phoscon.de/t/feature-request-touchlink-support-on-conbee-ii/340/5

Please proceed this feature request there :)

Closing and locking.

**Closed by Mimiix** 2024-04-08 11:37 UTC
Labels: Feature Request
