### ISSUE TITLE
Assistance Needed with Pairing Aqara Curtain Driver E1 with ConBee 2/deCONZ

### ISSUE THREAD

**Issue by G4rgoz3r** [dresden-elektronik/deconz-rest-plugin#7355] opened 2023-11-14 18:56 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hello Community,

I’m facing a challenging issue with pairing the Aqara Curtain Driver E1 Track version (CM-M01 (lumi.curtain.agl001) with my deCONZ setup. Despite numerous attempts and ensuring all my systems are updated, the device simply won’t pair with deCONZ.

I’m aware that others in the community have faced similar issues, ranging from partial functionality to incorrect device recognition. If anyone has successfully resolved the pairing issue or found a workaround to integrate the Aqara Curtain Driver E1 with deCONZ, your advice would be invaluable.

Thank you in advance for any tips or solutions you can provide. Your assistance could be a significant help in overcoming this obstacle in my smart home setup.

Best regards,
Nick

### Steps to reproduce the behavior

1. Go to Phoscon app in browser
2. Then go to blinds 
3. Start pairing in the phoscon
4. Start pairing the curtain driver by pressing the button for 5 secs

### Expected behavior

When pairing the device it should appear in Phoscon. However nothing happens.

### Screenshots

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/142296442/1b24f5b5-db94-4257-9bf3-053544693bfc)

### Environment

- Host system: Synology NAS
- Running method: deCONZ community Docker container 
- Firmware version: 26780700
- deCONZ version : 2.24.1
- Device: ConBee II
- Do you use an USB extension cable: Yes
- Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment] 2023-11-14 19:41
Hi

As this is not a bug as described in #5113, I am closing this issue.

Feel free to ask on the forums.

**Closed by Mimiix** 2023-11-14 19:41 UTC
Labels: Bug report
