### ISSUE TITLE
Phoscon App not reporting status of all lights after migration

### ISSUE THREAD

**Issue by DarkOrbit1** [dresden-elektronik/deconz-rest-plugin#5489] opened 2021-11-14 15:21 UTC
## Describe the bug
Some time ago I had deCONZ running on a Home Assistant OS installation. Everything worked until the SD-card gave up.
I was able to rescue the database file (zll.db) and decided to go with the stable release from here https://phoscon.de/en/conbee/sdcard .
Setting everything up and just replacing the zll.db file seems to have every device show up in the deCONZ GUI and connections light up for all expected devices. Switches are also able to control the lights which were configured before the SD-card crash.

Now, all of the Zigbee dimmers (Philips | ZG9101SAC-HP), appears as disconnected (not reachable?) in the Phoscon App and cannot be controlled from the Phoscon App, except pressing 'All off' which actually turns everything off. I have a TRÅDFRI switch which works properly and can be controlled without issues.
I tried integrating with a Home Assistant installation (from another machine) and this still shows the issue with the light reporting as off/disconnected. However from the Home assistant installation I am able to turn the lights on, but the status is reported as off a few moments later. I'm also able to control the dimmer level without issue but the light is still reported as off. The TRÅDFRI switch is reporting it's status and works as expected in HA.

## Steps to reproduce the behavior
Try to turn on one of the dimmable lights from within the Phoscon App.

## Expected behavior
Able to turn on (and off) the lights from within the Phoscon App as well as see the lights current status.

## Screenshots

![](https://user-images.githubusercontent.com/5033351/141686494-eaeaa38e-e1d4-46a4-85d3-34caa272e0c1.png)

![](https://user-images.githubusercontent.com/5033351/141686527-5c418e69-beef-4fe9-8d61-fd5aca824153.png)

## Environment
Raspberry Pi 4B with stable image from https://phoscon.de/en/conbee/sdcard
Environment
![](https://user-images.githubusercontent.com/5033351/141686916-1335bd63-c3c4-4c79-b0bd-ea3ce25b6ee7.png)
ConBee I, firmware 26400500
deCONZ (2.12.06 / 2021-08-19)

**Comment by Mimiix** [comment] 2021-11-14 16:16
Hi,

As this is not a bug report as described in #5113, I am closing this issue. Feel free to open an topic on the forum.

Kind regards,

**Closed by Mimiix** 2021-11-14 16:16 UTC
Labels: Bug report
