### ISSUE TITLE
xiaomi vibration sensor does not work

### ISSUE THREAD

**Issue by jjdave2002** [dresden-elektronik/deconz-rest-plugin#5678] opened 2022-01-17 18:56 UTC
## Describe the bug
After update to new firmware of Conbee II to _0x26720700
Xiaomi vibration sensor does no longer update it's status in deConz Software and no information sent to Homeassistant.
No change in behaviour after resetting and/or re-boot and even reconnect to the system.

## Steps to reproduce the behavior
it's reproducable, see above

## Expected behavior
see above, no update of the sensor either in Deconz App nor in Homeassistant

## Environment

 - Host system: Raspberry Pi 
 - Running method: Home Assistent deCONZ Add-on 
 - Firmware version: (_0x26720700)
 - deCONZ version: (2.13.04)
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: no

## deCONZ Logs

-->

**Comment by Mimiix** [comment] 2022-01-17 19:17
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-01-17 19:17 UTC
Labels: Bug report
