### ISSUE TITLE
Please support for Philips Hue bulb firmwareoption “Last Known State”  (in latest Hue Bulb firmware)

### ISSUE THREAD

**Issue by carver7** [dresden-elektronik/deconz-rest-plugin#1825] opened 2019-09-06 05:19 UTC

**Comment by manup** [comment] 2019-09-06 07:10
Duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1826

**Closed by manup** 2019-09-06 07:10 UTC
