### ISSUE TITLE
Devices disconnected

### ISSUE THREAD

**Issue by Nazarbayevv** [dresden-elektronik/deconz-rest-plugin#6534] opened 2022-11-14 22:19 UTC
## Describe the bug
<I migrated my devices to up to date Raspbian OS via backup option in Phoscon. And it works about 1 mounth without any issues. But last 3 days in the evening is something wrong. I can not manage my devices (turn on. turn off lights, treceive statuss from my sensors etc) and at this time I can see usual map, reacheble status in Phoscon (not grey) and when I try turn on lights from Node Red I can see changes in Phoscon, but lights does not turn on:
![image](https://user-images.githubusercontent.com/50654913/201780039-9c02bd57-b4ad-4f13-85a9-2b52bbc7be98.png)

I should reboot my Raspberry for resolve issue. 
>

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26400500
 - deCONZ version: (2.19.01)
 - Device: RaspBee I
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Sonoff zigbee (I use second zigbee network(zigbee2mqtt) with other channel)

## deCONZ Logs
  23:58:19:516 APS prevent duplicate req id: 62
23:58:21:260 APS prevent duplicate req id: 70
23:58:25:512 APS prevent duplicate req id: 88
23:58:27:012 APS prevent duplicate req id: 95
23:58:28:010 APS prevent duplicate req id: 100
23:58:32:160 reject aps request queue is full (25)
23:58:32:510 APS prevent duplicate req id: 120
23:58:33:763 APS prevent duplicate req id: 126
23:58:37:010 APS prevent duplicate req id: 140
23:58:37:617 APS prevent duplicate req id: 143
23:58:39:510 APS prevent duplicate req id: 152
23:58:41:510 APS prevent duplicate req id: 161
23:58:47:510 APS prevent duplicate req id: 186
23:58:48:510 APS prevent duplicate req id: 191
23:58:50:010 APS prevent duplicate req id: 198
23:58:50:510 APS prevent duplicate req id: 201
23:58:50:510 APS prevent duplicate req id: 202
23:58:51:510 APS prevent duplicate req id: 207
23:58:52:261 APS prevent duplicate req id: 211
23:58:54:090 Beacon src: 0x25CB ch: 15 updateId: 0
23:58:57:012 APS prevent duplicate req id: 231
23:58:58:516 APS prevent duplicate req id: 238
23:59:01:892 reject aps request queue is full (25)
23:59:01:893 enqueue APS request failed with error 2, drop
23:59:02:263 APS prevent duplicate req id: 0
23:59:04:175 reject aps request queue is full (25)
23:59:04:176 enqueue APS request failed with error 2, drop
23:59:06:833 reject aps request queue is full (25)
23:59:06:833 enqueue APS request failed with error 2, drop
23:59:07:724 reject aps request queue is full (25)
23:59:07:725 enqueue APS request failed with error 2, drop
23:59:08:010 APS prevent duplicate req id: 30
23:59:08:263 APS prevent duplicate req id: 32
23:59:09:012 APS prevent duplicate req id: 36
23:59:09:766 APS prevent duplicate req id: 40
23:59:13:999 reject aps request queue is full (25)
23:59:13:000 enqueue APS request failed with error 2, drop
23:59:14:510 APS prevent duplicate req id: 62
23:59:15:458 reject aps request queue is full (25)
23:59:15:459 enqueue APS request failed with error 2, drop
23:59:15:763 APS prevent duplicate req id: 70
23:59:20:010 APS prevent duplicate req id: 88
23:59:21:510 APS prevent duplicate req id: 95
23:59:21:964 reject aps request queue is full (25)
23:59:21:965 enqueue APS request failed with error 2, drop
23:59:22:037 APS prevent duplicate req id: 100
23:59:23:084 reject aps request queue is full (25)
23:59:23:085 enqueue APS request failed with error 2, drop
23:59:26:266 APS prevent duplicate req id: 120
23:59:27:510 APS prevent duplicate req id: 126
23:59:29:094 reject aps request queue is full (25)
23:59:29:095 enqueue APS request failed with error 2, drop
23:59:30:261 APS prevent duplicate req id: 140
23:59:30:763 APS prevent duplicate req id: 143
23:59:30:884 reject aps request queue is full (25)
23:59:30:884 enqueue APS request failed with error 2, drop
23:59:32:260 timeout on poll APS confirm
23:59:32:268 APS prevent duplicate req id: 152
23:59:33:030 reject aps request queue is full (25)
23:59:33:030 enqueue APS request failed with error 2, drop
23:59:33:051 reject aps request queue is full (25)
23:59:33:052 enqueue APS request failed with error 2, drop
23:59:33:137 APS prevent duplicate req id: 161
23:59:33:160 reject aps request queue is full (25)
23:59:33:161 enqueue APS request failed with error 2, drop
23:59:34:254 reject aps request queue is full (25)
23:59:34:255 enqueue APS request failed with error 2, drop
23:59:34:276 reject aps request queue is full (25)
23:59:34:277 enqueue APS request failed with error 2, drop
23:59:38:010 APS prevent duplicate req id: 186
23:59:39:016 APS prevent duplicate req id: 191
23:59:40:513 APS prevent duplicate req id: 198
23:59:41:020 APS prevent duplicate req id: 201
23:59:41:021 APS prevent duplicate req id: 202
23:59:42:013 APS prevent duplicate req id: 207
23:59:42:766 APS prevent duplicate req id: 211
23:59:43:227 Beacon src: 0x25CB ch: 15 updateId: 0
23:59:47:510 APS prevent duplicate req id: 231
23:59:49:010 APS prevent duplicate req id: 238
23:59:53:308 APS prevent duplicate req id: 0
23:59:59:608 Beacon src: 0x25CB ch: 15 updateId: 0

**Comment by Mimiix** [comment] 2022-11-15 06:07
Hi,

Can you share some logs with the following log levels ?
APS, APS_L2, INFO,INFO_L2,ERROR,ERROR_L2

**Comment by Nazarbayevv** [comment] 2022-11-16 03:13
Hello.

New day, new evening and the same issue :(
But today wihout connection lines:
![image](https://user-images.githubusercontent.com/50654913/202074592-e847185d-32fd-4ba
[Logs.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10017821/Logs.txt)
9-ac5c-b5ab4d1ab5f6.png)

**Comment by Nazarbayevv** [comment] 2022-11-16 03:14
[Logs.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10017826/Logs.txt)

**Comment by Mimiix** [comment] 2022-11-16 07:20
@Nazarbayevv Did you put the log levels as i asked? It seems not all of thjem are in.

**Comment by Nazarbayevv** [comment] 2022-11-16 08:07
Yes, I selected APS, APS_L2, INFO,INFO_L2,ERROR,ERROR_L2 + ZDP + ZCL

**Comment by Nazarbayevv** [comment] 2022-11-16 08:18
I add Logs when everithing OK (after Raspberry reboot) 
[Logs - everything OK.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10019506/Logs.-.everything.OK.txt)

**Comment by Mimiix** [comment] 2022-11-16 08:24
I didn't ask for ZDP and ZCL as they cause a lot of noise.

Can you share without that when the issue happens again?

**Comment by AlexKusnezov** [comment] 2022-11-23 17:07
experiencing similar issue. after approx. 12 hours runtime I suddenly can't control any device with a bunch of erro stuff in the logs:
```
16:58:10:679 0x00158D000713193F error APSDE-DATA.confirm: 0xE9 on task
0x0000 
16:58:24:280 0x00158D000713193F error APSDE-DATA.confirm: 0xE9 on task
0x0000 
16:58:33:091 0x00158D0006F04FCD error APSDE-DATA.confirm: 0xE9 on task
0x0000 
16:58:34:979 0x00158D000713193F error APSDE-DATA.confirm: 0xE9 on task
```
This behavior only started appearing with deconz v.2.19.1. Prior I had deconz running for moths without restarting and life was good.
I'm on 64bit rpi4 with ConBee V1 using the stable docker image

**Comment by Mimiix** [comment] 2022-11-24 09:36
@AlexKusnezov  can you share some full outputs?

**Comment by AlexKusnezov** [comment] 2022-11-30 19:13
@Mimiix well, actually I couldn't reproduce it after I reseated the ConBee stick

**Comment by Mimiix** [comment] 2022-11-30 19:22
Alright , good to hear it's solved for you :)

As there's no other logs coming forward from the issue starter, I'm closing

**Closed by Mimiix** 2022-11-30 19:22 UTC
Labels: Bug report
