### ISSUE TITLE
proxmox LXC: deconz not connecting to ConBee II gateway

### ISSUE THREAD

**Issue by SmartHomeNewbie** [dresden-elektronik/deconz-rest-plugin#5432] opened 2021-10-30 23:20 UTC
## Describe the bug
Hi.
Im trying to run deconz v2.13.01 in an LXC ubuntu 20.04 LTS container in proxmox, deconz starts and i can access it from browser but i cant seem to establish connection to my ConBee II.
I have passed my ConBee through to the cointainer and tried every solution i could find on the web, i've also tried installing docker in LXC and then deconz in that(because thats what was working on my Pi) also with no luck.

## Screenshots
passthrough (from inside the LXC container)
![GCFFlasher](https://user-images.githubusercontent.com/75638271/139560254-598a3045-7d99-4c6f-8e83-4bb8d346f641.jpg)
![dev ttyACM0](https://user-images.githubusercontent.com/75638271/139560255-914b7b2f-7e62-4e17-9e9d-072bf2fbf9b1.jpg)
deconz.service
![deconz service](https://user-images.githubusercontent.com/75638271/139560302-59c135a5-e5c6-49e8-b3af-f5422ac0fa48.jpg)
.conf from proxmox server.
![150 conf](https://user-images.githubusercontent.com/75638271/139560322-3e6c1652-0f33-40d3-bf48-602d12cabbcb.jpg)
udev.rules from proxmox server.
![udev rules](https://user-images.githubusercontent.com/75638271/139560328-b525e706-0817-427f-bead-d29e2a20a7c1.jpg)

## Environment
 - Host system: (PC running Proxmox)
 - Running method: ( ubuntu 20.04 LTS running in LXC ccontainer)
 - Firmware version: (can't connect so cant see firmware version)
 - deCONZ version: (2.13.01)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes)
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
systemctl status deconz
![systemctl status deconz](https://user-images.githubusercontent.com/75638271/139560567-00644542-ab16-4dac-b1aa-5523c6719588.jpg)
here is some of the log, let me know if i should be looking for something specific.
![log](https://user-images.githubusercontent.com/75638271/139560213-a55ea117-e0e3-42bf-833b-e9fb94fc3dc3.jpg)

**Comment by Mimiix** [comment] 2021-10-31 06:43
Hi,

As this is not a bug report as described in #5113, I am closing this issue. Please use the forum for this question.

Kind regards,Dennis

**Closed by Mimiix** 2021-10-31 06:43 UTC
Labels: Bug report
