### ISSUE TITLE
Eurotronic Spirit ZigBee (SPZB0001) temperature not updated on device since deCONZ 2.12.6

### ISSUE THREAD

**Issue by double1968** [dresden-elektronik/deconz-rest-plugin#5433] opened 2021-10-31 16:06 UTC
## Describe the bug
Temperature set in Home Assistant is never being sent to the device. Local changes are sent back to Home Assistant. As deCONZ sits in between and there were no firmware updates, we believe this issue has been introduced with v2.12.6 (where v2.11.5  not have this issue - full disclosure: I can guarantee the issue didn´t exist with addon v6.8.0/deCONZ v2.10.4).
## Steps to reproduce the behavior
Set new temperature in Home Assistant
Wait forever for the device to update
No temperature update on the valve 

## Expected behavior
Set new temperature in Home Assistant
Valve target temperature is being updated within max. 20 second

## Screenshots
![1](https://user-images.githubusercontent.com/48420012/139591381-b2730070-10f2-4d61-9c69-591f16457a67.PNG)
![2](https://user-images.githubusercontent.com/48420012/139591391-51fe0108-99c2-4822-a478-a5a6e6dfe3cb.PNG)

Reading on the net it seems that the problem is due to an incorrect writing of the value in the ID 0x0012 / 0x4003.
I remember after the DECONZ update if I changed the values via Phoscon the temperatures were transmitted to the valve

## Environment

 - Host system: Raspberry Pi
 - Running method:  Home Assistent deCONZ Add-on 
 - Firmware version: 26720700
 - deCONZ version: 2.12.6
 - Device: ConBee II
 - Do you use an USB extension cable: yes -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? Yes : Zwave Dongle

## Additional context

See issue raised within HA repo (which is not the right place I think) here https://github.com/home-assistant/addons/issues/2244

See another user @bcutter with similar setup and same issue (closed for non-compliant) here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5422

**Comment by Mimiix** [comment] 2021-10-31 16:18
Asked manup to check :)

**Comment by manup** [comment] 2021-11-01 10:29
There are multiple firmware versions for the Spirit out there. Somehow the newer ones are "tricky".
Mine has Datecode 20181205 shown in the Basic Cluster.

Does writing the 0x4003 attribute work for you when done directly in deCONz Cluster Info Panel?
(double click on the attribute which open)

![image](https://user-images.githubusercontent.com/383386/139658081-cb61b08a-8c27-4bd4-864d-7009527353c6.png)

Here I set mine to 10°C.

**Comment by double1968** [comment] 2021-11-01 14:12
I rolled back to the working Deconz version so as not to be cold.
My Spirit firmware version has never been updated and is dated 20191014

![fw_version](https://user-images.githubusercontent.com/48420012/139685224-8e6283d7-041a-43e6-9347-c7f1d35c83af.PNG)

The 0x4003 attribute does not accept write, but it seems to remember after Deconz update the write was possible.

![04003](https://user-images.githubusercontent.com/48420012/139685249-1ade39fb-2078-4c3d-a2b8-9ba3ac0c385a.PNG)

At the moment the temperature setup works by writing attribute 0x0012 and it is sent to Spirit

![00012](https://user-images.githubusercontent.com/48420012/139685284-6e0a5cdc-ca92-4874-af28-84ad28b6afc6.PNG)

Set 20°C

**Comment by SwoopX** [comment] 2021-11-01 14:54
The interesting thing with all this is that the API sends the setpoint to both attributes, 0x0012 and 0x4003, as there's no known way to determine which attribute the device actually uses.

**Comment by double1968** [comment] 2021-11-01 17:22
I am saying stupid, but it could not be that in the new version of Deconz one of the two data is sent in text format instead of numeric

**Comment by SwoopX** [comment] 2021-11-01 19:42
No. In fact, it's more the other way around. A few versions back, I implemented a mandatory type check for all configuration values send via REST API to deconz so that exactly that cannot happen anymore. In this particular case, the `heatsetpoint` values must be an integer. Hence, this would have a different cause.

**Comment by double1968** [comment] 2021-11-01 21:32
Right now I'm using version 2.11.05 and everything works !
![version](https://user-images.githubusercontent.com/48420012/139744866-a3725c43-44cd-4ebc-a781-9c01c00904c3.PNG)

**Comment by petermarasek** [comment] 2021-11-02 08:35
I can confirm the same behavior as described by @double1968

**Comment by SwoopX** [comment] 2021-11-02 09:03
Found the root cause. What you guys experience is what should have been addressed with https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3626 and https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3680, however, the implementation was slightly incorrect (the devil is always in the details). It's remarable that this just pops up or gets more prominent after a year... 🤷‍♂️ 

Short recap: Due to the firmware chaos with the Eurotronic Spirit, there's devices out there behaving differently although they show the very same firmware version. Older devices had their heating setpoint being set through attribute 0x4003, for newer devices, this is apparently only possible via the standard attribute 0x0012. As there's no way to determine which version of the device a user has, the aforementioned PRs have been implemented to send a request for each attribute BUT, that never seems to have worked correctly.

The root cause is that the very same request was used twice and therefore had identical task and request IDs. Before the 2nd request could be served (with the amended attribute and manufacturer code), it got deleted as the 1st request was determined to be successful due to the identical IDs.

The fix is to create a completely new 2nd request which now gets served as well.

**Comment by Mimiix** [comment] 2021-11-02 10:51
> Found the root cause. What you guys experience is what should have been addressed with #3626 and #3680, however, the implementation was slightly incorrect (the devil is always in the details). It's remarkable that this just pops up or gets more prominent after a year... 🤷‍♂️
> 
> Short recap: Due to the firmware chaos with the Eurotronic Spirit, there's devices out there behaving differently although they show the very same firmware version. Older devices had their heating setpoint being set through attribute 0x4003, for newer devices, this is apparently only possible via the standard attribute 0x0012. As there's no way to determine which version of the device a user has, the aforementioned PRs have been implemented to send a request for each attribute BUT, that never seems to have worked correctly.
> 
> The root cause is that the very same request was used twice and therefore had identical task and request IDs. Before the 2nd request could be served (with the amended attribute and manufacturer code), it got deleted as the 1st request was determined to be successful due to the identical IDs.
> 
> The fix is to create a completely new 2nd request which now gets served as well.

Great work :)

**Comment by bcutter** [comment] 2021-11-02 11:13
> Great work :)

Copy that. Awesome!

I'm curious to know what will be the next steps to estimate on a timeline how long it will take for my TRVs to finally work again (it's autumn with winter temperatures here so... 😀). 
Unfortunately I can't run beta versions of deCONZ (HA addon) which means usually it takes a lot of time until new stable versions are available.

If I can test something, please notify me.

**Comment by Mimiix** [comment] 2021-11-02 11:31
> I'm curious to know what will be the next steps to estimate on a timeline how long it will take for my TRVs to finally work again (it's autumn with winter temperatures here so... 😀). Unfortunately I can't run beta versions of deCONZ (HA addon) which means usually it takes a lot of time until new stable versions are available.


Brrr!

I think we are out of luck in this case. Assuming this could be fixed with DDF's (introduced in 13.x), this can't be done on the fly on HA As it still is on 12.x 

So indeed, you need to wait for stable. The other solution would be using a seperate machine for deCONZ. So if you have another RPI around you can just put deCONZ on there. 

What i can do, is make sure it is in the next stable (assuming Swoop makes a fix before that release).

**Comment by double1968** [comment] 2021-11-02 13:14
> Found the root cause. What you guys experience is what should have been addressed with https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3626 and https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3680, however, the implementation was slightly incorrect (the devil is always in the details). It's remarkable that this just pops up or gets more prominent after a year... 🤷‍♂️ 
> 
> Short recap: Due to the firmware chaos with the Eurotronic Spirit, there's devices out there behaving differently although they show the very same firmware version. Older devices had their heating setpoint being set through attribute 0x4003, for newer devices, this is apparently only possible via the standard attribute 0x0012. As there's no way to determine which version of the device a user has, the aforementioned PRs have been implemented to send a request for each attribute BUT, that never seems to have worked correctly.
> 
> The root cause is that the very same request was used twice and therefore had identical task and request IDs. Before the 2nd request could be served (with the amended attribute and manufacturer code), it got deleted as the 1st request was determined to be successful due to the identical IDs.
> 
> The fix is to create a completely new 2nd request which now gets served as well.

Great job, thanks

**Comment by manup** [comment] 2021-11-02 17:27
@SwoopX for reference the Basic Cluster Attributes of my Spirit

![image](https://user-images.githubusercontent.com/383386/139915341-04e61998-2005-484e-b52d-f79da544a6cc.png)

**Comment by SwoopX** [comment] 2021-11-02 18:37
That's mine

![grafik](https://user-images.githubusercontent.com/4005212/139924966-01376e6b-69d2-4467-87db-399c9c90ad9e.png)

**Comment by bcutter** [comment] 2021-11-02 19:48
> What i can do, is make sure it is in the next stable (assuming Swoop makes a fix before that release).

That would be great 👍🏼 

Here's my basic cluster for all my devices if helpful somehow in the further process:

![image](https://user-images.githubusercontent.com/13799156/139942016-3428b09b-47f3-4e0a-8e3d-1064747b6498.jpeg)

**Closed** 2021-11-06 19:38 UTC
Labels: Confirmed Bug, Bug report
