### ISSUE TITLE
Phoscon Web UI not compatible with lots of devices

### ISSUE THREAD

**Issue by cputoaster** [dresden-elektronik/deconz-rest-plugin#2026] opened 2019-11-01 09:32 UTC
The phoscon web UI has some logical problem with many lights:

- if there are a lot of lights (around 100 for me), a normal notebook screen is too small to show them for adding to a group. A simple fix would be to add scrolling to the light panel.
- if a new light is added, it is added at the bottom of the current lights list, which is invisible without manually scrolling. There is no visual cue if the light was detected or not, one always has to try to scroll to see if it worked. Ideally there would either be a pop-up, the list would automatically scroll up, or the new light be added on top so its visible.

**Comment by manup** [comment] 2019-11-01 11:47
Thanks for the report, I thought this was fixes already, we'll check the code.

**Comment by manup** [comment] 2019-11-19 11:37
The issue is fixed now in 2.05.71.

**Closed by manup** 2019-11-19 11:37 UTC
