### ISSUE TITLE
Deconz, RestApi and VNC hangs frequently for 30-60 seconds

### ISSUE THREAD

**Issue by LukasA83** [dresden-elektronik/deconz-rest-plugin#6590] opened 2022-12-04 15:46 UTC
System:
Raspi 4b
Deconz docker 2.19.03, same issue with, at least, .02

Frequently the network lags/hangs being unresponsive and therewith not receiving updates. In the VNC screen all nodes stop to blink blue for this period while the screen stays responsive. I enabled the logging and tried to copy a snippet:

`16:39:22:667 ZCL attribute report 0x00158D000362C576 for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
16:39:26:937 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
16:39:26:938 Skip automatic channel change, TODO warn user
16:39:36:937 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
16:39:36:938 Skip automatic channel change, TODO warn user
16:39:47:602 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
16:39:47:603 Skip automatic channel change, TODO warn user
16:39:48:437 Skip idle timer callback, too early: elapsed 830 msec
16:39:56:937 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
16:39:56:937 Skip automatic channel change, TODO warn user
16:40:04:520 ZCL attribute report 0x00158D000342F3F7 for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000  `

Any idea?

**Comment by Mimiix** [comment] 2022-12-04 15:50
Hi

As this issue is not as described in #5113 i am closing this issue.

Feel free to open a topic on the forums 

Kind regards,
Dennis

**Closed by Mimiix** 2022-12-04 15:50 UTC
Labels: Bug report

**Comment by LukasA83** [comment] 2022-12-04 15:53
It is clearly a bug because it was working before, so why closing it?

**Comment by Smanar** [comment] 2022-12-04 16:02
You haven't followed the procedure.

>16:39:26:937 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration

Take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6515#issuecomment-1312781817

**Comment by LukasA83** [comment] 2022-12-04 16:33
I looked at it and corrected the panid. Still, same issue:
`17:31:56:697 ZCL attribute report 0x00158D000362C576 for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
17:32:22:470 Skip idle timer callback, too early: elapsed 926 msec
17:32:24:436 Skip idle timer callback, too early: elapsed 873 msec
17:32:45:126 ZCL attribute report 0x00158D000362C576 for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 `

**Comment by ebaauw** [comment] 2022-12-04 17:05
I think this is a duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6588.

**Comment by LukasA83** [comment] 2022-12-04 17:37
Thanks for pointing this out, I have seen it. For me it is not involving any commands, but can confirm it works without any issue with 2.18.02.

**Comment by Mimiix** [comment] 2022-12-04 17:45
It's not a bug as the log indicates clearly there's a configuration issue as Smanar points out.

**Comment by LukasA83** [comment] 2022-12-04 17:46
This is already gone, I corrected it, issue remains.

**Comment by Mimiix** [comment] 2022-12-04 17:47
In that case it's a duplicate of the issue Erik mentioned.

I am not reopening this one in any case as the template has been ignored . Please use the forums or post in the issue Erik mentions.

Locking this one up as there's no point in continuing here.

**Comment by Mimiix** [comment] 2022-12-04 17:48
Personal advice: It really is in your best entrance to post on the forums and get help there. The GitHub is simply for bugs and I believe this might be some configuration issue.
