### ISSUE TITLE
Samsung SmartThings Arrival Sensor

### ISSUE THREAD

**Issue by theendisnye** [dresden-elektronik/deconz-rest-plugin#427] opened 2018-02-20 14:14 UTC
Does the Samsung SmartThings Arrival Sensor work with DeConZ or is that planned in the future?

Steve

**Comment by wvuyk** [comment] 2018-02-21 10:32
For Europe the name seems to be Samsung smartthings Presence F-PRS-UK-v2 Sensor. They are quite interesting as they also perform as router?

**Comment by manup** [comment] 2018-02-21 10:43
>They are quite interesting as they also perform as router?

On a small CR2032 battery that's unlikely :) routers usually are mains powered.

**Comment by theendisnye** [comment] 2018-02-21 12:07
Here is a link to the product http://www.samsung.com/uk/smartthings/sensors-plug-f-prs-uk-v2/ I think they basically send out a regular 'I am here' poll to maintain the presence status and then when Smartthings stops getting those polls for a period it sets the device to departed setting it back to arrive when they are re-instated. I was offered really cheap,  which I now have. I have tried to include it in DeConZ which seems to see it but does not seem to do anything with it.

**Comment by theendisnye** [comment] 2018-02-23 10:41
From what I can tell this is the end point information.

![screenshot 2018-02-23 09 04 23](https://user-images.githubusercontent.com/35459882/36590221-db0bb216-1885-11e8-825a-6f0f54f9e4e3.png)
![screenshot 2018-02-23 09 05 44](https://user-images.githubusercontent.com/35459882/36590222-db233134-1885-11e8-800f-83004a7288c7.png)
![screenshot 2018-02-23 09 06 20](https://user-images.githubusercontent.com/35459882/36590223-db380ac8-1885-11e8-9280-64023e2df4f4.png)
![screenshot 2018-02-23 09 06 27](https://user-images.githubusercontent.com/35459882/36590224-db4f6718-1885-11e8-8bf4-a89b10a19559.png)
![screenshot 2018-02-23 09 06 31](https://user-images.githubusercontent.com/35459882/36590225-db65bc0c-1885-11e8-91d0-610eb1163777.png)
![screenshot 2018-02-23 09 06 34](https://user-images.githubusercontent.com/35459882/36590226-db79972c-1885-11e8-9e01-a4745ae21ae2.png)
![screenshot 2018-02-23 09 06 40](https://user-images.githubusercontent.com/35459882/36590227-db9796b4-1885-11e8-8372-9ec38f168487.png)

**Comment by manup** [comment] 2018-02-23 12:33
Does the sensor return anything when `read` button pressed in `Basic Cluster`?
Knowing the `Model Identifier` attribute would be helpful.

**Comment by theendisnye** [comment] 2018-02-23 18:58
It returns manufacturer SmartThings and Model Identifier tagv4

Steve

**Comment by uldisbiks** [comment] 2018-03-14 18:30
Does it also shows up in REST API? I`m trying to connect presence sensor to Home Assistant trough deCONZ and I can see sensor in Xwindow APP but REST does not return sensor info.

**Comment by theendisnye** [comment] 2018-03-14 19:09
I am using homeseer with the Jowihue plugin and that does not seem to recognise the device. I assume it is not getting anything from the API.

Steve

**Comment by manup** [comment] 2018-03-29 22:30
Hi, does the binary input attribute change when presence is detected?

**Comment by cowinger** [comment] 2018-03-30 17:02
I also use homeseer with the jowihue plugin and would like to have this arrival sensor work. I did not see any changes to the binary input when it was removed from the area.

**Comment by uldisbiks** [comment] 2018-04-01 19:30
I can send sensor to someone to make better and faster dev

**Comment by wvuyk** [comment] 2018-06-09 11:13
I have been playing here wih a smarthings arrival sensor. @manup  Indeed there is no change in binary input. I hink the whole trick here is that the sensor is reachable or unreachable? If you test the Identify function in deCONZ, the sensor is beeping - would be nice to enable this in the REST API. 
There is a challenge with the unreachable function as indication if the car is in or out of reach.... it would be nice if unreachable detection for this device would be set faster then for other devices maybe?

I guess enabling this device for REST API could be simple - although adding the identify function as locating the device (beep) might be a bit more tricky? I also would have sensor to test for one of the developers?

**Comment by ebaauw** [comment] 2018-06-09 11:53
Supporting sending _Idenfity_ to the sensor will be straightforward.   We already do this for e.g. the Hue motion sensor through `config.alert`.

I don't think I've come across the _Binary Input_ cluster before.  As _Present value_ is read-write, it might be used for configuring the sensor, rather than reporting the state. I cannot seem to find the usual SmartThings custom config, probably because it's a standard SmartThings sensor supported out of the box.  I'm afraid we need to do some sniffing.  @uldisbiks, I'll be happy to take a look at the sensor and return it afterwards, if you're willing to send it to Amsterdam.

> I think they basically send out a regular 'I am here' poll to maintain the presence status and then when Smartthings stops getting those polls for a period it sets the device to departed setting it back to arrive when they are re-instated.

I would theorise that the "I am here" is actually an _Identify_ command, given the _Identify_ client cluster (in addition to the server cluster). If that's indeed the case, we could probably leverage the buttonhandler for switches, exposing the sensor as a (stateless) switch.  You could than create a `ddx` rule on `state.lastupdated` to detect that the sensor hasn't checked in for a while, setting a corresponding CLIPPresence companion sensor to false.  And a regular switch rule to set the CLIPPresence to true once the sensor checks in again.

BTW I'm using HomeKit geofencing to set some CLIP sensors on deCONZ (that homebridge-hue exposes as switches to HomeKit).  It works most of the time, but it's rather coarse, based on the location determination of your iPhone.  A solution based on reachability of the ZigBee network might be more precise, if it indeed has the advertised range of 27m.

**Comment by wvuyk** [comment] 2018-06-09 12:47
@ebaauw I can send it to you fine. I will need the address to send it to. Could you send this to w dot vuyk at upcmail dot nl?

**Comment by manup** [comment] 2018-06-09 20:30
Looks like the sensor is even more creative than the xiaomi devices :)

**Comment by ebaauw** [comment] 2018-06-13 18:14
Or not...

Received the sensor.  It pairs to the deCONZ GUI without any issues.  Indeed, it beebs when you send the _Identify_ command.  It seems quite responsive to reading characteristics - for a battery-powered device.

![untitled](https://user-images.githubusercontent.com/22179355/41368672-e9491418-6f42-11e8-9b6f-0bddc3f1ccbd.jpeg)

It only reports battery voltage, not percentage:
![untitled 2](https://user-images.githubusercontent.com/22179355/41368679-eba7973e-6f42-11e8-8aab-c3732b97ee9c.jpeg)

Every 10 minutes (588 seconds), the sensor sends a couple of _ZDP Match Descriptor Request_ messages (protocol 0x0000, cluster 0x0006), specifying a single input cluster 25 (0x0019, the _OTAU_ cluster), and no output clusters.  The RaspBee responds with matching endpoint 1.  Then, the sensor sends five _Query Next Image Request_ messages (profile 0x0104, cluster 0x0019), to which the RaspBee responds with an ACK.  
I never sniffed the OTAU sequence before, but @manup, I take it this is the normal way for a device to check whether it's firmware can be upgraded?  As checking every 10 minutes seems ridiculously often, I assume the sensor (ab)uses this for checking in. 

deCONZ seems to catch all these messages already, updating the last seen indication:
```
Jun 13 19:34:41 pi1 deCONZ[10162]: 19:34:38:702 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 587 s
Jun 13 19:34:42 pi1 deCONZ[10162]: 19:34:40:143 APS-DATA.indication srcAddr: 0x24fd5b000105ab46, dstAddrMode: 2, profile: 0x0000, cluster: 0x0006, lqi: 255, rssi: -33
Jun 13 19:34:42 pi1 deCONZ[10162]: 19:34:40:622 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 0 s
Jun 13 19:34:47 pi1 deCONZ[10162]: 19:34:42:107 APS-DATA.indication srcAddr: 0x24fd5b000105ab46, dstAddrMode: 2, profile: 0x0104, cluster: 0x0019, lqi: 255, rssi: -34
Jun 13 19:34:47 pi1 deCONZ[10162]: 19:34:42:542 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 0 s
Jun 13 19:34:47 pi1 deCONZ[10162]: 19:34:44:462 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 2 s
Jun 13 19:34:47 pi1 deCONZ[10162]: 19:34:45:034 APS-DATA.indication srcAddr: 0x24fd5b000105ab46, dstAddrMode: 2, profile: 0x0104, cluster: 0x0019, lqi: 255, rssi: -33
Jun 13 19:34:47 pi1 deCONZ[10162]: 19:34:45:162 int zmMaster::readParameter(ZM_DataId_t) 0x24
Jun 13 19:34:47 pi1 deCONZ[10162]: 19:34:46:382 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 1 s
Jun 13 19:34:50 pi1 deCONZ[10162]: 19:34:47:971 APS-DATA.indication srcAddr: 0x24fd5b000105ab46, dstAddrMode: 2, profile: 0x0104, cluster: 0x0019, lqi: 255, rssi: -34
Jun 13 19:34:50 pi1 deCONZ[10162]: 19:34:48:302 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 0 s
Jun 13 19:34:50 pi1 deCONZ[10162]: 19:34:50:222 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 2 s
Jun 13 19:34:50 pi1 deCONZ[10162]: 19:34:50:922 APS-DATA.indication srcAddr: 0x24fd5b000105ab46, dstAddrMode: 2, profile: 0x0104, cluster: 0x0019, lqi: 255, rssi: -33
Jun 13 19:34:54 pi1 deCONZ[10162]: 19:34:52:142 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 1 s
Jun 13 19:34:54 pi1 deCONZ[10162]: 19:34:53:849 APS-DATA.indication srcAddr: 0x24fd5b000105ab46, dstAddrMode: 2, profile: 0x0104, cluster: 0x0019, lqi: 255, rssi: -34
Jun 13 19:34:54 pi1 deCONZ[10162]: 19:34:54:062 Node 0x24FD5B000105AB46 is known by 0 neighbors, last seen 0 s
```

To support the sensor in deCONZ, I guess we need a hack when the last seen indication is updated, to set `state.presence` to `true`.  Then with a `config.duration` set to 600 (10 minutes), `state.presence` should revert to `false` when the check in is missed.  Also, we need to translate the battery voltage to percentage for reporting in `config.battery`.  Haven't seen any battery reports yet, though.  Maybe I need to setup attribute reporting first...

**Comment by ebaauw** [comment] 2018-06-13 18:34
Good news, no need for a hack!  The sensor does support attribute reporting for the_Binary Input_ cluster's _Present Value_ attribute (0x000f/0x0055) and for the _Power Configuration_ cluster's _Battery Voltage_ attribute.  The _Present Value_ remains false, but deCONZ could update `state.presence`, ignoring the value.

Currently set the report interval to every five minutes - seems to work.  I suppose I should take the sensor out for a walk, and see if the reporting resumes after coming back into network range.

**Comment by wvuyk** [comment] 2018-06-14 08:49
that is hopeful news :-) It means it can take up to 5 minutes to see if you are out? Am very curious how long it takes when you come back... am hoping it could be fast becuase it reports once connects I suppose?

**Comment by ebaauw** [comment] 2018-06-14 17:04
> It means it can take up to 5 minutes to see if you are out?

Depending on the frequency set in the report configuration.  Classical tradeoff between battery life and responsiveness.  I now reports 2.4V, where it reported 2.9V when I first paired it yesterday.

> am hoping it could be fast becuase it reports once connects I suppose?

Indeed, when coming into range, the sensor issues a report immediately after the device announcement.  I'm not sure yet how quickly it detects that it's in range.  Easier to test once I've added support to deCONZ and homebridge-hue.

**Comment by ebaauw** [comment] 2018-06-14 20:14
Please check out my latest PR.  The sensor should supported:
```json
{
  "config": {
    "alert": "select",
    "battery": 40,
    "duration": 310,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "44c7120057cef1c8abf2665833f55d9b",
  "manufacturername": "SmartThings",
  "modelid": "tagv4",
  "name": "Presence 10",
  "state": {
    "lastupdated": "2018-06-14T19:58:11",
    "presence": true
  },
  "swversion": "R743_#33",
  "type": "ZHAPresence",
  "uniqueid": "24:fd:5b:00:01:05:ab:46-01-000f"
}
```

Remarks:
- I'm not sure about `config.battery`, as the sensor only reports battery voltage.  I translate it to percentage assuming a linear scale from 3.0V (100%) to 2.0V (0%).  Max value I've seen is 2.9V and minimum 2.4V.  Please report what values you're seeing.  I setup reporting for the battery voltage once every hour, so you might need to wait a while before `config.battery` is updated.  Alternatively, you can manually read the _Power Configuration_ cluster in the deCONZ GUI;
- Attribute reporting should be setup for 0x000f/0x0055 (_Binary Input_/_Present Value_), to send a report every 300 seconds.  Only after the reporting has been setup, the sensor will report `state.presence` as true.  I initialise `config.duration` to 310 seconds, to reset `state.presence` to false when the next report hasn't been received;
- If you're feeling lucky, you might alter the reporting setup in the deCONZ GUI and adjust `config.duration` accordingly.  If you specify a longer interval, deCONZ will probably overwrite it, sooner or later, but if you specify a shorter interval, deCONZ might actually leave that be.  Not sure how badly this will effect the battery life;
- Set `config.alert` to `"select"` or `"lselect"` to make the sensor beep once or 12 times;

**Comment by wvuyk** [comment] 2018-06-14 21:10
Will be testing, but also have to wait for a build as I am still left handed on PR builing :-)

**Comment by ebaauw** [comment] 2018-06-15 06:50
First overnight test.  Eve reports motion for the last 10:25 hours, so that's looking good.

Battery is down to 2.2V.  It's a regular CR2032, which is good news: these are damn cheap at IKEA (look for PLATTBOJ).  There's also a small push button under hood - presumably to reset the sensor.

I will bring the sensor along some errands this afternoon and see how that goes.

**Comment by ebaauw** [comment] 2018-06-15 12:02
Hm, it took the sensor a good 15 minutes to report back in after coming home.  Granted, this is on my test network with only two routers besides the RaspBee (a Xiaomi in-wall switch and an innr smart plug).

**Comment by wvuyk** [comment] 2018-06-18 07:10
I will install .30 today and test it here also. But if it is taking this long it would miss the function 'arrival' really for what I want to use it. Maybe then still the reachable/unreachable should be used as arrival indicator?

Wim

**Comment by wvuyk** [comment] 2018-06-18 09:00
Ok, was hoping the rejoin would happen once a router could be found by the arrival sensor. For my plugin I do not use rules at all. The logic is done by my plugin in combination with Homeseer, so I could catch the unreachable/reachable state if needed.
Will do my own test soon here too.

**Comment by wvuyk** [comment] 2018-06-18 09:35
Tried to update my raspbee here to 2.05.30, but after updating and restyarting deCONZ does not start anymore? What changed that might prevent the autostart? Coming from 2.05.28 here

**Comment by manup** [comment] 2018-06-18 09:58
Is there something printed on the console?
Also if you compile the plugin on your own, make sure the libsqlite3-dev package is installed.

**Comment by wvuyk** [comment] 2018-06-18 09:59
also the update to 2.05.29 fails, returning to 2.05.28 works fine. Is this libsqlite3-dev new since .29?

**Comment by wvuyk** [comment] 2018-06-18 10:21
Ok, adding the package  libsqlite3-dev works, I am now getting deCONZ started. there was no errors on the console BTW and also before installing the package I did not see errors during compile, but could have missed those easily ....

**Comment by wvuyk** [comment] 2018-06-18 12:20
I have been waiting for a long time now, but no updates are coming in. I tried to do a read of the clusters and then an update came in setting presence to true, did set duration to 90 for testing and presence went to false after a bit, while the arrival sensor was still in the house. Went out for some time and came back in. No updates anymore here?

` "6": {
        "config": {
            "alert": "none",
            "battery": 60,
            "duration": 90,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "e667f31e996d9d828c7c4281b6d8f6bc",
        "manufacturername": "SmartThings",
        "modelid": "tagv4",
        "name": "Arrival sensor",
        "state": {
            "lastupdated": "2018-06-18T10:58:51",
            "presence": false
        },
        "swversion": "R743_#33",
        "type": "ZHAPresence",
        "uniqueid": "24:fd:5b:00:01:05:ab:ae-01-000f"
    },`

**Comment by ebaauw** [comment] 2018-06-18 19:45
Did the deCONZ REST API plugin setup the attribute reporting?  I cannot quite put my finger on it, but this might take some time and/or restarts of deCONZ.  Check in the deCONZ GUI, by double clicking on the _Present Value_ attribute of the _Binary Input_ cluster in the _Node Info_ panel, and pressing _read config_.  
![untitled](https://user-images.githubusercontent.com/22179355/41558355-d533050e-7340-11e8-9055-a32428953472.jpeg)

You might try and configure this manually, and, in the _Bind Dropbox_ panel create a binding from the cluster to the RaspBee.
![untitled 2](https://user-images.githubusercontent.com/22179355/41558361-d8c5ce72-7340-11e8-98af-c270190cf731.jpeg)

**Comment by wvuyk** [comment] 2018-06-19 09:07
I have checked the reproting configuration and it was set to 300 indeed. I have reset the config.duration to 310, as this might be confusing the updates here. Also did several restarts of deCONZ and checked the arrival sensor several times. During a read the lastupdated time is set and the presence set to true, but after 310 seconds the presence in REST API is reset to false. After that no updates on the lastupdated, so I get the feeling the reporting is not done?

If I try to check the bind Dropbox I can only change IEEE to Group, but I cannot change anything here?

Wim

**Comment by ebaauw** [comment] 2018-06-19 19:38
No.  The only way to check the. Inding is to delete it - if it displays success there was a binding, otherwise you’ll get a binding not found (or similar) message.  Make sure to (re-)bind afterwards.

**Comment by wvuyk** [comment] 2018-06-19 19:56
Sorry to be so ignorant here, but how do I delete a binding? I do not see if it is bound, nor can I acces a unbind button... everything is greyed out here?

<img width="248" alt="2018-06-19 21_52_25-samsung smartthings arrival sensor issue 427 dresden-elektronik_deconz-rest" src="https://user-images.githubusercontent.com/30700296/41620952-9203d440-740b-11e8-8efa-36d1b440e005.png">

**Comment by wvuyk** [comment] 2018-06-19 21:52
Can this be caused by the fact that this sensor already was joined in the earlier version of deCONZ? Should I have deleted it from deCONZ, or maybe even from the deCONZ SQLite database?

**Comment by ebaauw** [comment] 2018-06-19 22:16
> how do I delete a binding? I do not see if it is bound, nor can I acces a unbind button... everything is greyed out here?

You need to drag the source cluster to the _Source_ dropbox and the destination end point to the _Destination_ dropbox.  Then the fields are populated as on my screenshot, and the _Bind_ and _Unbind_ buttons become active.

I don’t think the binding has been created by deCONZ.  300/300 might be the sensor’s factory default reporting setting for the _Present Value_ attribute.  DeCONZ should set it to 10/300: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/a60076bd096269c8dd81aa78841c2aa1c2558720/bindings.cpp#L832-L839

**Comment by wvuyk** [comment] 2018-06-21 22:08
I did as you said and managed to setup the binding. Now the REST API is updating the status as defined. 
It could be that I have set the 300/300 setting, I tried it once but deCONZ reported an write error to me. Guessing there was no write error after all then....
For me also the report of arrival sensor came in quite some time after the real arrival of me. Although this might be a trustworthy report, it might be too late for switching the lights on arrival. 

One question left her for me is why deCONZ did not create the binding when the REST API was reporting the device? Why is this the first time I had to do a binding here? Could this have been caused by the fact that this arrival sensor was already connected to deCONZ before?

**Comment by ebaauw** [comment] 2018-06-22 05:10
> why deCONZ did not create the binding when the REST API was reporting the device?

Not sure, maybe I screwed up something, I’ll do some more testing and sniffing, but it definitely created the binding and attribute reporting for the battery for me.

deCONZ should check and setup the binding at device discovery and every so often.  In my experience, this is more reliable for mains-powered devices than for battery-powered devices.  For the latter, deCONZ will only send the request once it knows the device is awake, because it just received a message from the device.  Of course, it will only receive messages after the binding and reporting have been setup.  There’s a small window of opportunity to break this catch 22 when the device is paired or first announces it presence, but it seems to be a bit of a hit and miss.  Of course all the ZigBee I/O is asynchronous and sharing the same queues on the RaspBee or ConBee, so it’s hard to figure out what’s happening when exactly.

**Comment by ebaauw** [comment] 2018-06-23 13:46
> maybe I screwed up something

I found another place where clusters are whitelisted for attribute reporting, where the _Binary Input_ cluster was missing.  After adding it, deCONZ now sets up the reporting correctly.

**Comment by wvuyk** [comment] 2018-06-23 21:13
Will test this when available! 🥇

**Comment by wvuyk** [comment] 2018-06-28 12:39
Tested this yesterdy by unbinding the sensor in 2.05.29, installing 2.05.31 and the sensor ws boud again (reporting as expected). I gues it is working now! 
Who should close this issue now? @theendisnye ?

Wim

**Comment by theendisnye** [comment] 2018-06-28 13:03
Thanks Guys, I don't pretend to understand all the technical content but I can't wait to use it.

Steve

**Closed** 2018-06-28 13:02 UTC

**Comment by holdestmade** [comment] 2019-03-21 09:55
This is not being discovered in the Phoscon App, is there any way it can be added ?

Thanks
