### ISSUE TITLE
deconz new ip/pwa not usable if more than 3 deconz instance are running

### ISSUE THREAD

**Issue by holli73** [dresden-elektronik/deconz-rest-plugin#6049] opened 2022-05-12 07:20 UTC
## Describe the bug

i have now 3 deconz devices running

1x raspbee - ip.10
1x conbee - ip.1
1x conbee II -ip.99

if i want to use now the new webinterface (/pwa) it only shows 2 devices and the second entry changes always between the one i need but is only there for ms - so i can't click it even - if i'm on the IP - i need access to...

![image](https://user-images.githubusercontent.com/1434090/168012977-25098447-97b1-49eb-87f8-ba71c41b3baf.png)

so you can see that i'm on ip.1 but only ip.10 and ip.99 are shown - ip.1 changes with ip.99 but so fast that there is no way that i can click on it - so i must now turnoff one deconz to access the needed one - can this limitation be removed that it is possible to use more than 2 deconz devices within the same network?
## Steps to reproduce the behavior

use more than 2 deconz devices on the same network

## Environment

x64 linux ubuntu 20.04
raspbien buster for raspbee
ubuntu on pi4 for conbee II

**Comment by Mimiix** [comment] 2022-05-12 07:22
Hi There,

As this is not a bug report as described by #5113, I am closing this issue.

This is better suited to be posted on the forums. Please ask your question there: https://forum.phoscon.de

Kind regards,

**Closed by Mimiix** 2022-05-12 07:22 UTC
Labels: Bug report
