### ISSUE TITLE
Segmentation fault on scene recall

### ISSUE THREAD

**Issue by snozzlebert** [dresden-elektronik/deconz-rest-plugin#63] opened 2017-07-28 05:59 UTC
After recalling a scene I get a Segmentation fault and deCONZ crashes (tested with 2.04.55-57):

```
19:18:19:921 HTTP API PUT /api/<username>/groups/1/scenes/1/recall - 10.8.0.2
19:18:19:921 Text Data: 	{"id":"1"}
19:18:19:922 [{"success":{"id":"1"}}]
19:18:20:129 Erase task zclSequenceNumber: 20 send time 1
Segmentation fault
```

However, the lights are turned on after recalling the scene.

The group (id: 1) consists of an OSRAM Plug 01 (id: 1) and a Hue Extended color light LCT001 (id: 2)
The scene (id: 1) is:

```
{
    "lights": [
        {
            "bri": 0,
            "id": "1",
            "on": true,
            "transitiontime": 10
        },
        {
            "bri": 144,
            "colormode": "ct",
            "ct": 447,
            "id": "2",
            "on": true,
            "transitiontime": 10
        }
    ],
    "name": "relax",
    "state": 0
}
```

Could this be caused by using an On/Off device in this scene? The scene in de REST API shows “bri" and “transitiontime" while these settings are not supported by the OSRAM Plug.

**Comment by manup** [comment] 2017-07-28 06:06
Yes the On/off device could be the cause of the problem here, thanks for the report should be fixed in the next version.

**Closed** 2017-08-08 14:07 UTC
