### ISSUE TITLE
Conbee 2 0000000000000000 problem

### ISSUE THREAD

**Issue by ALF-2021** [dresden-elektronik/deconz-rest-plugin#6246] opened 2022-08-07 20:46 UTC
Hello I have the problem you can see on image. 

![image](https://user-images.githubusercontent.com/83036797/183310382-5ef7a6ec-7040-48b9-99e9-2f40172167fe.jpeg)

Someone knows how fix it?

Thanks best regards. 

## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment] 2022-08-07 21:27
Hi,

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-08-07 21:27 UTC
Labels: Bug report
