### ISSUE TITLE
New device request - Tuya Zigbee Smoke detector TZE200_ntcy3xu1

### ISSUE THREAD

**Issue by btk999** [dresden-elektronik/deconz-rest-plugin#6615] opened 2022-12-16 15:32 UTC
Could you please add Tuya Smoke detector?
I already found a similar topic in issue 5143 but its not exactly the same i think and the PR 5310 is stil open.
Unfortunately im running deconz on windows only and dont have a linux machine, so i would be very happy if you could compile it for windows. @Smanar can you help here?

## Device

Product name: Haozee Tuya Smoke Alarm ZigBee Fire Detector 3C Fire Smoke Alarm
Manufacturer: _TZE200_ntcy3xu1
Model identifier: TS0601
Device type:
Other: Smoke detector

## Screenshots
![image](https://user-images.githubusercontent.com/20415739/208132716-4ad11aec-e4b5-4676-9fe5-6be07e234b2a.png)

### Basic
![image](https://user-images.githubusercontent.com/20415739/208132815-410d7776-a59e-473c-9c5a-6eb4cf8e6dfb.png)

### Node Info
![image](https://user-images.githubusercontent.com/20415739/208132877-6ea507e2-c726-49e6-b7e4-9685b2871e68.png)

**Comment by Mimiix** [comment] 2022-12-16 15:40
Duplicate of : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6532

Closing this one.

**Comment by Mimiix** [comment] 2022-12-16 15:41
Closing the other one too, re-opening this one: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6236

**Closed by Mimiix** 2022-12-16 15:40 UTC
Labels: Device Request
