### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by KrOnAsK** [dresden-elektronik/deconz-rest-plugin#5952] opened 2022-04-10 19:04 UTC
## Device

- Product name: ZigBee MINI motion sensor
- Manufacturer: _TZ30000_msl6wxk9
- Model identifier: TS0202
- Device type : 

  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/82883104/162635365-5dd2737f-2e91-4037-b983-4849a18d2f2a.png)
### Basic
 
![image](https://user-images.githubusercontent.com/82883104/162635261-cb9017c4-4450-48ee-b140-0ff767b73c4d.png)
### Identify
![image](https://user-images.githubusercontent.com/82883104/162635280-62eae584-1560-4073-b8c4-bc5708232526.png)
### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/82883104/162639007-04e4759d-06d1-4fde-b450-01131efa678d.png)
![image](https://user-images.githubusercontent.com/82883104/162639018-9028e1aa-5f41-441d-b99f-a6103f62cbee.png)
![image](https://user-images.githubusercontent.com/82883104/162639067-b92bcaa3-f45a-470c-9330-ddab25e92c86.png)

**Comment by Mimiix** [comment] 2022-04-10 20:42
The model ID and manufacturer name can be found in the basic cluster.

Also, please add screenshots of all clusters.

**Comment by KrOnAsK** [comment] 2022-04-10 20:47
Okay I updated the information

**Comment by Mimiix** [comment] 2022-04-10 20:57
Looks like this one is a duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5584

And it seems that the DDF there works. As there's not a pr with a ddf yet, I'll re open the other one. Perhaps you can submit the pr when it works for you.

**Closed by Mimiix** 2022-04-10 20:57 UTC
Labels: Device Request, Incomplete issue

**Comment by KrOnAsK** [comment] 2022-04-11 06:22
Hi I am kinda new to this all could u explain the abbreviations u used ?

**Comment by KrOnAsK** [comment] 2022-04-11 06:49
Thanks but that is above my level of competency, I have no idea how the DDF works or how to create a good pr.

**Comment by Mimiix** [comment] 2022-04-11 07:14
Feel free to ask there :)

**Comment by KrOnAsK** [comment] 2022-04-11 07:15
Will do thanks again for your help
