### ISSUE TITLE
v2.27.0 is crashed on macOS 14.5 during pairing

### ISSUE THREAD

**Issue by RP-Develop** [dresden-elektronik/deconz-rest-plugin#7771] opened 2024-05-15 16:48 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

v2.27.0 is crashed on macOS 14.5 during pairing 

### Steps to reproduce the behavior

1. Start deConz
2. switch to Control and start pairing - "Enable permit join" (not via Phoscon)
3. start the process on the device - in my case IKEA Badring
4. after a while the deConz app was closed

### Expected behavior

-

### Screenshots

<img width="997" alt="deCONZ wurde unerwartet beendet" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/b8350d4c-ae7b-45d5-9a5a-443e474ca79d">

`
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               deCONZ [21680]
Path:                  /Applications/deCONZ.app/Contents/MacOS/deCONZ
Identifier:            de.phoscon.deconz
Version:               2.27.0 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-05-15 14:49:29.9584 +0200
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        78AE6119-A7D7-BC0D-8DC1-8D94E068485D

Sleep/Wake UUID:       F06512DE-3CF1-4D85-8E31-086C2DBEF297

Time Awake Since Boot: 91000 seconds
Time Since Wake:       8428 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x17434D4A2)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000060
Exception Codes:       0x0000000000000001, 0x0000000000000060

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [21680]

VM Region Info: 0x60 is not in any region.  Bytes before following region: 4331765664
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102318000-102404000    [  944K] r-x/r-x SM=COW  /Applications/deCONZ.app/Contents/MacOS/deCONZ

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x17434D4A2)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libde_rest_plugin.dylib       	       0x17434d4a2 DeviceDescriptions::get(Resource const*, DDF_MatchControl) + 306
1   libde_rest_plugin.dylib       	       0x17434e0ae DeviceDescriptions::handleDDFInitRequest(Event const&) + 158
2   QtCore                        	       0x10e500f95 0x10e2d5000 + 2277269
3   libde_rest_plugin.dylib       	       0x1742d5c14 EventEmitter::eventNotify(Event const&) + 52
4   libde_rest_plugin.dylib       	       0x17443a22a EventEmitter::process() + 618
5   libde_rest_plugin.dylib       	       0x1743e6212 DeRestPluginPrivate::apsdeDataIndication(deCONZ::ApsDataIndication const&) + 2210
6   QtCore                        	       0x10e5010d5 0x10e2d5000 + 2277589
7   libdeCONZ.1.2.0.dylib         	       0x10b0459e7 deCONZ::ApsController::apsdeDataIndication(deCONZ::ApsDataIndication const&) + 55
8   deCONZ                        	       0x10237c2fd zmController::onApsdeDataIndication(deCONZ::ApsDataIndication const&) + 12333
9   deCONZ                        	       0x10239dafd zmMaster::processPacked(zm_command const*) + 4781
10  deCONZ                        	       0x1023a1c82 0x102318000 + 564354
11  deCONZ                        	       0x1023285ea protocol_receive + 282
12  deCONZ                        	       0x1023a1788 SerialCom::readyRead() + 648
13  deCONZ                        	       0x1023a13ae 0x102318000 + 562094
14  QtCore                        	       0x10e4f8b9f QObject::event(QEvent*) + 943
15  QtWidgets                     	       0x10b9ef9ea QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
16  QtWidgets                     	       0x10b9f0e11 QApplication::notify(QObject*, QEvent*) + 497
17  QtCore                        	       0x10e4cda34 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
18  QtCore                        	       0x10e4ced79 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 809
19  libqcocoa.dylib               	       0x10c7ea259 0x10c7b0000 + 238169
20  libqcocoa.dylib               	       0x10c7ea9c8 0x10c7b0000 + 240072
21  CoreFoundation                	    0x7ff8115617d6 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
22  CoreFoundation                	    0x7ff811561779 __CFRunLoopDoSource0 + 157
23  CoreFoundation                	    0x7ff811561548 __CFRunLoopDoSources0 + 215
24  CoreFoundation                	    0x7ff8115601b8 __CFRunLoopRun + 919
25  CoreFoundation                	    0x7ff81155f859 CFRunLoopRunSpecific + 557
26  HIToolbox                     	    0x7ff81c452a09 RunCurrentEventLoopInMode + 292
27  HIToolbox                     	    0x7ff81c452816 ReceiveNextEventCommon + 665
28  HIToolbox                     	    0x7ff81c452561 _BlockUntilNextEventMatchingListInModeWithFilter + 66
29  AppKit                        	    0x7ff814b31c61 _DPSNextEvent + 880
30  AppKit                        	    0x7ff815445dc0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1273
31  AppKit                        	    0x7ff814b23075 -[NSApplication run] + 603
32  libqcocoa.dylib               	       0x10c7e962f 0x10c7b0000 + 235055
33  QtCore                        	       0x10e4c9acf QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
34  QtCore                        	       0x10e4ce042 QCoreApplication::exec() + 130
35  deCONZ                        	       0x102330bce main + 5838
36  dyld                          	       0x20263a366 start + 1942

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffbd1494 0x7ff7ffbcd000 + 17556

Thread 2:
0   ???                           	    0x7ff8a1726a78 ???
1   libsystem_kernel.dylib        	    0x7ff811446e46 __semwait_signal + 10
2   libsystem_c.dylib             	    0x7ff811339a61 nanosleep + 199
3   libdeCONZ.1.2.0.dylib         	       0x10b07461b U_thread_msleep + 75
4   deCONZ                        	       0x102323d4f 0x102318000 + 48463
5   libdeCONZ.1.2.0.dylib         	       0x10b07457e thread_func_wrapper + 14
6   libsystem_pthread.dylib       	    0x7ff81148418b _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81147fae3 thread_start + 15

Thread 3:: com.apple.CFSocket.private
0   ???                           	    0x7ff8a1726a78 ???
1   libsystem_kernel.dylib        	    0x7ff81144d2ca __select + 10
2   CoreFoundation                	    0x7ff8115893cf __CFSocketManager + 637
3   libsystem_pthread.dylib       	    0x7ff81148418b _pthread_start + 99
4   libsystem_pthread.dylib       	    0x7ff81147fae3 thread_start + 15

Thread 4:: Qt bearer thread
0   ???                           	    0x7ff8a1726a78 ???
1   libsystem_kernel.dylib        	    0x7ff81144b1f2 poll + 10
2   QtCore                        	       0x10e53001a qt_safe_poll(pollfd*, unsigned int, timespec const*) + 90
3   QtCore                        	       0x10e531a21 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 849
4   QtCore                        	       0x10e4c9acf QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
5   QtCore                        	       0x10e2f6603 QThread::exec() + 131
6   QtCore                        	       0x10e2f7619 0x10e2d5000 + 140825
7   libsystem_pthread.dylib       	    0x7ff81148418b _pthread_start + 99
8   libsystem_pthread.dylib       	    0x7ff81147fae3 thread_start + 15

Thread 5:: com.apple.NSEventThread
0   ???                           	    0x7ff8a1726a78 ???
1   libsystem_kernel.dylib        	    0x7ff8114443ce mach_msg2_trap + 10
2   libsystem_kernel.dylib        	    0x7ff811452c88 mach_msg2_internal + 84
3   libsystem_kernel.dylib        	    0x7ff81144b510 mach_msg_overwrite + 653
4   libsystem_kernel.dylib        	    0x7ff8114446bd mach_msg + 19
5   CoreFoundation                	    0x7ff811561909 __CFRunLoopServiceMachPort + 143
6   CoreFoundation                	    0x7ff81156037c __CFRunLoopRun + 1371
7   CoreFoundation                	    0x7ff81155f859 CFRunLoopRunSpecific + 557
8   AppKit                        	    0x7ff814c8fbbc _NSEventThread + 122
9   libsystem_pthread.dylib       	    0x7ff81148418b _pthread_start + 99
10  libsystem_pthread.dylib       	    0x7ff81147fae3 thread_start + 15

Thread 6:
0   ???                           	    0x7ff8a1726a78 ???
1   libsystem_kernel.dylib        	    0x7ff81144b1f2 poll + 10
2   deCONZ                        	       0x1023a202e 0x102318000 + 565294
3   deCONZ                        	       0x1023a243c 0x102318000 + 566332
4   libsystem_pthread.dylib       	    0x7ff81148418b _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff81147fae3 thread_start + 15

Thread 7:
0   runtime                       	    0x7ff7ffbef94c 0x7ff7ffbcd000 + 141644

Thread 8:
0   runtime                       	    0x7ff7ffbef94c 0x7ff7ffbcd000 + 141644

Thread 9:
0   runtime                       	    0x7ff7ffbef94c 0x7ff7ffbcd000 + 141644

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fdb13a66bf0  rbx: 0x0000000000000000  rcx: 0x0000000000000001  rdx: 0xffffffffffffffff
  rdi: 0x0000000000000000  rsi: 0x0000000001100004  rbp: 0x0000000308a31240  rsp: 0x0000000308a31180
   r8: 0x0000000000000054   r9: 0x00000000fec13041  r10: 0x00000000fea12826  r11: 0x0000000000000026
  r12: 0x0000000000001272  r13: 0x0000000174809ba8  r14: 0x0000000000004bee  r15: 0x0000600003784460
  rip: <unavailable>       rfl: 0x0000000000000287
 tmp0: 0x000000017434d469 tmp1: 0x000000017434d469 tmp2: 0x000000017496934c

Binary Images:
       0x202634000 -        0x2026c4fff dyld (*) <baa6f02e-dff3-3562-8c99-ea2820c91ad9> /usr/lib/dyld
       0x173d64000 -        0x173d7bfff libstd_otau_plugin.dylib (*) <d9ef1b21-0623-35bb-bc65-854f19dc5bc9> /Applications/deCONZ.app/Contents/Plugins/libstd_otau_plugin.dylib
       0x174dbb000 -        0x1750fafff libcrypto.3.dylib (*) <05fbb421-4ad3-3c2d-9312-ce83bff89bac> /Applications/deCONZ.app/Contents/Frameworks/libcrypto.3.dylib
       0x173c6c000 -        0x173c73fff libqgenericbearer.dylib (*) <8f60002d-17c7-31a6-81cf-51db475dff5c> /Applications/deCONZ.app/Contents/Plugins/bearer/libqgenericbearer.dylib
       0x1742cf000 -        0x1745fafff libde_rest_plugin.dylib (*) <596aee00-6c65-3f10-a7dd-86ce933c095e> /Applications/deCONZ.app/Contents/Plugins/libde_rest_plugin.dylib
       0x173cf7000 -        0x173d12fff org.qt-project.QtWebSockets (5.15) <ab8b8687-10f7-392d-81fb-0c38aff81a5f> /Applications/deCONZ.app/Contents/Frameworks/QtWebSockets.framework/Versions/5/QtWebSockets
       0x10cd8a000 -        0x10cd96fff libobjc-trampolines.dylib (*) <a994ca6d-8d6a-312f-a7d9-a1a01cb10e70> /usr/lib/libobjc-trampolines.dylib
       0x1195b8000 -        0x11964efff libqwebp.dylib (*) <e5bd754e-c8cf-3788-b2d6-347527b2aade> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqwebp.dylib
       0x10cd44000 -        0x10cd48fff libqwbmp.dylib (*) <75d3fbd1-5eea-3c2e-b14e-822a265afa67> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqwbmp.dylib
       0x119426000 -        0x11948cfff libqtiff.dylib (*) <4a7c57bc-ce03-315d-a828-80b3502f75cc> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqtiff.dylib
       0x10cd2c000 -        0x10cd30fff libqtga.dylib (*) <d8f0bcf5-90d7-3025-8af5-f959dbb2d68b> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqtga.dylib
       0x10cd11000 -        0x10cd16fff libqmacjp2.dylib (*) <6ebf7c32-c2dc-32ab-bd6f-e79f35b8095f> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqmacjp2.dylib
       0x10b9ba000 -        0x10b9c0fff libqmacheif.dylib (*) <f878d1f1-c295-3e94-b5ea-d53a00776427> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqmacheif.dylib
       0x119349000 -        0x1193adfff libqjpeg.dylib (*) <18b65be7-2104-3d96-9a0c-95dc8839ae72> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqjpeg.dylib
       0x10b99e000 -        0x10b9a3fff libqico.dylib (*) <6a858a22-8e2e-3f6d-b9ac-438c4749c8b7> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqico.dylib
       0x10b97e000 -        0x10b985fff libqicns.dylib (*) <87d3521f-7d97-3b63-b928-0c60e87dca21> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqicns.dylib
       0x10b54e000 -        0x10b555fff libqgif.dylib (*) <bd1de7f5-eacb-304c-b93c-79a6f06a9ec6> /Applications/deCONZ.app/Contents/Plugins/imageformats/libqgif.dylib
       0x10b900000 -        0x10b925fff libqmacstyle.dylib (*) <5b9adb30-04ac-325f-bb42-6e40df6d7e6a> /Applications/deCONZ.app/Contents/Plugins/styles/libqmacstyle.dylib
       0x10c7b0000 -        0x10c91efff libqcocoa.dylib (*) <d4ab240b-4535-3aec-b72b-5ffc4750e4e5> /Applications/deCONZ.app/Contents/Plugins/platforms/libqcocoa.dylib
       0x10acb1000 -        0x10ad10fff org.qt-project.QtDBus (5.15) <f6c498cb-9925-350d-b597-6c3f102e09d5> /Applications/deCONZ.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x10adf9000 -        0x10ae24fff org.qt-project.QtPrintSupport (5.15) <be399b08-503c-39e3-acac-268a9d866624> /Applications/deCONZ.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10b16e000 -        0x10b279fff libdeconzsqlite3.dylib (*) <66aa6b48-762d-3cf2-acce-5d7a7a2c1f9c> /Applications/deCONZ.app/Contents/Frameworks/libdeconzsqlite3.dylib
       0x10b041000 -        0x10b088fff libdeCONZ.1.2.0.dylib (*) <3d813975-99da-3c65-bde5-6e05b50b7531> /Applications/deCONZ.app/Contents/Frameworks/libdeCONZ.1.2.0.dylib
       0x10b9df000 -        0x10be25fff org.qt-project.QtWidgets (5.15) <b432d666-dcab-320a-8496-78a67f554c0e> /Applications/deCONZ.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10cdbb000 -        0x10d2a4fff org.qt-project.QtGui (5.15) <cbcec35a-ee54-354f-9c2b-188ac6b2790d> /Applications/deCONZ.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10af8f000 -        0x10af9bfff org.qt-project.QtSerialPort (5.15) <2ab6bad5-6934-3745-add9-3eb75e833ba8> /Applications/deCONZ.app/Contents/Frameworks/QtSerialPort.framework/Versions/5/QtSerialPort
       0x10b584000 -        0x10b694fff org.qt-project.QtNetwork (5.15) <c09a61c8-678f-339b-ad2e-b2a4a9b16bab> /Applications/deCONZ.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10e2d5000 -        0x10e845fff org.qt-project.QtCore (5.15) <c723812a-f7a5-3001-98d5-e60e8daa6ffb> /Applications/deCONZ.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
    0x7ff7ffbcd000 -     0x7ff7ffbfcfff runtime (*) <b091dec9-37ac-322a-bd9d-fc5dc22b0082> /usr/libexec/rosetta/runtime
       0x10a60c000 -        0x10a65ffff libRosettaRuntime (*) <8a85f070-3849-3b55-adde-143cc5902f92> /Library/Apple/*/libRosettaRuntime
       0x102318000 -        0x102403fff de.phoscon.deconz (2.27.0) <e1a94b0e-f41c-3599-9974-7ad3a85a7c81> /Applications/deCONZ.app/Contents/MacOS/deCONZ
    0x7ff8114e5000 -     0x7ff81197effc com.apple.CoreFoundation (6.9) <a32f4005-d666-32c2-8e52-f67fc64616e0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81c424000 -     0x7ff81c6beff3 com.apple.HIToolbox (2.1.1) <de4aeb8b-676c-3a36-9364-1cdee78a3b41> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff814af3000 -     0x7ff815f21ff2 com.apple.AppKit (6.9) <33ecd3dc-c895-35e2-a1fd-c1761b155964> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff811443000 -     0x7ff81147dff7 libsystem_kernel.dylib (*) <13597eeb-2ea0-3d48-8be1-dfc4872a784b> /usr/lib/system/libsystem_kernel.dylib
    0x7ff81132a000 -     0x7ff8113b1ff7 libsystem_c.dylib (*) <93fb3816-608b-33af-83d2-209b4bd673ad> /usr/lib/system/libsystem_c.dylib
    0x7ff81147e000 -     0x7ff811489ff7 libsystem_pthread.dylib (*) <25b2f3eb-07b4-3cb9-9457-2c26210c27c8> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=513.3M resident=0K(0%) swapped_out_or_unallocated=513.3M(100%)
Writable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG image                           284K       28 
ColorSync                          240K       28 
CoreAnimation                      272K       31 
CoreGraphics                        20K        3 
CoreUI image data                 3116K       22 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                             1.6G       52 
MALLOC guard page                  192K       12 
Rosetta Arena                     4096K        2 
Rosetta Generic                   1828K      454 
Rosetta IndirectBranch            1024K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               160K       16 
Rosetta Thread Context             160K       16 
STACK GUARD                         12K        3 
Stack                             12.1M        9 
Stack Guard                       56.0M        6 
VM_ALLOCATE                        464K       35 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__CTF                               824        1 
__DATA                            24.1M      420 
__DATA_CONST                      19.7M      231 
__DATA_DIRTY                       817K      116 
__FONT_DATA                        2352        1 
__LINKEDIT                       147.4M       35 
__OBJC_RO                         71.8M        1 
__OBJC_RW                         2197K        2 
__TEXT                           366.0M      429 
dyld private memory                260K        2 
mapped file                        1.7G      259 
shared memory                     1320K       15 
===========                     =======  ======= 
TOTAL                              4.1G     2236 
TOTAL, minus reserved VM space     4.1G     2236 

`

### Environment

- Host system: macOS 14.5
- Running method: via Rosetta
- Firmware version: 26510900
- deCONZ version (not Home assistant Addon version!): (2.27.0)
- Device: ConBee III 
- Do you use an USB extension cable: yes 
- Is there any other USB or serial devices connected to the host system? no

### deCONZ Logs

`
18:30:13:035 send permit join, duration: 59
18:30:14:008 neighbor 0xB0C7DEFFFE62A297 is unknown child
18:30:14:462 CTRL create node 0xB0C7DEFFFE62A297, nwk: 0xF75E
18:30:20:078 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
18:30:24:081 CTRL db store gui node 00:21:2e:ff:ff:05:43:ff
18:30:24:084 CTRL db store gui node b0:c7:de:ff:fe:62:a2:97
18:30:24:087 saved node state in 0 ms
18:30:25:867 0xB0C7DEFFFE62A297 0xF75E nwk changed to 0x176A
18:30:25:873 device announce 0xB0C7DEFFFE62A297 (0x176A) mac capabilities 0x80
18:30:25:874 set fast probe address to 0xB0C7DEFFFE62A297 (0x176A)
18:30:25:875 FP indication 0x0000 / 0x0013 (0xB0C7DEFFFE62A297 / 0xF75E)
18:30:25:876                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:25:877 device announce 0xB0C7DEFFFE62A297 (0x176A) mac capabilities 0x80
18:30:25:878 ZDP get node descriptor for 0x176A
18:30:25:878 DEV Tick.Join: event/device.anounce
18:30:25:879 DEV Tick: fast poll 0xB0C7DEFFFE62A297, mac capabilities: 0x80
18:30:25:996 DB pushZdpDescriptorDb()
18:30:26:000 DB UPDATE device_descriptors SET data = x'0240807c11525200002c520000', timestamp = 1715790625 WHERE device_id = (SELECT id FROM devices WHERE mac = 'b0:c7:de:ff:fe:62:a2:97') AND endpoint = 0 AND type = 2
18:30:26:001 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'0240807c11525200002c520000', 1715790625 FROM devices WHERE mac = 'b0:c7:de:ff:fe:62:a2:97'
18:30:26:006 FP indication 0x0000 / 0x8002 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:26:007                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:26:008 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) cluster 0x8002
18:30:26:009 ZDP get active endpoints for 0x176A
18:30:26:014 [2] get active endpoints for 0xb0c7defffe62a297
18:30:26:015 ZDP get active endpoints for 0x176A
18:30:26:888 FP indication 0x0000 / 0x8005 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:26:889                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:26:890 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) cluster 0x8005
18:30:26:891 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) clear timeout on cluster 0x8005
18:30:26:892 ZDP get simple descriptor 0x01 for 0x176A
18:30:26:899 [3] get simple descriptor 0x01 for 0xb0c7defffe62a297
18:30:26:899 ZDP get simple descriptor 0x01 for 0x176A
18:30:26:955 FP indication 0x0000 / 0x8005 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:26:957                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:26:958 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) cluster 0x8005
18:30:26:984 wait response fastEnddeviceProbe() 0xB0C7DEFFFE62A297, elapsed 84 ms
18:30:27:899 FP indication 0x0000 / 0x8005 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:27:901                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:27:902 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) cluster 0x8005
18:30:27:912 wait response fastEnddeviceProbe() 0xB0C7DEFFFE62A297, elapsed 1011 ms
18:30:27:947 DB pushZdpDescriptorDb()
18:30:27:949 DB UPDATE device_descriptors SET data = x'0104010204010800000100030020000005050b7cfc81fc03030004001900', timestamp = 1715790627 WHERE device_id = (SELECT id FROM devices WHERE mac = 'b0:c7:de:ff:fe:62:a2:97') AND endpoint = 1 AND type = 4
18:30:27:950 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 1, 4, x'0104010204010800000100030020000005050b7cfc81fc03030004001900', 1715790627 FROM devices WHERE mac = 'b0:c7:de:ff:fe:62:a2:97'
18:30:27:954 FP indication 0x0000 / 0x8004 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:27:955                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:27:956 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) cluster 0x8004
18:30:27:956 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) clear timeout on cluster 0x8004
18:30:27:962 [3.1] get IAS Zone type for 0xb0c7defffe62a297
18:30:28:919 DB pushZdpDescriptorDb()
18:30:28:922 FP indication 0x0000 / 0x8004 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:28:923                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:28:923 ZDP indication search sensors 0xB0C7DEFFFE62A297 (0x176A) cluster 0x8004
18:30:28:931 wait response fastEnddeviceProbe() 0xB0C7DEFFFE62A297, elapsed 968 ms
18:30:28:970 DJS evaluate()
18:30:28:971 DJS_GetAttributeValue
18:30:28:972 DJS_SetItemVal: attr/manufacturername --> IKEA of Sweden
18:30:28:973 DJS result  IKEA of Sweden, memory peak: 5079 bytes, freed: 4039
18:30:28:974 b0:c7:de:ff:fe:62:a2:97/attr/manufacturername expression: Item.val = Attr.val --> IKEA of Sweden
18:30:28:975 FP indication 0x0104 / 0x0000 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:28:976                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:28:987 wait response fastEnddeviceProbe() 0xB0C7DEFFFE62A297, elapsed 1024 ms
18:30:29:896 void DeRestPluginPrivate::handleIasZoneClusterIndication(const deCONZ::ApsDataIndication &, deCONZ::ZclFrame &),196: assertion 'itemIasState' failed
18:30:29:898 void DeRestPluginPrivate::handleIasZoneClusterIndication(const deCONZ::ApsDataIndication &, deCONZ::ZclFrame &),197: assertion 'itemPending' failed
18:30:29:900 FP indication 0x0104 / 0x0500 (0xB0C7DEFFFE62A297 / 0x176A)
18:30:29:901                       ...     (0xB0C7DEFFFE62A297 / 0x176A)
18:30:29:902 Clear fast probe timeout for cluster 0x0500, 0xB0C7DEFFFE62A297
18:30:29:903 [4.1] Get model ID
18:30:30:068 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0

`
Then came the crash.

### Additional context

It was tested on a MacBookAir with Apple M1 (my test environment). No other devices was paired. I started with an empty deConz system.

**Comment by Mimiix** [comment] 2024-05-15 16:50
Duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7698#issuecomment-2112064025

**Closed** 2024-05-15 16:50 UTC
Labels: Bug report
