### ISSUE TITLE
Ikea Parasoll

### ISSUE THREAD

**Issue by hyper2910** [dresden-elektronik/deconz-rest-plugin#7500] opened 2023-12-29 11:03 UTC
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Parasoll

### Manufacturer

Ikea

### Model identifier

E2013

### Device type to add

None

### Node info

![Screenshot 2023-12-29 115223](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/e3525d12-6cd4-49af-8d41-9e326f6cc686)

### Endpoints and clusters

![Screenshot 2023-12-29 120124](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/74a80805-fd04-4ce0-b084-55e550bdf129)
![Screenshot 2023-12-29 120056](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/fa470cc9-ff8d-464d-ac89-f48c12fd7487)

### Basic

![Screenshot 2023-12-29 115941](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/daf89fbc-c0a0-421d-a9b0-5accc40ff2ba)

**Comment by hyper2910** [comment] 2023-12-29 11:16
![Screenshot 2023-12-29 121356](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/22e91903-df5a-419b-a352-cc4d5600894c)
![Screenshot 2023-12-29 121459](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/47922833-c0c2-45cd-b37b-71b93ab702df)
![Screenshot 2023-12-29 121517](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/33656e8c-bae0-4ccb-8c25-4746f2c6f9f6)

**Comment by Mimiix** [comment] 2023-12-29 12:09
Hi,

Clearly you didn't search as it's a duplicate of #7417 

Closing

**Closed by Mimiix** 2023-12-29 12:09 UTC
Labels: Device Request
