### ISSUE TITLE
CLIPSensors must be visible to the user? [improvement]

### ISSUE THREAD

**Issue by mattreim** [dresden-elektronik/deconz-rest-plugin#7647] opened 2024-02-27 22:27 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

These CLIPSensors must be visible to the user? They are actually only intended for internal processing and not for external processing.

Or can you get your own folder? (e.g. FakeSensors;)

### Steps to reproduce the behavior

Sensor list

### Expected behavior

No FakeSensors to see

### Screenshots

RESTED:

![CLIPPresence](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/723cc11f-8e07-414b-88ce-240e0e76015d)

![CLIPGenericStatus](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/51097127-5d7d-4f3b-b45f-d7c110494499)

These have been added with version 2.26.1-beta.

![CLIPDaylightOffset](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/ec292d2b-b204-4078-89b3-6c9d01185e92)

ioBroker:

![ioBroker](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/afd6fd26-e10a-4739-b05b-701baa19435b)

### Environment

- Host system: (Raspberry Pi / PC / NAS / MAC)
- Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
- Firmware version: (26xxyy00)
- deCONZ version (not Home assistant Addon version!): (2.xx.yy)
- Device: (ConBee I / ConBee II / ConBee III / RaspBee I / RaspBee II)
- Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II/III
- Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by ebaauw** [comment] 2024-02-28 06:29
The CLIP sensors should definitely be exposed over the API.  Whether they should be visible to users is up to the API client interacting with the user, ioBroker in your case?

**Comment by ebaauw** [comment] 2024-02-28 10:40
My external programs don't have this problem, as they explicitly offer the feature to interact with CLIP sensors.  It's up to the user to configure the program which sensors should be visible.  Phoscon as external program doesn't have this issue, as it explicitly filters out CLIP sensors.  Exposing CLIP sensors this way is according to spec, and not a bug.

**Comment by mattreim** [comment] 2024-02-28 10:51
Ok thanks, then I'll probably have to live with it.

**Comment by mattreim** [comment] 2024-02-28 15:53
Just to understand: the API cannot access other folders such as secrets?

![DB-Folder](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/80219712/d83f2318-e273-41e8-a1ae-62d1e1f43134)

**Comment by ebaauw** [comment] 2024-02-28 16:10
This looks like the database.  It contains tables, not folders.  And its structure is undocumented, and not exposed by the API.  See https://dresden-elektronik.github.io/deconz-rest-doc/ for an overview of the API.

**Comment by Mimiix** [comment] 2024-02-28 19:51
Closing as this is not a bug

**Closed by Mimiix** 2024-02-28 19:51 UTC
Labels: Bug report
