### ISSUE TITLE
IKEA TRADFRI motion E1745 sensor duration

### ISSUE THREAD

**Issue by dracula385** [dresden-elektronik/deconz-rest-plugin#6336] opened 2022-09-16 19:49 UTC
## Describe the bug

When using the Ikea E1745 Motion sensor, and motion is detected, after 60 sec sensor goes to OFF state and  until 90 sec cooldown period stays in OFF state. That causes the sensor reported to HA goes constantly ON-OFF-ON-OFF when there is a constant motion because of extra 30 sec delay.

## Expected behavior

If there is a constant motion there sensor should stay in ON state like in screenshot below.
In the screenshot below Motion Sensor 1, Kitchen Motion Sensor 2, Drax Room Motion Sensor are connected to HA via Deconz.
Motion Sensor Test occupancy is connected to HA via Zigbe2mqtt where Zigbe2mqtt has 90 sec duration set for the sensor to match the delay and keep the sensor in ON state

## Screenshots

 ![image](https://user-images.githubusercontent.com/6754999/190718209-6b4f7006-a411-4f28-bd3d-9af0062aab73.png)

## Environment

 - Host system: PC
 - IKEA E1745 Motion Sensor
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: (26720700)
 - deCONZ version: (2.17.07)
 - Device:ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? Sonoff Zigbee 3.0 USB dongle

**Comment by ebaauw** [comment] 2022-09-16 22:48
Set `config.duration` to 0 to prevent deCONZ from clearing `state.presence` based on that setting, using `config.delay` as reported by the sensor instead.

**Comment by Mimiix** [comment] 2022-09-17 07:35
Hi,

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-09-17 07:35 UTC
Labels: Bug report

**Comment by dracula385** [comment] 2022-09-17 08:09
Can I just mention here you cannot set the duration to 0. I will open a topic of forum. Thanks
