### ISSUE TITLE
Problem with Phoscon interface after update 2.17.0 beta

### ISSUE THREAD

**Issue by RickyTR** [dresden-elektronik/deconz-rest-plugin#6147] opened 2022-06-21 05:40 UTC
## Describe the bug
The Phoscon web interface is not available. 
When I try to access the site I receive the following error:

`This is not the page you are looking for

The file / couldn't be found. `

Rest API works as expected.

## Steps to reproduce the behavior

Just go the web site

## Environment

 - Host system: PC
 - Running method: Windows
 - Firmware version: 26720700
 - deCONZ version: 2.17.00
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment] 2022-06-21 06:28
Hi,

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum.

Please note that Phoscon bugs are collected at the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-06-21 06:28 UTC
Labels: Bug report
