### ISSUE TITLE
RGBGenie ZB-5001  Remote Control 

### ISSUE THREAD

**Issue by rweise** [dresden-elektronik/deconz-rest-plugin#3250] opened 2020-09-12 06:57 UTC
-> Add it to the open Request

**Comment by SwoopX** [comment] 2020-09-13 09:58
I'm closing this one as it doesn't follow the required issue template. We request that information to gain a better understanding of your environment and possible root causes. Additionally, this is another duplicate for the device. Please use the search function to flip through the issues.

In case your question or situation is not yet addressed, feel free to open another issue based on the templates. Thanks!

**Closed** 2020-09-13 18:47 UTC
Labels: Device Request
