### ISSUE TITLE
Upgrade from 2.12.6 -> 2.13.6 doesn't work

### ISSUE THREAD

**Issue by donnib** [dresden-elektronik/deconz-rest-plugin#5667] opened 2022-01-14 12:09 UTC
## Describe the bug

Upgrade from 2.12.6 to 2.13.03 doesn't work
## Steps to reproduce the behavior

1. wget http://deconz.dresden-elektronik.de/raspbian/beta/deconz-2.13.03-qt5.deb
2. sudo dpkg -i deconz-2.13.03-qt5.deb
3. sudo apt-get install -f
4. => deconz doesn't launch e.g nothing happens
5. downgrade to 2.12.6 => everything works again.

## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment] 2022-01-14 12:12
Hi,

As this is not a bug report as described in #5113, I am closing this issue.

Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-01-14 12:12 UTC
Labels: Bug report
