### ISSUE TITLE
Cannot upgrade firmware (tried docker and windows)

### ISSUE THREAD

**Issue by ualex73** [dresden-elektronik/deconz-rest-plugin#5327] opened 2021-09-27 14:45 UTC
## Describe the bug

I have issues with my ConbeeII disconnecting from the USB port regularly, so I am trying to upgrade the firmware to a later version. I followed https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually with Docker and Windows, but neither of them works :-(
The flasher sees the com port and also detects the old firmware version, but after resetting the port ... It never connects successfully.

The screenshot shows where it fails on Windows10:
![conbee2-firmware-issue](https://user-images.githubusercontent.com/6293852/134930742-841a8840-d192-4566-b145-34d7458518ac.png)

## Steps to reproduce the behavior
Most likely not all users are impacted, but for me, firmware update does not work.

## Expected behavior
Firmware update works

## Environment
Docker and Windows 10

 - Host system: PC
 - Running method: Marthoc Docker container ^ Windows
 - Firmware version: (264A0700)
 - deCONZ version: (2.12.06)
 - Device: ConBee II 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so: No

**Comment by Mimiix** [comment] 2021-09-27 15:09
Hi, 

As this is not a bug report as per #5113, I am closing this issue. 

Feel free to post on the forums.

Kind regards,

**Closed by Mimiix** 2021-09-27 15:09 UTC
Labels: Bug report
