### ISSUE TITLE
Deconz uses a lot of energy/performance

### ISSUE THREAD

**Issue by antgustech** [dresden-elektronik/deconz-rest-plugin#6945] opened 2023-05-04 13:47 UTC
## Describe the bug
Upon inspecting my server with Powertop, I noticed that my deconz docker container uses a lof of performance&energy.

![energy](https://user-images.githubusercontent.com/8721113/236223783-8b381042-eac4-4e0a-8a6c-dcccc2af200f.PNG)

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

  1. I use the following docker compose file
`
version: "3.8"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: unless-stopped
    privileged: true
    ports: 
      - 81:81
      - 443:443
      - 5900:5900
      - 6080:6080 
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0 #Must be USB port where Conbee II stick is inserted
    environment:
      - TZ=Europe/Stockholm
      - DECONZ_WEB_PORT=81
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=0
      - DECONZ_VNC_PASSWORD=xxx
     `
  3. Launch with "docker compose up -d"
  4. Launch "sudo powertop"

## Expected behavior
Not sure exactly, but less than 1w of energy consumption

 - Host system: Intel NUC
 - Running method: Debian, docker container deconzcommunity/deconz:stable
 - Firmware version: (26780700)
 - Device: ConBee II 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment] 2023-05-04 13:51
Hi. 


As this is not a bug report as described in #5113 , i am closing this issue.

Feel free to open a topic on the forums.

Kind regards, Dennis

**Closed by Mimiix** 2023-05-04 13:51 UTC
Labels: Bug report
