### ISSUE TITLE
Xiaomi Mi Light Detection Sensor stops updating 

### ISSUE THREAD

**Issue by ParanoidiordnA** [dresden-elektronik/deconz-rest-plugin#7898] opened 2024-08-23 07:14 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

After updating deconz from version 2.26.3 to 2.27.6 my Xiaomi Mi Light Detection Sensors connect show as connected in Phoscon.app but stop delivering data after a while, as seems this morning „last update 9 hours ago“. I also tried deconz 2.28.0, same effect. 

### Steps to reproduce the behavior

Update deconz to version 2.27.6
Wait

### Expected behavior

-

### Environment

- Host system: Raspberry Pi
- Running method: Raspbian
- Firmware version: 26720700
- deCONZ version 2.27.6
- Device: ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? No.

**Comment by Mimiix** [comment] 2024-08-23 13:07
Hi,

As this is not a bug report as described in #5113, I am closing this issue.

Feel free to open a post on the forums.

Kind regards,

**Closed by Mimiix** 2024-08-23 13:07 UTC
Labels: Bug report
