### ISSUE TITLE
Conbee III in Raspi/Portainer enviroment not working

### ISSUE THREAD

**Issue by TSC-X2** [dresden-elektronik/deconz-rest-plugin#7810] opened 2024-06-09 17:41 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I have a Portainer enviroment running on my Raspberry Pi but i dont get the Conbee 3 working on it.
The deconz is running ant the Phoscon App is reachable via browser. In the Gateway Settings is the FIrmware status "Not connected". I'm using a USB extension cable and the COnbee is the only USB device. It is detected at ttyUSB0.

### Steps to reproduce the behavior

This are my Settings:

version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    privileged: true # This is important! Without it, the deCONZ image won't be able to connect to Conbee III.
    ports:
      - 80:80
      - 8443:8443
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyUSB0 # This is the USB device that Conbee III is running on.
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyUSB0 # This is the USB device that Conbee III is running on.
      - DECONZ_START_VERBOSE=0

### Expected behavior

Conbee is deteced

### Environment

- Host system: (Raspberry Pi)
- Running method: (deconz-docker container )
- Firmware version: (26xxyy00)
- deCONZ version (not Home assistant Addon version!): (2.26.3)
- Device: (ConBee III )
- Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II/III
- Is there any other USB or serial devices connected to the host system? If so: NO

### deCONZ Logs

[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.26.3
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 8443
[deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --dev-test-managed=0 --http-port=80 --ws-port=8443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
19:21:04:205 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
19:21:04:253 /opt/deCONZ/config.ini exists and is writeable
19:21:04:253 /opt/deCONZ/zll.db exists and is writeable
19:21:04:453 dev /dev/ttyAMA0
19:21:04:475 COM: /dev/ttyUSB0 / serialno: , ConBee
19:21:04:476 ZCLDB init file /opt/deCONZ/zcldb.txt
19:21:04:623 DDF enabled for Gold status
19:21:05:993 gw run mode: normal
19:21:05:993 GW sd-card image version file does not exist: /opt/deCONZ/gw-version
19:21:05:993 sd-card cid: 035344534c36344780ffffffff00f96f
19:21:05:995 DB sqlite version 3.42.0
19:21:05:997 DB PRAGMA page_count: 46
19:21:05:997 DB PRAGMA page_size: 4096
19:21:05:997 DB PRAGMA freelist_count: 0
19:21:05:997 DB file size 188416 bytes, free pages 0
19:21:05:997 DB PRAGMA user_version: 9
19:21:05:997 DB cleanup
19:21:05:998 DB create temporary views
19:21:06:049 [INFO] - Timezone read is 'Etc/UTC'
19:21:06:049 [INFO] - Environment variable TZ found: Europe/Berlin...
19:21:06:051 Started websocket server on 0.0.0.0, port: 8443
19:21:06:053 [INFO] - Found file containing button maps. Parsing data...
19:21:06:089 [INFO] - Button maps loaded.
19:21:06:092 found node plugin: /usr/share/deCONZ/plugins/libde_rest_plugin.so - REST API Plugin
19:21:06:095 found node plugin: /usr/share/deCONZ/plugins/libstd_otau_plugin.so - STD OTAU Plugin
19:21:06:159 dlg action: Read binding table
19:21:07:190 dev /dev/ttyAMA0
19:21:07:205 COM: /dev/ttyUSB0 / serialno: , ConBee
19:21:13:976 DEV Tick.Init: booted after 8000 seconds
19:21:20:086 dev /dev/ttyAMA0
19:21:20:105 COM: /dev/ttyUSB0 / serialno: , ConBee
19:21:26:976 start reconnect to network
19:21:31:976 failed to reconnect to network try=1
19:21:32:818 New websocket 192.168.1.178:62655 (state: 3) 
19:21:34:073 dev /dev/ttyAMA0
19:21:34:095 COM: /dev/ttyUSB0 / serialno: , ConBee
19:21:36:645 Websocket disconnected 192.168.1.178:62655, state: 0, close-code: 1001, reason: 
19:21:36:976 try to reconnect to network try=2
19:21:38:702 Invalid admin password hash
19:21:41:184 created username: 92A746FEC6, devicetype: Phoscon#B2512x1284
19:21:41:976 try to reconnect to network try=3
19:21:43:093 New websocket 192.168.1.178:62699 (state: 3) 
19:21:45:037 dev /dev/ttyAMA0
19:21:45:050 COM: /dev/ttyUSB0 / serialno: , ConBee
19:21:45:905 Websocket disconnected 192.168.1.178:62699, state: 0, close-code: 1001, reason: 
19:21:46:977 failed to reconnect to network try=4
19:21:47:132 New websocket 192.168.1.178:62707 (state: 3) 
19:21:51:975 failed to reconnect to network try=5
19:21:56:975 failed to reconnect to network try=6
19:21:59:076 dev /dev/ttyAMA0
19:21:59:090 COM: /dev/ttyUSB0 / serialno: , ConBee
19:22:01:975 try to reconnect to network try=7
19:22:06:976 try to reconnect to network try=8
19:22:09:084 dev /dev/ttyAMA0
19:22:09:097 COM: /dev/ttyUSB0 / serialno: , ConBee
19:22:11:976 failed to reconnect to network try=9
19:22:16:976 failed to reconnect to network try=10
19:22:21:976 reconnect network failed, try later
19:22:21:976 start reconnect to network
19:22:23:086 dev /dev/ttyAMA0
19:22:23:100 COM: /dev/ttyUSB0 / serialno: , ConBee
19:22:26:976 try to reconnect to network try=1
19:22:31:975 try to reconnect to network try=2
19:22:34:074 dev /dev/ttyAMA0
19:22:34:088 COM: /dev/ttyUSB0 / serialno: , ConBee
19:22:36:976 failed to reconnect to network try=3
19:22:41:976 failed to reconnect to network try=4
19:22:46:975 failed to reconnect to network try=5
19:22:48:072 dev /dev/ttyAMA0
19:22:48:086 COM: /dev/ttyUSB0 / serialno: , ConBee
19:22:51:976 try to reconnect to network try=6
19:22:56:976 try to reconnect to network try=7
19:22:59:092 dev /dev/ttyAMA0
19:22:59:106 COM: /dev/ttyUSB0 / serialno: , ConBee
19:23:01:976 failed to reconnect to network try=8
19:23:06:975 failed to reconnect to network try=9
19:23:11:975 failed to reconnect to network try=10
19:23:13:078 dev /dev/ttyAMA0
19:23:13:093 COM: /dev/ttyUSB0 / serialno: , ConBee
19:23:16:976 reconnect network failed, try later
19:23:16:976 start reconnect to network
19:23:21:975 try to reconnect to network try=1

**Comment by Mimiix** [comment] 2024-06-09 17:46
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Please open an topic on the forums.

Kind regards,
Dennis

**Closed by Mimiix** 2024-06-09 17:46 UTC
Labels: Bug report
