### ISSUE TITLE
Can't pair Xiaomi Multisensor 

### ISSUE THREAD

**Issue by derVicthor** [dresden-elektronik/deconz-rest-plugin#7162] opened 2023-08-12 10:01 UTC
## Describe the bug
Can't pair Xiaomi Multisensors anymore, even though they have worked in the past.

## Steps to reproduce the behavior

1. enable device scan in Phoscon App
2. select "Other", 
3. hold the reset button on the device (device blinks three times)
4. wait for the device to be found and show up

## Expected behavior
Device should show up in Phoscon App

## Environment
 - Host system: NUC 
 - Running method: Docker image "deconzcommunity/deconz:stable"
 - Firmware version: 26720700
 - deCONZ version: 2.22.02 / 19.9.2022
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: 2 USB 3 hard drives

## deCONZ Logs
Logs attached

[_deconz_logs.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/12327094/_deconz_logs.txt)

**Comment by Mimiix** [comment] 2023-08-12 10:47
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Please use the forums.

Kind regards,
Dennis

**Closed by Mimiix** 2023-08-12 10:47 UTC
Labels: Bug report
