### ISSUE TITLE
SONOFF PIR Motion Sensor - SNZB-03

### ISSUE THREAD

**Issue by Geoff571** [dresden-elektronik/deconz-rest-plugin#3192] opened 2020-08-25 10:44 UTC
## Device

- Product name: SONOFF SNZB-03
- Manufacturer: eWeLink
- Model identifier: ms01
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots
![image](https://user-images.githubusercontent.com/34867308/91164879-b5ba7e80-e6c7-11ea-843d-2e36a3939df8.png)

![image](https://user-images.githubusercontent.com/34867308/91164697-696f3e80-e6c7-11ea-8025-d9b4454e60d6.png)
![image](https://user-images.githubusercontent.com/34867308/91164984-db478800-e6c7-11ea-8f2d-187f812213e5.png)
![image](https://user-images.githubusercontent.com/34867308/91165189-2c577c00-e6c8-11ea-8455-6028a2f73ed0.png)
![image](https://user-images.githubusercontent.com/34867308/91165225-3aa59800-e6c8-11ea-8897-f2648c629fed.png)
![image](https://user-images.githubusercontent.com/34867308/91165314-5741d000-e6c8-11ea-9358-5df61a195041.png)

**Comment by SwoopX** [comment] 2020-08-25 12:17
Duplicate of #2991

**Closed** 2020-08-25 12:16 UTC
Labels: Device Request
