### ISSUE TITLE
deconz won't start after updating from 2.12.06 to 2.13.04

### ISSUE THREAD

**Issue by Goldsucher** [dresden-elektronik/deconz-rest-plugin#5659] opened 2022-01-12 19:21 UTC
## Describe the bug

update seems to work but deconz not running after update

## Steps to reproduce the behavior

1. wget http://deconz.dresden-elektronik.de/raspbian/stable/deconz-latest.deb
2. sudo dpkg -i deconz-latest.deb
3. sudo systemctl restart deconz

no errors until here but

sudo systemctl status deconz 

shows this:

`● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2022-01-12 20:11:23 CET; 27s ago
  Process: 1212 ExecStart=/usr/bin/deCONZ -platform minimal --http-port=80 (code=exited, status=127)
 Main PID: 1212 (code=exited, status=127)
      CPU: 1.182s`
 
Downgrade to 2.12.06 and reboot fixes the issue

## Environment

 - Host system:  Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26400500
 - deCONZ version: 2.13.04
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II) RaspBee
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment] 2022-01-12 20:13
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Feel free to open an topic on the forum.

Kind regards
Dennis

**Closed by Mimiix** 2022-01-12 20:13 UTC
Labels: Bug report
