### ISSUE TITLE
deconz service will not start any more

### ISSUE THREAD

**Issue by vzografos** [dresden-elektronik/deconz-rest-plugin#7026] opened 2023-05-30 15:57 UTC
## Describe the bug

I have a RaspBee I adapter on a raspberry pi 3. Everything used to work perfectly (deCONZ service, PHOSCON) and I could control my devices via a phone app. However after (I guess) various system updates the deCONZ service does not start any more. 
```

● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2023-05-30 17:47:39 CEST; 22s ago
  Process: 11848 ExecStart=/usr/bin/deCONZ -platform minimal --http-port=80 (code=exited, status=127)
 Main PID: 11848 (code=exited, status=127)
```

when I try to start it manually via 

/usr/bin/deCONZ -platform minimal --http-port=80

I get the following error:

```
libpng warning: iCCP: known incorrect sRGB profile
/usr/bin/deCONZ: symbol lookup error: /usr/share/deCONZ/plugins/libdeconz_cli_plugin.so: undefined symbol: DBG_Printf
```

-->

## Environment

HEADLESS: NO GUI
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
- device RaspBee I

deconz         2.22.00-raspbian-buster-beta armhf
deconz_cli_plugin from source 2.04.35

**Comment by Mimiix** [comment] 2023-05-30 16:45
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

This might be your issue : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6937 

Please use the forum for furthur help as i am closing this one.

Additionally, opening 2 issues (this and #7025) is not really how this works.

Closing & locking.

Kind regards,

**Closed by Mimiix** 2023-05-30 16:45 UTC
Labels: Bug report
