### ISSUE TITLE
loosing pair devices

### ISSUE THREAD

**Issue by elpaso666** [dresden-elektronik/deconz-rest-plugin#8051] opened 2024-12-02 13:13 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hi,

today for 2nd time after restart of RPI with Conbee2<>Phoscon<>Deconz<>NodeRed I lost most of all devices and their pairing. About half of xiaomi buttons, all door sensors, some temperature sensons

I tried to reboot again, nothing, change zigbee channel, nothing...

I need to repair all devices again :(

Anyone an idea why this is happening? Restore of backup does not help as well.

thx
Jakub

### Steps to reproduce the behavior

loose of zigbee devices

### Expected behavior

no device loosing

### Environment

RPI, conbee 3, all fully patched

**Comment by Mimiix** [comment] 2024-12-02 14:06
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

Please post on the forums.

Best regards,
Dennis

**Closed by Mimiix** 2024-12-02 14:06 UTC
Labels: Bug report
