### ISSUE TITLE
No button map fo: ZHEMI101

### ISSUE THREAD

**Issue by schabert** [dresden-elektronik/deconz-rest-plugin#5199] opened 2021-08-12 07:13 UTC
## Describe the bug
I have a frient Electricity Meter Interface (ZHEMI101 manufactured by Develco). 
The connection through Deconz UI was possible and data is sent.
However, all the details like imps/KWh as described in the merge request 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4337#issuecomment-777022349 are missing.
I have to set these to get correct values.

These contents should be visible after reading the ZHEMI101 by deconz.

When reading the specifics through deconz the error "No button map fo: ZHEMI101" flies and therefore I can't set the values (I think).

## Steps to reproduce the behavior

1. In Deconz VNC 
2. Right click on Node 
3. Click Read node description 

## Expected behavior
Should read the specificas from the device 

## Screenshots

![Bildschirmfoto 2021-08-12 um 08 52 14](https://user-images.githubusercontent.com/5402091/129151153-1b6dfe51-b11e-46e3-80cd-52b048afa989.png)
## Environment

 - Host system: (Raspberry Pi 4b)
 - Running method: (Home Assistent deCONZ Add-on )
 - Firmware version: (26660700)
 - deCONZ version: (2.11.5)
 - Device: ConBee II 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## deCONZ Logs

![Bildschirmfoto 2021-08-12 um 09 04 27](https://user-images.githubusercontent.com/5402091/129152640-cede9cb0-2654-451b-a91e-77c4c19008fe.png)

-->

**Comment by SwoopX** [comment] 2021-08-12 07:41
Your issue title does not fit to the description you've given and your screenshots do not fit to any of these? I don't know what you're trying to say but I'd suggest you read the referenced issue to the end.

**Comment by Mimiix** [comment] 2021-08-12 08:24
Closing this issue as its not a bug report.

For help, please refer to the forums

https://forum.phoscon.de

**Closed by Mimiix** 2021-08-12 08:24 UTC
Labels: Bug report
