### ISSUE TITLE
SONOFF SNZB-02

### ISSUE THREAD

**Issue by cllatser** [dresden-elektronik/deconz-rest-plugin#3037] opened 2020-07-13 11:54 UTC
## Device

- Product name: SNZB-02
- Manufacturer: SONOFF EWELINK
- Model identifier: TH01
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [X] Sensor Temperature and Humidity
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

## Screenshots
![SNZB-02-01](https://user-images.githubusercontent.com/65849393/87301533-0d35ce00-c510-11ea-804d-51219b4aa29e.jpg)
![SNZB-02-Basic Cluster](https://user-images.githubusercontent.com/65849393/87301545-10c95500-c510-11ea-8545-295bb2e36d5d.jpg)
![SNZB-02-humidity Cluster](https://user-images.githubusercontent.com/65849393/87301555-14f57280-c510-11ea-837a-5a622a5108d2.jpg)
![SNZB-02-Temperature Cluster](https://user-images.githubusercontent.com/65849393/87301557-1757cc80-c510-11ea-8654-0fccd2006455.jpg)
![SNZB-02-Power Configuration Cluster](https://user-images.githubusercontent.com/65849393/87301564-19ba2680-c510-11ea-86f5-8c87af82a2a8.jpg)

**Comment by SwoopX** [comment] 2020-07-19 19:04
Closing this as device is now supported with .79 beta.

**Comment by SwoopX** [comment] 2020-07-19 19:04
Closing this as device is now supported with .79 beta.

**Closed by SwoopX** 2020-07-19 19:04 UTC
Labels: Awaiting Merge, Device Request

**Comment by Plaatjesdraaier** [comment] 2021-11-02 10:34
Unfortunately, the Sonoff devices are only added in the app, but not visible in the visual overview.
Furthermore, they do not indicate any ![image](https://user-images.githubusercontent.com/25374760/139830900-35d91904-fd85-4df4-96cd-ae11636b3ac5.png)

**Comment by 0nlytom** [comment] 2021-11-03 07:01
It actually does work and connects properly. Can you please confirm the `Appilication Version` is 5? I managed to get mine to report data after manually setting the maximum reporting value to 600 second for the Temperature and humidity.

**Comment by tiix95** [comment] 2021-11-07 14:46
Same issue here. Can connect SNZB-02 correctly but Phoscon app shows "Status : Not reachable".
Same version as @Plaatjesdraaier but firmware 26660700

**Comment by Smanar** [comment] 2021-11-09 17:50
Have just buy one and have same issue.

After 3 tries it have finally worked, my procedure
- Long press (around 5s)
- Wait for 3 red blink
- press the button every 0.5s
- Force a read temperature in the GUI (not sure if it have an impact)

**Comment by 0nlytom** [comment] 2021-11-10 21:21
The issue is that the reporting time interval is between 30 seconds and 65535 seconds. To get the sensors to increase the reporting frequency, the upper value needs to be changed. Please note, that once the device is pair, it maintains a connection with the coordinator for 30 to 60 seconds. All steps need to be complete before the sensor goes into sleep mode. 
You will need to have deCONZ GUI open for this and pair the device via deCONZ, which is under the `Control` tab. Have the `Cluster info` tab open. 
So, please read through everything first, as there is limited time to change the values.

1. Delete the old device
2. Set deCONZ into Pairing mode and switch to the `Cluster info` tab
2. Reset the sensor, hold the button down until the red LED flashes.
3. Wait for a new device to show up
4. Enable the dropdown menu by click the circle on the far right of the sensor. 

![image](https://user-images.githubusercontent.com/10347635/141193975-347941b1-b1b5-48ea-96cd-ea3ce0c8e70a.png)

5. Click on the `Temperature measurement` and go to the `Cluster info` tab.
6. Double click on the `Meaured Value`, this will open a new window allowing you to edit the attributes 
7. Change to the `Max Report Interval` to 900. This is in seconds. 

![image](https://user-images.githubusercontent.com/10347635/141194672-fc98b007-e0b0-4a21-94d4-51c3725cb6eb.png)

8. Now click `write config`. Above the button it edit notify you if it was a success 
9. Do the same for the humidity.

Please note that the less the `Max Report Interval`, is sooner you will have to replace the battery

**Comment by Smanar** [comment] 2021-11-10 21:26
Ha yes it have worked after some tries.
Have used 30/3000/100 as setting on my side.

>The issue is that the reporting time interval is between 30 seconds and 65535 seconds

So it mean there is a problem, deconz need to set the reporting with thoses value for temperature
```
            rq.minInterval = 10;           // value used by Hue bridge
            rq.maxInterval = 300;          // value used by Hue bridge
            rq.reportableChange16bit = 20; // value used by Hue bridge
```

But we are not alone with issue on inclusion for this device ATM
https://github.com/Koenkk/zigbee2mqtt/issues/8971
https://github.com/Koenkk/zigbee2mqtt/issues/5562

**Comment by Plaatjesdraaier** [comment] 2021-11-11 09:03
Hi Onlytom,
Thank your for your clear contribution.
At first it seems to work, but unfortunately the values are not refreshed
![image](https://user-images.githubusercontent.com/25374760/141269327-5f9f7dab-00d2-4635-a7bf-6f71f65ab8ec.png)

**Comment by Mimiix** [comment] 2021-11-11 09:55
It probably takes a while

**Comment by Plaatjesdraaier** [comment] 2021-11-11 11:59
Everything else updates except the SNZB-02's  
![image](https://user-images.githubusercontent.com/25374760/141294071-716d3290-d249-4171-99ce-a29cba192d53.png)

It is also useful if the update frequency is not too low because, for example, I also use these sensors to activate the fan as soon as the humidity gets too high in the shower.
It is of course the intention here that the sensor detects the increased humidity as soon as the shower is switched on, not when I have finished showering

**Comment by Mimiix** [comment] 2021-11-11 12:23
What happens if you click the button on them?

**Comment by Plaatjesdraaier** [comment] 2021-11-11 12:44
I removed the sensors and added them again with the values:  min 30 /  max 600 / reportable 100 and now it works
(clicking the button did nothing)

**Comment by Smanar** [comment] 2021-11-11 13:06
Yes, have same result.

The device can be included easily , but no report at all (for me it leave the network).
But if you just set a reporting setting like said 0nlytom it can work immediatly.

I have tried to wake up the device to set report after the inclusion procedure, almost impossible, even pressing the button.

**Comment by andreasgruener** [comment] 2021-11-18 16:53
I followed the very precise and detailed description by 0nlytom. Perfect!

**Comment by 20design** [comment] 2021-11-23 22:38
For me too, I followed the steps described by 0nlytom and its working fine. Just be fast to add the humidity sensor as well.
Thanks!

**Comment by mgrn0** [comment] 2021-12-07 20:58
adding two of the snzb-02 sensors with latest beta worked out of the box for me without ANY problems, no manual steps required.

**Comment by camarril** [comment] 2021-12-10 16:05
> adding two of the snzb-02 sensors with latest beta worked out of the box for me without ANY problems, no manual steps required.

Thank you!
I was setting up sizbee2mqtt for the fist time yesterday, using the latest stable version (1.22.1) and my SNZB-02 only sent battery and signal strength information once after pairing and then stopped working. No temperature or humidity. Today I tried the latest-dev image (published 11 hours ago) and now it works perfectly.

**Comment by mgrn0** [comment] 2022-01-04 09:23
very weird, both my snzb-02 sensors lost connection today and I cannot get them to re-connect at all. removing (once) and re-pairing does not work, deconz does not 'see' them anymore. updating to latest beta did not help, both sensors are not recognized. battery levels were 100%, using a new battery does not help, neither.

any ideas?

**Comment by Mimiix** [comment] 2022-01-04 09:30
@mgrn0 I suggest opening a forum post and add some logs.

**Comment by nook24** [comment] 2022-01-10 13:12
@mgrn0  I have the exact same issue with the exception that my setup is brand new :(

**Comment by AndRe5575** [comment] 2022-02-09 20:31
@0nlytom is there a way to do this without GUI? I installed deconz without because I also use openmediavault on my PI and therefore I had to use the lite OS version without GUI. Pairing my sonoff sensor just works for about one day and then it´s not found anymore so I have to pair them again.

**Comment by 0nlytom** [comment] 2022-02-10 20:24
@AndRe5575 which version are you running? I know that in the latest version `2.13.04` everything work fine. Please try and upgrade.

**Comment by 0nlytom** [comment] 2022-02-11 05:37
@AndRe5575 Please try and reconnect the sensors. I successfully re-provisioned one sensor on version `2.14.01`

**Comment by AndRe5575** [comment] 2022-02-11 16:00
@0nlytom I reconnected them. One is working at the moment and one shows no new update since a few hours. The one which is working shows sometimes that the last update was / will be in 1 hour. A bit strange.

**Comment by Stubbs** [comment] 2022-08-18 21:35
It appears that any devices added with an earlier version that had the default `Max Report Interval` set to 65535 still retain this value when re-added to the network, new devices work as expected.

I have tried updating the value while the device is awake immediately after adding to the network as described by @0nlytom however it seems to keep the incorrect value.

Can these devices be factory reset?

**Comment by TheSOMGuy** [comment] 2022-09-22 13:10
Is there an working solution for this problem bc i run in the same situation with a completely new setup. 
My door sensor is recognized as it should be but the Multisensor ( Temp/Humidity ) is not.
I can't use the gui bc of my headless openhabian installation and i have to solve this by hand or has to by new sensors.
And i do prefer the first one.

Any new suggestions?
Thanks

**Comment by Smanar** [comment] 2022-09-27 08:37
What is the issue ?
Have you tried to re-include the device without deleting it ?

**Comment by BabaIsYou** [comment] 2022-09-27 13:29
Can't it be included in a DDF that will be loaded at inclusion ?

**Comment by Smanar** [comment] 2022-09-27 14:42
Yeah can use a DDF to bypass the legacy code, but I don't see what we need.

>it should be but the Multisensor ( Temp/Humidity ) is not.

It's incomplete, bad values ....

**Comment by BabaIsYou** [comment] 2022-09-27 17:09
> @0nlytom I use Version `2.14.01` and a Raspbee II with FW `26720700`

Version 2.15.03 and ConBee II with FW 26720700on RPi4  and no issue with my 3 devices.

**Comment by nickelnine** [comment] 2023-02-06 16:04
Could someone kindly explain what is required to make these devices show values for temperature and humidity? I'm running deconz in Docker:
![image](https://user-images.githubusercontent.com/28116390/217021188-5f226032-f16b-4f89-a319-2ec5d7095501.png)
I've had the sensor for almost a week and I see only this:
![image](https://user-images.githubusercontent.com/28116390/217022135-999097f4-d8f9-4c9a-826b-dc39088199bc.png)
and
![image](https://user-images.githubusercontent.com/28116390/217022377-35d701a1-ee9e-4110-b62f-8b75aba33b81.png)

**Comment by nook24** [comment] 2023-02-06 19:09
In case you are using a Raspberry Pi it is **important to connect the ConBee via an USB extension cord**.  That is very important.
Beside from this, start scanning for new sensors via the Phoscon Website and press the button on the Sonoff sensor to start pairing.

Also make sure that the battery in the Sensor has charge

That's basically it.

**Comment by dennisb1** [comment] 2023-02-12 15:49
> Could someone kindly explain what is required to make these devices show values for temperature and humidity? I'm running deconz in Docker: ![image](https://user-images.githubusercontent.com/28116390/217021188-5f226032-f16b-4f89-a319-2ec5d7095501.png) )


Just a tought but maybe a good idea to do update of deCONZ first? At the moment it is 2.20.01 / 19-9-2022

**Comment by Smanar** [comment] 2023-02-12 17:20
Lol, ha yes lol, haven't see that, 2.13 ^^, I think it s a new record.

**Comment by misel86** [comment] 2023-09-28 08:19
> very weird, both my snzb-02 sensors lost connection today and I cannot get them to re-connect at all. removing (once) and re-pairing does not work, deconz does not 'see' them anymore. updating to latest beta did not help, both sensors are not recognized. battery levels were 100%, using a new battery does not help, neither.
> 
> <img alt="Screenshot 2022-01-04 at 10 24 06" width="348" src="https://user-images.githubusercontent.com/3019226/148037458-3c5a3983-b440-40ec-b6de-1823199299f0.png">
> 
> any ideas?

Hello, did you manage to solve this? I have the same setup and the status is Not Reachable after multiple restart/pairing/etc

**Comment by Smanar** [comment] 2023-09-28 11:04
Do you have some logs ? or a capture from the GUI ?
What is your deconz version ? On the capture was the 2.13, so  a realy old one.

**Comment by misel86** [comment] 2023-09-28 12:02
Hello:

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5527854/e072c17a-45b0-41a8-aeaa-dc82adfdfc14)

and I'm using DDF from  #6697 with this modification:

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5527854/1f20ede7-a712-410f-a84b-749e1caaba4f)

**Comment by Smanar** [comment] 2023-09-28 12:14
So same answer, update your deconz version, you have the 2.13 we are ATM at 2.23

**Comment by misel86** [comment] 2023-09-28 12:25
Oh, okay, looks like I'm using the old docker image. My bad, thanks :D

**Comment by boelle** [comment] 2024-04-11 05:34
i have the same issue and when i try to change the config from within deconz app i fails to write the config

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/3832239/69411135-7db4-457e-943f-28a1ba2d2801)


![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/3832239/b77e207c-7ec3-42b1-a429-96258a48294a)


even reading config fails


![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/3832239/fe4a507b-e1ac-4c27-8837-58408c38e02a)




not that it matter i think but in zigbee2mqtt everything works except the addon stops a few times a week and faisls to restart on its own... i have to reboot the pi completely

**Comment by Mimiix** [comment] 2024-04-11 06:39
@Smanar  can you check the comment of @boelle ?

**Comment by Smanar** [comment] 2024-04-11 17:04
Hello,
What are you trying to do ?
Those device are slepper, so you can need to awake them in same time you press the "read" button, generaly with short press on the reset button.

Can you show the cluster list ? (with pressing the "+" on the node title.

**Comment by boelle** [comment] 2024-04-11 20:35
> What are you trying to do ?

add the device just like a light bulb or switch

> Can you show the cluster list ?

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/3832239/32320bab-481a-4983-8b80-a791d7590232)

> And you have no report at all, no temperature, no humidity, no battery ?

correct

> Nothing in logs about this device in deconz/help/debug view, with flag "info" * 2 and "error" * 2 ?

will edit this post tomorrow, i have to switch from zigbee2mqtt to deconz each time i do testing. zigbee2mqtt works but crashes once a week, that is why i try to switch to deconz as i remember that as stable

**Comment by boelle** [comment] 2024-04-12 06:21
so i got one sensor added.... along with some other lights i have

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/3832239/fef4ee88-0131-4d29-b051-410f3604da4e)


if i blow air with my mouth it updates instantly

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/3832239/a52c930e-6439-410c-80e5-c920cc352516)


now to check if i'm also lucky with the other 4 i have

**Comment by boelle** [comment] 2024-04-12 14:02
@Smanar everything worked first time today, not sure why it was such a pain yesterday

**Comment by Smanar** [comment] 2024-04-12 17:34
Lol, zigbee is magic.
No seriously it's not normal, to add new sensor you don't need to use the "permit join" in deconz, just use phoscon, select "add new sensor" and make the procedure on the sensor.
Phoscon will enable itself the "permit join" for a limited period.

**Comment by boelle** [comment] 2024-04-13 06:46
> And you have other problem. Too much device with name like "0xXXXX" ....

those changed when i began to add my light bulbs in phoscon

and yes i would normal use phoscon to add the sensors but that did not worked so i tried with deconz instead, that with all 5 of them, the day before even decons did not work for the sensors

but yeah, very "strange" that it did not work one day and then the next it does

**Comment by Smanar** [comment] 2024-04-13 07:28
>EDIT: btw.... would it be in the near future to see an update function inside phoscon so we can easy update the firmware in devices?

Yes, for the moment you can use the desktop version or enable automatic update with "router" devices, but yes there is nothing for sensor out of deconz.

**Comment by boelle** [comment] 2024-04-13 07:51
i was thinking in phoscon, there are no section for updates

**Comment by Smanar** [comment] 2024-04-13 07:57
Not for sensor, but you can enable OTAU for router device in the settings (automatic working mode, no specific action possibles). And you need to put files in a specific folder.

**Comment by boelle** [comment] 2024-04-13 08:58
that is something i will miss from zigbee2mqtt, they have updates in one single screen for everything

but i guess a stable system that do not crash 1-2 times a week is better than easy updates :-D
