### ISSUE TITLE
No ZHAswitch created for Xiaomi Aqara D1 2-gang switch (no neutral wire) - model: QBKG22LM

### ISSUE THREAD

**Issue by esseki** [dresden-elektronik/deconz-rest-plugin#4316] opened 2021-01-31 23:22 UTC
## Describe the bug
When adding the Aqara D1 2-gang (no neutral wire) to my Zigbee network I don't get any ZHASwitch sensor created in the Deconz Rest API. 
- 2 lights resources are created allowing me to control the 2 relays remotely : this is expected behavior.
- I can decouple the buttons from the relay as explained here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1816#issuecomment-674511033 . This is working fine.
- But I have no way to create rules when a decoupled button is pressed since I have no ZHASwitch sensor created corresponding to my switch. 

## Steps to reproduce the behavior
I can reproduce the issue by doing :

  1. Delete one of the lights (they actually show as smart plug) in Phoscon (in Devices / Lights) to delete the node in Deconz (if previously inserted) 
  2. In Phoscon, in Devices / Switch click on the "Add a new switch" button, then choose "Other"
  3. Press and maintain the first button on the switch until Led flash blue.
  4. A new node is created in Deconz
  5. The "Add Switch" popup does not get updated after the node is created in Deconz. The "Ready" button never gets clickable. And no new corresponding ZHAswitch resource becomes available in the Rest API.
  6. 2 new lights resources becomes visible in Phoscon (Devices / Lights) and accessible via the Rest API. 
  7. FYI i have tested adding the Switch via the "Devices / Lights" "Add new lights" process and outcome is exactly the same : 2 lights are created but no ZHAswitch in the Rest API.

## Expected behavior
I would expect to get a new ZHAswitch resource available in the Rest API. Mainly as my goal is to use one of the buttons in decoupled mode. Decoupling is working fine it seems but is pretty useless if I don't have the ZHAswitch resource available to report the button events.

## Screenshots
<img width="1410" alt="Capture d’écran 2021-02-01 à 00 07 53" src="https://user-images.githubusercontent.com/9165877/106400932-ad5a3280-6421-11eb-8221-30d9bb1e483c.png">
<img width="1397" alt="Capture d’écran 2021-02-01 à 00 17 41" src="https://user-images.githubusercontent.com/9165877/106401316-bfd56b80-6423-11eb-8803-9e23b747acc3.png">

## Environment
 - Host system: NUC running Proxmox
 - Running method: Home Assistant deCONZ Add-on in a VM
 - Firmware version: 26680700
 - deCONZ version: 2.07.01 / 08/12/2020 (Can not upgrade since Home Assistant Deconz Add-on has not been updated yet)
 - Device: ConBee II 
 - Do you use an USB extension cable: yes

## deCONZ Logs
Just let me know what kind of log is needed and I will provide.

Thank you in advance for your help.

**Comment by Mimiix** [comment] 2021-02-01 09:03
This is not supported yet 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4199

Duplicate of that one. So i close this one and continue in that one.

**Closed by Mimiix** 2021-02-01 09:03 UTC
Labels: Bug report
