### ISSUE TITLE
Hue lamp flashing every x minutes

### ISSUE THREAD

**Issue by djfanatix** [dresden-elektronik/deconz-rest-plugin#5692] opened 2022-01-21 15:43 UTC
## Describe the bug

I added a Philips Hue bulb to my Zigbee Network (add-on in Home Assistant)
The Bulb is now flashing every 1 to 2 minutes.
How to fix this?
## Environment

 - Host system: NAS DS218+
 - Running method: Virtual Machine
 - Firmware version: latest
 - deCONZ version: 6.11.1
 - Device:  ConBee II 
 - Do you use an USB extension cable: (yes / **no**) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## deCONZ Logs

16:36:33:146 0x000b57fffeb9e3f0 found group 0xFFF0
16:36:33:146 0x000b57fffeb9e3f0 found group 0x0003
16:36:33:815 0x00178801036b9095 found group 0xFFF0
16:36:34:560 0x000b57fffe8fd7fa found group 0x8F51
16:36:34:560 0x000b57fffe8fd7fa found group 0xFFF0
16:36:34:560 0x000b57fffe8fd7fa found group 0x0003
16:36:37:091 0x00178801036B9095 error APSDE-DATA.confirm: 0xE9 on task
16:36:47:541 Skip idle timer callback, too early: elapsed 6 msec
16:37:08:462 0x00178801036B9095 error APSDE-DATA.confirm: 0xD0 on task
16:37:22:460 0x00178801036B9095 error APSDE-DATA.confirm: 0xD0 on task
16:37:24:562 Device TTL 2549 s flags: 0x7
16:37:50:519 Skip idle timer callback, too early: elapsed 329 msec
16:38:11:866 0x00178801036B9095 error APSDE-DATA.confirm: 0xE9 on task

**Comment by Mimiix** [comment] 2022-01-21 15:50
Hi,

As this is not a bug as described in #5113 i am closing this issue. Feel free to open a post on the forums.

Kind regards,
Dennis

**Closed by Mimiix** 2022-01-21 15:50 UTC
Labels: Bug report
