### ISSUE TITLE
[Docker] New install of 2.17.01: `this.autoUpdateBtnOff is null` on GW page

### ISSUE THREAD

**Issue by Commifreak** [dresden-elektronik/deconz-rest-plugin#6181] opened 2022-07-08 18:14 UTC
## Describe the bug

I installed the newest docker image with an ConBeeII. When I open the GW page inside Phoscon, the page does not show much and a JS error is thrown: `this.autoUpdateBtnOff is null`:

## Steps to reproduce the behavior

* Setup latest docker image
* Open GW page
* Page does not show much informations and throws a JS error

## Expected behavior

* Normal working GW page :)

## Screenshots

![grafik](https://user-images.githubusercontent.com/87267/178047498-aa0ab478-97c8-4c92-883e-a72927bca758.png)
![grafik](https://user-images.githubusercontent.com/87267/178047712-76605616-cf7d-493a-9c44-361286cfe89e.png)

## Environment

 - Host system: unRAID
 - Running method: Docker
 - Firmware version: 0x26580700
 - deCONZ version: 2.17.01
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs

```
[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.17.01
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=80 --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
20:08:43:923 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
20:08:43:931 /opt/deCONZ/config.ini exists and is writeable
20:08:43:931 /opt/deCONZ/zll.db exists and is writeable
20:08:44:034 COM: /dev/ttyACM0 / serialno: , ConBee II
20:08:44:034 ZCLDB init file /opt/deCONZ/zcldb.txt
20:08:44:162 DDF enabled for Gold status
20:08:44:262 gw run mode: docker
20:08:44:262 GW sd-card image version file does not exist: /opt/deCONZ/gw-version
20:08:44:263 DB sqlite version 3.34.1
20:08:44:264 DB PRAGMA page_count: 46
20:08:44:264 DB PRAGMA page_size: 4096
20:08:44:264 DB PRAGMA freelist_count: 0
20:08:44:264 DB file size 188416 bytes, free pages 0
20:08:44:264 DB PRAGMA user_version: 9
20:08:44:264 DB cleanup
20:08:44:265 DB create temporary views
20:08:44:270 Started websocket server on 0.0.0.0, port: 443
20:08:44:272 [INFO] - Found file containing button maps. Parsing data...
20:08:44:284 [INFO] - Button maps loaded.
20:08:44:284 found node plugin: libde_rest_plugin.so - REST API Plugin
20:08:44:286 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
20:08:44:295 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
20:08:44:334 dlg action: Read binding table
20:08:45:353 COM: /dev/ttyACM0 / serialno: , ConBee II
20:08:46:969 Device firmware version 0x26580700 ConBee II
20:08:46:970 unlocked max nodes: 512
20:08:46:988 Device protocol version: 0x010B
20:08:47:005 Current channel 15
20:08:47:009 CTRL ANT_CTRL 0x03
20:08:47:020 Device protocol version: 0x010B
20:08:47:038 CTRL ANT_CTRL 0x03
20:08:49:455 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26720700.bin.GCF
20:08:49:455 GW firmware version shall be updated to: 0x26720700
20:08:49:620 Announced to internet https://phoscon.de/discover
20:08:52:436 DEV Tick.Init: booted after 8000 seconds
20:08:54:272 created username: 236FAB4DA9, devicetype: Phoscon#B1920x927
20:08:55:520 New websocket 192.168.178.33:51553 (state: 3) 
20:08:56:790 Websocket disconnected 192.168.178.33:51553, state: 0, close-code: 1001, reason: 
20:08:58:012 New websocket 192.168.178.33:51555 (state: 3) 
20:09:02:761 Websocket disconnected 192.168.178.33:51555, state: 0, close-code: 1001, reason: 
20:09:04:229 New websocket 192.168.178.33:51560 (state: 3) 
20:09:43:441 Device TTL 3267 s flags: 0x7
20:10:43:443 Device TTL 3207 s flags: 0x7
20:10:59:436 GW firmware version shall be updated to: 0x26720700
20:11:43:443 Device TTL 3147 s flags: 0x7
20:12:43:441 Device TTL 3087 s flags: 0x7
20:13:09:437 GW firmware version shall be updated to: 0x26720700
20:13:43:443 Device TTL 3027 s flags: 0x7
```

## Additional context

Docker run command:

```
docker run -d --name='deconz' --net='br0' --ip='192.168.178.4' -e TZ="Europe/Berlin" -e 'DECONZ_DEVICE'='/dev/ttyACM0' -e 'TZ'='Europe/Berlin' -v '/mnt/cache/appdata/deconz':'/opt/deCONZ':'rw' --device='/dev/ttyACM0' 'deconzcommunity/deconz:latest'
```

**Comment by Mimiix** [comment] 2022-07-08 18:48
Hi,

Thank you for your report. 

As this is not a bug report as described in #5113 I am closing this issue. Phoscon bug reports are collected at the forums. In your case, this already is reported. 

https://forum.phoscon.de/t/phoscon-app-broken-with-deconz-2-17-0/2099/11

Kind regards, 
Dennis

**Closed by Mimiix** 2022-07-08 18:48 UTC
Labels: Bug report
