### ISSUE TITLE
routers (bulbs & smart switches) can't be connected anymore

### ISSUE THREAD

**Issue by Rainerlan** [dresden-elektronik/deconz-rest-plugin#5749] opened 2022-02-03 21:41 UTC
## Describe the bug
Bulbs & smart plugd not reacting anymore (can't witch bulbs)
After deleting the bulbs & resetting them, they do not get detected anymore properly

## Steps to reproduce the behavior
1. updated to deConz 2.14.0
2. deleted bulbs (as I could not switch them)
3. re-installed 2.13.4
Not sure if its reproducible, as I cannot connect the bulbs anymore

## Expected behavior
Bulbs can be switched after update
Plugs can be switched
Bulbs can be re-added after deleting them

## Screenshots
![Screenshot 2022-02-03 223609](https://user-images.githubusercontent.com/179617/152433002-b4a6e2c5-ddf0-411a-bdb6-d5e0d0feeb8c.png)

## Environment
 - Host system: Raspberry Pi 4
 - Running method: Raspbian
 - Firmware version: 26720700
 - deCONZ version: 2.13.4 and 2.14.0
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? Yes: CUL, Jeelink modem, SSD

## deCONZ Logs
[debug2.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7998373/debug2.txt)

## Additional context
Also the plugs seem to be not switchable anymore
in DeConz-gui I can find the devices - but they do not get visible in Phoscon 
Hence they are note usable

**Comment by Mimiix** [comment] 2022-02-04 06:49
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

Feel free to open an topic on the forums.

Kind regards,

Dennis

**Closed by Mimiix** 2022-02-04 06:49 UTC
Labels: Bug report
