### ISSUE TITLE
Aqara C1 Pet Feeder PETC1-M01

### ISSUE THREAD

**Issue by mcormick** [dresden-elektronik/deconz-rest-plugin#7667] opened 2024-03-15 16:32 UTC
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Aqara Smart Pet Feeder C1

### Manufacturer

Aqara

### Model identifier

aqara.feeder.acn001

### Device type to add

Other

### Node info

![node_info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/8dc7d913-a75c-4b61-9003-537bd2bd5273)

### Endpoints and clusters

![clusters](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/6a71c248-a8cf-458f-95fa-fafcc38518b6)

### Basic

![cluster_basic](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/3e6fe187-440f-4f75-9912-25247ecb9bf0)

### Power Configuration
N/A
### On/Off
![cluster_onoff](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/5c5a5656-7f06-4f65-b404-d5a1eb08fc82)
### Level Control
N/A
### Color Control
N/A
### Thermostat
N/A
### Simple Metering
N/A
### Electrical Measurement
N/A
### Groups
![cluster_groups](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/cd741c7b-dc53-447f-95f1-22c27a7b7fd5)
### Identify
![cluster_identify](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/3bbac73f-25eb-44c1-8358-dc8eb0a332d3)
### Lumi Specific
![cluster_lumi_specific_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/9b7f01b0-046b-417f-8e80-0d339d463f64)
![cluster_lumi_specific_2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/91b1f631-f5dd-43d0-8b2e-49fca51c3a8d)
![cluster_lumi_specific_3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/f977b5aa-c837-4472-b53a-3772858c6cac)
### Otau
![cluster_otau](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/c1d11ebb-cdcf-49b4-b034-4b4af6310ca6)
### Scenes
![cluster_scenes](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/ee61dcb6-654e-483f-8d02-8bb1e02adb8a)
### Time
![cluster_time](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18458852/7994857c-3482-4bd2-bfd7-df4a874de34c)

**Comment by mcormick** [comment] 2024-03-15 16:58
https://forum.phoscon.de/t/aqara-pet-feeder-c1/4740

**Comment by SwoopX** [comment] 2024-03-15 20:57
Duplicate of #6595, therefore closing

**Closed by SwoopX** 2024-03-15 20:57 UTC
Labels: Device Request

**Comment by mcormick** [comment] 2024-03-15 21:31
Rucksichtlos closing a new request because a 1.5 year old one was already closed, without satisfying result I might add? Surely this could be looked into again with all the work that has been done in deCONZ in the months thereafter? Also, the new cluster screenshots differ to a certain degree from this original request. Politely requesting a reopening of either this, or the old request and a serious look into possible support for this device.

**Comment by francescopeloi** [comment] 2024-03-18 07:31
@SwoopX kindly tagging you to see if you agree with the above message?

**Comment by SwoopX** [comment] 2024-03-20 22:14
Apologies, but I do not understand what is reckless in this regard. We have rules here and give guidance on what to do prior to raising new device requests. This is available on the one hand to point the potential requestor at what to do before putting work into creation of an issue (which admittedly can be rather extensive depending on the device), and on the other hand to not unnecessarily blow up the number of device issues per se and/or scatter any device relevant information over various issues. Specifically the latter is very inconvenient and error prone and this just makes the lives of the developers harder as it needs to be.

It is unfortunate that the result of the already available issue is unsatisfying for you, but this is not an acceptable justification. You're always free to request re-opening issues and welcome to contribute with newly available or missing information to resume work. Please do note though that often information about functionality, issues or blockers is already documented in the respective issues.

Thanks for understanding!
