### ISSUE TITLE
deCONZ 2.14.01 not working on Raspberry Pi 3 with FHEM

### ISSUE THREAD

**Issue by Jackie78De** [dresden-elektronik/deconz-rest-plugin#5781] opened 2022-02-10 19:05 UTC
## Describe the bug

  I fail to successfully install the version 2.14.01 of deCONZ on my Raspberry Pi 3 Model B Rev 1.2. When I install it the following way, my Gateway is not discovered, the Gateway section on the PWA websie remains empty, and all my devices are not connected.

wget http://deconz.dresden-elektronik.de/raspbian/stable/deconz-2.14.01-qt5.deb
sudo dpkg -i deconz-2.14.01-qt5.deb
sudo apt update
sudo apt install -f

sudo systemctl enable deconz

When I try the very same with version 2.12.06, which is my current version, everything works fine again. So how do I make the new version work with my Raspi3?

Btw, Firmware of my Conbee2 stick is 26660700, and installed version 2.12.06 / 19.8.2021. Although this is not the latest stable version available in the repo, it is listed as latest. Why?

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

  1. Install deCONZ 2.14.01 as described above
  2. Enter the PWA-Index page, go to "Gateways". The section is empty, and no devices are connected.
  3. Install deCONZ 2.12.06 the same way as described above
  4. Enter the PWA-Index page, go to "Gateways". The section shows the Conbee 2 gateway again and all devices are connected

  If the problem can't be reproduced and is sporadic, please provide some details
  on how often and when the issue happens.

## Expected behavior

  I expect hte new version to work like the old one, with bugs removed (i.e. for the Tradfri remote longpress issue fixed in that release

## Environment

  Firmware of my Conbee2 stick is 26660700, and installed version 2.12.06 / 19.8.2021

- Host system: Raspberry Pi 3 Model B Rev. 1.2
 - Headles deCONZ, FHEM as client using HUEDevice module
 - Firmware version: (26660700)
 - deCONZ version: 2.14.01 (not working); 2.12.06 (working)
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If No

**Comment by Mimiix** [comment] 2022-02-10 19:28
Hi

As this is not a bug report as described in #5113 I am closing this issue.

Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-02-10 19:28 UTC
Labels: Bug report
