### ISSUE TITLE
Philips hue dimmer RWL021 does not work after update to v2.13.03 and above 

### ISSUE THREAD

**Issue by brunoz78** [dresden-elektronik/deconz-rest-plugin#5611] opened 2021-12-25 11:54 UTC
## Describe the bug
After updating to v2.13.03 and higher (also v2.13.04) my Philips Hue Dimmer RWL021 does not work anymore. It no longer responds to any button. The dimmer is found and also displayed. If the older version v2.13.02 is installed over it again, everything works fine again.

In addition, in version v2.13.03 and higher, the display of the battery level is missing in the overview display. 

Something seems to be defective in the file "de_rest_plugin.dll". If I install version 2.13.03 (or .04) and replace the file "de_rest_plugin.dll" in the directory deCONZ/bin/plugins/ with the old version from 2.13.02, then it also works fine.

## Screenshots
![25-12-_2021_12-56-17](https://user-images.githubusercontent.com/74092347/147384419-74d9356d-143e-4457-9118-9557e1c309ac.jpg)

![25-12-_2021_11-52-57](https://user-images.githubusercontent.com/74092347/147384348-f4eccb1b-7889-49a7-9fae-cdcaf6cbef6d.jpg)
![25-12-_2021_11-56-06](https://user-images.githubusercontent.com/74092347/147384354-9ba4b942-488f-41c8-be20-99929fbb82e1.jpg)

## Environment
 - Host system: PC
 - Running method: Windows 10 x64 (21H2)
 - Firmware version: (0x26720700)
 - deCONZ version: 2.13.03 und neuer
 - Device: ConBee II
 - Do you use an USB extension cable: yes

## deCONZ Logs

**V2.13.04 DEBUG logs (INFO) with click of ON and OFF switch.**

- 12:15:33:890 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
12:15:33:922 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:15:33:937 SC tick --> StateRead
12:15:33:937 ZCL read attr 0x00178801040A6480, ep: 0x02, cl: 0x0000, attr: 0x0031, mfcode: 0x100B, aps.id: 124, zcl.seq: 139
12:15:33:946 ZCL attribute report 0x00178801040A6480 for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
12:15:34:031 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
12:15:34:063 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
12:15:34:812 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4000
12:15:34:837 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:15:34:937 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4002
12:15:34:962 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
12:15:36:047 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
12:15:36:066 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:15:36:083 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0100003000210000, zclSeq: 143
12:15:36:084 Websocket 10.0.1.20:53892 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":1000,"eventduration":0,"lastupdated":"2021-12-25T11:15:36.066"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:15:36:172 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
12:15:36:189 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
12:15:36:206 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0100003002210100, zclSeq: 145
12:15:36:208 Websocket 10.0.1.20:53892 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":1002,"eventduration":1,"lastupdated":"2021-12-25T11:15:36.189"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:15:36:549 GW update firmware not found: deCONZ_ConBeeII_0x26660700.bin.GCF
12:15:36:551 rule event /config/localtime: 12:15:35.547 -> 12:15:36.547 (1000ms)
12:15:37:156 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4000
12:15:37:192 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:15:37:204 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0400003000210000, zclSeq: 146
12:15:37:205 Websocket 10.0.1.20:53892 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":4000,"eventduration":0,"lastupdated":"2021-12-25T11:15:37.192"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:15:37:297 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4002
12:15:37:321 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
12:15:37:331 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0400003002210100, zclSeq: 148
12:15:37:332 Websocket 10.0.1.20:53892 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":4002,"eventduration":1,"lastupdated":"2021-12-25T11:15:37.321"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:15:37:547 Idle timer triggered
12:15:37:547 Force read attributes for ZHALightLevel SensorNode BM Aqara (2)
12:15:37:549 rule event /config/localtime: 12:15:36.547 -> 12:15:37.547 (1000ms)
12:16:18:232 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
12:16:18:255 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:16:18:344 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
12:16:18:378 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
12:16:19:250 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
12:16:19:277 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:16:19:411 ZCL attribute report 0x588E81FFFE5314C4 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
12:16:19:578 binding for cluster 0x0006 of 0x842E14FFFE77EE93 exists (verified by reporting)
12:16:19:578 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x842E14FFFE77EE93 (seems to be active)
12:16:20:072 DeviceAnnce of SensorNode: 0x0017880102C0245A [1]
12:16:20:141 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
12:16:20:166 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
12:16:20:453 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4000
12:16:20:474 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:16:20:672 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4002
12:16:20:707 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 2
12:16:21:989 Bind response success for 0x842e14fffe77ee93 ep: 0x01 cluster: 0x0008
12:16:21:990 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0x842E14FFFE77EE93 (wait reading or unsupported)
12:16:22:344 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4000
12:16:22:374 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
12:16:22:562 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 4002
12:16:22:579 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 2

**V2.13.02 DEBUG logs (INFO) with click of ON and OFF switch.**

- 12:12:32:406 [INFO] - Button 1000 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:32:419 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:32:578 [INFO] - Button 1002 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:32:582 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:32:582 trigger rule 122 - Rule ON
12:12:33:333 ZCL attribute report 0x000B57FFFE9511F2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
12:12:33:453 [INFO] - Button 4000 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:33:467 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:33:666 [INFO] - Button 4002 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:33:675 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:33:675 trigger rule 121 - Rule OFF
12:12:33:750 DEV Tick.Init: booted after 429461648307134272 seconds
12:12:34:349 ZCL attribute report 0x000B57FFFE9511F2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
12:12:34:767 rule event /config/localtime: 12:12:33.765 -> 12:12:34.765 (1000ms)
12:12:35:750 Daylight now: goldenHour1, status: 160, daylight: 1, dark: 0
12:12:35:767 rule event /config/localtime: 12:12:34.765 -> 12:12:35.766 (1001ms)
12:12:35:875 [INFO] - Button 1000 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:35:885 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0100003000210000, zclSeq: 74
12:12:35:886 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":1000,"eventduration":0,"lastupdated":"2021-12-25T11:12:35.875"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:12:35:886 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:36:000 [INFO] - Button 1002 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:36:014 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0100003002210100, zclSeq: 76
12:12:36:014 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":1002,"eventduration":1,"lastupdated":"2021-12-25T11:12:36.000"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:12:36:014 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:36:014 trigger rule 122 - Rule ON
12:12:36:014 add task 35 type 14 to group 0x001B cluster 0x0006 req.id 79
12:12:36:016 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"9","r":"lights","state":{"alert":null,"bri":3,"on":true,"reachable":true},"t":"event","uniqueid":"00:0b:57:ff:fe:95:11:f2-01"} (ret = 147)
12:12:36:016 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"27","r":"groups","state":{"all_on":true,"any_on":true},"t":"event"} (ret = 88)
12:12:36:687 Node data 0x000b57fffe9511f2 profileId: 0x0104, clusterId: 0x0006
12:12:36:687 0x000B57FFFE9511F2: update ZCL value 0x01/0x0006/0x0000 after 0 s
12:12:36:698 ZCL attribute report 0x000B57FFFE9511F2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
12:12:36:698 	payload: 00001001
12:12:36:719 Erase task req-id: 79, type: 14 zcl seqno: 1 send time 0, profileId: 0x0104, clusterId: 0x0006
12:12:36:782 rule event /config/localtime: 12:12:35.766 -> 12:12:36.781 (1015ms)
12:12:36:922 [INFO] - Button 4000 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:36:936 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0400003000210000, zclSeq: 77
12:12:36:936 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":4000,"eventduration":0,"lastupdated":"2021-12-25T11:12:36.922"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:12:36:936 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:37:109 [INFO] - Button 4002 - RWL021 endpoint: 0x02 cluster: PHILIPS_SPECIFIC (0xFC00)
12:12:37:114 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0xFC00, command: 0x00, payload: 0400003002210100, zclSeq: 79
12:12:37:114 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"93","r":"sensors","state":{"buttonevent":4002,"eventduration":1,"lastupdated":"2021-12-25T11:12:37.109"},"t":"event","uniqueid":"00:17:88:01:02:c0:24:5a-02-fc00"} (ret = 183)
12:12:37:114 rule event /sensors/93/state/lastupdated: 0 -> 0
12:12:37:114 trigger rule 121 - Rule OFF
12:12:37:114 add task 42 type 14 to group 0x001B cluster 0x0006 req.id 92
12:12:37:116 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"9","r":"lights","state":{"alert":null,"bri":3,"on":false,"reachable":true},"t":"event","uniqueid":"00:0b:57:ff:fe:95:11:f2-01"} (ret = 148)
12:12:37:116 Websocket 10.0.1.20:53666 send message: {"e":"changed","id":"27","r":"groups","state":{"all_on":false,"any_on":false},"t":"event"} (ret = 90)
12:12:37:782 rule event /config/localtime: 12:12:36.781 -> 12:12:37.781 (1000ms)
12:12:37:828 Node data 0x000b57fffe9511f2 profileId: 0x0104, clusterId: 0x0006
12:12:37:828 0x000B57FFFE9511F2: update ZCL value 0x01/0x0006/0x0000 after 0 s
12:12:37:840 ZCL attribute report 0x000B57FFFE9511F2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
12:12:37:840 	payload: 00001000
12:12:37:864 Erase task req-id: 92, type: 14 zcl seqno: 2 send time 1, profileId: 0x0104, clusterId: 0x0006

**Comment by Mimiix** [comment] 2021-12-25 16:26
Hi,

Did you enable silver in control in ddf?

If so  please disable and see again.

Either way  as this is not a bug report as described in #5113 I'm closing this issue.

Feel free to open an topic on the forum.

Kind regards
Dennis

**Closed by Mimiix** 2021-12-25 16:26 UTC
Labels: Bug report
