### ISSUE TITLE
Aqara Multisensor incorrectly integrated after second registration || Battery always 0%

### ISSUE THREAD

**Issue by calvarium** [dresden-elektronik/deconz-rest-plugin#6077] opened 2022-05-26 09:08 UTC
## Describe the bug

I have built a test computer based on Raspberry Pi and RaspBee 2 in which I have integrated a new Aqara multisensor. The first registration ran without problems. The sensor was recognized immediately and all values were displayed correctly, including the battery status. Also the integration in Hombridge went without problems.

After all completed tests I wanted to transfer this sensor to my live system. Have removed it from the test gateway, the gateway even reset. So everything was freshly ready for integration.

The livesystem is an identical Raspi with the identical configuration. I started the search in the Phosconapp and wanted to connect the sensor. But to my dismay this did not work the first 3 times. Only after the fourth connection attempt, the sensor was added. However, I have received here no success notification of the web interface which I found strange. But it did not bother me further, the sensor was available.

When I then integrated the sensor in Homebridge I noticed that the battery status is displayed with 0%. I found that strange, so I have replaced the battery. Unfortunately, the sensor still shows 0%.

Also a new add has brought no success. I even reinstalled the live system once completely and tried to add the sensor again, but always with this strange behavior.
  

## Steps to reproduce the behavior
1. Connect sensor to deconz
2. remove sensor
3. reset gateway
🠊 on a second freshly installed invironment
4. try to connect Sensor
5. repeat 4. 4 times until device is added
🠲 battery = 0%

## Expected behavior
The sensor should be added immediately and the battery status should be displayed correctly

## Screenshots
![battery](https://user-images.githubusercontent.com/94163719/170455843-a445cb05-26ee-46e1-956c-2cc7f13dcecf.PNG)

## Environment
**Both systems are based on identical conditions**

 - Host system: Raspberry Pi 3 Model B Plus Rev 1.3
 - Running method: Hombridge image - Raspbian GNU/Linux 11 (bullseye) 
 - Firmware version: 26690700
 - deCONZ version: 2.16.01 / 21.4.2022
 - Device: RaspBee II

**Comment by Mimiix** [comment] 2022-05-26 09:57
Hi,

As this is not a bug report as described in #5113, i am closing this issue.

Feel free to open an topic on the forums.

To give another comment on this: Battery often takes a while. If it isn't there in 6 hours, try re-pairing. This really is one of the downsides of Xiaomi sensors: they are hard to pair properly. 

Kind regards,

**Closed by Mimiix** 2022-05-26 09:57 UTC
Labels: Bug report
