### ISSUE TITLE
Blizwolf shp15 not power cosumation on HA and state on/off not work

### ISSUE THREAD

**Issue by manustars** [dresden-elektronik/deconz-rest-plugin#5591] opened 2021-12-20 10:01 UTC
## Describe the bug

I installed deconz on rbpi3+raspbee 2 with image download from phoscom, the pair is done on light tab, but on ha i see only switc on/off and doesent work.

i see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3788 and test but the problem its same. on deconz i see the power consumation and switch on/off work fine.

## Screenshots

![image](https://user-images.githubusercontent.com/60410607/146747957-6e30b851-659f-4154-8208-dde335de1114.png)
![image](https://user-images.githubusercontent.com/60410607/146748040-a77d511e-3172-4746-b9c7-17ebbe2ba83d.png)
![image](https://user-images.githubusercontent.com/60410607/146748263-ab427390-a92c-49a8-a5c4-cd7930ab57c7.png)
![image](https://user-images.githubusercontent.com/60410607/146748371-096b56b0-81bd-4849-bafe-00863704b6ae.png)
![image](https://user-images.githubusercontent.com/60410607/146748422-f8774246-d160-4e2a-85ab-29a217722df2.png)

## Environment

 - Host system: (Raspberry Pi )
 - Running method: (Raspbian )
 - Firmware version: (26690700)
 - deCONZ version: (2.12.06)
 - Device: (RaspBee II)
 - 
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment] 2021-12-20 10:22
Hi

Please update to the latest version as support was added  after 2.12.06

**Comment by manustars** [comment] 2021-12-20 11:22
now i see the power, the name changed after what I see it in ha? is it automatic or must it be updated manually on ha?

**Comment by Mimiix** [comment] 2021-12-20 11:30
I think automatically. Either way as this is not a bug on the device / implementation, i'm closing it.

**Closed by Mimiix** 2021-12-20 11:30 UTC
Labels: Bug report

**Comment by manustars** [comment] 2021-12-20 11:33
yes, thanks
