### ISSUE TITLE
Conbee II / 2 only works in certain USB ports.

### ISSUE THREAD

**Issue by oneseventhree** [dresden-elektronik/deconz-rest-plugin#6135] opened 2022-06-16 07:18 UTC
## Describe the bug

My Conbee II (with extension USB cable) has been sitting in the same USB port for weeks and hasn't had a problem but now it won't work in the USB port.
I can move it to the front USB of my NUC and it works but none of the back USB's work. It used to work flawlessly with those USB ports but now I only see:
![image](https://user-images.githubusercontent.com/15043282/174012717-c1e124de-8b19-4a64-901e-bbed721143be.png)

and when I click connect nothing happens.
When I unplug the extension cable from the NUC it disappears so it shows that it can see the device:
![image](https://user-images.githubusercontent.com/15043282/174012885-7c7cacb5-a9a2-4992-8c20-908d26d18065.png)

As soon as I plug it into my front port of the NUC it works and I don't even need to click 'Connect':
![image](https://user-images.githubusercontent.com/15043282/174013084-ba30dad5-3f1f-48e5-bc6d-1830e96cf15d.png)

Now logically I can just leave it in the front USB port but I am worried this port will have problems in the future just like my back ports of my NUC.

I have a USB hub plugged into the back port of the NUC, and only ONE of those four ports works.
I am not sure why it's so selective about which port its connected to when all the USB hub ports are the same.

## Steps to reproduce the behavior

  1. Plug Conbee into extension then into back port of the NUC (where it worked for weeks)
  2. Deconz can't connect to Conbee for some reason(see logs)
  3. Connect to front port of NUC or into USB hub's port
  4. Deconz connects in less than 1 second and works.

## Expected behavior

Any port should work especially when it used to work

## Environment

![image](https://user-images.githubusercontent.com/15043282/174013859-3d7576dd-9286-4c5c-8f9a-00804f5b6fe1.png)

 - Host system: NUC running Oracle VM VirtualBox
 - Running method: Home Assistent deCONZ Add-on with above
 - Firmware version: Home Assistant Core 2022.6.6
 - deCONZ version: 2.16.1
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? Unsure what this means

## deCONZ Logs

![image](https://user-images.githubusercontent.com/15043282/174012373-d8e47776-6557-47c0-bda5-02df390d1b24.png)

## Additional context

I also switched to ZHA a few weeks ago and found that the Conbee only worked on certain USB ports but not the ones Deconz works on.
I switched back to Deconz as ZHA does not support the hue tap switch.

**Comment by Mimiix** [comment] 2022-06-16 07:27
Hi

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-06-16 07:27 UTC
Labels: Bug report
