### ISSUE TITLE
Unable to update my firmware on RaspBeeII

### ISSUE THREAD

**Issue by pippo73** [dresden-elektronik/deconz-rest-plugin#5467] opened 2021-11-08 16:11 UTC
## Describe the bug

I'm trying to update the firmware of a raspbee II device from 26660700 to 26720700 version on a raspbian system

## Steps to reproduce the behavior

```

 $ sudo GCFFlasher_internal -l
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyS0       | 0x0000 | 0x0000  |            | RaspBee

$ sudo GCFFlasher_internal -r
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26660700
Bootloader version 0x00030003, app crc: 0x5CBFD214

 $ sudo systemctl stop deconz
 $ sudo GCFFlasher_internal -t 60 -f ./deCONZ_ConBeeII_0x26720700.bin.GCF
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26660700
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
wiringPi 2.52 initialized
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x5CBFD214
retry, failed


```

## Expected behavior

Firmware upgrades

## Screenshots

NA
## Environment

```
 $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

 $ uname -a
Linux sk4mc 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

```

 - Host system: Raspberry Pi 4
 - Running method: Raspbian
 - Firmware version: de26660700
 - deCONZ version: 2.12.06-raspbian-buster-stable
 - Device: RaspBee II
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? Yes, USB HD with the system installed on it

**Comment by Mimiix** [comment] 2021-11-08 16:13
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Please use the forum for this question.

Kind regards

**Closed by Mimiix** 2021-11-08 16:13 UTC
Labels: Bug report
