### ISSUE TITLE
Update 2.18.2 MLI tint Smart Switches loosing connection

### ISSUE THREAD

**Issue by ottelo9** [dresden-elektronik/deconz-rest-plugin#6378] opened 2022-10-02 13:41 UTC
## Describe the bug
After deconz update from 2.17.1 to 2.18.2 my tint Smart Switches (Müller Licht Aldi) loosing connection randomly. I've 5 of them. One day  1-2 switches have problems, next day they work for days without any problems. They work again if I reset the power.
tint smart switch V2.5.3_r47. I now try to go back to 2.17.1. I use deconz inside Home Assistant with Conbee 2.

## Steps to reproduce the behavior
...

## Expected behavior
...

## Screenshots
![404021_a03_001](https://user-images.githubusercontent.com/33122175/193456882-3867b4e8-a5d4-4634-8e32-2f278dfca8d9.jpg)
![2022-10-02 15_37_01-deCONZ – Home Assistant](https://user-images.githubusercontent.com/33122175/193456980-b3a16465-389a-4f48-a57c-49493ec3c55f.png)

## Environment
- deCONZ 2.18.2
- Conbee II 26720700
- Home Assistant 2022.9.6
- Deconz Addon 6.16.0
- Do you use an USB extension cable: yes

**Comment by Mimiix** [comment] 2022-10-02 15:58
Hi there,

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum 's.

Kind regards,
Dennis

**Closed by Mimiix** 2022-10-02 15:58 UTC
Labels: Bug report

**Comment by ottelo9** [comment] 2022-10-11 08:51
Problem was the new OTA updates:
https://community.home-assistant.io/t/deconz-official-thread/100504/3305
