### ISSUE TITLE
Support for  ZGP proxy

### ISSUE THREAD

**Issue by posixx** [dresden-elektronik/deconz-rest-plugin#436] opened 2018-02-24 16:20 UTC
When does deCONZ support ZGP proxy messages so our Hue TAP devices are working more reliably? Could someone pick up the development / implementation for this?

**Comment by posixx** [comment] 2019-03-23 13:12
This is still an active problem.. If a tap is far away from the controller it doesn't work, even if it is surrounded with lights. It should mesh through the network.

**Comment by posixx** [comment] 2019-06-15 12:31
Is this still unresolved? Having trouble with a TRADFRI remote i want to use a TAP in my garden but before i'm going to buy one i want to make sure proxying is supported..

**Comment by manup** [comment] 2019-06-15 15:32
The proxy support is still in active development, there is unfortunately no ETA but we made some progress in the past weeks in figuring out the needed crypto details.

**Comment by posixx** [comment] 2019-07-09 09:22
@manup great news, my wife is keeping me reminded of this issue:-) Hope to hear some progress soon!

**Comment by rendgeor** [comment] 2019-09-07 20:08
@manup 
1) Is there any basic support for ZGP coming withing the next two months?
2) or is there any other ZGP proxy available?

**Comment by UltraSub** [comment] 2019-09-21 12:26
Also very interested in this. Have a switch surrounded by lights, but it can’t reach the controller. Since it doesn’t mesh/route I’m stuck and can’t use the switch.
Ordered a Conbee II since that should have a bit better range and will try to extend the location of the Conbee stick further away from the server. But there’s only so much I can do there. Really hope you guys can get this fixed! 👍

**Comment by posixx** [comment] 2019-09-28 15:33
Yes keep this thread alive so they don't forget:-) Having to turn on/off my garden shed lights every weekend with the ipad instead of a tap becomes more and more anoying..

**Comment by rendgeor** [comment] 2019-11-05 13:33
@manup Dear Manuel, is it possible to get some kind of feedback that the users know when more or less a feature will be supported. Short feedback within the threads would be great!!!

Not beeing able to use the switched is annoying...

**Comment by posixx** [comment] 2020-01-04 05:13
@manup any updates on this?

**Comment by Torrentus** [comment] 2020-02-29 13:56
Hue tap devices are very usable to 'tweak' and integrate in normal-looking switches that fit in busch-jeager and gira switches. Thus, we have them throughout the entire house. I would love to use them with Deconz. Please prioritize ZGP-support!

**Comment by Koenkk** [comment] 2020-03-17 17:48
> The proxy support is still in active development, there is unfortunately no ETA but we made some progress in the past weeks in figuring out the needed crypto details.

@manup would you mind sharing these crypto details? I'm working on the green power implementation in zigbee-herdsman and managed to successfully setup a ZGP proxy on a Hue bulb for a Hue tap switch. However currently uses the key which I sniffed with my Hue hub, this key is probably specific for my Hue tap switch (https://github.com/Koenkk/zigbee-herdsman/blob/feature/greenpower/src/controller/greenPower.ts#L19). Once it's implemented in herdsman I think it can be easily ported to Deconz.

**Comment by manup** [comment] 2020-03-19 19:21
@Koenkk unfortunately the decryption part hasn't progressed much. I looked into the ZGP related sources of the stack but haven't figured out yet how exactly it's done. So current situation is what can be found in the deCONZ REST-API plugin main ZGP handler for incoming commands:

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/de_web_plugin.cpp#L1124

Do you have access to the ZGP specification? The security aspects are described there, I can send you the PDF if that would be any help.

**Comment by Koenkk** [comment] 2020-03-19 20:53
@manup I don't have access to it, however some contact of me mentioned that Hue uses a proprietary key (not sure if that's true though).

**Comment by Koenkk** [comment] 2020-03-29 16:18
@manup could you share the pdf with me? (koenkanters94@gmail.com)

**Comment by Koenkk** [comment] 2020-04-07 18:20
@manup with some help I've managed to figure out to crypto details. Javascript implementation can be found here: https://github.com/Koenkk/zigbee-herdsman/blob/feature/greenpower/src/controller/greenPower.ts#L20 . I also have a C# implementation, in case you are interested feel free to contact me.

**Comment by posixx** [comment] 2020-04-07 18:54
Nice work @Koenkk! Hopefully this will spped up ZGP Proxy implementation..

**Comment by ebaauw** [comment] 2020-06-27 17:05
Bump

**Comment by SwoopX** [comment] 2020-06-27 17:10
Smanar has already finished the C++ implementation. Should be included at the appropriate place

**Comment by Smanar** [comment] 2020-06-27 17:24
But it works ouside deconz ^^.
It need some convertion, and I haven't this kind of device to make test.

**Comment by ebaauw** [comment] 2020-06-27 17:59
@Smanar, I have a couple of Hue taps and am eager to try this.  Happy to take over and integrate the code into the REST API plugin.

**Comment by Smanar** [comment] 2020-06-27 18:15
Nice :) > https://github.com/Smanar/Zigbee_firmware/blob/master/Encryption.cpp

**Comment by posixx** [comment] 2020-07-02 09:55
@ebaauw any progress on implementing this? I'm also eager to try!

**Comment by ebaauw** [comment] 2020-07-02 10:41
Not yet.  Crazy times at work.  Hopefully find some time this weekend, but no promises.

**Comment by ebaauw** [comment] 2020-07-25 05:10
Bump

**Comment by jaxer** [comment] 2020-07-29 21:22
Let me know if i can help testing as well. Looking forward for this one

**Comment by macpo** [comment] 2020-09-23 19:35
If another tester is needed, I will gladly help.

**Comment by manup** [comment] 2020-10-14 15:34
Spend the whole day on figuring out the ZGP specification, the code from @Smanar works for Zigbee test vectors but the generated value doesn't seem to be the desired GPDKey. I compared with Philips Hue bridge and their generated GPDkey looks different for the same input parameters.

Perhaps what we need is &rarr; A.1.5.3.3.2 Individual GPD key derivation

**Comment by Smanar** [comment] 2020-10-14 16:03
I have compared with zigbee2mqtt result (on windows hardare)

@manup do you have an exemple with correct values ? To change my code ?

**Comment by manup** [comment] 2020-10-14 16:04
F+ck, correction, I called the function with the wrong sourceId.... it seems to work now. Will do some tests.

**Comment by manup** [comment] 2020-10-14 16:10
All ZGP routers seem to forward the ZGP command, I wonder how well it scales and if it is troublesome then many ZGP end-devices get paired. Next step is to unwrap the ZGP notifications into our ZGP handlers.

![image](https://user-images.githubusercontent.com/383386/96015858-53b90280-0e48-11eb-8d07-79ddc81972e8.png)

**Comment by lh14576** [comment] 2020-11-04 18:23
does ZGP also work for adding new switches? I am trying to add a FOH Scenic switch and it's only working when the switch is close to my raspbee2. I am on FW 26660700 and 2.05.86
Thanks

**Comment by Mimiix** [comment] 2020-11-06 14:44
Created a internal ticket :)

**Comment by manup** [comment] 2020-11-08 11:20
The code is fixed now in deCONZ core and available in the upcoming release.
The problem is that the Green Power endpoint wasn't configured automatically.

As workaround prior to the release the endpoints can be configured manually via *deCONZ > Edit > Network Settings > Endpoints*
And there the following configuration needs to be set:

![image](https://user-images.githubusercontent.com/383386/98463567-6232d980-21bc-11eb-8bd6-cdaa98d9eb29.png)

Then press save, the endpoints for the coordinator should look like:

![image](https://user-images.githubusercontent.com/383386/98463622-c35aad00-21bc-11eb-8987-5dee6403d060.png)

**Comment by posixx** [comment] 2020-11-14 14:43
Ok i installed 2.05.88 on my HASS system, added a new Hue Tap, and moved to my gardenhouse, but it doesn't work; my lights in the gardenhouse are not triggered when using the Tap. As soon as i move back to my house the lights are triggered when using the Tap..

**Comment by manup** [comment] 2020-11-14 15:43
What kind of routers are near the garden house? Can you please provide some logs during switch adding and when triggering the switch outside the house.

**Comment by posixx** [comment] 2020-11-14 16:18
In the garden house i have 4 LCT001 lights (fw 5.23.1.13452) and a LCT015 (fw 1.19.0_r19755) about 10m from the gardenhouse. I'm sorry but i don't have the skills nor the tools to get you any logs..

**Comment by manup** [comment] 2020-11-14 17:01
Ok these are all Hue lights and should support ZGP.

I think when pairing the switch it needs to be near the real destination so that lights create an entry for it in their local device table.

**Comment by jaxer** [comment] 2020-11-14 17:37
i can second above. also have a bigger flat, single floor house full of hue lights and i cannot control nor pair friends of hue switch if i am in the corner furthest from conbee II.
running latest firmware.

idk if its wrong, but some lights have more than one Green Power thing:
![image](https://user-images.githubusercontent.com/202096/99153348-ab999200-26b0-11eb-9111-480301789432.png)

Although those are same lights (hue gu10 zb/ble color bulbs)

**Comment by manup** [comment] 2020-11-14 17:41
Note it's important to pair the switch near the real destination. The routing won't be automatically added by updating deCONZ.

Lights which have two ZGP clusters (blue = server and grey = client) is valid.
The coordinator should also have ZGP endpoint i its list.

**Comment by jaxer** [comment] 2020-11-14 17:46
I understood, and tried few times to pair it there. With no success.

Sorry, those two lights are actually different:
the one on right is e26 hue bulb and the one on left is newer gu10 hue zigbee/bluetooth bulb.
Does it mean that only those with blue Green Power endpoint can receive communication from friends of hue switches? I thought that gu10 should also be able to forward those packets?

here is coordinator, seems fine to me:
![image](https://user-images.githubusercontent.com/202096/99153612-17c8c580-26b2-11eb-946d-6c70e42e8874.png)

**Comment by manup** [comment] 2020-11-14 17:54
Hmm, I need to do some testing to see if there is a problem, have only testet it in near distance where it worked that devices did reroute the ZGP frame.

>Does it mean that only those with blue Green Power endpoint can receive communication from friends of hue switches? I thought that gu10 should also be able to forward those packets?

Good question, I think they both should support it but I'm not 100% sure.

My IKEA and Philips (E27) lights all have both ZGP server and client clusters.

**Comment by jaxer** [comment] 2020-11-14 18:00
tried it again: was able to pair it somewhere in the middle between the conbee and the furthest room.
but it did not improve the performance: in target room i am able to control lights only occasionally. i.e. 50% of clicks do what i expect and other 50% do nothing.

**Comment by jaxer** [comment] 2020-11-14 18:15
on the other hand, i have this same setup from a year or so (i have stable versions of deconz running on HASS). and i think few months ago performance was way worse. now i can with much smaller problems use frineds of hue switches in the middle of the house. i.e. maybe 80-90% of clicks work there. and it used to be like 50% (if not less) clicks only.

so i mean, maybe what you did actually works but range is still limited,  i.e. number of hops is only 1 atm? i.e. if switch needs to pass green power packet through 2 proxies instead of one then it will not work?

**Comment by lh14576** [comment] 2020-11-15 06:39
.87 final ZGP seems to work fine for me now. All my Hue Lights have blue and grey ZGP.

**Comment by posixx** [comment] 2020-11-15 09:46
All my Hue Lights have blue and grey ZGP as well, but my Tap isn't working on distance..

**Comment by posixx** [comment] 2020-11-15 09:55
Ok, i removed the Tap, walked to the garden house and tried to add it there, but i cannot add it, deconz is not responding on my tab button presses.

**Comment by ICTSMART** [comment] 2020-11-16 15:03
As there was a new stable release of Phoscon (addon in HA) version 2.05.88 I decided to retest this issue again.
Still, for this specific model (the Niko Smart Switch PTM 215Z) the ZGP telegrams are still not relayed through the network.
My setup consists of a Raspbee I - latest firmware 26390500 running Phoscon/deCONZ version 2.05.88 / 10/15/2020.
When I increase the distance between the Niko Switch and the Raspbee, although multiple routers are in between, no messages are relayed. For testing purposes I used Ikea Signal extenders as Routers. Your suggestions are welcome.

**Comment by ICTSMART** [comment] 2020-12-01 19:29
@manup Please let me know how I can help or provide debug info to sort this out.

**Comment by manup** [comment] 2020-12-07 22:00
Found some issues in handling the proxy commands, and made a lot of tests.
The latest PR should fix the issue.

So when the next version v2.8.0 is out, you need to start sensor search once and repeat the joining process by holding the respective channel button for 10 seconds (the switch does *not* need to be deleted first). The gateway will then setup up to 3 proxies for the switch.

I think in future versions we need to remove proxies when they report a poor signal from the ZGP device and when other better proxies are available. The IKEA lights report they can only manage up to 5 ZGP end devices.

**Comment by posixx** [comment] 2020-12-09 17:48
@manup you mention v2.8.0 for this change, so i guess it's not part of the current stable v2.7.1 release from yersterday?

**Comment by manup** [comment] 2020-12-09 19:37
Sorry my bad, yes it is in v2.7.1.

**Comment by jensflorian** [comment] 2020-12-09 20:14
Just to be sure, there will be no response message in sensor search after pressing the channel button on ZGP switch?

**Comment by macpo** [comment] 2020-12-09 20:34
After the installation I had to delete and to repeat the join process. It did not work by holding the join keys. I have only two switches... But now the switches works as expected... Great job

**Comment by posixx** [comment] 2020-12-10 11:17
I tried to pair a Hue Tap on the destination but it will not pair. 
@manup is it still a requirement to pair the ZGPSwitch on destination far away from the bridge?

**Comment by manup** [comment] 2020-12-10 14:19
It should also work when the switch is at it's final destination, which is also better so the most appropriate routers can be selected based on the signal strength.

Can you please enable ZGP logging in *Help &rarr; Debug view* when pairing the switch, it should yield some info about the proxies when they receive something.

Note also to only open the Phoscon App (especially the Sensors/Switches pages ) in just one browser at the time of joining.

**Comment by posixx** [comment] 2020-12-10 14:25
I don't see that option. Also i don't know where the logs go as i'm using the HASS plugin version. I can view the log but only a fraction of it.

**Comment by manup** [comment] 2020-12-10 14:40
Do have version 2.7.1 installed? The ZGP option should be there, also in the latest Hassio add-on.

![image](https://user-images.githubusercontent.com/383386/101786161-e64ee880-3afd-11eb-99f8-d3b3078766e9.png)

**Comment by posixx** [comment] 2020-12-10 14:50
Found it. I was able to register the switch by having it almost directly held agains the lightbulb. Afther that it doesn't react very good when clicking the buttons; i need to have it placed within half a meter of the lightbulb:

![image](https://user-images.githubusercontent.com/2280400/101787505-73467180-3aff-11eb-8d39-3f07e8f617aa.png)

**Comment by posixx** [comment] 2020-12-10 15:10
Ok it sort of works. Maybe it's my situation. the lights in the gardenhouse are housed in a metal hoursing havind only upper and lower beaming against the walls. Maybe the Tap isn't strong enough to come though. These light are fairly old (1st generation E27 color)i will see ef i can place another light in the neigbourhood. Will this light automatically proxy the tap commands ?

**Comment by Mimiix** [comment] 2020-12-10 15:13
@posixx While reading, i noticed the 0xE9 in the screen above. What device is is that?

**Comment by manup** [comment] 2020-12-10 15:17
Oh yes metal is very hostile to wireless in general, could well be that the proxies found the signal too weak and didn't process further. deCONZ does also filter for proxies which at least report "moderate" signal strength but won't pick proxies which report "poor".

**Comment by posixx** [comment] 2020-12-10 15:23
@Mimiix these are random lights, not one in particular. Yesterday my gateway was not reacting at all. It only logged these errors for all lights. I upgraded to v2.7.1 and all was back as normal but these 0xE9 errors aswell as unknown neighbour errors are all over the place.. I'm hoping this will eventually clear itself..

**Comment by manup** [comment] 2020-12-11 01:14
I've changed the unknown neighbor print now to the "ROUTING" log level (which is quite noisy itself in the upcoming release).

**Comment by posixx** [comment] 2020-12-13 12:58
I added 3 Hue Lightstrips Outdoor to my gardenhouse. I installed the Senic Gira Friends of Hue switch within 3 metres of the lightstrips. I was able to register the Gira switch but i get no reaction on the button presses.. So to me it looks like ZGP proxy is still NOT WORKING.

**Comment by posixx** [comment] 2020-12-13 15:57
Removed the Gira and added it again. I see the pairing in the log:

![image](https://user-images.githubusercontent.com/2280400/102016968-22838280-3d64-11eb-883d-7eaf19ecafa9.png)

As you can see signal is excellent. But after pairing the lights don't flash, and the wizard doesn't close. It looks like the pairing doesn't create the ZGP proxies because afterwards non of the buttons work.

**Comment by SwoopX** [comment] 2020-12-13 16:26
Actually, your screenshots proves the switch emmits the button events.

**Comment by posixx** [comment] 2020-12-13 17:19
Excactly, only during pairing. But after that no ZGP messages are logged when pressing buttons, so no ZGP proxies are present.

**Comment by manup** [comment] 2020-12-13 17:32
Hmm that's odd, also no button events when using the switch near the gateway?

**Comment by posixx** [comment] 2020-12-13 18:36
I cannot test that as i have mounted the switch using the adhesive stickers, i'm not going to remove that for test purposes.. I can test tomorrow with a Hue Tap as i have one spare.

**Comment by posixx** [comment] 2020-12-13 18:45
Sorry can't wait until tomorrow:-) Yes the Tap works. When pairing the lights flash and i see the button presses:

![image](https://user-images.githubusercontent.com/2280400/102020769-9aa97280-3d7b-11eb-8b8d-caaf0ff3f187.png)

So it is due to the Senic Gira switch...

**Comment by posixx** [comment] 2020-12-13 18:48
What i notice; when pairing the tap is see 2 proxy notifications, when pairing the Gira only one.. Maybe the paring routine isn't completed within deconz due to the missing 2nd signal?

**Comment by posixx** [comment] 2020-12-13 19:04
Ok i used the "Other" inclusion wizard, now i got a flash fo my lights when including the switch. But, after closing the wizard, the switch is dead again..

**Comment by posixx** [comment] 2020-12-16 12:53
Yesterday i searched for alternative green power implementations and stumbled on this https://www.zigbee2mqtt.io/devices/GreenPower_7.html#pairing-friends-of-hue-switches-enocean-ptm-216z-module-based

So i removed the Gira from my sistem, opened the "other" paring wizard again and followed instructions from this link. And Voila it registered successfully now! Buttons are working. So ZGP Proxy works!

**Comment by posixx** [comment] 2020-12-16 13:43
It seems ZGP Proxies are not saved/stored, so when a light is powercycled it looses the ZGP Proxy. Is this correct?

**Comment by posixx** [comment] 2020-12-17 10:12
This morning my Gira switch doesn't work anymore. Seems like it lost the ZGP proxies.

**Comment by manup** [comment] 2020-12-17 19:10
Hmm strange I would have thought that lights keep their proxy configuration after power-cycle, but I have to admit that was not tested. Your proxy is a Philips Hue light?

**Comment by posixx** [comment] 2020-12-17 19:19
Yes correct, i only have Hue stuff. To be clear; the loss of proxies this morning are not due to a power-cycle; they simply are gone / gira doesn't react anymore. 

Also when power-cycle the lights they loose ZGP proxy.

**Comment by manup** [comment] 2020-12-17 19:23
That makes things more complicated and would mean we need to keep proxy configuration in the database and restore it periodicaly or after an power cycle. A bit surprising since Hues store other stuff like scenes and groups across power-cycles. I guess it's time to sniff the Hue gateway how they do it :)

**Comment by ebaauw** [comment] 2020-12-17 19:53
@manup, do you need help with that?

**Comment by manup** [comment] 2020-12-17 20:06
Perhaps the on the sniffing part, I currently only have a v1 brige here, hope ZGP works the same as with the v2?

**Comment by ebaauw** [comment] 2020-12-17 21:25
Still have this one from 2017.  Key is in the file.  Looking at my notes, NWK 0xBDEC is a gen-2 Hue bridge; 0x0045 is a Hue LCT003 GU.10 spot.
[hue_tap_2.dcf.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5712186/hue_tap_2.dcf.zip)

**Comment by posixx** [comment] 2020-12-17 22:07
Just to be on the safe side i have started paring again and clicked the Gira buttons. I see the GPP Proxy messages again:

![image](https://user-images.githubusercontent.com/2280400/102549480-7079ec80-40bc-11eb-8396-8300f35dd6ab.png)

Buttons start to work again, but slow response is back (CMD_APS_DATA_INDICATION2). I will let you know tomorrow if the same happens as yesterday.

**Comment by posixx** [comment] 2020-12-18 23:21
Confirmed: after xx hours ZGP Proxies are lost and delays are resolving again!

**Comment by manup** [comment] 2021-01-09 15:20
I've done some sniffing with Philips Hue v1 bridge, Innr plug as ZGP proxy and a Philips Hue Tap.

To pair ZGP devices the Hue bridge sends a Pairing command via broadcast to all routers. While this works in smaller networks, I think it's an bad idea given that Proxies often only allow max. 5 entries. I can imagine this might be problematic with more than 5 ZGP devices in larger random setups.

To keep the pairing alive, the Hue bridge is sending a Pairing command via broadcast every 15 minutes via broadcast. Tricky but at least the proxy can be assumed to be mostly in operational mode, not commission mode, where new ZGP entries are added.

For deCONZ this means the initial pairing works and I think the unicast approach is better in terms of scalability when broadcast. But the maintenance of entries in proxies is missing.

For this some code needs to be written, where:
* ZGP frame counters and security information is stored and updated in the database;
* Periodically send unicast or broadcasts per ZGP device to keep the entries in proxies alive;

I'll figure something out, but it will take likely until February to be released.

**Comment by posixx** [comment] 2021-01-09 17:30
Great Manuel, thanks for your update! Looking forward to the fix.

**Comment by ICTSMART** [comment] 2021-01-10 08:14
With that in view - it's definately worth waiting a little longer!

**Comment by SeraphimSerapis** [comment] 2021-01-13 17:55
I got pointed to this issue on #4176 by @Mimiix. I can confirm that my switches (not all of them) periodically stop working while I am not power cycling any of the lights that may serve as their proxy.

Momentarily, I have 9 FoH Switches by [Busch Jäger](https://www.busch-jaeger.de/produkt/future-linear/friends-of-hue) and more than 25 lights (mostly Hue) in my deCONZ network.

**Comment by SeraphimSerapis** [comment] 2021-01-16 10:09
It occurred to me that some switches seem to be working perfectly fine. The ones that seem to not be affected by the issue are those closer to my ConBee I. I happen to have a ConBee II lying around and wonder if I could use that as second coordinator in my network. Does deCONZ support this? I'm currently using the docker container on my main host but am happy to go for a different installation if required.

**Comment by ebaauw** [comment] 2021-01-16 11:56
> I could use that as second coordinator in my network.

No. A Zigbee network can only have one coordinator (blue node on the GUI with NWK address 0x0000).

You can have multiple gateways on a single Zigbee network, but then you'd have to configure the other gateway device as router.  While theoretically possible, this feature is currently broken in the GUI.  Also some devices (notably Xiaomi) will only send notifications to the coordinator (hard-coded to NWK address 0x0000), so a gateway running on another router won't know their state.

When ZGP devices are in direct range of the gateway, everything works fine, as the gateway device receives the ZGP messages directly.  When the ZGP device is out of direct range, you need a nearby router with a special function, ZGP Proxy, to package the ZGP message in a regular Zigbee message and forward that to the gateway.  Configuring the ZGP proxies proves to be very challenging.

**Comment by SeraphimSerapis** [comment] 2021-01-16 13:03
> > I could use that as second coordinator in my network.
> 
> No. A Zigbee network can only have one coordinator (blue node on the GUI with NWK address 0x0000).
> 
> You can have multiple gateways on a single Zigbee network, but then you'd have to configure the other gateway device as router. While theoretically possible, this feature is currently broken in the GUI. Also some devices (notably Xiaomi) will only send notifications to the coordinator (hard-coded to NWK address 0x0000), so a gateway running on another router won't know their state.
> 
> When ZGP devices are in direct range of the gateway, everything works fine, as the gateway device receives the ZGP messages directly. When the ZGP device is out of direct range, you need a nearby router with a special function, ZGP Proxy, to package the ZGP message in a regular Zigbee message and forward that to the gateway. Configuring the ZGP proxies proves to be very challenging.

Thanks for the elaborate response @ebaauw -- I really appreciate it!

**Comment by JayJay68** [comment] 2021-01-31 11:51
I have the same problem with Senic Smart Switch (FoH): Pairing and using the switches works fine (when they are in the direct range of the bridge/coordinator). If they are out of the range to the bridge - so they must use the mesh-network - it doesn't work. It is just as @ebaauw described it.
I hope, that @manup will have some time in the near future to to solve the problem.
**I would like to say a big "Thank you" to all contributors and devs for your great work!**

**Comment by posixx** [comment] 2021-02-16 15:11
> For this some code needs to be written, where:
> 
> * ZGP frame counters and security information is stored and updated in the database;
> * Periodically send unicast or broadcasts per ZGP device to keep the entries in proxies alive;
> 
> I'll figure something out, but it will take likely until February to be released.

@manup will this be part of the next release? Hope so!

**Comment by ICTSMART** [comment] 2021-02-16 17:47
@posixx this is great news! This will bring a lot of ZGP based switches into the ecosystem.

**Comment by SeraphimSerapis** [comment] 2021-03-11 10:49
Hi @Mimiix @manup -- my apologies for the direct ping. I was wondering if there is any way we can help with testing potential fixes/solutions to this matter. For now, I'd have to move all my FoH switches back to Hue, which seems like a compromise when knowing what deCONZ is capable of doing.

Looking forward to hearing more on ZGP,
Tim

**Comment by Mimiix** [comment] 2021-03-11 10:54
@SeraphimSerapis I'll make sure Manup reads along ;)

**Comment by cranxi** [comment] 2021-04-17 15:19
What is the progress of this implementation? My FoH ZGP switch is still only connecting directly to the controller, not to the lights around the switch.

**Comment by posixx** [comment] 2021-04-19 10:40
This was added to the v2.11 milestone so we can expect implementation in one of the upcoming beta's!

**Comment by cranxi** [comment] 2021-04-19 10:50
Ah ok, I see it now, my bad! That's awesome, I'll wait patiently :)

**Comment by tomdegoeij** [comment] 2021-04-26 11:35
Great thing I found this topic, since I'm experiencing the exact same issue. I'll be looking forward to the upcoming betas. If I can help testing out functionality, just let me know. In my house I currently have 12 FoH ZGP switches (Senic) and around 75 other Zigbee devices (mostly Hue lights). The ZGP switches further away from my coordinator stop functioning after a day or so. My coordinator is a Deconz docker installed on a Synology NAS, with a Conbee II plugged in.

What is the easiest workaround for the time being? I found out that pairing one of the non functioning switches again using Phoscon makes sure all of the switches are working again. Is there a workaround I can apply periodically (i.e. every 12 hours) before the switches lose connection?

**Comment by cranxi** [comment] 2021-04-26 17:38
Not sure what you mean, but my (and others ofc) problem is that the FoH ZGP switches would only connected to the router (Conbee stick) and not nearby lights. At the moment there is no workaround for it other than leave all the lights and switches on the Hue Bridge for the time being, that's what I did.

**Comment by tomdegoeij** [comment] 2021-04-26 17:59
That’s exactly my problem. However, right after pairing the FoH ZGP switches to the router/coordinator they do work through nearby Hue lights. Then after a day or so they lose connection. Switches close to the router/coordinator continue to work. It is exactly the problem described in this topic/issue.

Going back to using a Hue Bridge isn’t a viable option for my use case. Probably I will just use some battery powered switches (non ZGP) as a temporary solution.

**Comment by cranxi** [comment] 2021-04-26 18:18
Ah I see, then you're 'lucky' haha, mine don't even work with nearby Hue lights. Anyhow, yes you can just use battery powered switches instead for the meantime.

**Comment by SeraphimSerapis** [comment] 2021-04-26 18:25
> Ah I see, then you're 'lucky' haha, mine don't even work with nearby Hue lights. Anyhow, yes you can just use battery powered switches instead for the meantime.

As far as I understand, it doesn't even matter if Hue lights are nearby, as currently they don't serve as nearby proxies (the intended use) -- only the coordinator is doing so at the moment, thus only FoH switches close to your Zigbee stick work. The workaround is a) use actively powered switches (like the Hue remote) or b) transition the FoH switches back to a Hue bridge and have enough lights (or other active Zigbee devices) connected to that additional network to make sure these switches can be reached.

**Comment by spalanzani** [comment] 2021-05-16 17:30
I'll add one tale to the list: I have two Sunricher SR-ZG2833PAC-C4s installed in very close proximity (less than a meter apart). I can pair both of them as FoH switches, and one of them is giving me "ZGP button"s in the debug log and toggles my bedroom lights, the other one leaves a single ZGP button log directly after pairing and is then never seen again.

Both of them do not show up as nodes in deCONZ by the way.

After scratching my head over this for hours, I have decided I must be looking at mesh/wireless randomness that will only go away once this issue is resolved.

**Comment by tomdegoeij** [comment] 2021-05-16 17:40
> > As far as I understand, it doesn't even matter if Hue lights are nearby, as currently they don't serve as nearby proxies (the intended use) -- only the coordinator is doing so at the moment, thus only FoH switches close to your Zigbee stick work.

I have been using my setup for the last 3 weeks and the FoH switches close to the Zigbee stick work without any problems. The FoH switches further away from the Zigbee stick stop working once every day or so. I can fix all of the non-working FoH switches quite easily, by going to Switches -> Add new switch -> Other in Phoscon and holding the right button on one of the FoH switches for 10 seconds. After this procedure all non-working FoH buttons instantly work again, and keep working for a day.

So it takes me less than a minute a day to keep this setup working. For the time being I won't mind. Hopefully it will be possible to resolve this issue. My wife will be happy when it does.

**Comment by posixx** [comment] 2021-06-17 15:38
@manup; i don't see any updates in the last 2 beta's for ZGP proxy; does this mean it will again be postponed?

**Comment by manup** [comment] 2021-06-21 21:56
It's planned to be included within the v2.12.x version series, not going to be postboned again since this already took too long.
I'm aiming for v2.12.3-beta or v2.12.4-beta before the next stable release.

**Closed** 2021-08-10 21:50 UTC
Labels: To-Do, Backlog

**Comment by JayJay68** [comment] 2021-09-17 18:28
I updated to 2.12.06 and flashed my RaspBee to 26400500 and **it works now!**!! 

For other users it might be useful to know, that you have to do a new commissioning, if the switch was already in the network:
1. Bring the switch within radio range to your controller (RaspBee, RaspBee II, ConBee, ConBee II).
2. Do the steps 4 and 5 from https://phoscon.de/en/support#phoscon-app-usage-on-smartphone (section "How can Friends of Hue switches be paired to the network?")
3. Wait 15 to 30 Minutes.
4. Switch on / off

ithin radio range to your controller 

After this procedure my FoH-Switches (Gira Senic) works (even if they aren't within radio range).

@manup and all involved developer: **Thank you for implementation of ZGP**

I think that the support of ZGP should be mentioned in the changelog in big lettern.

**Comment by posixx** [comment] 2021-09-17 21:31
Yes works beautifully. Another way to re-register the ZGP proxies on existing switches; Start inclusion mode for a new switch (even if you don't have one), and click one of the buttons of the existing switch. After cancelling the inclusion mode the switch will work using ZGP Proxy

**Comment by tomdegoeij** [comment] 2021-10-01 22:20
It indeed works wonderfully!

At first it didn’t seem to work, but that was because I used the Deconz docker image (marthoc/deconz). Using that image, whenever I try to commission a ZGP switch, Deconz gives an OpenSSL related error message in the console/log.  Hence GPDKey  isn’t calculated. See https://github.com/marthoc/docker-deconz/issues/426.

Using the Deconz SD image for Raspberry Pi everything works very well!
