### ISSUE TITLE
[Request device support] Support for Namron 4-channel switch (Luzense/Sunricher clone)

### ISSUE THREAD

**Issue by eckhart** [dresden-elektronik/deconz-rest-plugin#2158] opened 2019-12-01 14:30 UTC
This is widely available in Norway, and fits the standard ELKO frames which are common here:

https://www.elektroimportoren.no/namron-zigbee-4-kanaler-bryter-k8/4512703/Product.html

To me it seems more or less identical to the 4-channel ones in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1509 but under a different brand name. It shows up in deCONZ with "Namron AS" as manufacturer instead of "Sunricher" and doesn't show up as a switch in Phoscon/REST API after the switch confirms successful pairing.

Below is what I have from deCONZ. I've read out all the attributes from the seperate channels, they look identical so just including one of them here. Let me know if more info is needed.

![namron_switch1](https://user-images.githubusercontent.com/1478965/69915308-e4177000-144d-11ea-96d1-8e9bd471ba8d.png)
![namron_switch3](https://user-images.githubusercontent.com/1478965/69915321-fe514e00-144d-11ea-92ba-a1f22eaea360.png)
![namron_switch4](https://user-images.githubusercontent.com/1478965/69915322-fe514e00-144d-11ea-8426-b57bc67c6c7d.png)
![namron_switch5](https://user-images.githubusercontent.com/1478965/69915323-fee9e480-144d-11ea-88c5-90003d906c61.png)
![namron_switch6](https://user-images.githubusercontent.com/1478965/69915325-fee9e480-144d-11ea-994f-9797e16367ef.png)
![namron_switch11](https://user-images.githubusercontent.com/1478965/69915341-29d43880-144e-11ea-81e9-ba81ca75dfe7.png)

**Comment by corvy** [comment] 2019-12-02 12:03
@eckhart it does not show up in groups  in the old web interface either? 

@ebaauw I guess it takes a very basic change to add support for this?

**Comment by eckhart** [comment] 2019-12-02 17:41
No, it doesn't show in the old web interface either.. Would be great to have it supported as it's a lot cheaper than other brands.

**Comment by ebaauw** [comment] 2019-12-02 19:13
Probably.  Just whitelist it in `supportedDevices` in `de_web_plugin.cpp` and assign it to the buttonmap for the 8-button switch in `sensors.cpp`.

**Comment by eckhart** [comment] 2019-12-07 09:07
@ebaauw Sorry that I haven't had the time to follow this up, would be great if no more than this is needed. Being new to this, do the devs prefer that I add, build and test this myself and then make a pull request?

**Comment by ebaauw** [comment] 2019-12-07 10:06
> do the devs prefer that I add, build and test this myself and then make a pull request?

That's what I've done for the devices I own or could borrow.  Adding support without having physical access to the device is almost undoable, due to different interpretations of the ZigBee standards by different manufacturers, and due to the complexity of the REST API plugin code (there's always one more place to whitelist a device).

**Comment by monsivar** [comment] 2020-01-04 10:44
> @ebaauw Sorry that I haven't had the time to follow this up, would be great if no more than this is needed. Being new to this, do the devs prefer that I add, build and test this myself and then make a pull request?

Do you have an config that works for this switch?

**Comment by eckhart** [comment] 2020-01-10 09:04
@monsivar Unfortunately no, I haven't had the time to set up a building and testing environment yet. I'll submit a pull request when I have something working.

**Comment by monsivar** [comment] 2020-01-17 20:14
Is there any recipes on the net for adding this switch to the deconz for an nuub like me? @ebaauw

**Comment by ebaauw** [comment] 2020-01-17 20:40
None official.  I did a writeup here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2061#issuecomment-568191933

**Comment by phithor** [comment] 2020-01-23 12:14
I'd like support for this switch myself. Going to try to do this over the weekend.

**Comment by monsivar** [comment] 2020-01-23 16:07
> I'd like support for this switch myself. Going to try to do this over the weekend.

Nice, I did not see the effort of trying..

**Comment by flemmingss** [comment] 2020-01-25 17:11
I am also interested in getting this Namron 4-channel switch to work with Deconz,
I have one still unopened because of this support missing. I am not in any way experienced with doing anything non-phoscon at this time, but if there is some info I can supply just let me know

**Comment by phithor** [comment] 2020-01-27 10:57
I tried to whiteliste it and button map it as described above and then i was unable to build it in my environment, got an error with missing QT module serialport for some reason and did not have time to debug it. Do I need to install qt explicitly in addition to deconz-dev?

https://github.com/dresden-elektronik/deconz-rest-plugin/compare/master...phithor:namronswitch

**Comment by mk1blacklimited** [comment] 2020-01-31 14:35
+1 for wanting this supported! :)

**Comment by monsivar** [comment] 2020-02-04 13:04
> buntu EDIT: Set up a fresh new Ubuntu VM and was able to build it. I re-paired the switch but nothing showed up in Phoscon. Maybe I need to whitelist some more places as linked to above.

Any update on this?

**Comment by bardnilsen** [comment] 2020-02-08 10:51
@eckhart I am having trouble setting the switch in network pairing mode. How did you do it? (Namron 4512703)
I tried holding down on and off buttons in group1 followed by pressing off button in group1 when the led turned on. It blinks 13 times then stops. Any ideas?

**Comment by lrzorg** [comment] 2020-02-09 15:08
+1 for supporting Namron switches.
New to HA and bought some of the 2-channel ones (4512702) thinking any ZigBee 3.0 switch would work :-/
The hardware seems visually equal to the iCasa switches, apart from the button symbols...

About pairing:
Not sure if this helps, but the manual states that if the device is in "network mode" (already paired), it needs to be factory reset before pairing.
The device is in "network mode" if the led blinks when a button is pressed.
To do a factory reset, as per the manual press and hold the first "1" button until the light goes on, then press 5 times on the "1" button. **The 5 presses cannot be too fast in my experience. This took me a couple of tries to get right. About one second between each press seems right**
The device responds by blinking three times if successful.
If pressing a button does not cause the led to blink, it is ready for pairing again.
Pairing mode should be just holding down the first "1" until the light goes on, then press the first "0".

This worked for the 2 channel switch to behave as intended (still needs deconz support), and I checked the manual for the 4-channel and it is the same setup.

**Comment by monsivar** [comment] 2020-02-19 21:12
Any updates on this one?

**Comment by crazyclona** [comment] 2020-03-09 20:49
> Any updates on this one?

I hope there is soon ;) Would be awsome.. bought a few of them.......

**Comment by phithor** [comment] 2020-03-09 21:05
OK guys, I have not figured out if my branch works, I think I need to try again. Or can any of you help test my branch above? Build it, install it, test of you can add the button.

**Comment by bardnilsen** [comment] 2020-03-10 20:52
Hi phithor,

Great work :)

I have tested it. I can now add the 4-channel switch in phoscon app, but it does not show up in phoscon web gui. I see it in the rest-api and shows up in my HomeAssistant, but with no entities.

**Comment by phithor** [comment] 2020-03-13 15:05
Ah, thanks for that, I did not understand what worked and what not. At least we have gotten somewhere when it shows up in the rest-api. It's corona-time, so I think I will have time to do some more on this today/this weekend.

**Comment by phithor** [comment] 2020-03-14 15:47
Hah, in conclusion the commit I made almost two months ago works perfectly fine. 
I did it the same as was done here: https://github.com/dresden-elektronik/deconz-rest-plugin/commit/d5554bf5e47f96a609fb40df7eb96c047907a5aa

The key to fixing this is pressing open network and reding the basic cluster of each of the groups while the network is open. Then the groups will be made where you can add lights to. 
See info in this thread:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1509#issuecomment-555191920

I will push the commit to the main repo asap.

**Comment by monsivar** [comment] 2020-03-24 12:08
@phithor  cloned your git https://github.com/phithor/docker-deconz

Then I get this problem when trying to test, after running the command: qmake && make -j2


In file included from bindings.cpp:11:
de_web_plugin.h:16:10: fatal error: deconz.h: Ingen slik fil eller filkatalog
 #include <deconz.h>
          ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:527: release/bindings.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from authorisation.cpp:13:
de_web_plugin_private.h:23:10: fatal error: sqlite3.h: Ingen slik fil eller filkatalog
 #include <sqlite3.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:509: release/authorisation.o] Error 1
make[1]: Leaving directory '/home/pi/deconz-rest-plugin'
make: *** [Makefile:40: release] Error 2

**Comment by phithor** [comment] 2020-03-24 18:06
Hm, I think I got that as well the first time, but I believe that is missing files in your qt setup? Have you install deconz-dev?

**Comment by monsivar** [comment] 2020-03-24 20:52
> Hm, I think I got that as well the first time, but I believe that is missing files in your qt setup? Have you install deconz-dev?

I have. Restarted my pi, and its working :-)

**Comment by monsivar** [comment] 2020-03-25 09:57
> Hm, I think I got that as well the first time, but I believe that is missing files in your qt setup? Have you installed deconz-dev?

Hi. but i still have an problem . The switch is not listed upp in the old web interface, or in the api.

![image](https://user-images.githubusercontent.com/32893134/77524275-5857a280-6e87-11ea-9aeb-704ab36ec2b9.png)

**Comment by phithor** [comment] 2020-03-25 14:31
Did you follow the instructions I linked to above? In the old interface, open the network and then read cluster in each of the channels. That should create the groups.

**Comment by monsivar** [comment] 2020-03-25 14:54
I did, but no new switch. Was also thinking about removing the switch first, then including it, but did not find any way of doing that. Is that needed?

**Comment by phithor** [comment] 2020-03-25 18:31
You will not see a new switch. Only a new group in the old web interface. See the info i linked to above, there you see the end result as well.

**Comment by monsivar** [comment] 2020-03-25 21:58
> You will not see a new switch. Only new groups in the old web interface. See the info i linked to above, there you see the end result as well.

No new group either. I have done all that is listed in the linked info, but no results

**Comment by phithor** [comment] 2020-03-26 09:32
Hi, I tested it again with a fresh version without the groups and it successfully created the groups again. Took a few minutes so let it work after you have read the basic cluster of each channel. So I believe it should work. 

I have bound one of the on/off clusters to a light on/off in deCONZ GUI , does that make it not create a group for that channel? I only got three this time, and tested it twice. 

![image](https://user-images.githubusercontent.com/6831666/77631424-d762de80-6f4c-11ea-871d-6e4ec8a59477.png)

**Comment by monsivar** [comment] 2020-03-26 13:13
Tested again from the beginning.

1: git clone https://github.com/phithor/deconz-rest-plugin
2: cd deconz-rest-plugin
3: qmake && make -j2
4: sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
5: confirm updatet libde_rest_plugin.so
5: started DeCONZ
6: Open network (10min)
7: Cluster info read an push switch on all 4 Basic (i see that DeCONZ is getting data
8: waiting for several minuts, an still no new groups in the old web interface.

![image](https://user-images.githubusercontent.com/32893134/77650431-c83f5900-6f6b-11ea-902c-464096739627.png)

![image](https://user-images.githubusercontent.com/32893134/77650580-00df3280-6f6c-11ea-97ce-e9502dea2cce.png)


![image](https://user-images.githubusercontent.com/32893134/77650492-dd1bec80-6f6b-11ea-9435-955a43cd72f3.png)

**Comment by corvy** [comment] 2020-03-26 14:24
Might be related to the problems... I have the Namron verions, two of them. Due to some noise from Wi-Fi I have tried to move my Zigbee network off channel 11 onto channel 20 or 25 (tried these two, not 15). On the two I tried the switches both stopped working. Tried a ferw times but no success. They only seem to work on channel 11.  

Also, remember to use a new battery, that was my problem earlier on.

**Comment by phithor** [comment] 2020-03-26 14:38
Ah, you have to pull the namronswitch branch from my repo, not the master branch ! ;)

**Comment by monsivar** [comment] 2020-03-26 14:57
> To check if you are on the right version you will see Software version 2.05.75 on the REST-API as I have merged in all recent changes.

Ok, i now did:  git clone https://github.com/dresden-elektronik/deconz-rest-plugin.git
That is the right one?

This is the old web gui result now
![image](https://user-images.githubusercontent.com/32893134/77660749-017ec580-6f7a-11ea-8b59-fb2005a800f7.png)




> Also, remember to use a new battery, that was my problem earlier on.

The switch is responding in web gui, so i dont think that is the problem

**Comment by phithor** [comment] 2020-03-26 15:03
and then "git checkout namronswitch", then you will have the correct content in the files

**Comment by monsivar** [comment] 2020-03-26 15:32
Aha. thanks for all the help. Did not get that point, first time workin on this

1: git clone https://github.com/phithor/deconz-rest-plugin
2: cd deconz-rest-plugin
3: git status
4: git checkout -b namronswitch
3: qmake && make -j2
4: sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins

**Comment by crazyclona** [comment] 2020-05-10 19:57
Anyone know if this patch will be included in thee official branch?

**Comment by pselnes** [comment] 2020-05-26 15:13
This should be included in the last version v76/77.

I managed to create the groups by reading the cluster info as described above.
However, the switch seems to go sleep after a short while? The first keypress is ignored (no light on the switch), but on a consecutive press, the switch lights up and the lights respond.

Is this the case for everyone?

**Comment by crazyclona** [comment] 2020-05-31 22:47
Seems it works better now. though, I for some reason do not get anything on the api..

**Comment by flemmingss** [comment] 2020-07-05 11:01
Deconz 2.05.78 /22.05.2020
Firmware 26330500

Phoscon gw showing "Update to 26350500", but it looks like it is not updating, even if it looks like it is in the interface.

Should it work for me on this version? I tried to add the Namron 4-channel switch yesterday by the Phoscon GUI, but I did not find any device.

**Comment by phithor** [comment] 2020-07-05 11:58
You will not be able to add it through the Phoscon GUI, you need to go to the old interface and press open network, then open deconz gui and read cluster for all 4 groups of the namron switch. Then you will see the groups. Read above for more info.

**Comment by habakke** [comment] 2020-07-09 14:09
I am having the issues getting this setup working, only seeing the 8 ch switch (Namron) battery level status in Home Assistant and not having any Groups created in the old-webapp to which I can assign devices. The setup is running the latest deConz 2.05.78 release on a Conbee II with 26580700 firmware.

![image](https://user-images.githubusercontent.com/642472/87046698-c8512500-c1f9-11ea-80af-91a1668839af.png)

In the old-webapp, no groups are created for the switch when following the procedure below:
1. Reset device
2. In the Phoscon web-app, choose to search for new switch (Philips or Other)
3. Follow devices procedure for "Zigbee Network Pairing through Coordinator or Hub"
4. Read all of the 4 basic cluster groups in deConz UI.

![image](https://user-images.githubusercontent.com/642472/87050398-7fe83600-c1fe-11ea-886c-6fb3ea8b7887.png)

The switch does show up in the deConz UI:

![image](https://user-images.githubusercontent.com/642472/87049737-a35eb100-c1fd-11ea-9840-10f032f5fdd3.png)

Any idea how to get the groups created so I can assign devices to be controlled by the switch? And to have additional entities show up (besides the battery level) in Home Assistant through the integration? I have tried to re-run the procedure many times, and reading the basic cluster groups multiple time, but still the same result.

**Comment by phithor** [comment] 2020-07-09 18:41
You need to press "Open Network" in the old web-app. Then re-read the cluster info. There is nothing else to it. I am not sure what other tricks that can be used, but remember to set the open network to enough time.

**Comment by habakke** [comment] 2020-07-10 12:29
> You need to press "Open Network" in the old web-app. Then re-read the cluster info. There is nothing else to it. I am not sure what other tricks that can be used, but remember to set the open network to enough time.

I did a test again. Before starting I did a reset of the gateway and rest of the Namron switch.

1. Changed the duration the network is kept open in the old web-app:

![image](https://user-images.githubusercontent.com/642472/87153853-699eb080-c2b8-11ea-8ff5-279f49fc5509.png)

2. Opened the network in the old web-app

3. While the network was open, I executed the "Zigbee Network Pairing through Coordinator or Hub" procedure to pair the switch with the gateway. (Essentially holding down the first pair of on/off buttons until the light come on and the immediately pressing the first off button) It then blinks to indicate pairing is successful and I can se the device showing up in the deConz UI.

4. While the network is still open, manually read all the cluster groups using the deConz UI. (Clicking on the group, selecting the "Cluster info" tab, pressing the read button and then a button on the switch to wake it up.

Still the same result as before, no groups are created and visible in the old web-app. Am I doing something incorrect?

**Comment by Mimiix** [comment] 2020-07-10 13:21
@habakke It could be possible that the device is not in Phoscon  yet. They need to add it manually. However, the RestAPI (deCONZ) does show them thus they are implemented correctly. Phoscon is closed source, so we can't do that.

If you need it implemented, please open a git issue https://github.com/dresden-elektronik/phoscon-app-beta

I'll be closing this issue as it seems to be resolved and implemented.

**Comment by SwoopX** [comment] 2020-07-10 14:13
It is implemented, but not properly. There's some afterwork to be done, mainly around the groups and binding. I can see if I can fix it once I have the new switches to oversee all the implications.

**Closed** 2020-07-10 14:53 UTC
Labels: Device Request

**Comment by habakke** [comment] 2020-07-10 19:46
@Mimiix && @SwoopX I am sort of confused whether this is added correctly or not? It is definitely not working here.

For good measure I created a git issue as suggested by @Mimiix: https://github.com/dresden-elektronik/phoscon-app-beta/issues/152

**Comment by SwoopX** [comment] 2020-07-10 20:14
It is supported and also whitelisted in the code. However, the support was provided by someone who obviously wasn't that familiar with the code.

As such, the underlying request is done. Visibility in Phoscon is a different thing, as Mimiix pointed out, therefore the requirement for a request.

**Comment by phithor** [comment] 2020-07-11 07:43
@habakke i checked your issue in the Phoscon App and I noticed your switch shows manufacturer id "NAMRON AS" in all caps. I have not seen that before. That might why it is not working for you, as the whitelist is only for "Namron AS" if I remember correctly. 
Can you confirm the manufacturer ID shows all caps?

**Comment by habakke** [comment] 2020-07-12 19:56
@phithor I can confirm the manufacturer name show all caps "NAMRON AS" as seen in the screenshot of the basic cluster group below:

![image](https://user-images.githubusercontent.com/642472/87255361-580d0280-c48a-11ea-976b-ccce15e227b4.png)

The OTAU cluster group shows the manufacturer ID to be 0x1224 as seen below:

![image](https://user-images.githubusercontent.com/642472/87255373-84288380-c48a-11ea-9c9d-5dffcc86caa2.png)

**Comment by habakke** [comment] 2020-07-12 23:39
@phithor I installed the dev env. and did a quick change to the code to assign the sunricher buttonmap if the manufacturer matches upper case "NAMRON AS", compiled and installed. Now the groups are created as expected:

![image](https://user-images.githubusercontent.com/642472/87259188-bc8b8a00-c4a9-11ea-8e48-e33504bad449.png)

**Comment by SwoopX** [comment] 2020-07-13 08:46
Taken care of this in my last PR real quick. While pairing, we now set the Manufacturer to "Namron AS" for all devices beginning with 451270. Should be included in the next release.

**Comment by clindland** [comment] 2020-07-21 08:25
> Taken care of this in my last PR real quick. While pairing, we now set the Manufacturer to "Namron AS" for all devices beginning with 451270. Should be included in the next release.

Mine still won´t work. After this release I checked the model identifier number, and it says 4512721, and still "NAMRON AS" with all caps. Is it possible to include the switches with these id numbers?

<img width="416" alt="Skjermbilde 2020-07-21 kl  10 25 12" src="https://user-images.githubusercontent.com/45068563/88031161-82228c80-cb3c-11ea-9e00-dccacc8b82a3.png">

**Comment by SwoopX** [comment] 2020-07-21 15:47
Renaming will be done based on the modelId. Of course your device brings another one into play, which doesn't fit the pattern... How many different IDs can one device have...?

**Comment by clindland** [comment] 2020-07-28 20:02
Yeah, they didn't make it easy on us.. Is it possible to add my ID's (or my pattern if there's anyone out there with an ID similar to mine) to the renaming pool? It would be really great to get this to the deconz hassio addon 👍

**Comment by SwoopX** [comment] 2020-07-28 20:55
Don't worry, will be supported with the next release.

**Comment by flemmingss** [comment] 2020-08-03 19:39
Do you know when that is? because I am on the least one now and am not able to discover it.

![image](https://user-images.githubusercontent.com/25674067/89220324-aa48cb80-d5d1-11ea-85c8-52723fbace14.png)

**Comment by SwoopX** [comment] 2020-08-03 19:48
August 15th, if you run bare Raspian, without HA and have subscribed to the beta channel.

**Comment by flemmingss** [comment] 2020-08-03 21:59
I am using Raspian, without HA, but how do i subscribe to the beta channel?

**Comment by SwoopX** [comment] 2020-08-04 19:48
https://phoscon.de/en/conbee2/install#raspbian

**Comment by flemmingss** [comment] 2020-08-04 21:01
Thanks, can i run stable and beta side-by-side?

**Comment by SwoopX** [comment] 2020-08-05 08:55
Nope. But since you already run version .79 I'd assume you're using the beta channel already.

**Comment by flemmingss** [comment] 2020-08-05 16:37
I will wait until August 15th and see then :)

**Comment by flemmingss** [comment] 2020-08-15 14:44
```
pi@phoscon:~ $ sudo dpkg -i deconz-latest-beta.deb

dpkg: warning: downgrading deconz from 2.05.78-raspbian-stretch-stable to 2.05.72-raspbian-stretch-beta
(Reading database ... 74742 files and directories currently installed.)
Preparing to unpack deconz-latest-beta.deb ...
Unpacking deconz (2.05.72-raspbian-stretch-beta) over (2.05.78-raspbian-stretch-stable) ...
Setting up deconz (2.05.72-raspbian-stretch-beta) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
pi@phoscon:~ $ 
```

Still not able to add it. deconz-latest-beta.deb last modify is 15-Aug-2020 14:04.

![image](https://user-images.githubusercontent.com/25674067/90314715-2918ff00-df16-11ea-9886-2d77336505a8.png)

```
pi@phoscon:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://phoscon.de/apt/deconz stretch InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease      
Reading package lists... Done              
pi@phoscon:~ $ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  deconz
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5,843 kB of archives.
After this operation, 12.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Reading changelogs... Done
(Reading database ... 74105 files and directories currently installed.)
Preparing to unpack .../deconz_2.05.78-raspbian-stretch-stable_armhf.deb ...
Unpacking deconz (2.05.78-raspbian-stretch-stable) over (2.05.72-raspbian-stretch-beta) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Setting up deconz (2.05.78-raspbian-stretch-stable) ...
pi@phoscon:~ $ 

```


![image](https://user-images.githubusercontent.com/25674067/90314760-87de7880-df16-11ea-98ea-b07f71a4d262.png)

**Comment by SwoopX** [comment] 2020-08-15 15:02
You first downgraded 6 versions and then upgraded 6 versions. And are still 2 versions behind...

**Comment by flemmingss** [comment] 2020-08-15 15:05
can you give me te correct commands to get the last one :P

**Comment by flemmingss** [comment] 2020-08-15 16:17
Okay, I am on the last one, still not able to add it.
![image](https://user-images.githubusercontent.com/25674067/90316592-7354ad00-df23-11ea-9cc1-fb4c875162d0.png)

**Comment by t112013** [comment] 2020-09-01 15:03
Hello, i have a question i just got two of these but one with 2 channels and one with only 1 channel. (4 and 2 buttons).
But i cannot add them in phoscon app. could anyone please tell me what to do ? or is it only the 4 channels one supported ? 
iam running hassio with deCONZ ver 2.05.79.
thanks a lot. iam completly noob :)

**Comment by Mimiix** [comment] 2020-09-01 15:14
@t112013 Support was added in .80. So you have to wait until HA updates it. 

Same goes for @flemmingss : You are not on latest update afaik.  Please open a seperate issue.

Locking this issue for further conversation. If there's issue, please open seperate userquestions/bugreports.
