### ISSUE TITLE
Heiman HS2WD-E siren sensors become 'Note reachable' after few hours

### ISSUE THREAD

**Issue by monpelaud** [dresden-elektronik/deconz-rest-plugin#6020] opened 2022-05-05 13:43 UTC
## Describe the bug
Hi,
After migrating deCONZ plugin from 2.14.1 to 2.15.3, my Heiman HS2WD-E siren works fine but its binary sensors become 'Note reachable' after a few hours.
If I restart the host, the siren sensors are reachable again but become 'Note reachable' again after a few hours.
Best regards

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: 26720700
 - deCONZ version: 2.15.03
 - Device: RaspBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so: Which?: no

## Additional context

![Capture-1](https://user-images.githubusercontent.com/16806004/166936234-59ef313b-2a08-4f9f-8d91-470be9625443.JPG)
![Capture-2](https://user-images.githubusercontent.com/16806004/166936281-9dede36b-5571-4cd9-b69f-77c8f4147803.JPG)

**Comment by Mimiix** [comment] 2022-05-05 14:00
Hi,

As this is not a bug report as per #5113 , i am closing this issue.

Feel free to post on the forums: https://forum.phoscon.de

Kind regards,

**Closed by Mimiix** 2022-05-05 14:00 UTC
Labels: Bug report
