### ISSUE TITLE
Aqara TVOC Air Quality Monitor (VOCKQJK11LM)

### ISSUE THREAD

**Issue by redphx** [dresden-elektronik/deconz-rest-plugin#4704] opened 2021-04-05 03:41 UTC
## Device

- Product name: [Aqara TVOC Air Quality Monitor](https://www.aqara.com/cn/productDetail/TVOC-air-quality-monitor)
- Manufacturer: LUMI
- Model identifier: lumi.airmonitor.acn01
- Device type :
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/96280/120405281-6863ef80-c372-11eb-97cc-36e995df7724.png)

![image](https://user-images.githubusercontent.com/96280/120405183-3488ca00-c372-11eb-92a2-615a2ab319a8.png)

### Node Info

![image](https://user-images.githubusercontent.com/96280/113534399-dc944800-95fa-11eb-9dcd-27dfdd7c3d79.png)

### Basic

![image](https://user-images.githubusercontent.com/96280/119922943-033b8300-bf9b-11eb-8551-fc07ef1afab1.png)

### Identify

![image](https://user-images.githubusercontent.com/96280/113534308-8c1cea80-95fa-11eb-944e-c141bfcc929a.png)

### Temperature measurement

![image](https://user-images.githubusercontent.com/96280/119923445-e81d4300-bf9b-11eb-969d-6a9d0afba6dc.png)

### Relative humidity measurement

![image](https://user-images.githubusercontent.com/96280/119923485-f79c8c00-bf9b-11eb-90b4-a530d13e3b9b.png)

### Analog Input (Basic)

![image](https://user-images.githubusercontent.com/96280/119923532-0b47f280-bf9c-11eb-8d25-6026dc37d002.png)

### Power Configuration

![image](https://user-images.githubusercontent.com/96280/119923752-785b8800-bf9c-11eb-8ae7-d3205e95d61b.png)

**Comment by apper13** [comment] 2021-05-27 18:59
I would highly appreciate re-opening this ticket. This device is really interesting and I would love to see it in deconz! It is newly available directly in Europe (https://www.amazon.de/dp/B094N7X7NH)

**Comment by redphx** [comment] 2021-05-28 03:09
Updated screenshots with values (had to use the Reset Node feature first + press the Pair button)

**Comment by redphx** [comment] 2021-05-28 03:14
Not sure where this `ppb (tvoc)` came from:   
  
![image](https://user-images.githubusercontent.com/96280/119924237-69290a00-bf9d-11eb-9f7e-3e60a212c501.png)

**Comment by 00lex** [comment] 2021-06-01 09:07
im interested too! :)

**Comment by lisanet** [comment] 2021-06-01 19:38
I'd love to see this too.

**Comment by SwoopX** [comment] 2021-06-01 19:51
Can anyone please add the required screenshot of the node's clusters?

**Comment by redphx** [comment] 2021-06-02 00:15
> Can anyone please add the required screenshot of the node's clusters?

Sorry I missed that. Added to the first post.

**Comment by SwoopX** [comment] 2021-06-05 20:06
Thanks. Would anybody also be able to compile a test version of the plugin?

**Comment by rasssta** [comment] 2021-06-15 14:55
> Thanks. Would anybody also be able to compile a test version of the plugin?

Could you please elaborate a bit? :-)

**Comment by rgers** [comment] 2021-06-15 16:50
> Thanks. Would anybody also be able to compile a test version of the plugin?

I just got the sensor and I'm fairly confident I'll be able to compile a test version. Which branch?

**Comment by SwoopX** [comment] 2021-06-15 18:25
It's branch `tvoc` in my repo (https://github.com/SwoopX/deconz-rest-plugin). Would be great to collect like 20 mins of debug log, which includes the pairing of the device. You can so do with `/usr/bin/deCONZ --dbg-info=2 --dbg-error=2 > tvoc_debug`

**Comment by rgers** [comment] 2021-06-15 21:53
[tvoc_debug.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6658932/tvoc_debug.log)

Will this help? It looks to me that after pairing there's no communication... 
Let me know if you need anything else.

**Comment by SwoopX** [comment] 2021-06-16 12:32
Thanks!

Hm, there's indeed nothing. Have you tried forcing the values on the device to change (e.g. blow at it) during that time? If not, it would be good if you could take another short debug log where you try to tickle all sensors.

On the other hand, it wouldn't be too surprising if the device is "honest" zigbee and really follow the specs. I haven't whitelisted it for attribute reporting yet, since most Xiaomi devices ignore it anyway and to their own thing. Will amend the code later and let you know for a new try

**Comment by redphx** [comment] 2021-06-16 12:54
@rgers maybe you'll need to use the `Reset Node` feature in the `Edit` menu, then press (not hold) the Pair button on the TVOC. 
I haven't tried the new build yet, but with the stable build it only transfers data to deCONZ after I do those steps.

**Comment by rgers** [comment] 2021-06-17 14:53
@SwoopX here's a new log with your latest updates. This time I can see correct values for temperature, humidity and battery level in the log. Nothing shows up in Phoscon. I don't see air quality in the log.
[tvoc_debug321.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6671150/tvoc_debug321.log)

**Comment by SwoopX** [comment] 2021-06-17 18:34
Looks like we're almost there. Remarkable that it seems to adhere to the specs indeed.

For the air quality, can you try to do the manual binding with the `analog input` cluster as described here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-bind-server-clusters and try to configure attribute reporting for 0x0055 with values `60,600,1`? When done, you should enter sensor search once again (without repair) to hopefully have the missing senor being created.

**Comment by rgers** [comment] 2021-06-17 19:17
Will let you know when I try manual binding, probably tomorrow.
Currently temp and humidity works correctly with OpenHAB, although I see it as 2 different devices (one with temp and other with hum) instead 1 device with 2 channels as usual... but maybe that's specific to this device?

**Comment by SwoopX** [comment] 2021-06-20 18:49
In the end, there's 3 sensors exposed via REST API. From what I've seen so far in the logs, all's as expected (apart from the missing air quality sensor). I got no clue what OH makes out of it but it's also nothing we can help you here with.

**Comment by rgers** [comment] 2021-06-28 17:16
I've done the manual binding and in Cluster Info in 0x0055 I can see the correct value changing but no sensor is being created. Maybe I've done the binding incorrectly...

**Comment by SwoopX** [comment] 2021-06-28 17:36
Do you recall if the values have updated even without the bindig? It's always kind of a challenge with Xiaomi to find out if it is required and accepted or not.

The sensor can show up if you enter sensor search, wake up the device by pushing the physical button once and then reading the voc attribute.

**Comment by jan666** [comment] 2021-07-08 07:48
Any news? Anything I can do to help? (I have this device, not yet paired - I'm on the latest stable deCONZ version)

**Comment by kenge1967** [comment] 2021-07-17 15:21
How is this going on, I just bought it so is there anything I can do to help out?

**Comment by SwoopX** [comment] 2021-07-19 00:12
I did some updates on the code for the air quality sensor. Can somebody please compile and test it?

Instructions: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
Repository: https://github.com/swoopx/deconz-rest-plugin.git
Branch: tvoc

**Comment by balu-** [comment] 2021-07-27 15:56
i would love to see the sensor working

**Comment by Mimiix** [comment] 2021-07-27 16:04
@balu- Well someone needs to test the changes @SwoopX made ;)

**Comment by balu-** [comment] 2021-07-27 16:11
> @balu- Well someone needs to test the changes @SwoopX made ;)

I orderd the Aqara device, so if i find a way to temporary enable the changes from @SwoopX without getting my Setup in an unrecoverable state i might help out on that

**Comment by 00lex** [comment] 2021-07-27 19:19
OT: would it be possible to sent text to the screen?

**Comment by FitziCJ** [comment] 2021-07-28 21:14
Maybe because i am using Phoscon in an docker environment and have just ConBee II v2.12.01 running i have some issues someone other does not have (no listing in Phoscon webinterface, but Node-Red is working fine).
BUT: I compiled the tvoc fork and could connect the Aqara TVOC Air Quality Monitor (VOCKQJK11LM) with the phoscon app
I could read temperature und humidity, but not AirQuality:

{
    "13": {
        "config": {
            "battery": 100,
            "offset": 0,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "3697e824bc9beeb8fb6dbea98e7e683f",
        "lastseen": "2021-07-28T21:04Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.airmonitor.acn01",
        "name": "Temperature 13",
        "state": {
            "lastupdated": "2021-07-28T21:04:50.632",
            "temperature": 2421
        },
        "swversion": "20210204",
        "type": "ZHATemperature",
        "uniqueid": "54:ef:44:10:00:10:5c:4a-01-0402"
    },
    "14": {
        "config": {
            "battery": 100,
            "offset": 0,
            "on": true,
            "reachable": true,
            "temperature": 0
        },
        "ep": 1,
        "etag": "b54258af6fe54309f2bd1ac4e4dfbc77",
        "lastseen": "2021-07-28T21:04Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.airmonitor.acn01",
        "name": "Humidity 14",
        "state": {
            "humidity": 6238,
            "lastupdated": "2021-07-28T21:03:20.819"
        },
        "swversion": "20210204",
        "type": "ZHAHumidity",
        "uniqueid": "54:ef:44:10:00:10:5c:4a-01-0405"
    },
    "15": {
        "config": {
            "battery": 100,
            "on": true,
            "reachable": true,
            "temperature": 0
        },
        "ep": 1,
        "etag": "89306a469b30c3c4630cd2ec4eb973a3",
        "lastseen": "2021-07-28T21:04Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.airmonitor.acn01",
        "name": "AirQuality 15",
        "state": {
            "airquality": null,
            "airqualityppb": null,
            "lastupdated": "none"
        },
        "swversion": "20210204",
        "type": "ZHAAirQuality",
        "uniqueid": "54:ef:44:10:00:10:5c:4a-01-000c"
    }
}

Does someone else have the same expirience like me regarding the AirQuality sensor?

**Comment by SwoopX** [comment] 2021-07-28 23:15
Hey, thanks for taking the effort to test it. So we're apparently one step further as the air quality sensor is now created. Now the question is why the values are not coming in...

You could wait over night to see if that changes or try setting up a manual binding as mentioned here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4704#issuecomment-863470991 . Meanwhile, I can check the code once again.

**Comment by SwoopX** [comment] 2021-07-29 00:28
@FitziCJ I made some changes on the air quality processing. Could you please download and compile again (no need to re-pair the device)?

**Comment by jtscott** [comment] 2021-07-29 02:53
I have updated to the tvoc branch but I can't get my device to even pair? Debug logs don't show even an attempt for it to join. Any pro tips? I have tapped, held for 8 seconds, pulled batteries, etc. but the thing won't connect?

**Comment by SwoopX** [comment] 2021-07-29 19:18
Do "permit join: 59" messages show up in the logs (hopefully not immediately followed by "permit join: 0")? How do you pair it? Does it show up in deconz GUI?

**Comment by jtscott** [comment] 2021-07-29 19:29
Here are some snippets I see regarding permit join logs; Via webui I did sensor > add new sensor. It appears that it flaps between 0 and 59 pretty quickly.
[tvoc_debug.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6903163/tvoc_debug.txt)


`	Line 4836: 01:58:11:182 send permit join, duration: 0

	Line 5119: 01:58:27:049 send permit join, duration: 59

	Line 5123: 01:58:27:055 send permit join, duration: 0

	Line 5780: 01:59:28:048 send permit join, duration: 59

	Line 5785: 01:59:28:054 send permit join, duration: 0

	Line 6781: 02:00:29:048 send permit join, duration: 59

	Line 6789: 02:00:29:062 send permit join, duration: 0

	Line 7250: 02:01:23:047 send permit join, duration: 0
`

**Comment by SwoopX** [comment] 2021-07-29 21:44
Could it be that you have 2 tabs opened for Phoscon? Just received note that they could interfere with each other.

**Comment by jtscott** [comment] 2021-08-01 17:22
I've completely knackered my install somehow, will have to let someone else keep testing.

**Comment by rasssta** [comment] 2021-08-02 11:52
I've compiled the tvoc branch and copied the plugin according to the manual. But I'm not able to add the device. Any hints?

FW: 26680700 /  2.12.03

**Comment by rasssta** [comment] 2021-08-02 12:32
Seem to have the same issue as scott.

```
14:19:31:085 send permit join, duration: 59
14:19:31:091 send permit join, duration: 0
14:19:54:085 send permit join, duration: 0
14:29:12:086 send permit join, duration: 59
14:29:12:093 send permit join, duration: 0
14:30:11:086 send permit join, duration: 59
14:30:11:089 send permit join, duration: 0
14:31:10:090 send permit join, duration: 59
14:31:10:101 send permit join, duration: 0

```

**Comment by Mimiix** [comment] 2021-08-02 14:58
As swoop mentioned: make sure you only have 1 tab open of Phoscon.

**Comment by SwoopX** [comment] 2021-08-02 15:35
Better also make sure you've opened Phoscon just once throughout all your devices (PC, mobile, tablet...).

**Comment by rasssta** [comment] 2021-08-05 07:57
Only 1 tab on 1 device. I've tried to reboot the rpi running deconz as well. Still getting the 59 -> 0 stuff :( 

```
09:51:46:856 Load config permitjoin: 0 from db.
09:51:46:856 Load config permitjoinfull: 0 from db.
09:51:46:955 Load config permitjoin: 0 from db.
09:51:46:955 Load config permitjoinfull: 0 from db.
09:54:43:210 send permit join, duration: 59
09:54:43:214 send permit join, duration: 0
09:55:42:211 send permit join, duration: 59
09:55:42:216 send permit join, duration: 0
09:56:41:211 send permit join, duration: 59
09:56:41:220 send permit join, duration: 0

```

**Comment by rasssta** [comment] 2021-08-08 09:03
Just noticed that HASS is using the websocket as well. Is this the cause of my issues?

```
11:01:08:307 New websocket 192.168.x.8:50415 (state: 3) 
11:01:15:349 New websocket 192.168.x.7:37262 (state: 3) 

```

**Comment by rasssta** [comment] 2021-08-08 13:59
I downgraded to deCONZ 2.11.05 and the "permit join" issue is gone == that parts works as intended. But the tvoc plug doesn't work in that version. Catch 22 here...

**Comment by f04ly** [comment] 2021-08-16 06:42
i'm new to conbee2 - is there a prediction when the tvoc devices will be in the firmware?

**Comment by rasssta** [comment] 2021-08-16 11:27
I did another try with 2.12.5-beta and managed to get it added right away. It shows battery level, temperature and humidity, but not air quality.

I get both reading failed and writing failed for attribute 0x0055.

Log from writing attempt ('grep 0x54' from the log):
```
13:23:02:757 [REQUEST] - 0x54EF4410001058DC (0x68E3) - Profile: 0x0104, Cluster: 0x000C, EP: 0x01, DstAddrMode: 02, Configure reporting (0x06), SeqNo.: 4, Mfc: 0x0000
13:23:53:395 Node data 0x54ef4410001058dc profileId: 0x0104, clusterId: 0x0402
13:23:53:396 0x54EF4410001058DC: update ZCL value 0x01/0x0402/0x0000 after 0 s
13:23:53:398 ZCL attribute report 0x54EF4410001058DC for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
13:23:53:399 [INDICATION] - 0x54EF4410001058DC (0x68E3) - Profile: 0x0104, Cluster: 0x0402, EP: 0x01, Unicast to: 0x0000, DstAddrMode: 02, Report attributes (0x0A), SeqNo.: 217, Mfc: 0x0000, Attr: 0x0000, Datatype: i16, Value: 2565 (0xA05)

```

**Comment by rasssta** [comment] 2021-08-16 11:56
Okay. So I re-pair'd it and was able to change the attributes. But 0x0055 still says 0.

Attaching log (grep 0x54) from pairing, attribute changing, etc.
[tvoc.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6992117/tvoc.txt)

**Comment by SwoopX** [comment] 2021-08-16 11:58
I wonder what makes you think that the few lines above have anything to do with any write attempt. I added some additional code to the PR which basically includes a sniffer for maximum transparency of the device communication so just a few random lines is not too helpful.

If the analog input cluster does not give anything back on either read or write, the device apparently uses something different to send TVOC data, which needs to be identified then.

**Comment by FitziCJ** [comment] 2021-08-16 15:51
I needed to reconnected my Aqara TVOC to deconz again and updated afterwards to my docker environment to v2.12.05, included the previous build TVOC-libde_rest_plugin.so and the result was, that the temperature, humdity AND the tvoc-values are shown in API:

{
    "config": {
        "battery": null,
        "on": true,
        "reachable": true,
        "temperature": 0
    },
    "ep": 1,
    "etag": "b751b2992cc3afa7aee7a8feeac88d1c",
    "lastseen": "2021-08-16T15:49Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.airmonitor.acn01",
    "name": "AirQuality 18",
    "state": {
        "airquality": "good",
        "airqualityppb": 209,
        "lastupdated": "2021-08-16T15:49:01.161"
    },
    "swversion": "20210204",
    "type": "ZHAAirQuality",
    "uniqueid": "54:ef:44:10:00:10:5c:4a-01-000c"
}

I don't why these values weren't visible before, maybe it is the update to v2.12.05

**Comment by rasssta** [comment] 2021-08-16 16:42
@FitziCJ Which commit are you referring to as "previous build"? :)

**Comment by FitziCJ** [comment] 2021-08-16 17:32
Indeed :) , i compiled the tvoc branch from SwoopX on my raspberry pi round about 19 days ago and saved the libde_rest_plugin.so before i updated today deconz to 2.12.05.

**Comment by f04ly** [comment] 2021-08-18 07:34
awaiting merge sounds great, thanks for your work!

**Comment by f04ly** [comment] 2021-08-23 12:29
is there a way to get the software before the merge? seems it takes a bit more than a few days :(

**Comment by leonardpitzu** [comment] 2021-08-24 15:28
`git clone --recursive https://github.com/dresden-elektronik/deconz-rest-plugin
cd deconz-rest-plugin/
git fetch origin pull/5213/head
git checkout FETCH_HEAD
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
sudo reboot`

**Comment by f04ly** [comment] 2021-08-30 08:45
compile and copy was fine. i can find the sensor now (search new sensor, green button with "found new sensor") but then there is no new sensor on deconz browser gui and i cant find anything what happend in messages/syslog

what is wrong?

**Comment by Mimiix** [comment] 2021-08-30 09:22
@f04ly That's normal. The Rest API shoudl show it though L)

**Comment by FitziCJ** [comment] 2021-08-30 09:22
Maybe some adaptions must be done to fix this. I still have this behavior in my docker environment too, but can see the reported values in the api. Do you see the three sensors in your api?

**Comment by f04ly** [comment] 2021-08-30 10:31
how can i check that?
in openhab i see 4 new sensors - but i am not absolutely sure, whether they are really new...
humidity, temperature, power, consumption (LUMI) 

is it possible that they are the 4 values from tvoc?

**Comment by FitziCJ** [comment] 2021-08-30 10:47
You should see temperature, humidity and Airquality. You could check your api on your phoscon gateway Unser help - > api. Choose Sensor and you should see at least three sensors.

**Comment by f04ly** [comment] 2021-08-30 10:59
ah ok yeah i see air quality - nice i didn't know that api feature. 
is there a reason why this sensor is not "forwarded" to openhab? oder deconz gui?
this is output of api for air quality

                    {
    "config": {
        "battery": 100,
        "on": true,
        "reachable": true,
        "temperature": 2613
    },
    "ep": 1,
    "etag": "70ddfc74e2db4a2008abc5375a880809",
    "lastannounced": "2021-08-30T08:49:03Z",
    "lastseen": "2021-08-30T10:54Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.airmonitor.acn01",
    "name": "AirQuality 23",
    "state": {
        "airquality": "good",
        "airqualityppb": 100,
        "lastupdated": "2021-08-30T10:39:18.900"
    },
    "swversion": "20210204",
    "type": "ZHAAirQuality",
    "uniqueid": "54:ef:44:10:00:10:61:9f-01-000c"
}

**Comment by f04ly** [comment] 2021-08-30 11:04
according to unique id i can see temperature and humidity in openhab als new things, but air quality is not shown so far

**Comment by Mimiix** [comment] 2021-08-30 11:16
@f04ly That's something that needs to be figured out on Openhab's site. @SwoopX seems good so far :)

**Comment by f04ly** [comment] 2021-08-30 11:21
ah ok, great, thx :)

**Comment by Notsosmarthome** [comment] 2021-09-25 10:16
How do you guys even get them to pair with Deconz..? I'm using Conbee 2 and have three TVOC meters, none of which will pair (pressed button until network logo comes up, then release, also tried holding the button in).

**Comment by FitziCJ** [comment] 2021-09-25 11:56
> How do you guys even get them to pair with Deconz..? I'm using Conbee 2 and have three TVOC meters, none of which will pair (pressed button until network logo comes up, then release, also tried holding the button in).

Which version du you use? I use the dev-version vom SwoopX. See post https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4704#issuecomment-882139767

**Comment by chief110** [comment] 2021-09-30 08:26
when can I expect a stable version with the support for the tvoc?

**Comment by Mimiix** [comment] 2021-09-30 11:10
@chief110 The next stable is not due for another month or so and could be a bit longer due to DDFs.

2.13.0 is exptected this week.

**Closed** 2021-11-10 14:57 UTC
Labels: Device Request, Awaiting Merge

**Comment by Darathor17** [comment] 2021-11-19 21:19
> Hi everyone, I've been following along and was able to get the branch installed, but my TVOC sensor doesn't seem to be pushing any sensor data through...
> 
> Am I missing something or have I run into an issue? Also, Phoscon shows that it connected the sensor, but nothing new shows up in the list of sensors. Is this currently able to display TVOC sensor data in phoscon->Hue plugin yet?
> 
> "config": { "battery": null, "on": true, "reachable": true, "temperature": 0 }, "ep": 1, "etag": "60f0e0e0ffa34665db7d97d7fd7fb9be", "lastannounced": "2021-10-20T15:45:03Z", "lastseen": "2021-10-20T15:44Z", "manufacturername": "LUMI", "modelid": "lumi.airmonitor.acn01", "name": "AirQuality 12", "state": { "airquality": null, "airqualityppb": null, "lastupdated": "none" }, "swversion": "2020", "type": "ZHAAirQuality", "uniqueid": "54:ef:44:10:00:10:66:52-01-000c" } }

I'm in the same boat as you are (running v2.13.02) and I got humidity/temperature but not the air quality.

**Comment by alextud** [comment] 2021-11-20 11:11
> > Hi everyone, I've been following along and was able to get the branch installed, but my TVOC sensor doesn't seem to be pushing any sensor data through...
> > Am I missing something or have I run into an issue? Also, Phoscon shows that it connected the sensor, but nothing new shows up in the list of sensors. Is this currently able to display TVOC sensor data in phoscon->Hue plugin yet?
> > "config": { "battery": null, "on": true, "reachable": true, "temperature": 0 }, "ep": 1, "etag": "60f0e0e0ffa34665db7d97d7fd7fb9be", "lastannounced": "2021-10-20T15:45:03Z", "lastseen": "2021-10-20T15:44Z", "manufacturername": "LUMI", "modelid": "lumi.airmonitor.acn01", "name": "AirQuality 12", "state": { "airquality": null, "airqualityppb": null, "lastupdated": "none" }, "swversion": "2020", "type": "ZHAAirQuality", "uniqueid": "54:ef:44:10:00:10:66:52-01-000c" } }
> 
> I'm in the same boat as you are (running v2.13.02) and I got humidity/temperature but not the air quality.

Same for me and I don't have an Aqara hub that is needed to update the TVOC sensor firmware :(

**Comment by Darathor17** [comment] 2021-11-20 11:56
> > Hi everyone, I've been following along and was able to get the branch installed, but my TVOC sensor doesn't seem to be pushing any sensor data through...
> > Am I missing something or have I run into an issue? Also, Phoscon shows that it connected the sensor, but nothing new shows up in the list of sensors. Is this currently able to display TVOC sensor data in phoscon->Hue plugin yet?
> > "config": { "battery": null, "on": true, "reachable": true, "temperature": 0 }, "ep": 1, "etag": "60f0e0e0ffa34665db7d97d7fd7fb9be", "lastannounced": "2021-10-20T15:45:03Z", "lastseen": "2021-10-20T15:44Z", "manufacturername": "LUMI", "modelid": "lumi.airmonitor.acn01", "name": "AirQuality 12", "state": { "airquality": null, "airqualityppb": null, "lastupdated": "none" }, "swversion": "2020", "type": "ZHAAirQuality", "uniqueid": "54:ef:44:10:00:10:66:52-01-000c" } }
> 
> I'm in the same boat as you are (running v2.13.02) and I got humidity/temperature but not the air quality.

Update: After some time the battery is now displaying 100% (normal then) and I get the `airquality` & `airqualityppb` reporting the correct value. Only the `airquality` is passed along to Home Assistant tho but it might be another issue.

**Comment by Darathor17** [comment] 2021-11-20 11:58
> > > Hi everyone, I've been following along and was able to get the branch installed, but my TVOC sensor doesn't seem to be pushing any sensor data through...
> > > Am I missing something or have I run into an issue? Also, Phoscon shows that it connected the sensor, but nothing new shows up in the list of sensors. Is this currently able to display TVOC sensor data in phoscon->Hue plugin yet?
> > > "config": { "battery": null, "on": true, "reachable": true, "temperature": 0 }, "ep": 1, "etag": "60f0e0e0ffa34665db7d97d7fd7fb9be", "lastannounced": "2021-10-20T15:45:03Z", "lastseen": "2021-10-20T15:44Z", "manufacturername": "LUMI", "modelid": "lumi.airmonitor.acn01", "name": "AirQuality 12", "state": { "airquality": null, "airqualityppb": null, "lastupdated": "none" }, "swversion": "2020", "type": "ZHAAirQuality", "uniqueid": "54:ef:44:10:00:10:66:52-01-000c" } }
> > 
> > 
> > I'm in the same boat as you are (running v2.13.02) and I got humidity/temperature but not the air quality.
> 
> Same for me and I don't have an Aqara hub that is needed to update the TVOC sensor firmware :(

Hi @alextud the firmware update is for your conbee stick and not the TVOC sensor itself. (I don’t own an aqara hub either). Hope it works out for you!

**Comment by alextud** [comment] 2021-11-20 19:14
Thanks @Darathor17 I've upgraded conbee firmware, and is working. (I've assumed that it's the latest but I was wrong)

**Comment by Mimiix** [comment] 2021-12-01 09:47
@MiguelAlbiac Can you please post in english?

**Comment by MiguelAlbiac** [comment] 2021-12-01 10:27
> 

Hello. I am interested in integrating the TVOC in my home automation system but some doubts.
1-I have deconz running in home-assistant on a raspberry pi4, how do I update the firmware of conbee II?
2-When updating the firmware the configuration of my conbee II devices will be erased, I have a lot and it would be a problem.
Thanks

**Comment by Mimiix** [comment] 2021-12-01 10:38
1. When deCONZ updates to stable
2. Nope.

**Comment by hAMMERlized** [comment] 2021-12-05 18:58
Hey guys,

I'm not sure but is the TVOC now fully compatible with the Conbee Stick / deCONZ? Is the air quality pushed passed through to homekit now? Thanks.

**Comment by jan666** [comment] 2021-12-21 06:23
I updated to 2.13.04 / 18.12.2021 and firmware 26720700 yesterday and paired my TVOC sensor. Temperature and Humidity works as expected, but "airqualityppb" is unreliable. I already tried re-pairing, removing the battery for a few seconds, waited a few hours... the last value now is 8 hours old:


```
  "state": {
    "airquality": "good",
    "airqualityppb": 75,
    "lastupdated": "2021-12-20T22:52:44.826"
  }
```

on the display the value is 51. I there anything I can do to fix this?

**Comment by sieren** [comment] 2021-12-28 22:35
Can confirm... with the current master version changing the reporting interval also doesn't do anything for me.

**Comment by Fredo70** [comment] 2022-01-17 11:53
Hi
I have the problem too. The air quality is not updated:
```
"state": {
    "airquality": null,
    "airqualityppb": null,
    "lastupdated": "none"
}
```
`lastseen` is updated.
Conbee II
Version 2.13.04 / 18.12.2021
Firmware 26660700

**Comment by sieren** [comment] 2022-01-17 20:27
When rebasing master against my commit https://github.com/sieren/deconz-rest-plugin/commit/655d476cd22d13682bdc5df2f59ac8143c36e87d automatic updates seem to work again after setting the reporting values manually in deconz-gui. However with just plain master, even those don't update.
@SwoopX do you mind taking a look at this and which parts are helpful here? I'd like to get this merged to master even if it means having to set the reporting interval manually for now.

**Comment by jan666** [comment] 2022-01-18 05:41
@sieren how to set reporting manual?

**Comment by sieren** [comment] 2022-01-18 08:27
@jan666 Go to the "ANALOG INPUT" Cluster of the device in Deconz Gui, then to Cluster Info tab, open up "Present Value", and write the following data into the reporting value fields. Then press "Write Config" and tap once on the button at the top of the TVOC device. On occasion it requires more than one attempt.
<img width="1286" alt="Screenshot 2022-01-18 at 09 25 47" src="https://user-images.githubusercontent.com/5174440/149899029-e5abfc87-ac16-4561-a25e-d5f6c4a71168.png">

**Comment by jan666** [comment] 2022-01-18 12:17
Thx. Success on first try - but changed nothing so far

**Comment by sieren** [comment] 2022-01-18 12:18
@jan666 yeah, thats what ive been saying. If youre using the most recent version it needs some of the changes i made in here: https://github.com/sieren/deconz-rest-plugin/commit/655d476cd22d13682bdc5df2f59ac8143c36e87d

**Comment by edouardprevotlydia** [comment] 2022-04-21 19:37
Hi, also interested to know if it's gonna be merged after all? thx for the hard work

**Comment by Darathor17** [comment] 2022-04-21 19:38
Hi, also interested to know if it's gonna be merged after all? thx for the hard work
