### ISSUE TITLE
Conbee detected as Raspbee

### ISSUE THREAD

**Issue by AgentAnguz** [dresden-elektronik/deconz-rest-plugin#1221] opened 2019-02-05 10:28 UTC
I bought the Conbee USB stick and when inserted into my Raspberry Pi 3B+ with PoE HAT attached to the GPIO interface, I see Phoscon showing the device being a Raspbee.
![image](https://user-images.githubusercontent.com/44953715/52267350-1b55e700-2939-11e9-9d2f-7a172c6e2b65.png)

I haven't tried to remove the PoE HAT though.

**Comment by manup** [comment] 2019-02-05 10:49
Firmware not connected is suggesting the connection between ConBee and deCONZ isn't established.

Which linux system is this? Note the linux user which runs deCONZ needs to have access to the USB device. Usually the user needs to be in the group `dialout`, so that deCONZ can access /dev/ttyUSB0.

    sudo gpasswd -a pi dialout

Restart might be required.

**Comment by 4ndersjensen** [comment] 2019-02-05 11:00
This is a hass.io system. HassOS 1.12

**Comment by manup** [comment] 2019-02-05 11:04
Ah ok, which device did you specify in the Hass.io/deCONZ Add-on?

**Comment by 4ndersjensen** [comment] 2019-02-05 11:06
I put in /dev/ttyUSB0

core-ssh:~# hassio hw info
audio:
  "0":
    devices:
    - chan_id: "0"
      chan_type: digital audio playback
    - chan_id: "1"
      chan_type: digital audio playback
    name: bcm2835_alsa - bcm2835 ALSA
    type: ALSA
disk: []
gpio:
- gpiochip0
- gpiochip128
input: []
serial:
- /dev/ttyUSB0
- /dev/ttyAMA0

**Comment by 4ndersjensen** [comment] 2019-02-05 11:08
I have an Aeotec Z-wave USB stick which is unplugged right now, but it shows up as /dev/ttyAMC0 and it works fine.

**Comment by manup** [comment] 2019-02-05 11:09
/dev/ttyUSB0 looks correct.
Have you tried using the *Update to 0x262f0500* button in the Phoscon App?

**Comment by 4ndersjensen** [comment] 2019-02-05 11:14
Yes. If I click the Update button a cog is rotating for a while and returns with OK.
Then Firmware shows "Not connected" but I just saw it changed to a different value, something like 262B0500 or similar, but changed back to "Not connected".
The log is showing this:
12:00:11:900 Announced to internet
12:00:11:901 discovery server date: Tue, 05 Feb 2019 11:00:11 GMT
12:00:11:901 	 local time seems to be ok
12:02:13:618 dev /dev/ttyAMA0
12:04:23:624 dev /dev/ttyAMA0
12:06:33:627 dev /dev/ttyAMA0
12:08:43:625 dev /dev/ttyAMA0
12:10:11:867 Announced to internet
12:10:11:867 discovery server date: Tue, 05 Feb 2019 11:10:11 GMT
12:10:11:868 	 local time seems to be ok
12:10:26:239 GW firmware start update (device not connected)
12:10:46:085 GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
no device specified use RaspBee (/dev/ttyAMA0)
using firmware file: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF 
reset target 
error: bootloader not responding
device used by other application?
12:10:46:085 GW firmware update exit code 0
12:10:47:086 Wait reconnect after firmware update
12:10:48:087 Wait reconnect after firmware update
12:10:49:087 Wait reconnect after firmware update
12:10:50:085 Wait reconnect after firmware update
12:10:51:086 Wait reconnect after firmware update
12:10:52:087 Wait reconnect after firmware update
12:10:53:087 Wait reconnect after firmware update
12:10:54:087 Wait reconnect after firmware update
12:10:55:086 Wait reconnect after firmware update
12:10:56:087 Wait reconnect after firmware update
12:10:56:629 dev /dev/ttyAMA0
12:10:57:086 Wait reconnect after firmware update
12:10:58:087 Wait reconnect after firmware update
12:10:59:087 Wait reconnect after firmware update
12:11:00:085 Wait reconnect after firmware update
12:11:01:087 Wait reconnect after firmware update
12:11:02:086 Wait reconnect after firmware update
12:11:03:086 Wait reconnect after firmware update
12:11:04:085 Wait reconnect after firmware update

**Comment by 4ndersjensen** [comment] 2019-02-05 11:17
As I don't have any active setup, lights, switches or anything else, I can reset the gateway if needed.

**Comment by manup** [comment] 2019-02-05 11:18
This looks like /dev/ttyUSB0 is available for some reason.

>As I don't have any active setup, lights, switches or anything else, I can reset the gateway if needed.

No this does nothing especially since the connection isn't working currently.

Can you please try without the POE-hat I don't know if it matters but seems to be the only difference here?

Do you have any other USB-devices connected?

**Comment by 4ndersjensen** [comment] 2019-02-05 11:20
I have no other USB devices connected ATM no.
I'll dismount the PoE HAT later in the afternoon, getting back to you. Thanks!

**Comment by 4ndersjensen** [comment] 2019-02-05 11:21
The /dev/ttyAMA0 is the bluetooth device, isn't it? I can try and disable it.

**Comment by manup** [comment] 2019-02-05 11:23
>The /dev/ttyAMA0 is the bluetooth device, isn't it? I can try and disable it.

Shouldn't be a problem, the problem is the missing or not accessible /dev/ttyUSB0 interface

**Comment by 4ndersjensen** [comment] 2019-02-05 11:49
Perhaps. I wouldn't know. My hass.io skills are limited :)
I've not set up the /dev/ttyUSB0 in any other service though, but what's automagically polling / using it, I don't know.

**Comment by 4ndersjensen** [comment] 2019-02-05 11:59
After a reboot I get this in the logs:

**Comment by 4ndersjensen** [comment] 2019-02-05 12:01
After a reboot I get this in the logs:
```
12:57:13:227 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
12:57:13:227 COM: --dev: /dev/ttyUSB0
12:57:13:255 dev /dev/ttyAMA0
12:57:13:477 Device firmware version 0x260B0500
12:57:13:500 unlocked max nodes: 200
12:57:13:787 Device protocol version: 0x0104
12:57:13:811 new node - ext: 0x00212effff029d04, nwk: 0x0000
12:57:14:059 Current channel 11
12:57:14:123 CTRL ANT_CTRL 0x02
12:57:14:252 Device protocol version: 0x0104
12:57:14:443 Current channel 11
12:57:14:508 CTRL ANT_CTRL 0x02
12:57:16:725 dev /dev/ttyAMA0
**12:57:16:729 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF
12:57:16:729 GW firmware version: 0x260b0500
12:57:16:729 GW firmware version shall be updated to: 0x262f0500**
12:57:17:030 Announced to internet
12:57:17:030 discovery server date: Tue, 05 Feb 2019 11:57:16 GMT
12:57:17:030 	 local time seems to be ok
12:57:17:031 discovery found version 2.04.35 for update channel stable
12:57:18:724 don't close database yet, keep open for 900 seconds
12:57:21:694 channel is 11 but should be 15, start channel change
12:57:22:690 network configuration NOT verified!
12:57:23:691 channel change not successful.
12:57:25:991 scan finished
```
So, even though it shows updated in the web GUI, the logs show it's not updates. I'll remove the HAT and get back.

**Comment by manup** [comment] 2019-02-05 21:47
And this is only hassio running or more services?

**Comment by 4ndersjensen** [comment] 2019-02-05 21:48
It's only hassio running, yes. Did a clean install some days ago from an images downloaded specifically for RPI3B

**Comment by manup** [comment] 2019-02-05 21:55
Hmm hard to tell what's going on here.

I've only testet the update in hassio with RaspBee, will test with ConBee but it will take a while.

It is also possible manually within the hassio deCONZ container but you would need to setup ssh debugging access:

https://developers.home-assistant.io/docs/en/hassio_debugging.html

**Comment by 4ndersjensen** [comment] 2019-02-05 23:17
I got all Philips and IKEA lights added. I added IKEA motion sensors and smart outlets as well. Went smooth. But would really like to use the PoE HAT.

**Comment by pvizeli** [comment] 2019-02-06 19:25
The Firmware update for Conbee should work. If you attach the shell and execute the command manually it works in the same container.

The Phoscon app show also a Raspbee but I attach an Conbee and start also the doCONZ binary with `--dev=/dev/ttyUSB0`

**Comment by pvizeli** [comment] 2019-02-06 20:00
I think the problem is, that the flasher sees raspberry as default device:
![image](https://user-images.githubusercontent.com/15338540/52369986-205a8980-2a52-11e9-8ba7-cb275c4a96f7.png)

If I attach to the same container without change any privileged, and flash it with device option, it works:
![image](https://user-images.githubusercontent.com/15338540/52370037-3cf6c180-2a52-11e9-80dd-d717ac95d840.png)

**Comment by manup** [comment] 2019-02-06 20:09
Normally the firmware update invoked by deCONZ tries to select the proper device and calls GCFFlasher with the related parameters.

There seem to be cases here where this isn't properly handled I'll do some tests..

**Comment by 4ndersjensen** [comment] 2019-02-07 17:05
I'm sorry, but I don't know how to attach the shell. I'm quite new in this stuff. I, however, think the updater from Phoscon should work.
I returned the PoE HAT today and got a new revision. It turns out that the first revision didn't deliver clean enough power. In revision 2 a filter was applied making the input current cleaner:
https://www.raspberrypi.org/blog/poe-hat-revision/

**Comment by RyanRayNeff** [comment] 2019-02-16 00:42
I'm also having this issue. I'm running this alongside an aeotec z-wave stick on a Raspberry Pi 3B+ running Hass.io 87.1.  The conbee was appearing as the Phoscon-GW(Raspbee).  The update firmware wasn't working, so I connected the conbee to a windows 10 pc, and it was recognized correctly.  I updated the firmware, then reset the device, then transferred it back to the Pi, and the problem persisted.  I used the official deCONZ Addon and setup the deCONZ Zigbee gateway integration.

**Comment by manup** [comment] 2019-02-16 08:02
The issue should be fixed now with 2.05.59, the official Hass.io deCONZ add-on (version 1.3) is not yet updated and contains 2.05.58.

Note that since you have two USB devices attached, the proper device must be selected in the configuration.

**Comment by 4ndersjensen** [comment] 2019-02-25 11:22
I can confirm the issue has been resolved in the latest version. I'm now able to upgrade and the Conbee stick is detected as a stick.

**Comment by jerrychong25** [comment] 2019-04-15 01:19
I faced similar issue.

But on my side, RaspBee is detected as ConBee, as per screenshot below:
<img width="267" alt="Screenshot 2019-04-15 at 9 10 22 AM" src="https://user-images.githubusercontent.com/15714095/56102392-6d317380-5f5f-11e9-91c6-ccef3ec51f40.png">

This issue link: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1433

**Comment by Smus** [comment] 2019-05-09 19:07
Any luck solving this issue? I have the exact same issue

**Comment by manup** [comment] 2019-05-09 19:45
Which version are you using? Does the device work otherwise?

The display of the device graphic should normally have no impact on functionality.

**Comment by nilzolin** [comment] 2019-06-23 21:20
I have this issue as well on the latest version of Hass.io . Now my Conbee is shown as a Raspbee and I get "Firmware Not connected". Any idea how to fix this? 

![Anteckning 2019-06-23 231827](https://user-images.githubusercontent.com/31097973/59982094-45b8f000-960d-11e9-9af5-76fbea66f5fe.png)

**Comment by manup** [comment] 2019-06-24 12:52
Can you please provide the logs as shown in the Hassio Add-on.

**Comment by pvizeli** [comment] 2019-06-24 14:18
Works fine with conbee2 on my env

**Comment by nilzolin** [comment] 2019-06-25 05:15
Problem solved. Was a config error by me using the wrong device.

mån 24 juni 2019 kl. 16:18 skrev Pascal Vizeli <notifications@github.com>:

**Comment by ghorsie** [comment] 2019-07-07 18:17
I have the conbee and after changing the path to the device it now is shown as a raspbee.
The device works and I am sure that the path is correct. 

I changed the path from /dev/ttyUSB0 to /dev/serial/by-id/usb-FTDI_FTi230X_Basic_UART_DM01H1DB-if00-port0. This is a symbolic link to the correct usb device which in my case is pointing to the /dev/ttyUSB1

**Comment by brettyj** [comment] 2019-07-09 11:57
I've got the same issue as @ghorsie - updating firmware within the docker works fine though and everything seems to work fine

**Comment by pvizeli** [comment] 2019-09-05 15:48
Is fixed with latest version of Add-on

**Comment by noohi** [comment] 2019-11-28 16:58
Just noticed this issue, Conbee II is detected as RaspBee on latest Home Assistant (0.102.2 docker) + deconz (2.05.71 docker) with USB symlink.

Can I fix it manually for the vanilla Home Assistant like it was for the Hassio Add-on?

Thanks.

**Comment by galaris** [comment] 2019-12-14 04:25
Same with home assistant hassOS 2.12 (supervisor 192), deCONZ addon 232. Configured conbee II as /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_...

shows up as raspbee

**Comment by pvizeli** [comment] 2019-12-14 16:22
That is an issue inside deconz docker container. The Add-on work because we handle udev inside container

**Comment by sebastien-k** [comment] 2020-01-26 18:22
I have the same issue; my Conbee II suddenly became a RaspBee last night, I can't control anything anymore. Does anyone found the solution have his Conbee II detected as a Conbee II ?

I'm using on a :
- HassOS 3.8
- Home Assistant 0.104.3
- deCONZ 5.1
- Hass.io 195

(on a Raspberry Pi 3 B+)

![conbee](https://user-images.githubusercontent.com/57752274/73139598-cf331380-406f-11ea-9067-351852b97ebe.png)

![HW](https://user-images.githubusercontent.com/57752274/73139692-e58d9f00-4070-11ea-9a49-a9e8ac1fe11c.png)



Thanks for your help!

**Comment by Smanar** [comment] 2020-01-26 19:02
You have something strange on the serial configuration, I m not sure I have read

ConBee >  /dev/ttyUSB0.
Conbee II > /dev/ttyACM0.
RaspBee > /dev/ttyAMA0 or /dev/ttyS0.

**Comment by Scharunge** [comment] 2020-01-27 14:07
My Issue is the same as sebastien-k described. My Conbee II, wich was previously detected correctly somehow appears to be a RaspBee now.

My System is also the same: 
+ HassOS 3.8
+ Home Assistant 0.104.3
+ deCONZ 5.1
+ Hass.io 195
(on a Raspberry Pi 3 B+)

only the ConBee Firmware is different: 
+ Firmware: 26490700

I can control my devices but every few hours or sometimes minutes all devics are unavailable in Home Assistant for some time before they are suddenly available again.for seconds .

**Comment by Scharunge** [comment] 2020-01-27 21:18
> My Issue is the same as sebastien-k described. My Conbee II, wich was previously detected correctly somehow appears to be a RaspBee now.
> 
> My System is also the same:
> 
> * HassOS 3.8
> * Home Assistant 0.104.3
> * deCONZ 5.1
> * Hass.io 195
>   (on a Raspberry Pi 3 B+)
> 
> only the ConBee Firmware is different:
> 
> * Firmware: 26490700
> 
> I can control my devices but every few hours or sometimes minutes all devics are unavailable in Home Assistant for some time before they are suddenly available again.



I fixed the problem by not using /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_

but my connected Devices are stil unavailable for a few seconds from time to time.

**Comment by sebastien-k** [comment] 2020-01-27 21:41
> I fixed the problem by not using /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_
> 
> but my connected Devices are still unavailable for a few seconds from time to time.

Good news. 
What did you use then?

**Comment by Scharunge** [comment] 2020-01-27 21:47
I basically did it the other way around galaris did it only I used   "device": "/dev/ttyACM0"

**Comment by xavieraijon** [comment] 2020-01-30 15:29
> I used "device": "/dev/ttyACM0"

I have same problem, and fixed using this device. Thanks!

**Comment by liudger** [comment] 2020-03-07 19:54
> I used "device": "/dev/ttyACM0"

Worked for me too. Exactly the same error. This needs fixing!

**Comment by jeanclode76** [comment] 2020-03-24 12:04
Yes, I have the exact same problem and it really needs fixing !!!!! Using device /dev/ttyACM0 is NOT a reliable solution when you have multiple usb devices !

**Comment by Bellumatt** [comment] 2020-04-01 12:44
Hi there!
Same issue here!!!
I connected it to the RPI4B via /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DEXXXXXX-if00
A result:

![image](https://user-images.githubusercontent.com/32400144/78138096-ad1a9080-7426-11ea-9368-7407ed5e4696.png)

Conbee2 detected as raspbee.
Running HassOS 3.12 and got also this error message in the logs after I installed the Conbee2:
20-04-01 11:40:39 WARNING (MainThread) [supervisor.api.ingress] Ingress for QXncXpRLctIeVKeivD_ztUt8raaEFvt1hbvt9U5RalI not available

Any hints how to solve the issue??
Many thanks

**Comment by Berglund** [comment] 2020-04-07 23:12
I see the same issue using Home Assistant. Using /dev/ttyACM0 works, but as I have multiple USB devices the path changes. If I use `/dev/serial/by-id/usb...` the stick is detected as a RaspBee. Let me know if I can help debug somehow.

**Comment by yapishkahilt** [comment] 2020-05-07 03:42
The issue just came up for me a couple of days ago. Running Hassio on RPi3B+ also with Aeotec Z-wave stick. Conbee shows up as Raspbee, version listed is 2.05.75, firmware 260B0500. I initially lost connectivity to seven of my eight bulbs, now I've lost the eighth as well. I'm not advanced enough to debug (wouldn't really know what that entails) but I volunteer my device to be a guinea pig for any other experiment attempting to resolve the issue.

**Comment by yapishkahilt** [comment] 2020-05-07 04:16
Leaving the z-wave stick unplugged, I uninstalled and reinstalled deconz. The installation process seemed to hang, so I rebooted HA. I then went back to the dashboard and found that deconz had in fact been installed. The only thing I did in the config area was paste the path copied from the hardware area (not ACM0). The bulbs all appeared connected and were controllable again, but in deconz, Gateway was a blank page. I restarted HA server to see if that would do anything; this time, Gateway asked me for a login, but didn't recognize my password. After resetting my password, no devices showed up. I restored from a recent backup, and all the bulbs are again connected and controllable. I don't know if any of the above is useful, as I'm a total noob with no deep understanding of how this stuff works, but I figured I'd share just in case it contains any info that may be of help.

**Comment by kh-online** [comment] 2020-05-07 09:39
same issue here. Trying to run marthoc/deconz:armhf  docker container on a new ubuntu 20.04 64bit on RPI4. I created udev rules to appear /dev/ttyACM0 as /dev/ZIGBEE. When i start the container with --device=/dev/ttyACM0 , deconz sees the Conbee II. Deconz version is 2.05.75 / 8.3.2020. When I use the /dev/ZIGBEE symbolic link, it is shown as Raspbee device, Firmware 2640700. However, it works correctly but should be fixed.

**Comment by yapishkahilt** [comment] 2020-05-08 21:04
I spoke too soon. About 30 minutes after everything was working, all of a sudden all my zigbee devices became unavailable again. When I reboot HA, they become available, but it's just a matter of time before they again become unavailable (usually after I've gone up two flights of stairs and want to turn off my lights, of course).

**Comment by Mimiix** [comment] 2020-06-06 15:38
Continue in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2579

**Closed by Mimiix** 2020-06-06 15:38 UTC
