### ISSUE TITLE
GCFFlasher to list current firmware version

### ISSUE THREAD

**Issue by mmattel** [dresden-elektronik/deconz-rest-plugin#6224] opened 2022-07-26 15:35 UTC
## Describe the bug
Got my new ConBee II an flashed the firmware with the W10 command line tool - worked.
What I missed was to get the current firmware release when running the -l list devices command.
As you can write to it, you can read too and it would not be a big thing adding this to the current output.
I do only want to flash and I am not using the deconz sw.

## Steps to reproduce the behavior

Run `GCFFlasher -l`

## Expected behavior
Output also writes current firmware

## Screenshots
none

## Environment
 - Host system: W10x64
 - Running method: plain
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
Not relevant because only using the flash command.

## Additional context
Note, I am using a headless system where the ConBee II will be connected to without running deconz. W10 is just for flashing as there is no pure GCFFlasher alone and I do not install a full blown package that needs to get stopped just for using the flasher - maybe to think about providing the flasher alone...

**Comment by Smanar** [comment] 2022-07-26 16:08
>W10 is just for flashing as there is no pure GCFFlasher alone

Just by curiosity, have you tried this flasher https://github.com/dresden-elektronik/gcfflasher ?

**Comment by Mimiix** [comment] 2022-07-26 16:20
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Please use this github https://github.com/dresden-elektronik/gcfflasher

Kind regards,

**Closed by Mimiix** 2022-07-26 16:20 UTC
Labels: Bug report

**Comment by mmattel** [comment] 2022-07-27 16:53
Note, would be nice if you would point readers of your documentation to the [gcfflasher](https://github.com/dresden-elektronik/gcfflasher) repo.
There is no mentioning of it or link provided.

**Comment by Mimiix** [comment] 2022-07-27 21:40
> Note, would be nice if you would point readers of your documentation to the [gcfflasher](https://github.com/dresden-elektronik/gcfflasher) repo. There is no mentioning of it or link provided.

Hi!

Feel free to edit the wiki documentation   :)!

**Comment by mmattel** [comment] 2022-07-28 06:13
Done, see wiki
