### ISSUE TITLE
Aquara Cube T1 Pro - new Device not recognized by Phoscon

### ISSUE THREAD

**Issue by neomorph77** [dresden-elektronik/deconz-rest-plugin#6585] opened 2022-11-30 14:55 UTC
Hi there,
I got the brandnew Aquara Cube T1 Pro and try to connect it to deCONZ but with no luck.
When I try in Phoscon App to pair, I got these messages:

> 13:36:07:427 ZCL attribute report 0x54EF44100062D271 for cluster: 0x0000, ep: 0x01, frame control: 0x18, mfcode: 0x0000
> 13:36:07:427 0x54EF44100062D271 skip Xiaomi attribute 0x0000
> 13:36:07:517 0x54EF44100062D271 extract Xiaomi special attribute 0x00F7
> 13:36:07:517 01 battery 3086 (0x0C0E)
> 13:36:07:517 03 Device temperature 25 °C
> 13:36:07:517 04 unknown 424 (0x01A8)
> 13:36:07:517 05 RSSI dB (?) 209 (0x00D1)
> 13:36:07:517 06 LQI (?) 8589934592 (0x0200000000)
> 13:36:07:517 08 unknown 281 (0x0119)
> 13:36:07:517 0a Parent NWK 20619 (0x508B)
> 13:36:07:517 0c unknown 1 (0x01)
> 13:36:07:517 66 unknown 3 (0x03)
> 13:36:07:517 67 unsupported tag (data type 0x20)
> 13:36:07:517 68 unsupported tag (data type 0x21)
> 13:36:07:517 97 unknown 0 (0x0000)
> 13:36:07:517 98 unknown 1 (0x0001)
> 13:36:07:517 99 unknown 0 (0x0000)
> 13:36:07:517 9a unknown 4 (0x0004)
> 13:36:07:517 9B unsupported tag (data type 0x20)
> 13:36:07:517 FP indication 0x0104 / 0xFCC0 (0x54EF44100062D271 / 0x199C)
> 13:36:07:517 … (0x54EF44100062D271 / 0x199C)

In deCONZ I can find it, but it seems not to be supported now:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/4579031/204830025-6fd4604d-14dc-4871-9156-915ffd24e74a.png">

Is there a plan to support this device?

have a nice day
neo

**Comment by Mimiix** [comment] 2022-11-30 14:59
Hi,
Duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5732

I'm re-opening the other one.

For the next time: please stick to the template.

Kind regards,

**Closed by Mimiix** 2022-11-30 14:59 UTC
Labels: Device Request
