### ISSUE TITLE
When will we be able to permanent delete a device

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2895] opened 2020-06-08 01:19 UTC
Hi folks

When we be able to delete a device and not have it reappear when Deconz is restarted even though it will never be on our network again?

**Comment by Mimiix** [comment] 2020-06-08 05:36
Hi!

What do you mean with Reappearing?

If i remove a device from my network, it will show only if it is not added by anything else. This is because the device is looking to join a network.

**Comment by jensflorian** [comment] 2020-06-08 05:43
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2064

**Comment by Mimiix** [comment] 2020-06-08 06:23
Closing this one as it is duplicate of #2064 . 

Thank you @jensflorian

**Closed by Mimiix** 2020-06-08 06:23 UTC
