### ISSUE TITLE
plug _TZ3000_gvn91tmx

### ISSUE THREAD

**Issue by lepeno82** [dresden-elektronik/deconz-rest-plugin#6976] opened 2023-05-15 20:00 UTC
## Device

- Product name: aubess plug
- Manufacturer: _TZ3000_gvn91tmx
- Model identifier: TS011F
- Device type : plug 
 

### Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97314358/aa946b55-792d-445c-ab85-d2377b8cd0a2)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97314358/d2fbfb81-8897-4ffb-b55f-4b72af494f50)

### Simple Metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97314358/4af814ed-620f-4d6b-ad32-228c1be75645)

### Other clusters that are not mentioned above
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97314358/e559653e-4237-411c-bea1-cc59e341991f)

**Comment by BabaIsYou** [comment] 2023-05-15 20:09
Looks like duplicate of #6423

**Comment by Mimiix** [comment] 2023-05-16 18:33
Yep, Agree.

Closing.

**Closed by Mimiix** 2023-05-16 18:33 UTC
Labels: Device Request
