### ISSUE TITLE
RaspBeeI lost conection

### ISSUE THREAD

**Issue by morfei1** [dresden-elektronik/deconz-rest-plugin#7820] opened 2024-06-21 12:19 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

RaspbeeI lost conection and is not able to reconnect.

### Steps to reproduce the behavior

not  reproducable

### Expected behavior

to reconnect

### Screenshots

![raspbee](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62436468/2d787b03-8a14-4c9c-b34a-0d0133b81eda)

### Environment

- Rasoberi Pi 3b+
- Raspbian
- 26400500
- v2.26.3
- RaspBee I
- No
- No

### deCONZ Logs

14:50:53:754 failed to reconnect to network try=3
14:50:54:254 wait reconnect 5 seconds
14:50:55:254 wait reconnect 4 seconds
14:50:55:755 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
14:50:56:255 wait reconnect 3 seconds
14:50:57:255 wait reconnect 2 seconds
14:50:58:254 wait reconnect 1 seconds
14:50:58:308 COM: /dev/ttyAMA0 :  :  (0x0000/0x0000)
14:50:58:309 COM: /dev/ttyS0 :  :  (0x0000/0x0000)
14:50:58:309 dev /dev/ttyS0 (/dev/ttyS0)
14:50:58:310 auto connect com /dev/ttyS0
14:50:58:755 failed to reconnect to network try=4
14:50:58:761 ZDP get active endpoints for 0x831F
14:51:01:755 ZDP get active endpoints for 0xD0EC
14:51:05:754 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
14:51:09:264 device disconnected reason: 1, device index: 0
14:51:09:755 ZDP get active endpoints for 0x831F
14:51:10:255 wait reconnect 15 seconds
14:51:10:358 COM: /dev/ttyAMA0 :  :  (0x0000/0x0000)
14:51:10:359 COM: /dev/ttyS0 :  :  (0x0000/0x0000)
14:51:10:359 dev /dev/ttyS0 (/dev/ttyS0)
14:51:11:255 wait reconnect 14 seconds
14:51:12:254 wait reconnect 13 seconds
14:51:12:755 ZDP get active endpoints for 0xD0EC
14:51:13:255 wait reconnect 12 seconds
14:51:13:754 failed to reconnect to network try=5
14:51:14:255 wait reconnect 11 seconds
14:51:15:254 wait reconnect 10 seconds
14:51:15:755 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
14:51:16:255 wait reconnect 9 seconds
14:51:17:254 wait reconnect 8 seconds
14:51:18:255 wait reconnect 7 seconds
14:51:18:756 failed to reconnect to network try=6
14:51:19:254 wait reconnect 6 seconds
14:51:20:255 wait reconnect 5 seconds
14:51:20:755 ZDP get active endpoints for 0x831F
14:51:21:255 wait reconnect 4 seconds
14:51:22:255 wait reconnect 3 seconds
14:51:23:255 wait reconnect 2 seconds
14:51:23:754 failed to reconnect to network try=7
14:51:23:760 ZDP get active endpoints for 0xD0EC
14:51:24:254 wait reconnect 1 seconds
14:51:24:308 COM: /dev/ttyAMA0 :  :  (0x0000/0x0000)
14:51:24:309 COM: /dev/ttyS0 :  :  (0x0000/0x0000)
14:51:24:310 dev /dev/ttyS0 (/dev/ttyS0)
14:51:24:311 auto connect com /dev/ttyS0
14:51:25:755 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
14:51:26:755 APS-DATA.request id: 216, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 0 len: 11 tx.options 0x00
14:51:26:757 	asdu (length: 11): 1049000F00100011000040
14:51:27:755 APS-DATA.request id: 222, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 0 len: 11 tx.options 0x00
14:51:27:757 	asdu (length: 11): 104F000F00100011000040
14:51:28:756 APS-DATA.request id: 227, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 0 len: 11 tx.options 0x00
14:51:28:757 	asdu (length: 11): 1054000F00100011000040
14:51:28:777 APS-DATA.request id: 228, addrmode: 0x03, addr: 0x842E14FFFE139589, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:28:779 	asdu (length: 5): 1055000100
14:51:28:781 APS-DATA.request id: 229, addrmode: 0x03, addr: 0x842E14FFFE139589, profile: 0x0000, cluster: 0x0033, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x04
14:51:28:783 	asdu (length: 2): 4C00
14:51:29:754 APS-DATA.request id: 231, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 0 len: 11 tx.options 0x00
14:51:29:756 	asdu (length: 11): 1057000F00100011000040
14:51:30:755 APS-DATA.request id: 237, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:30:757 	asdu (length: 5): 105D000F00
14:51:30:758 APS-DATA.request id: 238, addrmode: 0x03, addr: 0x842E14FFFE139589, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:30:760 	asdu (length: 5): 105E000100
14:51:31:755 APS-DATA.request id: 243, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:31:756 	asdu (length: 5): 1063000F00
14:51:31:774 ZDP get active endpoints for 0x831F
14:51:31:776 APS-DATA.request id: 244, addrmode: 0x03, addr: 0x842E14FFFE13A10A, profile: 0x0000, cluster: 0x0005, ep: 0x00 -> 0x00 queue: 0 len: 3 tx.options 0x00
14:51:31:778 	asdu (length: 3): 4D1F83
14:51:32:754 APS-DATA.request id: 246, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:32:756 	asdu (length: 5): 1065000F00
14:51:32:758 APS-DATA.request id: 247, addrmode: 0x03, addr: 0x842E14FFFE139589, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:32:759 	asdu (length: 5): 1066000100
14:51:32:785 APS-DATA.request id: 252, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:32:787 	asdu (length: 5): 106B000F00
14:51:32:789 APS-DATA.request id: 253, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:32:790 	asdu (length: 5): 106C000340
14:51:32:792 APS-DATA.request id: 254, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0000, cluster: 0x0033, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x04
14:51:32:793 	asdu (length: 2): 4E00
14:51:33:755 APS-DATA.request id: 0, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:33:756 	asdu (length: 5): 106E000F00
14:51:33:775 APS-DATA.request id: 1, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:33:777 	asdu (length: 5): 106F000F00
14:51:33:780 APS-DATA.request id: 2, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:33:782 	asdu (length: 5): 1070000340
14:51:33:784 APS-DATA.request id: 3, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0000, cluster: 0x0033, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x04
14:51:33:785 	asdu (length: 2): 4F00
14:51:34:755 APS-DATA.request id: 8, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0300, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:34:757 	asdu (length: 5): 1075000F00
14:51:34:758 APS-DATA.request id: 9, addrmode: 0x03, addr: 0x842E14FFFE139589, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:34:759 	asdu (length: 5): 1076000000
14:51:34:787 ZDP get active endpoints for 0xD0EC
14:51:34:789 APS-DATA.request id: 10, addrmode: 0x03, addr: 0xD0CF5EFFFE6D3440, profile: 0x0000, cluster: 0x0005, ep: 0x00 -> 0x00 queue: 0 len: 3 tx.options 0x00
14:51:34:791 	asdu (length: 3): 50ECD0
14:51:35:168 device disconnected reason: 1, device index: 0
14:51:35:254 wait reconnect 15 seconds
14:51:35:309 COM: /dev/ttyAMA0 :  :  (0x0000/0x0000)
14:51:35:311 COM: /dev/ttyS0 :  :  (0x0000/0x0000)
14:51:35:312 dev /dev/ttyS0 (/dev/ttyS0)
14:51:35:755 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
14:51:36:254 wait reconnect 14 seconds
14:51:37:255 wait reconnect 13 seconds
14:51:38:254 wait reconnect 12 seconds
14:51:38:756 failed to reconnect to network try=8
14:51:39:255 wait reconnect 11 seconds
14:51:40:255 wait reconnect 10 seconds
14:51:41:255 wait reconnect 9 seconds
14:51:42:254 wait reconnect 8 seconds
14:51:42:755 ZDP get active endpoints for 0x831F
14:51:43:254 wait reconnect 7 seconds
14:51:43:754 failed to reconnect to network try=9
14:51:44:255 wait reconnect 6 seconds
14:51:45:255 wait reconnect 5 seconds
14:51:45:755 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
14:51:45:765 ZDP get active endpoints for 0xD0EC
14:51:46:254 wait reconnect 4 seconds
14:51:47:255 wait reconnect 3 seconds
14:51:48:254 wait reconnect 2 seconds
14:51:48:755 failed to reconnect to network try=10
14:51:49:255 wait reconnect 1 seconds
14:51:49:342 COM: /dev/ttyAMA0 :  :  (0x0000/0x0000)
14:51:49:343 COM: /dev/ttyS0 :  :  (0x0000/0x0000)
14:51:49:344 dev /dev/ttyS0 (/dev/ttyS0)
14:51:49:345 auto connect com /dev/ttyS0
14:51:51:754 APS-DATA.request id: 101, addrmode: 0x03, addr: 0xD0CF5EFFFE2E18E2, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:51:755 	asdu (length: 5): 10CB000000
14:51:52:755 APS-DATA.request id: 106, addrmode: 0x03, addr: 0xD0CF5EFFFE2E45B8, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:52:756 	asdu (length: 5): 10D0000000
14:51:52:757 APS-DATA.request id: 107, addrmode: 0x03, addr: 0x842E14FFFE139589, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
14:51:52:757 	asdu (length: 5): 10D1000B05

### Additional context

A rebbot, update and a try to recover the network did not help.

**Comment by Mimiix** [comment] 2024-06-21 13:00
Hi,

As this is not a bug as described in #5113 i'm closing this issue.

Please open a post on the forums.

**Closed by Mimiix** 2024-06-21 13:00 UTC
Labels: Bug report
