### ISSUE TITLE
OSRAM - CLA60 RGBW Z3 / Poweron state can't be set

### ISSUE THREAD

**Issue by LaCruz75** [dresden-elektronik/deconz-rest-plugin#5535] opened 2021-11-30 16:49 UTC
## Describe the bug
I can't chaneg poweron onoff value to off. Writing failed. Setting via FC0F also not possible.

## Steps to reproduce the behavior
- Go to attributes
- Change PowerOn OnOff to OFF
- On read attribut, it said "unsupported"
-  Setting via FC0F not avaible

## Expected behavior
Storing the PowerOn value

## Screenshots
![osram1](https://user-images.githubusercontent.com/20754788/144088563-3ce6efdd-b6a8-4ec4-850e-69dd7d36a9db.png)
![osram2](https://user-images.githubusercontent.com/20754788/144088843-69e8f07d-2747-427a-98ca-abcb28e366a9.png)

## Environment
 - Host system: VM
 - Running method: (Home Assistent deCONZ Add-on
 - Firmware version: (26700700)
 - deCONZ version: (v2.12.6)
 - Device: ConBee II

## deCONZ Logs
not yet avaible

## Additional context
none

**Comment by Mimiix** [comment] 2021-11-30 20:22
Hi,

This is not a bug, but this means the device doesn't support it.

For questions on this, feel free to open a post on the forums.

As this is not a bug according to #5113 i am closing this issue.

Kind regards,

**Closed by Mimiix** 2021-11-30 20:22 UTC
Labels: Bug report
