### ISSUE TITLE
Unable to connect to device

### ISSUE THREAD

**Issue by knutknutso** [dresden-elektronik/deconz-rest-plugin#7160] opened 2023-08-09 16:34 UTC
Dear Community,
below picture does show my issue.
I cannot choose device to connect.
Cobee2 device is connected to /../../ttyACM0
deconz.service is started
I am connected via rdp to the remote system which is Debian 10
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/102857583/732e6942-fbb2-4b15-b4ed-e3acbc6ab649)

Thank you for your kind support
Regards

**Comment by Mimiix** [comment] 2023-08-09 17:50
Hi,

As this is not a bug report as described in #5113 I am closing this issue.

Feel free to open a topic on the forums.

Kind regards,

**Closed by Mimiix** 2023-08-09 17:50 UTC
