### ISSUE TITLE
Update to 2.12.6 and Firmware 267700700/26720700 NO connection at all

### ISSUE THREAD

**Issue by easybeat** [dresden-elektronik/deconz-rest-plugin#5244] opened 2021-08-24 09:50 UTC
## Describe the bug

 I've updated my system to latest stable release and latest firmware. But with latest conbeeII firmware 26700700 or 26720700 nothing is connecting. If I go back to Firmware 26680700 then everything seems to work.

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

  1. Update to 2.12.6
  2. Update conbeeII Firmware to 26700700 or 26720700
  3. restart the system
  4. After waiting minutes no connections show in deconz gui and nothing ist working

I can see in logs following entries:
11:47:04:328 apsUseExtPanid is 0x23D1DDDDDDDDCDAB but should be 0, start reconfiguration
11:47:04:328 Skip automatic channel change, TODO warn user

Do I have to change something on my configuration?

## Expected behavior

Should setup connections like with firmware 26680700 

## Screenshots

![no connection with FW 26720700](https://user-images.githubusercontent.com/37217887/130595018-0d4bb9b4-226e-4af3-bacc-e5b791a48fd9.png)
![deconz system](https://user-images.githubusercontent.com/37217887/130595207-3cf26c31-93f5-48b8-ba46-9f6ccbec26df.png)

## Environment

 see screenshots

 - Host system: (NAS)
 - Running method: (Ubuntu)
 - Firmware version: (26720700)
 - deCONZ version: (2.12.6)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes)
 - Is there any other USB or serial devices connected to the host system? If so: Which? ZWave Stick on separate powered USB extension

## deCONZ Logs

[26720700 problem.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7038249/26720700.problem.txt)

**Comment by Mimiix** [comment] 2021-08-24 10:18
Hi,

As this seems to be a problem with your local installation(not a bug), i am closing this.

Support/Help is moved to the forums :) https://forum.phoscon.de

Kind regards,

**Closed by Mimiix** 2021-08-24 10:18 UTC
Labels: Bug report

**Comment by easybeat** [comment] 2021-08-24 10:28
Well, how can you be sure it is a problem with my local installation?

**Comment by easybeat** [comment] 2021-08-24 10:37
And also I can't post in the forum:

![image](https://user-images.githubusercontent.com/37217887/130602514-f8fa5b67-ff6c-4dfd-851b-798cf07e6d89.png)

**Comment by Mimiix** [comment] 2021-08-24 10:49
> Well, how can you be sure it is a problem with my local installation?
Small answer: We can't.
Long answer: How can we be sure it's a bug? There isn't anything to point on in the code as explained in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5113 .  That's why we point to the forums, just to keep Github clear and make things more clear. 
 
I've approved your account.
