### ISSUE TITLE
Update to 2.17.01 - Aqara Motion sensors have lost Temperature sensor

### ISSUE THREAD

**Issue by evan-shaw** [dresden-elektronik/deconz-rest-plugin#6180] opened 2022-07-07 12:24 UTC
## Describe the bug

Since upgrading to deconx 2.17.01 this morning, my Aqara Motion sensors have lost their temperature sensor.
I'm running this on a Raspberry Pi 4B v1.1,  4GB RAM, with Raspbian OS Buster, 64Bit Kernel 5.10.103-v8+ aarch64
This is with a ConBee II with firmware  26720700

The only evidence I have of this is that in Home Assistant "Core" running on the same Pi, is that the Temperature sensors on these motion sensors now report as "Unavailable".

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

  1. Upgrade deconz from 2.16.01 to 2.17.01
  2. Login to Home Assistant
  3. Check motion sensor temperature reporting
  4. Shows as "Unavailable" - history showing it active previously is still available in HA

  If the problem can't be reproduced and is sporadic, please provide some details
  on how often and when the issue happens.

 It is constant since the upgrade, for the past 3hrs.

## Expected behavior

  I would expect temperature for the sensor to be displayed.

## Screenshots

  Screenshots attached.

## Environment

  -->
![Selection_882](https://user-images.githubusercontent.com/34520506/177771608-ede8a0a9-0ac3-4287-a07f-f54cbaea0028.png)

![Selection_883](https://user-images.githubusercontent.com/34520506/177771600-e76e4dc1-a552-4259-9529-6b728c6c11ad.png)
![Selection_889](https://user-images.githubusercontent.com/34520506/177774306-19cd846c-8ef6-4e38-9431-21b66c9732ec.png)

![Selection_885](https://user-images.githubusercontent.com/34520506/177771575-45507179-3f85-4f3e-94d5-b5702f5bc492.png)
![Selection_886](https://user-images.githubusercontent.com/34520506/177771564-358d2265-2cd8-423c-b9e8-4a6a6e2ea21a.png)

![Selection_888](https://user-images.githubusercontent.com/34520506/177771531-b9005bce-8597-4db5-89c5-7d9ec612871a.png)
![Selection_887](https://user-images.githubusercontent.com/34520506/177773955-bb4a3910-688f-49d1-9c06-e0796583079b.png)

 - Host system: Raspberry Pi4B
 - Running method: Raspbian Buster 
 - Firmware version: 26720700
 - deCONZ version: 2.17.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## Additional context

  As can be seen in the screenshot files, HA now shows the temperature sensor of these motion sensors as unavailable.

**Comment by evan-shaw** [comment] 2022-07-07 13:45
Hi Mimlix,

Thanks for the response, does this help: -

"8": {
            "config": {
                "battery": 100,
                "on": true,
                "reachable": true,
                "tholddark": 12000,
                "tholdoffset": 7000
            },
            "ep": 1,
            "etag": "c8ef78d1f38242dbb2c454d781dd56db",
            "lastannounced": null,
            "lastseen": "2022-07-07T13:36Z",
            "manufacturername": "LUMI",
            "modelid": "lumi.sensor_motion.aq2",
            "name": "FrontDoorMotionSensor",
            "state": {
                "dark": false,
                "daylight": true,
                "lastupdated": "2022-07-07T12:41:53.480",
                "lightlevel": 30001,
                "lux": 1000
            },
            "swversion": "20170627",
            "type": "ZHALightLevel",
            "uniqueid": "00:15:8d:00:03:3a:d8:49-01-0400"
        };

and

"9": {
            "config": {
                "battery": 100,
                "duration": 90,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "fa7989be29512a64fd19ec5c7e58a0be",
            "lastannounced": null,
            "lastseen": "2022-07-07T13:36Z",
            "manufacturername": "LUMI",
            "modelid": "lumi.sensor_motion.aq2",
            "name": "FrontDoorMotionSensor",
            "state": {
                "lastupdated": "2022-07-07T12:43:23.663",
                "presence": false
            },
            "swversion": "20170627",
            "type": "ZHAPresence",
            "uniqueid": "00:15:8d:00:03:3a:d8:49-01-0406"
        },

Thanks

**Comment by Mimiix** [comment] 2022-07-07 13:50
Is there a ZHATemperature for this device?

**Comment by Mimiix** [comment] 2022-07-07 13:52
It looks like the DDF is missing the Temperature part here. I think you should be able to solve it now by changing the state of the DDF to Draft : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by Mimiix** [comment] 2022-07-07 13:58
I've asked @SwoopX  to check in.

**Comment by Mimiix** [comment] 2022-07-07 14:03
I just tested it with my own. Re-paired on 2.17.01. @Thomas-Vos did the same on his environment. Here we see the temperature:

![image](https://user-images.githubusercontent.com/43333120/177792459-4c128d30-1e5e-4062-be6b-3d94001a68c1.png)

This seems to be a issue on your own environment i guess. I recommend re-pairing and see from there. As it's not a bug, i am closing this issue. If you still need some help, please use the forums. 

Kind regards

**Closed by Mimiix** 2022-07-07 14:03 UTC
Labels: Bug report

**Comment by ebaauw** [comment] 2022-07-07 16:10
Like most Xiaomi devices, these report a coarse-grained internal device temperature, which deCONZ exposes as `config.temperature`, and, for reasons beyond my comprehension, Phoscon shows the same way as a proper temperature sensor.  Looks like the `config` attribute is missing from the DDF.

**Comment by bcutter** [comment] 2022-07-19 11:02
> This seems to be a issue on your own environment i guess.

No it's not. Same happened for me: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6203

> I recommend re-pairing and see from there.

I repaired (soft-repairing without deletion) and it changed nothing.

> As it's not a bug, i am closing this issue.

Why do you think it's not a bug? There's evidence 2.17.1 broke it. Two issues exist on the same problem. If you can't replicate it, it's not automatically "no bug".

> If you still need some help, please use the forums.
It's an issue and GitHub is for issues, right.
