### ISSUE TITLE
IKEA 5 button remote (e1810) assigns random lights which cannot be detached from remote.

### ISSUE THREAD

**Issue by schumi2004** [dresden-elektronik/deconz-rest-plugin#6101] opened 2022-06-02 13:27 UTC
## Describe the bug
When adding a IKEA remote (5 button white/gray e1810) it automaticly links to excisting lights. Without any further configuration it already controls these lights. Trying to re-pair(or remove and pair again) only adds up more lights.
It also doesn't create a new light group as described on multiple sites.

## Steps to reproduce the behavior
Just pairing the remote with Deconz Conbee2

## Expected behavior
Just a isolated remote until configured otherwise.

## Environment
Version: 
Firmware: 

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 2.16.01 / 21-4-2022
 - deCONZ version: 26720700
 - Device: ConBee II
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? If so: n/a

**Comment by Mimiix** [comment] 2022-06-02 18:33
Hi,

As this is not a bug report as described in #5113, I am closing this.

Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-06-02 18:33 UTC
Labels: Bug report
