### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by smulle48** [dresden-elektronik/deconz-rest-plugin#4318] opened 2021-02-01 09:37 UTC
## Device

- Product name: Smart Wireless Door Bell STKZ 1 A1
- Manufacturer: SilverCrest / Lidl / Tuya
- Model identifier: TS0211
- Device type : Please remove all unrelated device types. 
  - Other: Door Bell

## Screenshots

![Skærmbillede 2021-02-01 kl  10 31 17](https://user-images.githubusercontent.com/24297824/106440036-a7dc0700-6478-11eb-9b3e-524da5cca57b.png)
![Skærmbillede 2021-02-01 kl  10 33 34](https://user-images.githubusercontent.com/24297824/106440315-00ab9f80-6479-11eb-92cd-4ce94a6baba1.png)
![Skærmbillede 2021-02-01 kl  10 34 28](https://user-images.githubusercontent.com/24297824/106440385-1a4ce700-6479-11eb-87cc-09d09de0fd0e.png)

**Comment by Mimiix** [comment] 2021-02-01 09:38
Duplicate of 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4260

Please use search next time to prevent yourself some time 😅

**Closed by Mimiix** 2021-02-01 09:38 UTC
Labels: Device Request
