### ISSUE TITLE
commandline get a api key

### ISSUE THREAD

**Issue by syswombat** [dresden-elektronik/deconz-rest-plugin#7702] opened 2024-04-09 04:01 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Raspbeery Pi 4b
Kernel: 6.6.20+rpt-rpi-v8 
bits: 64 
Distro: Debian GNU/Linux 12 (bookworm)

hello
just with command line how do i get a API Key to add it to openHAB Binding?
the Linux is whitout desktop.

nmap against the device is only port 22 open.

please point me to the right plase to read further 

have a nice time

### Steps to reproduce the behavior

$ curl http://10.18.42.15:22/api/ -X POST -d '{"devicetype": "TestKey"}'
curl: (1) Received HTTP/0.9 when not allowed

### Expected behavior

not getting a api key

### Environment

- Host system: (Raspberry Pi )
- Running method: (Raspbian )
- Firmware version: (26xxyy00)
- deCONZ version (how to find out?)
- Device: (C RaspBee II)
- Is there any other USB or serial devices connected to the host system? If so: Which? No

**Comment by Mimiix** [comment] 2024-04-09 05:27
Clearly not a bug.

Closing.

**Closed by Mimiix** 2024-04-09 05:27 UTC
Labels: Bug report
