### ISSUE TITLE
Add Support for lumi.magnet.agl02 (Not lumi.senor_magnet.agl02)

### ISSUE THREAD

**Issue by iDragonfighter** [dresden-elektronik/deconz-rest-plugin#7276] opened 2023-10-04 17:39 UTC
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Aqara Door and Window Sensor T1

### Manufacturer

Aqara

### Model identifier

lumi.magnet.agl02

### Device type to add

None

### Node info

Hi,
there is already support for "lumi.senor_magnet.agl02". #4428 
But somehow my device shows. "lumi.magnet.agl02" (without the "sensor_").
Therefore it will not show in the app after connecting.

Like the other device it says "Aqara Door and Window Sensor T1" on the box.
The Box is beige other than my other devices wich came in an blue box.

### Endpoints and clusters

![Bildschirmfoto 2023-10-04 um 19 36 44](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62772449/05b7857c-e822-4a1e-8ec7-927857446243)

### Basic

![Bildschirmfoto 2023-10-04 um 19 35 42](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62772449/34b8db32-8302-4f2d-8b2b-b27ec4c967dd)

**Comment by Mimiix** [comment] 2023-10-04 18:05
Looks like a new one :)

Can you please add all screens?

**Comment by SwoopX** [comment] 2023-10-04 20:53
Sorry, but it's a duplicate of #4428

**Comment by Mimiix** [comment] 2023-10-04 20:57
> Sorry, but it's a duplicate of #4343

As far as I can see it is the sensor_magnet instead of magnet in your issue.

**Comment by SwoopX** [comment] 2023-10-04 20:59
> > Sorry, but it's a duplicate of #4343
> 
> As far as I can see it is the sensor_magnet instead of magnet in your issue.

You might want to look again closely 😉

**Comment by Mimiix** [comment] 2023-10-04 21:07
> > > Sorry, but it's a duplicate of #4343
> > 
> > 
> > As far as I can see it is the sensor_magnet instead of magnet in your issue.
> 
> You might want to look again closely 😉

You mean your edit on #4428? Now it's fine. Thanks

**Comment by iDragonfighter** [comment] 2023-10-04 22:50
Sorry, i usually don‘t use github and the terminology here and in the deconz Program is a bit too much for me 😂

You‘re right. 
It is the Same Device as mentioned in the request #4343
So if needed, you can take the Screenshots from there. 
But in the „commit?“ (in the changed Code) #4428
Ist says „sensor_magnet“ instead of „magnet“.

again, sorry if that was clear already.

**Closed** 2023-11-06 11:59 UTC
Labels: Device Request, Awaiting Merge

**Comment by iDragonfighter** [comment] 2024-01-10 21:56
Thank you for implementing the T1 Sensor.
The sensor is now identified as "lumi.magnet.agl02". However, it seems to be malfunctioning as very few details are displayed in the Deconz App, and there is no Open/Closed state. 
![Bildschirmfoto 2024-01-10 um 22 51 50](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62772449/93d36e36-c6cb-4bf8-8b44-53304385b453)

**Comment by SwoopX** [comment] 2024-01-10 22:22
Have you re-paired it?

**Comment by SwoopX** [comment] 2024-01-13 00:27
@iDragonfighter Conbee 3?

**Comment by iDragonfighter** [comment] 2024-01-13 12:23
No, RaspBee II

**Comment by SwoopX** [comment] 2024-01-13 23:41
Hm, very odd. However, I also pleayed around with an E1 sensor and experienced the very same. The device was stuck in some strange state I have to say. It seemingly paired correctly (I had the sniffer running) but it just kept quiet while moving the magnet, literally zero response, but all that was with a Conbee 3.

I'll see that have another look with the T1 on Conbee 2 within the next few days.

**Comment by sirinveen** [comment] 2024-01-24 10:10
I've just bought this sensor and it works very well, just modify the DDF so that it takes on/off cluster. And also re-pair is always a good idea.

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/102876220/b8ffca64-aab5-4008-816b-11c5f88d3a97)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/102876220/9d77236c-62cb-4622-8022-36c5d6038bbf)


```json
{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.magnet.agl02",
  "vendor": "Xiaomi",
  "product": "Aqara T1 open/close sensor MCCGQ12LM",
  "sleeper": true,
  "status": "Gold",
  "path": "/devices/xiaomi_mccgq12lm_t1_openclose_sensor.json",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500",
          "0xFCC0"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x00f7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x01",
            "mf": "0x115f",
            "script": "xiaomi_battery.js"
          },
          "default": 0
        },
        {
          "name": "config/enrolled",
          "public": false,
          "default": 1
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/open",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        }
      ]
    }
  ]
}
```

**Comment by chc88** [comment] 2024-02-04 21:26
The adjusted ddf by @sirinveen works for me

**Comment by SwoopX** [comment] 2024-02-04 22:10
The DDF has already been amended in this regard. However, I'd recommend to take code from here https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/xiaomi/xiaomi_dw-s03d_t1_openclose_sensor.json to prevent the device being hammered with unnecessary requests.

**Comment by iDragonfighter** [comment] 2024-02-05 09:13
I don't know what I'm doing wrong, but unfortunately, it still doesn't work for me.
Not with the DDF from @sirinveen, and not even with the DDF file provided by @SwoopX.
Same behavior as [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7276#issuecomment-1885802896).
I now believe that my sensor is simply broken...
I think I am going to toss it out.

But thanks for the support.
