### ISSUE TITLE
Aquara Wireless Mini Switch T1 lumi.remote.b1acn02

### ISSUE THREAD

**Issue by dbweb-ch** [dresden-elektronik/deconz-rest-plugin#7654] opened 2024-03-07 17:31 UTC
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Aquara Wireless Mini Switch T1

### Manufacturer

LUMI

### Model identifier

lumi.remote.b1acn02

### Device type to add

Switch

### Node info

![Screenshot 2024-03-07 133225](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/57174794/bf452518-a75c-48a3-97d4-f3849d4d77e0)

### Endpoints and clusters

![Screenshot 2024-03-07 133410](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/57174794/4b9d4e7c-225f-47f4-a10e-061b6d67a7da)
![Screenshot 2024-03-07 133419](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/57174794/770d0ece-4c86-4e59-a5f8-dfaa203b6e6d)

### Basic

![Basic](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/57174794/e4c89626-d7a5-4249-8c8e-148aa1c582b3)

**Comment by SwoopX** [comment] 2024-03-29 10:32
Duplicate of #7536

**Closed** 2024-03-29 10:32 UTC
Labels: Device Request, Duplicate
