### ISSUE TITLE
Request support for new device _TZ3000_bjawzodf TY0201

### ISSUE THREAD

**Issue by c-hoeger** [dresden-elektronik/deconz-rest-plugin#7685] opened 2024-03-29 10:38 UTC
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

TUYA Zigbee

### Manufacturer

_TZ3000_bjawzodf

### Model identifier

TY0201

### Device type to add

Sensor

### Node info

<img width="545" alt="Bildschirmfoto 2024-03-29 um 11 23 50" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4416051/3995f664-e4a4-402e-99b7-c391b67ccd13">

### Endpoints and clusters

<img width="369" alt="Bildschirmfoto 2024-03-29 um 11 38 28" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4416051/7dab480d-0662-4139-a944-94123a356308">

### Basic

<img width="900" alt="Bildschirmfoto 2024-03-29 um 11 23 11" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4416051/37a853aa-fa90-4b7d-95ac-3a40c3ed8208">

### Power Configuration

<img width="552" alt="Bildschirmfoto 2024-03-29 um 11 39 30" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4416051/c4aa483d-19b4-4d73-9f74-8e2865a389f2">

### Temperature measurement

<img width="525" alt="Bildschirmfoto 2024-03-29 um 11 40 32" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4416051/d330445b-64bb-4812-a558-448c0e912dca">

### Relative humidity measurement

<img width="530" alt="Bildschirmfoto 2024-03-29 um 11 41 23" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4416051/3d0a0990-e294-465a-a374-bf778b03f2a3">

**Comment by SwoopX** [comment] 2024-03-29 12:37
Duplicate of #7684

**Closed by SwoopX** 2024-03-29 12:37 UTC
Labels: Device Request, Duplicate
