### ISSUE TITLE
Aqara Motion sensors temperature is static since 2.17.1 release

### ISSUE THREAD

**Issue by evan-shaw** [dresden-elektronik/deconz-rest-plugin#6191] opened 2022-07-12 11:21 UTC
## Describe the bug

I orginally had a problem with this release and the Aqara motion sensors not reporting temperature at all, see issue #6180
So I re-paired the devices as suggested, which did indeed give me the temperature reading back.
But since this I've noticed that the temperature isn't fluctuating, it remains static.

## Steps to reproduce the behavior

1. Go to Phoscon-GW/Sensors page
2. Click on an Aqara motion sensor
3. Check Temperature reading
4. It has remained static since the update/re-pairing of the devices

## Expected behavior

I would expect the temperature to vary during the day/night

## Screenshots

Attached screenshot from Home Assistant shows temperature data captured before the latest update, a gap showing initial issue  #6180 and then the data captured after the re-pairing

## Environment

![Selection_909](https://user-images.githubusercontent.com/34520506/178477673-2f63769e-ac4e-4e0b-ba63-ac3059b77ffc.png)

 - Host system: Raspberry Pi 4B
 - Running method: Raspbian OS Buster (64bit Kernel aarch64 with 32Bit OS - i.e. "arm_64bit=1" in config.txt)
 - Firmware version: 26720700
 - deCONZ version: 2.17.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system?  No   If so: Which?

## Additional context

API Information

"16": {
        "config": {
            "battery": 100,
            "on": true,
            "reachable": true,
            "temperature": 2800,
            "tholddark": 12000,
            "tholdoffset": 7000
        },
        "ep": 1,
        "etag": "a76c0d26be3483d4d95b2f86abe0c874",
        "lastannounced": null,
        "lastseen": "2022-07-12T11:00Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.sensor_motion.aq2",
        "name": "DiningRoomMotionSensor",
        "state": {
            "dark": false,
            "daylight": true,
            "lastupdated": "2022-07-12T07:02:07.132",
            "lightlevel": 21140,
            "lux": 130
        },
        "swversion": "3000-0001",
        "type": "ZHALightLevel",
        "uniqueid": "00:15:8d:00:02:78:ae:00-01-0400"
    },
    "17": {
        "config": {
            "battery": 100,
            "duration": 90,
            "on": true,
            "reachable": true,
            "temperature": 2800
        },
        "ep": 1,
        "etag": "dd27bf5e5f9aa29e0bb2e00dd2785ab7",
        "lastannounced": null,
        "lastseen": "2022-07-12T11:00Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.sensor_motion.aq2",
        "name": "DiningRoomMotionSensor",
        "state": {
            "lastupdated": "2022-07-12T07:03:37.270",
            "presence": false
        },
        "swversion": "3000-0001",
        "type": "ZHAPresence",
        "uniqueid": "00:15:8d:00:02:78:ae:00-01-0406"
    }

**Comment by Mimiix** [comment] 2022-07-12 11:25
Hi,

This is not a dedicated sensor, but more a sensor for the device itself. It is general advice to not use it (I believe Xiaomi isn't exposing it either) as it is not correct.  

deCONZ doesn't do anything with sensor readings other then scale calculations (for example, If the device reports kWh instead of Wh). So this is not a bug.

For questions like this, i'd recommend using the forums (https://forum.phoscon.de) or the discord: https://discord.gg/3XGEYY9

Closing this.

**Closed by Mimiix** 2022-07-12 11:25 UTC
Labels: Bug report
