### ISSUE TITLE
Sengled Model Z01-A19NAE26 Smart LED Tunable White A19

### ISSUE THREAD

**Issue by stevewull** [dresden-elektronik/deconz-rest-plugin#4536] opened 2021-03-08 00:21 UTC
## Device

- Product name: Smart LED Tunable White 2700K-6500K
- Manufacturer: Sengled
- Model identifier: Z01-A19NAE26
- Device type :
  - Light

Note: DeCONZ recognizes this as a light and can control the brightness (See API output at bottom of this post). However, API does not have the ct attribute and the color temperature cannot be displayed or controlled. This was mentioned in issue #3045, but it was never resolved. Bulb also has a metering cluster.

## Screenshots

Node Info:
![image](https://user-images.githubusercontent.com/46251961/110259698-f2f8a680-7f5d-11eb-9c44-17fd523714a4.png)

Clusters:
![image](https://user-images.githubusercontent.com/46251961/110259824-84681880-7f5e-11eb-8f82-55eeb70bb209.png)

Basic cluster:
![image](https://user-images.githubusercontent.com/46251961/110259855-9a75d900-7f5e-11eb-9f24-8793a16d66c4.png)

Identify cluster:
![image](https://user-images.githubusercontent.com/46251961/110259869-ab264f00-7f5e-11eb-98a2-bdf99d49d483.png)

Groups cluster attributes:
![image](https://user-images.githubusercontent.com/46251961/110259905-d6a93980-7f5e-11eb-81ad-13ba8af311d9.png)

Scenes cluster attributes:
![image](https://user-images.githubusercontent.com/46251961/110259928-e9bc0980-7f5e-11eb-8086-8a076a9975eb.png)

On/Off Cluster:
![image](https://user-images.githubusercontent.com/46251961/110259939-fb051600-7f5e-11eb-8fcd-d060398f3556.png)

Level Control Cluster:
![image](https://user-images.githubusercontent.com/46251961/110259951-0bb58c00-7f5f-11eb-9e65-f3b6231063cd.png)

Color Control Cluster:
![image](https://user-images.githubusercontent.com/46251961/110259967-26880080-7f5f-11eb-9a84-ae8b10ee0734.png)
![image](https://user-images.githubusercontent.com/46251961/110259976-36074980-7f5f-11eb-9ac9-3b9e3933ff3f.png)
![image](https://user-images.githubusercontent.com/46251961/110259999-4a4b4680-7f5f-11eb-9fdc-743a98ad484d.png)
![image](https://user-images.githubusercontent.com/46251961/110260019-63ec8e00-7f5f-11eb-910b-9c06896de889.png)
![image](https://user-images.githubusercontent.com/46251961/110260035-72d34080-7f5f-11eb-91af-9d9d1ee62cf0.png)
![image](https://user-images.githubusercontent.com/46251961/110260046-7cf53f00-7f5f-11eb-80a8-39ba7352fc16.png)
![image](https://user-images.githubusercontent.com/46251961/110260061-87afd400-7f5f-11eb-815d-7356e23d9aea.png)
![image](https://user-images.githubusercontent.com/46251961/110260068-91d1d280-7f5f-11eb-9d1c-d13dbc5c675e.png)
![image](https://user-images.githubusercontent.com/46251961/110260076-9bf3d100-7f5f-11eb-99c4-475c6b1b7c51.png)
![image](https://user-images.githubusercontent.com/46251961/110260087-a6ae6600-7f5f-11eb-83e3-5941e0d1e027.png)
![image](https://user-images.githubusercontent.com/46251961/110260098-b4fc8200-7f5f-11eb-874a-0890195def64.png)
![image](https://user-images.githubusercontent.com/46251961/110260104-bfb71700-7f5f-11eb-9203-a698b84afe63.png)
![image](https://user-images.githubusercontent.com/46251961/110260125-d198ba00-7f5f-11eb-9570-26fe17b3a2b8.png)
![image](https://user-images.githubusercontent.com/46251961/110260134-d9f0f500-7f5f-11eb-831e-ca4a02dd07cf.png)
![image](https://user-images.githubusercontent.com/46251961/110260146-e37a5d00-7f5f-11eb-9d5e-1b4b4ac39577.png)
![image](https://user-images.githubusercontent.com/46251961/110260158-eecd8880-7f5f-11eb-9c7e-2b3ac076990a.png)

Simple metering cluster:
![image](https://user-images.githubusercontent.com/46251961/110260185-060c7600-7f60-11eb-986d-fd2916d0d89e.png)

Diagnostics cluster:
![image](https://user-images.githubusercontent.com/46251961/110260210-1b81a000-7f60-11eb-973f-48252acf4413.png)

OTAU Cluster:
![image](https://user-images.githubusercontent.com/46251961/110260237-276d6200-7f60-11eb-9786-c3cd495559ba.png)

API:
![image](https://user-images.githubusercontent.com/46251961/110260311-77e4bf80-7f60-11eb-9147-2632b48a1004.png)

**Comment by stevewull** [comment] 2021-03-08 00:26
On the Color Temperature cluster, I see that names of some clusters on truncated in my post. Here they are:

![image](https://user-images.githubusercontent.com/46251961/110260575-ab741980-7f61-11eb-812b-807ba803c0ea.png)
![image](https://user-images.githubusercontent.com/46251961/110260590-bdee5300-7f61-11eb-8c64-95bb692af3a3.png)

**Comment by deviantintegral** [comment] 2021-03-09 02:28
👋 I think this is a duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4469

Also, see my note there about being able to set the colour temperature.

**Comment by stevewull** [comment] 2021-03-09 03:06
Whoops. Sorry I missed that. Hopefully, the screenshots here provide what you were asking for.  I'll add the rest of my comments there.

**Comment by Mimiix** [comment] 2021-03-09 10:53
As this is a duplicate, I'll close it and we continue in the other one.

**Closed by Mimiix** 2021-03-09 10:53 UTC
Labels: Device Request
