### ISSUE TITLE
deconz / VNC inside homeassistant has unusable window layout

### ISSUE THREAD

**Issue by raidenlal** [dresden-elektronik/deconz-rest-plugin#8028] opened 2024-11-09 19:55 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hello there,
after an update several weeks/months ago the deconz application became unusable. I use Homeassitant with deconz plugin.

![image](https://github.com/user-attachments/assets/35b14d38-690b-4567-9a04-7361607d01bd)

I am not able to change the layout of the windows so currently I just scroll the small window.

I waited for some time for an update to fix this (I have seen multiple people reporting this), however it is still broken.

Will there be any update for this? Also: I am not able to decide if this is the correct repo for this ticket, so I am sorry if this is not the correct one.

### Steps to reproduce the behavior

Use deCONZ inside HASS for few years, always upgrade to latest versions, this just happened.

### Expected behavior

Window layout inside VNC is usable.

### Environment

- Host system: Raspberry Pi
- Running method: Home Assistent deCONZ Add-on
- Firmware version: 26720700
- deCONZ version (not Home assistant Addon version!): 2.28.1
- Device: ConBee II
- Do you use an USB extension cable: no
- Is there any other USB or serial devices connected to the host system? If so: zwave stick

### deCONZ Logs

n/a

### Additional context

n/a

**Comment by bluemoehre** [comment] 2024-11-12 20:30
Actually that's not a bug. Looks like you accidentally moved the title bar of that window beyond the viewport or you switched the window to undecorated mode.

In decorated mode there is a dropdown with the window options in the upper left corner. You can also open it by pressing `ALT` + `SPACE` and click "Un/Decorate" or maybe another option like "Restore". 

![image](https://github.com/user-attachments/assets/6b8bebd5-a184-4a97-86b7-de8539f6f3a9)

**Comment by bluemoehre** [comment] 2024-11-12 20:47
I don't know how people get into such a situation, but again: it's not a bug in Deconz. 
That behavior is caused by the Window Manager of the Linux running the VNC host.

Another user was able to resize the window by using the hotkeys I mentioned above. 
In case it is not possible to use hotkeys in your browser, you should try a regular VNC client. I'm afraid that's the only way to get back to normal.

**Comment by bluemoehre** [comment] 2024-11-12 21:16
@raidenlal I am just trying to help you. I am not related to Dresden and their support in any way. I am just another user like you and I already had the issue myself after maximizing both.

Normally Deconz + VNC are two separated windows like here:

<img width="1153" src="https://github.com/user-attachments/assets/dd6f4633-ced0-4373-8cfc-d9722a9d7916">

**Comment by bluemoehre** [comment] 2024-11-12 21:49
I do not use the HASS integration myself. But if the browser based VNC client cannot send the required keystrokes to the remote desktop, the only chance is to use a client which can. (Or find out what changed some weeks ago.)

**Comment by Mimiix** [comment] 2024-11-12 21:57
> And I don't know how this half baked VNC in browser got approved for consumers to use with the hardware that was bought by them. But let's not get into things we do not know about.
> 
> Again: I do not care about Linux, VNC, window manager or anything else. I did not choose those, nor I manage them. Those are part of the supplied deconz software and should be supported accordingly.
> 
> So again, this IS deconz issue. Supplied software should not autodestruct nor be able to autodestruct with regular usage. This is extremely poor engineering on the Dresden elektronik side.
> 
> Moreso that after asking for help by the end user - NO SOLUTION is provided.

Hi as this issue is not as described in #5113  i'm closing this issue. This is an issue in the addon and not this repository as that vnc client is not selected nor added by this repository. The addon is maintained by home assistant.

Please seek support in the Ha repo.

Kind regards,

**Closed by Mimiix** 2024-11-12 21:57 UTC
Labels: Bug report
