### ISSUE TITLE
Aqara E1 Door & Window Sensor (MCCGQ14LM)

### ISSUE THREAD

**Issue by a-jey** [dresden-elektronik/deconz-rest-plugin#5403] opened 2021-10-20 19:24 UTC
## Device

- Product name: Aqara E1 MCCGQ14LM.
- Manufacturer: .
- Model identifier: lumi.magnet.acn001.
- Device type :  
  - Sensor

## Screenshots

Node
![grafik](https://user-images.githubusercontent.com/72740604/138157510-a78228c7-e1a1-4016-8b45-3bb6df359ec2.png)

Node Info
![grafik](https://user-images.githubusercontent.com/72740604/138157578-ec648e42-3aef-4a4e-8b90-73051789ddf6.png)

Basic
![grafik](https://user-images.githubusercontent.com/72740604/138157339-7c43f064-7e08-4992-b4b2-1de980081880.png)

Identify
![grafik](https://user-images.githubusercontent.com/72740604/138157412-cf132931-4631-4950-8cf5-5865040380b9.png)

Power Configuration
![grafik](https://user-images.githubusercontent.com/72740604/138157705-53562caa-1a59-4ddb-a71e-7ff058a517f9.png)

OTAU
![grafik](https://user-images.githubusercontent.com/72740604/138157769-ca89fe72-1694-43bd-9cc3-acd635d77fb1.png)

IAS Zone (1)
![grafik](https://user-images.githubusercontent.com/72740604/138159262-f00cdce6-a13f-4417-af1a-135862a831e7.png)

IAS Zone (2)
![grafik](https://user-images.githubusercontent.com/72740604/138157934-d8628b3a-7b3b-4ed5-855e-e58febcdb64d.png)

Package
![grafik](https://user-images.githubusercontent.com/72740604/138158263-cbba580c-60d9-4b86-b9a3-56e18b38c0e7.png)

![grafik](https://user-images.githubusercontent.com/72740604/138158316-8595c535-3a24-4cba-9f43-329fb893da01.png)

As you can see on the two IAS Zone screenshots: the basic function is working.
Manufacturer field is empty, but that's also on other LUMI Sensors which are already supported.

**Comment by SwoopX** [comment] 2021-10-29 19:59
> 
> 
> > My bad, change the status from draft to anything else. Eventually, you need to restart deconz
> 
> No, your json got bronze as status. Even if change it from draft to bronze on that mask and save the file, overwriting yours, on restarting the app it's set to draft again.

That very much sound like the editor takes an auto generated one. Have you stored my file where the editor suggests to save the file? And have you changed the file type to .json?

Just to be clear: with restarting the app, you meant deconz and not just the editor?

**Comment by a-jey** [comment] 2021-10-29 20:57
Just to go thge save way I uninstalled deCONZ, deleted the folders 
AppData\Local\dresden-elektronik\deCONZ
AppData\Local\deCONZ

Then I installed deCONZ again
generated the folder AppData\Local\dresden-elektronik\deCONZ\devices
(that's exactly the folder which the DDF editor showed in the save menu before)
placed the renamed lumi.magnet.acn001.json in that folder
started deCONZ
set DDF handling to normal
started pairing

The node appears and gets Manufacturer Name and Model Identifier from your File.

Maybe I wrote it a bit unclear before: if I then rightclick the node and select edit DDF the status shows as draft (maybe that's the normal appearance?).
If I open your DDF file in a text editor the status is set to bronze.

If I open the Phoscon App through deCONZ menu and go to sensor->connect new sensor->other
the sonsor got not registered, no matter if I just trigger or reset the sensor.
Checked in several browsers with the same result.

**Comment by SwoopX** [comment] 2021-11-01 20:42
I just tried it in a Windows 10 VM and for me it works. I've taken the file from the PR above and saved it to `AppData\Local\deCONZ\devices\xiaomi`. During sensor search, it got properly recognized and added.

**Comment by a-jey** [comment] 2021-11-01 23:01
> 
> 
> I just tried it in a Windows 10 VM and for me it works. I've taken the file from the PR above and saved it to `AppData\Local\deCONZ\devices\xiaomi`. During sensor search, it got properly recognized and added.

recognized and added in deCONZ or in Phoscon WebApp?

I got no problem to get it recognized in deCONZ but in Phoscon WebApp it also doesn't work if I use the save location you mentioned. Tried in different browsers.

**Comment by SwoopX** [comment] 2021-11-02 08:05
> recognized and added in deCONZ or in Phoscon WebApp?

Both, full service.

Are you running in normal mode?

![grafik](https://user-images.githubusercontent.com/4005212/139808462-6849fbe0-5203-4c4f-8910-50f17ec6c63c.png)

**Comment by a-jey** [comment] 2021-11-02 09:53
Yeah, I'm running it in normal mode.

**Comment by a-jey** [comment] 2021-11-02 10:34
Just tried it on a Windows 10 Laptop, the same result:
no problem in deCONZ, but doesn't find the sensor in Phoscon.

**Comment by Mimiix** [comment] 2021-11-02 11:31
How does it show in deCONZ?

**Comment by a-jey** [comment] 2021-11-02 12:26
> 
> 
> How does it show in deCONZ?

This is how it shows with 2 Sensors I tried:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403#issuecomment-956821785

**Comment by Mimiix** [comment] 2021-11-02 12:29
> > How does it show in deCONZ?
> 
> This is how it shows with 2 Sensors I tried: [#5403 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403#issuecomment-956821785)

Sorry, missed that comment.

**Comment by lboue** [comment] 2021-11-02 17:34
Hello,

My lumi.magnet.acn001 is recognized after a uploading the 'xiaomi_mccgq14lm_openclose_sensor.json' file to this directory:

Running config:

- deCONZ_ConBeeII_0x26720700.bin.GCF
- deCONZ plugin version 2.13.01 / 06/10/2021

C:\Users\%username%\AppData\Local\deCONZ\devices\xiaomi
![lumi magnet acn001-phoscon](https://user-images.githubusercontent.com/938089/139914901-6e5f614a-214d-4f8b-a50b-cc3cde7029e7.png)

**Comment by a-jey** [comment] 2021-11-02 19:52
> 
> 
> Hello,
> 
> My lumi.magnet.acn001 is recognized after a uploading the ['xiaomi_mccgq14lm_openclose_sensor.json](https://raw.githubusercontent.com/dresden-elektronik/deconz-rest-plugin/010938bf929362b535b0cf420e1e60796cf4f1f3/devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json)' file to this directory: C:\Users%username%\AppData\Local\deCONZ\devices\xiaomi
> 
> Running config:
> 
>     * deCONZ_ConBeeII_0x26720700.bin.GCF
> 
>     * deCONZ plugin version 2.13.01 / 06/10/2021
> 
> 
> ![lumi magnet acn001-phoscon](https://user-images.githubusercontent.com/938089/139914901-6e5f614a-214d-4f8b-a50b-cc3cde7029e7.png)

Yes yes yes!!!

With your linked file it immediately works like a charm.
Thanks a lot!

**Comment by a-jey** [comment] 2021-11-02 20:08
> 
> 
> I just tried it in a Windows 10 VM and for me it works. I've taken the file from the PR above and saved it to `AppData\Local\deCONZ\devices\xiaomi`. During sensor search, it got properly recognized and added.

The reason it didn't work on my side:
I missed the detail to use the new mentioned file.
I used the first one mentioned in this thread.

**Comment by febalci** [comment] 2021-11-05 15:24
Tried the 'xiaomi_mccgq14lm_openclose_sensor.json'  ddf file on ubuntu. It shows 'closed' all the time; not getting any status update from the sensor.

**Comment by Glennesink** [comment] 2021-11-05 18:47
Any way to add this to a Raspberry? Or wait for an update?

**Comment by febalci** [comment] 2021-11-06 12:49
Updated deconz firmware from 26660700 to 26720700. Phoscon  web app shows the details now, including the battery. So the sensor details page is just like the ones above. Good, however the sensor never updates the state; it is always 'open' whether i use the magnet to open or close it.

**Closed** 2021-11-06 14:30 UTC
Labels: Device Request

**Comment by Glennesink** [comment] 2021-11-06 14:32
> Any way to add this to a Raspberry? Or wait for an update?

Got it done with this instruction
https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

**Comment by mcormick** [comment] 2021-11-11 20:25
> [...] however the sensor never updates the state; it is always 'open' whether i use the magnet to open or close it.
Same here. The status is only updated when I manually press the little button.

**Comment by Myth5656** [comment] 2021-11-11 21:55
same for me:  I am running my ConBee2 on Rpi4
2.13.02 / 10.11.2021
26720700

I have 10 sensors here. I Managed to connect one. Update for open/close was diplayed instantly in Phoscon App. I added a second sensor. Sice I did this, values only gets refreshed when I push the "connect" button on the sensor.

**Comment by Mimiix** [comment] 2021-11-12 07:32
@Myth5656  How many sensors / routers do you have in total?

**Comment by Myth5656** [comment] 2021-11-12 08:19
> @Myth5656 How many sensors / routers do you have in total?

I have 10 sensors (just connected 2) and use one Gateway

Is there anything that I can provide to support fixing the bug?

**Comment by Mimiix** [comment] 2021-11-12 08:35
@Myth5656 To make sure it's not a user question, i suggest opening a forum post and we see from there. Or join the discord and check there. 

If you just have these sensors, and nothing else, we can't be really sure that its the device or not.

**Comment by Myth5656** [comment] 2021-11-12 10:34
> @Myth5656 To make sure it's not a user question, i suggest opening a forum post and we see from there.

@Mimiix 
Just did.. 
https://forum.phoscon.de/t/aqara-door-sensor-mccgq14lm-not-updating/865

**Comment by Myth5656** [comment] 2021-11-16 21:44
@Mimiix 
Did you follow the [Thread](https://forum.phoscon.de/t/aqara-door-sensor-mccgq14lm-not-updating/865)? Is it a "user problem" or is there a bug that can be fixed?

**Comment by Mimiix** [comment] 2021-11-17 07:40
I did.  Manuel mentioned something up with Xiaomi stuff pairing, but i am not sure if i understood correctly.

**Comment by SwoopX** [comment] 2021-11-17 09:08
The odd thing over here is that it worked and works flawlessly. However, there's obviously a couple of things to follow:

1. Make sure your running the latest Conbee/Raspbee firmware https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog
2. If you run 2.13.0 or 2.13.1, make sure you update to 2.13.2
3. If any of the above was not given **before** you paired the device(s), reset and re-pair while being up to date
4. Pair in normal/hybrid mode (tab control)
5. 5. If you followed 1-4, try restarting deconz

**Comment by KebapBoy** [comment] 2021-11-17 22:36
I just paired 10 sensors sucessfully and their state is updating seemlessly now when triggered.
I followed @SwoopX s guidelines and had to restart the deconz container otherwise the sensors were indeed shown in Phoscon but only with the correct state after I pressed the little button on a sensor.
Is this the intended behaviour to have to restart deconz or is this due to any bug?

**Comment by pipiche38** [comment] 2021-11-26 16:56
> @SwoopX do you know what binds/enrolling commands deconz uses to get this device working? For z2m Ive tried both writing the ias + enroll response and a bind of the ias cluster but no luck. I think this info could also be used for ZHA.

@Koenkk did you make it working on z2m ? getting similar request and problem with zigate

**Comment by Koenkk** [comment] 2021-11-26 21:11
@pipiche38 yes, coordinator needs to respond with the Xiaomi manufacturer code when the sensor sends a node descriptor to it. (requires a fw update)

**Comment by pipiche38** [comment] 2021-11-27 10:41
> @pipiche38 yes, coordinator needs to respond with the Xiaomi manufacturer code when the sensor sends a node descriptor to it. (requires a fw update)

Thanks very much for the hint, I'll check with the firmware guys. I beleive the challenge is to differentiate a Aqara Door Sensor to an other device doing the Node Desriptor request. Do you use the mac@ prefix for that ?

**Comment by Koenkk** [comment] 2021-11-28 17:35
@pipiche38 yes, you can find the changeset I did to the TI firmware here: https://github.com/Koenkk/Z-Stack-firmware/blob/f29b4525bb7bfdc28c91139d0926469bb5754ab9/coordinator/Z-Stack_3.x.0/firmware.patch#L533

**Comment by nukleuz80** [comment] 2021-12-09 15:26
Hey guys,

i got it to work now:

Setup:
RPI3B+ with Raspbian Buster Desktop (all updates incl.)
RaspBee I with actual firmware: **26400500**
DeConz: 2.13.02 / 10.11.2021

I copied the DDF in this folder: /home/pi/.local/share/dresden-elektronik/deConz/devices
and restarted deConz - now the sensor is changing from close to open...

Thanks to all of you guys!

**Comment by Zahnweh** [comment] 2021-12-14 15:28
Up to now 2.13.02 can only be installed manually on native Deconz. At least that's what I could find out. But what about the Deconz HA addon?

**Comment by nukleuz80** [comment] 2021-12-15 18:05
Can anyone tell me how to include more than one of these sensors pls? From today i‘m on 2.13.3 Beta and i can‘t pair the second sensor. Phoscon cant find it like the first one. In DeConz the Sensor is visible.

thanks for your help!

**Comment by ShlomiPorush** [comment] 2021-12-20 19:49
> > Up to now 2.13.02 can only be installed manually on native Deconz. At least that's what I could find out. But what about the Deconz HA addon?
> 
> We need to wait for the stable release and then for the update for the Home Assistant Addon because as far as I know the Addon is always based on a stable release.

The Home Assistant added updated today and I still can't add any of the Aqara sensors.

**Comment by Mimiix** [comment] 2021-12-20 19:51
@ShlomiPorush you can't add them or they don't show up?

**Comment by ShlomiPorush** [comment] 2021-12-20 19:56
> @ShlomiPorush you can't add them or they don't show up?

they don't show up in Phoscon only in deCONZ as an unidentified sensor. 
![1](https://user-images.githubusercontent.com/5992161/146824988-d7e92311-0be4-4ba7-b58d-ff526809c090.png)

**Comment by Mimiix** [comment] 2021-12-20 20:04
> > @ShlomiPorush you can't add them or they don't show up?
> 
> they don't show up in Phoscon only in deCONZ as an unidentified sensor. ![1](https://user-images.githubusercontent.com/5992161/146824988-d7e92311-0be4-4ba7-b58d-ff526809c090.png)
> 
> I do have other Aqara door sensors and no problem with them. just the sensor MCCGQ14LM

Did you re pair.?

**Comment by Mimiix** [comment] 2021-12-20 20:05
And to add to thar: are you on the latest firmware?

**Comment by ShlomiPorush** [comment] 2021-12-20 20:11
Yes. on version 2.13.04. did try to delete the node did not help. 

![conbee](https://user-images.githubusercontent.com/5992161/146826777-b67d3b18-4cf3-4f87-a167-08b495fa25c2.png)
![nodeinfo](https://user-images.githubusercontent.com/5992161/146826788-14bd73c1-2063-4747-b315-4550213b69b5.png)

**Comment by DoomiW** [comment] 2021-12-20 20:19
Just had the same issue one hour ago after updating deCONZ to 2.13.04
First I noticed I was also not on the latest Firmware (should be 26720700 for Conbee 2). After updating the Firmware I had to switch deCONZ to hybrid mode and delete the node which I tried to pair before. Another try following these steps worked fine - the node appears in deCONZ and also within Phoscon.

**Comment by ShlomiPorush** [comment] 2021-12-20 20:26
so my firmware 26660700 is not the latest? how do I go about updating it

**Comment by Zahnweh** [comment] 2021-12-20 20:29
> Just had the same issue one hour ago after updating deCONZ to 2.13.04
> 
> First I noticed I was also not on the latest Firmware (should be 26720700 for Conbee 2). After updating the Firmware I had to delete the node which I tried to pair before and switch deCONZ to hybrid mode (as SwoopX already guided [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403#issuecomment-971378048)). Another try following these steps worked fine - the node appears in deCONZ and also within Phoscon.
> 
> 

How do I enter hybrid mode?

**Comment by woytekbode** [comment] 2021-12-20 20:29
@ShlomiPorush Easiest for me is to just use Windows 10.

@DoomiW I have the same problem, device only shows in Deconz app. I have the latest Deconz and Conbee II versions. I'm using the HA addon on HA OS. Not sure how to switch Deconz to Hybrid mode, is that required for this device?

**Comment by DoomiW** [comment] 2021-12-20 20:30
> so my firmware 26660700 is not the latest? how do I go about updating it

Take a look on [those steps](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually) depending on your host system. The latest Firmware can be checked [here](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog)

**Comment by kanuni89** [comment] 2021-12-20 20:32
Sinze the DDF file is in Bronze status.. you should activate in Deconz to allow the states..
Go to: Panel -> Control -> on the DDF tab check the Bronze checkbox.. After that it worked for me

**Comment by DoomiW** [comment] 2021-12-20 20:33
> @ShlomiPorush Easiest for me is to just use Windows 10.
> 
> @DoomiW I have the same problem, device only shows in Deconz app. I have the latest Deconz and Conbee II versions. I'm using the HA addon on HA OS. Not sure how to switch Deconz to Hybrid mode, is that required for this device?

Same environment for me (and a long time to wait for stable deCONZ version :D ). At least for me it just worked in hybrid mode
deCONZ -> Panels -> Check control
On the bottom you'll see a new tab 'Control' where you can set the DDF Mode to hybrid

**Comment by woytekbode** [comment] 2021-12-20 20:38
@kanuni89 HERO! Works like a charm now! Can see it in Phoscon too, very snappy. @DoomiW thanks!

**Comment by oli737** [comment] 2021-12-20 20:41
I see a openclose123 in deconz but not in Phoscon. What i am doing wrong?

**Comment by Mimiix** [comment] 2021-12-20 20:44
@oli737 phoscon probably didn't add support yet. It should show in rest api / home assistant.

**Comment by kanuni89** [comment] 2021-12-20 20:45
> I see a openclose123 in deconz but not in Phoscon. What i am doing wrong?

have you put the DDF file into the data folder ? If yes, try to delete the node and restart the deconz, maybe after that it will work...

**Comment by kanuni89** [comment] 2021-12-20 20:46
> @oli737 phoscon probably didn't add support yet. It should show in rest api / home assistant.

for me it works... i see it in deconz and phoscon

**Comment by DoomiW** [comment] 2021-12-20 20:46
openclose123 sounds normally good as i had the same before manually renaming it via Phoscon. Could be worth restarting deCONZ

**Comment by oli737** [comment] 2021-12-20 20:46
i we try again pair the sensor

**Comment by oli737** [comment] 2021-12-20 20:48
Thanks guys, it works lika a charm.

**Comment by ShlomiPorush** [comment] 2021-12-20 21:42
So I updated deCONZ to firmware 26720700, in deCONZ I can see the type of the device "Open Close" but in Phoscon the status of the sensor is Not reachable.

![aqara](https://user-images.githubusercontent.com/5992161/146835946-bce3e52f-0f76-4fcd-a6c0-b15f27f607d5.png)
![app](https://user-images.githubusercontent.com/5992161/146835961-c44c5619-aa48-43bd-b96b-84275e00ec9f.PNG)

**Comment by dfrommi** [comment] 2021-12-20 21:47
I have the same problem as @ShlomiPorush 

I have 2 of those Aqara devices and both are behaving strangely... the blue light flashes continuously with a certain pattern:
flash -> 2 sec pause -> flash -> 2 sec pause -> flash flash flash -> 2 sec pause .... and again from the beginning. 
Is that normal? Or is this some kind of reset loop?
Already removed the battery for a while, put it back in, same again.

**Comment by a-jey** [comment] 2021-12-20 22:16
Works like a charm now!

Thank you all for your work :-)

**Comment by a-jey** [comment] 2021-12-20 22:17
> So I updated deCONZ to firmware 26720700, in deCONZ I can see the type of the device "Open Close" but in Phoscon the status of the sensor is Not reachable.
> 
> ![aqara](https://user-images.githubusercontent.com/5992161/146835946-bce3e52f-0f76-4fcd-a6c0-b15f27f607d5.png) ![app](https://user-images.githubusercontent.com/5992161/146835961-c44c5619-aa48-43bd-b96b-84275e00ec9f.PNG)

You changed the mode in deCONZ to Hybrid?

**Comment by ShlomiPorush** [comment] 2021-12-20 22:18
> You changed the mode in deCONZ to Hybrid?

Yes. did not help

**Comment by a-jey** [comment] 2021-12-20 23:40
> > You changed the mode in deCONZ to Hybrid?
> 
> Yes. did not help

Deleted the Sensor?
Sent CtrlAltDel in deCONZ and then add sensor again?

**Comment by ShlomiPorush** [comment] 2021-12-20 23:46
> Deleted the Sensor? Sent CtrlAltDel in deCONZ and then add sensor again?

Yes. did it - not lock. 
Meanwhile after waiting for about an hour more information are updated in Phoscon. But the status is really not updating 
![1](https://user-images.githubusercontent.com/5992161/146847354-c51a49a6-192b-4bc8-9dbb-1062b61afe14.png)

**Comment by Mimiix** [comment] 2021-12-21 04:48
> > Deleted the Sensor? Sent CtrlAltDel in deCONZ and then add sensor again?
> 
> Yes. did it - not lock. Meanwhile after waiting for about an hour more information are updated in Phoscon. But the status is really not updating ![1](https://user-images.githubusercontent.com/5992161/146847354-c51a49a6-192b-4bc8-9dbb-1062b61afe14.png)

Ah this tells me that it now behaves like a xiaomi device.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by Zahnweh** [comment] 2021-12-21 07:51
I finally got them paired. Here's how I did it: https://community.home-assistant.io/t/new-aqara-door-sensors-connection-problem-with-zigbee/351836/27?u=zahnweh

**Comment by OlivenBurrito** [comment] 2021-12-21 14:48
I also have been struggling unsuccessfully to get this working, for quite a while now.

deCONZ 2.13.02 in Docker on a Raspberry PI 4 ( buster); Conbee-II w/ FW26720700

The sensor paring is easy and I can see instant state updates to Alarm1 field in the IAS Zone info. But these state changes are not passed on to neither Phoscon or the deconz adapter instance within Iobroker.
They are communicated however within a short time period (a couple of seconds) after I repeatedly short-press the reset button of the sensor.

This is becoming increasingly frustrating... :-|

**Comment by Mimiix** [comment] 2021-12-21 14:53
@OlivenBurrito Please make sure to run the latest version of deconz. Perhaps this can help : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by OlivenBurrito** [comment] 2021-12-21 15:25
Nice. Just updated the deconz image and now all bindings are lost ...

**Comment by pignonson** [comment] 2021-12-28 17:46
Hi all,

I'm  using this stick for add deconz software on my jeedom rpi.
As all of you, I have same issue for discover and add new Aqara windows sensor.

I recently updated conbee II firmware and phoscon version:

version = 2.13.04 / 18/12/2021
Firmware = 26720700

Your screenshots with some box and links are not available for me, and I don't understand how to add specific "DDF" for new aqara.

thank you all
JLB

**Comment by Zahnweh** [comment] 2021-12-28 19:03
You may find the solution here:

https://community.home-assistant.io/t/new-aqara-door-sensors-connection-problem-with-zigbee/351836/27?u=zahnweh

**Comment by Markus030789** [comment] 2021-12-28 19:44
> You may find the solution here:
> 
> https://community.home-assistant.io/t/new-aqara-door-sensors-connection-problem-with-zigbee/351836/27?u=zahnweh

I second this! I also updated both deconz and conbee2 to the latest firmware three days ago and the mentioned manual did finally the Trick for two sensors. Thanks for sharing this!

**Comment by pignonson** [comment] 2021-12-28 20:16
Thank you Zahnweh and Markus for had shared this link.

But in this case, i need to use an os windows for perform this step by step, isn’t it? GUI you shared seems to be deconz software? And it’s not available for my buster which running jeedom. I also have a personnal apple mac os, but this software is also not available.

If you know some CLI to suggest to me, it should be easier for me.

But again, thank you for this link !!! I have a solution now… ;-)

**Comment by pixou80** [comment] 2021-12-28 20:16
> You may find the solution here:
> 
> https://community.home-assistant.io/t/new-aqara-door-sensors-connection-problem-with-zigbee/351836/27?u=zahnweh

unfortunately for me this solution doesn't work (trying to select bronze/gold or silver/gold and hybrid)
3 "OpenClose" devices are created on deconz but in phoscon the status stay the same

**Comment by Zahnweh** [comment] 2021-12-28 22:50
You will have to delete the orphaned nodes in Deconz first. Then try to pair them again.

**Comment by pixou80** [comment] 2021-12-28 23:01
What do you mean by delete the orphaned nodes ? If it's to remove the openclose devices created on deconz it's already done but the problem stay the same at the next pairing

**Comment by Zahnweh** [comment] 2021-12-28 23:56
Well, have you tried to open/close them while they're shown as unreachable in Phoscon? Mine switched to reachable and changed status once I did this. 

And are you really sure that you're using the latest version of Deconz and the Conbee stick has the latest firmware?

**Comment by pixou80** [comment] 2021-12-29 00:07
Yes i've tried to open close Them and nothing happen.
The first one has already worked but after deconz reboot due to the 2 other devices unreachabled, the first device became unreachable
Like the 2 others...

**Comment by Zahnweh** [comment] 2021-12-29 06:41
I have no idea. If I was in your place I would delete all three, make sure everything including HA is up to date and try again from the beginning.

**Comment by pixou80** [comment] 2021-12-29 08:28
I've no HA, i use jeedom on a rpi 4. All tests of the new devices are made on windows 10 on my computer.
I will try with an empty tree without using my phoscon save.
Thank you for your help ;)

**Comment by Zahnweh** [comment] 2021-12-29 10:06
Oh, I was assuming you are on HA. Good luck to you.

**Comment by pignonson** [comment] 2021-12-29 10:15
Hi,

First of all, thank you for have shared the link on community.home-assistant.io. Now I show Aqara E1 as new node on deConz workspace.
But as pixou80, on phoscon webapp, my 3* sensors always still closed and not reachable...

What means "HA" in your conversation?
Pixou80, did you found a solution with a complete reset of your tree?

Thanks

**Comment by fnittoli** [comment] 2021-12-29 10:21
> Hi,
> 
> First of all, thank you for have shared the link on community.home-assistant.io. Now I show Aqara E1 as new node on deConz workspace. But as pixou80, on phoscon webapp, my 3* sensors always still closed and not reachable...
> 
> What means "HA" in your conversation? Pixou80, did you found a solution with a complete reset of your tree?
> 
> Thanks

I had the same problem, check the firmaware version of your conbee, should be 26720700, otherwise it won't work

**Comment by pignonson** [comment] 2021-12-29 10:23
I already update conbee II and firmware.

![image](https://user-images.githubusercontent.com/78655945/147652305-9f9264bb-e50e-4a31-82d9-8979abb88347.png)

any other idea?

**Comment by Zahnweh** [comment] 2021-12-29 10:36
> What means "HA" in your conversation?

HA means Home Assistant.

**Comment by pignonson** [comment] 2021-12-29 11:39
Hummm.... Just a questoin regarding your device.
When magnet approach of aqara, does it blink blue?
Actually, in my case, MCCGQ14LM doesn't blink blue when I removed the magnet. I presume blue led is like a sending status?
Perhaps, it's for that I still have no RX state...

thanks

**Comment by Zahnweh** [comment] 2021-12-29 11:56
The LED does exactly nothing when opening/closing them.

**Comment by pignonson** [comment] 2021-12-29 16:32
crap of sensors !!!

I don't want to give up. But truly, I think I have tested all propositions of solutions I read...

Conbee II stick have lastest firmware. As well as phoscon software. With DeconZ software on my PC, I can added them. But, on phoscon, it still be like unreachable...
I also perform process : "Xiaomi: Lost devices or functional issues"

![image](https://user-images.githubusercontent.com/78655945/147683462-8ff7552f-64af-48f7-955e-6fddd00ee4ed.png)
![image](https://user-images.githubusercontent.com/78655945/147683516-d968c868-97c5-42b4-8fc0-89cac5052fe8.png)
![image](https://user-images.githubusercontent.com/78655945/147683560-6be871e0-1657-443c-b491-dd7e75e2aabf.png)


Is someone could paste here a screenshot of "Lumi Specific cluster information"? I would like to compare...

Thank you all

**Comment by Zahnweh** [comment] 2021-12-29 17:29
I can't see you have the control tab open and activated hybrid mode. Did you follow these instructions strictly? https://community.home-assistant.io/t/new-aqara-door-sensors-connection-problem-with-zigbee/351836/27?u=zahnweh

**Comment by pignonson** [comment] 2021-12-29 17:37
Yes I did. Strictly as you mentionned zahnweh.
I also tryied to copy/paste specific json file in to different folder (AppData\Local\dresden-elektronik\deCONZ and also in C:\Program Files (x86)\deCONZ\devices\xiaomi)
I tryied to reboot in order to rescan devices with new json file.

I correctly saw "alarm1" tick and untick when I approach magnet... But, I didn't see this state on phoscon side (and still less in jeedom)

Do you have any new proposition? Could you share your in use json file for this device please? Just to compare...

Thanks

**Comment by pignonson** [comment] 2021-12-29 21:00
ok...

For an uncomprehensible reason, my setup work fine now ;-)
After so many reboot, so many delete and new add. Perhaps, I think it's the last global reinit' of phoscon app', and reload a previous backup which fix my issue...

Anyway... dont' forgot the goal : new aqara MCCGQ14LM works fine with latest COnbee II et latest phoscon firmware. 

Stay convinced... If you have same issue

**Comment by pixou80** [comment] 2021-12-29 21:06
Unfortunately i've already made like you pignonson and the result stay the same for me...
Tomorrow i will reinstall deconz on windows to check if it's change something

**Comment by pignonson** [comment] 2021-12-29 21:12
Hello pixou,

did you have already tried to "play" with json file as mentioned upper on this page? I'm not sure, but it's possible that's the rootcause (because, it "failed in works" with no comprehesion for me. After another reboot...)

Good luck. Feel free to contact me if you need some screenshot comparaison.

A+

**Comment by pixou80** [comment] 2021-12-29 21:19
Thank you i will try with the json file tomorrow.

**Comment by Zahnweh** [comment] 2021-12-29 23:42
Just for the record I have no clue what this is all about with the json file. Plus I don‘t use Windows. But great to hear it‘s finally working for you, pignonson.

Perhaps the complications you‘re facing are particularly concerning jeedom. Maybe you should open an issue for this in the right place.

**Comment by pignonson** [comment] 2021-12-30 07:14
Thank you Zahnweb, thank you for your help and your work !!!
The most important, as you said, it’s that work fine for me now ;-)
Thanks

**Comment by pixou80** [comment] 2021-12-30 14:41
so i've reinstall the deconz and 5 devices are ok.
I've a problem with the last. the light never go in blue so i've remove the battery and next replace them. Now the led blinck all the time. 3times long and 3times quickly and again and again. device broken or can i fix it ?

**Comment by dfrommi** [comment] 2021-12-30 16:06
@pixou80 Same problem here, as I described earlier. 

For me the pattern is:
flash -> 2 sec pause -> flash -> 2 sec pause -> flash flash flash -> 2 sec pause .... and again from the beginning.

3 out of my 10 devices do that and as the rest is working fine, I concluded those 3 are broken. 

I hope very much that I'm wrong, but I tried everything.

**Comment by pixou80** [comment] 2021-12-30 16:17
buyed on aliexpress, if the sensor is broken i think i can forgot the refund (buyed on november)

**Comment by pignonson** [comment] 2021-12-30 18:29
> so i've reinstall the deconz and 5 devices are ok.
> I've a problem with the last. the light never go in blue so i've remove the battery and next replace them. Now the light blink all the time. 3times long and 3times quickly and again and again. device broken or can i fix it ?

Sounds good… congrat’s for the 5´st one !!! Sorry for the last one.

**Comment by pixou80** [comment] 2022-01-06 19:59
For information the after sales service of aqara said me that the sensor is defective.
The aliexpress seller has refund me (i've shared the answer from aqara with him)

**Comment by nukleuz80** [comment] 2022-02-02 12:17
After updating to 2.13.4 Beta i can't get the sensor working. 

I see it in the gui but not in Phoscon.

Any ideas?

Thanks

**Comment by RickyTR** [comment] 2022-04-28 16:09
I recently bought a couple of these sensors. I can pair the sensor with deconz but it seems that it cannot read battery values nor temperature values. Any suggestion?

**Comment by ygerlovin** [comment] 2022-06-25 13:18
Hi,
Could someone please provide a sniff that shows the correct pairing?
I'm trying to add this device to smarthings hub.
Thanks
