### ISSUE TITLE
Hue dimmer switch not working

### ISSUE THREAD

**Issue by Barsonax** [dresden-elektronik/deconz-rest-plugin#5630] opened 2022-01-02 06:58 UTC
## Describe the bug
I used the switch editor to setup some buttons but when I press them the hue lights do nothing:

I do see the button flashing in phoscon but the lights don't do anything. If I control them from phoscon or hue essentials then the lights do work properly.

## Steps to reproduce the behavior
  If the problem is reproducable, list the steps here:

  1. Create a new group
  2. Add lights
  3. Setup a switch with the switch editor
  4. Click button
  5. Observe the lights don't do anything

## Expected behavior
Lights should be controlled by the dimmer switch

## Screenshots
![image](https://user-images.githubusercontent.com/19387223/147868494-10264971-bf17-4239-8f6f-bde7e736ae80.png)
![image](https://user-images.githubusercontent.com/19387223/147868518-c2c56e35-0a97-486e-8a64-5036863326fb.png)
![image](https://user-images.githubusercontent.com/19387223/147868667-1bc77b87-3a64-4678-abcd-95564597889e.png)

## Environment
![image](https://user-images.githubusercontent.com/19387223/147868588-3e0ca937-f880-40e6-aefd-3230eb32f49d.png)

 - Host system: PC
 - Running method: Windows
 - Firmware version: (26xxyy00)
 - deCONZ version: 2.13.04 / 12/18/2021
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? wired mouse/keyboard

## deCONZ Logs
Clicked the dimmer switch a couple of times and this shows in the logs:
```
07:56:20:514 APS-DATA.confirm id: 198, status: 0x00 SUCCESS
07:56:20:514 APS-DATA.confirm request id: 198 -> erase from queue
07:56:20:556 APS-DATA.indication srcAddr: 0xee4b, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -26
07:56:20:556 APS-DATA.request id: 198 erase from queue
07:56:20:556 ZCL got data for node=0xEE4B, cl=0x0006, at=0x0000, status=0x00, type=0x10
07:56:20:671 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -42
07:56:20:718 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -43
07:56:20:718 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:20:727 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:20:850 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -43
07:56:20:850 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:20:856 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:20:896 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -44
07:56:20:927 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -44
07:56:20:927 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:20:953 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:057 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -44
07:56:21:057 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:21:073 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:21:094 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -44
07:56:21:125 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -44
07:56:21:125 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:21:138 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:220 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:220 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:21:237 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:21:257 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -44
07:56:21:289 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:289 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:21:305 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:389 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:389 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:21:407 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:21:427 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -45
07:56:21:473 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -44
07:56:21:473 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:21:486 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:605 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:605 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:21:614 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:21:658 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:658 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:21:671 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:708 APS-DATA.request id: 220, addrmode: 0x03, addr: 0x00178801098cbde7, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
07:56:21:718 APS-DATA.confirm id: 220, status: 0x00 SUCCESS
07:56:21:718 APS-DATA.confirm request id: 220 -> erase from queue
07:56:21:735 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:735 APS-DATA.request id: 220 erase from queue
07:56:21:735 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:21:752 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:758 APS-DATA.indication srcAddr: 0xc197, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -45
07:56:21:758 ZCL got data for node=0xC197, cl=0x0006, at=0x0000, status=0x00, type=0x10
07:56:21:835 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:835 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:21:852 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:921 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:21:921 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:21:931 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:21:974 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -45
07:56:22:021 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:22:021 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:22:026 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:121 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:121 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:22:126 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:22:205 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:22:205 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:22:219 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:290 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:290 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:22:297 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:374 Mgmt_Lqi_req zdpSeq: 28 to 0x00212EFFFF07D5D1 start index 0
07:56:22:374 APS-DATA.request id: 234, addrmode: 0x03, addr: 0x00212effff07d5d1, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
07:56:22:378 APS-DATA.confirm id: 234, status: 0x00 SUCCESS
07:56:22:378 APS-DATA.confirm request id: 234 -> confirmed, timeout 726029
07:56:22:380 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 71, rssi: -81
07:56:22:380 APS-DATA.indication request id: 234 -> finished
07:56:22:380 APS-DATA.request id: 234 erase from queue
07:56:22:380 ZDP status = 0x00 -> SUCCESS
07:56:22:380 ZDP Mgmt_Lqi_rsp zdpSeq: 28 from 0x00212EFFFF07D5D1 total: 2, startIndex: 0, listCount: 2
07:56:22:380     * neighbor: 0x00178801098C7611 (0xEE4B), LQI: 255, relation: 0x02, depth: 1, rxOnWHenIdle: 1
07:56:22:380     * neighbor: 0x00178801098CBDE7 (0xC197), LQI: 252, relation: 0x02, depth: 1, rxOnWHenIdle: 1
07:56:22:385 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:385 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:22:397 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:459 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:459 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:22:476 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:510 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -46
07:56:22:542 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:542 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:22:561 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:626 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:626 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:22:642 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:659 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -26
07:56:22:721 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:721 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:22:740 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:806 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -46
07:56:22:806 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:22:818 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:906 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -45
07:56:22:906 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:22:923 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:22:924 APS-DATA.request id: 246, addrmode: 0x03, addr: 0x00178801098c7611, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
07:56:22:940 APS-DATA.confirm id: 246, status: 0x00 SUCCESS
07:56:22:940 APS-DATA.confirm request id: 246 -> erase from queue
07:56:22:941 aps request id: 246 finished, erase from queue
07:56:22:991 APS-DATA.indication srcAddr: 0xee4b, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -26
07:56:22:991 ZCL got data for node=0xEE4B, cl=0x0006, at=0x0000, status=0x00, type=0x10
07:56:22:998 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -44
07:56:22:998 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:23:006 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:075 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -43
07:56:23:091 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:23:096 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:159 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -42
07:56:23:159 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:23:175 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:306 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:23:306 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:23:314 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:360 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:23:360 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:23:365 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:398 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -40
07:56:23:429 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:23:429 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:23:448 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:539 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:23:539 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:23:557 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:23:609 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:23:609 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:23:615 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:23:635 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -39
07:56:23:907 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -26
07:56:23:976 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -40
07:56:24:039 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:24:039 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:24:049 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 4
07:56:24:123 APS-DATA.request id: 11, addrmode: 0x03, addr: 0x00178801098cbde7, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
07:56:24:134 APS-DATA.confirm id: 11, status: 0x00 SUCCESS
07:56:24:134 APS-DATA.confirm request id: 11 -> erase from queue
07:56:24:176 aps request id: 11 finished, erase from queue
07:56:24:192 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -39
07:56:24:192 APS-DATA.indication srcAddr: 0xc197, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -39
07:56:24:192 ZCL got data for node=0xC197, cl=0x0006, at=0x0000, status=0x00, type=0x10
07:56:24:234 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:24:234 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:24:242 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:24:510 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:24:510 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:24:523 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 2
07:56:24:756 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -26
07:56:24:893 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:24:893 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:24:903 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:24:993 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:24:993 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:25:004 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:25:093 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:25:093 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:25:104 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:25:193 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:25:193 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:25:207 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:25:211 Mgmt_Lqi_req zdpSeq: 29 to 0x00178801098CBDE7 start index 0
07:56:25:212 APS-DATA.request id: 25, addrmode: 0x03, addr: 0x00178801098cbde7, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
07:56:25:223 APS-DATA.confirm id: 25, status: 0x00 SUCCESS
07:56:25:223 APS-DATA.confirm request id: 25 -> confirmed, timeout 728867
07:56:25:278 APS-DATA.indication srcAddr: 0xc197, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -40
07:56:25:278 APS-DATA.indication request id: 25 -> finished
07:56:25:278 APS-DATA.request id: 25 erase from queue
07:56:25:278 ZDP status = 0x00 -> SUCCESS
07:56:25:278 ZDP Mgmt_Lqi_rsp zdpSeq: 29 from 0x00178801098CBDE7 total: 3, startIndex: 0, listCount: 3
07:56:25:278     * neighbor: 0x00212EFFFF07D5D1 (0x0000), LQI: 222, relation: 0x02, depth: 0, rxOnWHenIdle: 1
07:56:25:278     * neighbor: 0x00178801098C7611 (0xEE4B), LQI: 230, relation: 0x02, depth: 15, rxOnWHenIdle: 1
07:56:25:278     * neighbor: 0x001788010872596F (0x091B), LQI: 241, relation: 0x01, depth: 2, rxOnWHenIdle: 0
07:56:25:320 APS-DATA.request id: 27, addrmode: 0x03, addr: 0x00178801098c7611, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
07:56:25:331 APS-DATA.confirm id: 27, status: 0x00 SUCCESS
07:56:25:331 APS-DATA.confirm request id: 27 -> erase from queue
07:56:25:363 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -40
07:56:25:363 APS-DATA.request id: 27 erase from queue
07:56:25:363 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -40
07:56:25:378 APS-DATA.indication srcAddr: 0xee4b, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -26
07:56:25:378 ZCL got data for node=0xEE4B, cl=0x0006, at=0x0000, status=0x00, type=0x10
07:56:25:402 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:25:402 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:25:413 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:25:527 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:25:527 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:25:541 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:25:642 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -39
07:56:25:642 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:25:648 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:25:710 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:25:710 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:25:728 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:25:863 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -40
07:56:25:863 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1000
07:56:25:873 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 0
07:56:25:984 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -42
07:56:25:984 expression: Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(4) --> 1002
07:56:26:004 expression: Item.val = ZclFrame.at(6) | ZclFrame.at(7) << 8 --> 1
07:56:26:290 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -40
07:56:26:511 APS-DATA.indication srcAddr: 0x091b, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -42
07:56:26:527 APS-DATA.request id: 43, addrmode: 0x03, addr: 0x00178801098cbde7, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
07:56:26:540 APS-DATA.confirm id: 43, status: 0x00 SUCCESS
07:56:26:540 APS-DATA.confirm request id: 43 -> erase from queue
07:56:26:589 APS-DATA.indication srcAddr: 0xc197, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -42
07:56:26:589 APS-DATA.request id: 43 erase from queue
07:56:26:589 ZCL got data for node=0xC197, cl=0x0006, at=0x0000, status=0x00, type=0x10
07:56:27:458 Mgmt_Lqi_req zdpSeq: 30 to 0x00178801098C7611 start index 0
07:56:27:458 APS-DATA.request id: 50, addrmode: 0x03, addr: 0x00178801098c7611, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
07:56:27:470 APS-DATA.confirm id: 50, status: 0x00 SUCCESS
07:56:27:470 APS-DATA.confirm request id: 50 -> confirmed, timeout 731113
07:56:27:520 APS-DATA.indication srcAddr: 0xee4b, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -26
07:56:27:520 APS-DATA.indication request id: 50 -> finished
07:56:27:520 APS-DATA.request id: 50 erase from queue
07:56:27:520 ZDP status = 0x00 -> SUCCESS
07:56:27:520 ZDP Mgmt_Lqi_rsp zdpSeq: 30 from 0x00178801098C7611 total: 2, startIndex: 0, listCount: 2
07:56:27:520     * neighbor: 0x00212EFFFF07D5D1 (0x0000), LQI: 255, relation: 0x02, depth: 0, rxOnWHenIdle: 1
07:56:27:520     * neighbor: 0x00178801098CBDE7 (0xC197), LQI: 218, relation: 0x02, depth: 15, rxOnWHenIdle: 1
```

**Comment by Mimiix** [comment] 2022-01-03 07:59
Hi. 

As this is not a bug as described in #5113 i am closing this issue.

To add to this: Check if you are running "silver" DDf's. You can check that by clicking Panel > Control and see if Silver is checked. If it's checked, uncheck it and reboot.

If this is not the case, feel free to open a post on the Forums.

Kind regards,

**Closed by Mimiix** 2022-01-03 07:59 UTC
Labels: Bug report
