### ISSUE TITLE
Don't manage to get direct bindings to work

### ISSUE THREAD

**Issue by ThorstenDtk** [dresden-elektronik/deconz-rest-plugin#6619] opened 2022-12-19 18:29 UTC
I manage ~50 hue lamps with DeCONZ (on a raspberry). Most of them are controlled through iOBroker via Javascript from Homematic switches, some by hue dimmer switches and IKEA remotes. Everything is running fine for a couple of years now as long as the Raspis with iOBroker and DeCONZ are running. 
**But I want to be able to control at least a couple of lamps on each floor even if DeCONZ is down.** The idea is to create direct bindings between lamps/groups of lamps and a couple of additional zigbee remotes. 

This is how I tried:

Dagged and dropped the on/off node of the remote on source. Dragged and dropped the on/off node of the light to destination:

![grafik](https://user-images.githubusercontent.com/35042154/208492977-2b4244f6-9cb5-4063-9b10-7baca9e04ca8.png)

Result is success, but when I press the on/off buttons of the remote nothing happens.
Created additional binding for level control, problem persists. Even after waiting for an hour.

Then I removed the bindings and created a binding between the same remote and the group containing the light:

![grafik](https://user-images.githubusercontent.com/35042154/208493986-9c074cfa-5338-41dd-b8ef-bb5ebe024ed6.png)

![grafik](https://user-images.githubusercontent.com/35042154/208494245-e300d8e7-a8c4-4c49-861a-4fd0a32da601.png)

But nothing happens when using the remote. I tried the same with a hue remote, but that also doesn't work.

Is this supposed to work? And if yes - what am I doing wrong?

**Comment by Mimiix** [comment] 2022-12-19 19:28
Hi,

As this is not a bug report as described in #5113 i am closing this issue 

Please ask the question on the forums.

Kind regards

**Closed by Mimiix** 2022-12-19 19:28 UTC

**Comment by ThorstenDtk** [comment] 2022-12-19 19:41
> Hi,
> 
> As this is not a bug report as described in #5113 i am closing this issue
> 
> Please ask the question on the forums.
> 
> Kind regards

If it's only for bugs and device requests then you should remove the following link:

![grafik](https://user-images.githubusercontent.com/35042154/208506646-129ced58-341b-4d46-91f0-12018b19a19b.png)

**Comment by Mimiix** [comment] 2022-12-19 19:44
I wish we could.

**Comment by Mimiix** [comment] 2022-12-19 19:49
I just found out we could! Thanks for the heads-up :)
