### ISSUE TITLE
Please create apt repo for deconz on Debian bullseye

### ISSUE THREAD

**Issue by KennethLavrsen** [dresden-elektronik/deconz-rest-plugin#5280] opened 2021-09-05 11:55 UTC
## Describe the bug

Please create a debian repo for the Bullseye. You currently only support buster.

This was raised already on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5040 but the way too aggresively configured stale bot closed it and though people keep on posting metoo responses the item remains closed probably because developers do not look at closed bugs. So here is a fresh new one.

## Steps to reproduce the behavior

I expect to be able to put this in my /etc/apt/sources.list.d/deconz.list

```
deb [arch=amd64] http://phoscon.de/apt/deconz bullseye-beta main
deb [arch=amd64] http://phoscon.de/apt/deconz bullseye main

```

I cannot safely upgrade my Debian from Buster to Bullseye as long as I have this hanging. 

For those running Home Assistant supervised and running Deconz from apt and not in the error-prone addons this is a significant problem as HA has announced the buster deprecated and people end up with unsupported installation if they do not upgrade Debian

I personally do not do this but I run other software on the Debian and I'd like to be able to run the others up to date. We cannot have the signifcant software lagging behind. It is probably trivial to do this for Bullseye since dependencies for Deconz do not seem to be very exotic.

## Expected behavior

See above

## Screenshots

N/A

## Environment

 - Host system: PC
 - Running method: Debian
 - Firmware version: all
 - deCONZ version: latest, any
 - Device: any
 - Do you use an USB extension cable: n/a
 - Is there any other USB or serial devices connected to the host system? If so: Which? n/a

## deCONZ Logs

n/a

**Comment by Mimiix** [comment] 2021-09-05 13:43
Hi,

As mentioned in #5113 all feature requests and user questions are moved to the forums.

As this is not a bug report, I'll close this issue. Please use the forum for these requests :)

Closing.

**Closed by Mimiix** 2021-09-05 13:43 UTC
Labels: Bug report
