### ISSUE TITLE
On/off button of Ikea remote (5 buttons) isn't working

### ISSUE THREAD

**Issue by ChristianPorsche** [dresden-elektronik/deconz-rest-plugin#5125] opened 2021-07-15 15:57 UTC
## Describe the bug
 Whatever I try, I can't connect an action to the on/off button on the remote. Light toggle, brightness up whatever isn't working. I can see a responsive within deconz that the signal is received of the remote. Any clue what causes this problem?

Brightness up, brightness down, and both buttons left and right are working.

## Steps to reproduce the behavior
  
  1. Connect a remote (5 buttons)
  2. Connect the on/off button to 'toggle' 

## Expected behavior

 The light should go on and off, on the click on the on/off button of the remote

## Screenshots

  No screenshot with more information

## Environment

 - Host system: (Raspberry Pi 4)
 - Running method: (Raspbian)
 - Firmware version: (26660700)
 - deCONZ version: (2.11.05)
 - Device: (ConBee II )
 - Do you use an USB extension cable: (Yes) 
 - Is there any other USB or serial devices connected to the host system? (No)

## deCONZ Logs

Not sure how to get logs out of Deconz, but if it really is necessary, I will find those to solve the problem.

## Additional context

  No.

**Comment by ChristianPorsche** [comment] 2021-07-15 16:02
I see on this page that there is a fix release in the beta software. https://phoscon.de/en/changelog/

How could I install the beta?

**Comment by Smanar** [comment] 2021-07-15 16:10
On a Raspberry pi, if you have used the package method (you need to change the branch, I think you are on the stable one,  https://www.phoscon.de/en/conbee2/install#raspbian)
`sudo apt install deconz`

Else just instal the file http://deconz.dresden-elektronik.de/raspbian/beta/

**Comment by moschnetwork** [comment] 2021-07-17 18:09
hey guys,

thank you for this great work.

I got a problem with my Ikea Tradfri (5 Buttons / Round) Remotes:

Every time if I press the power button for more than 3 seconds (1001), a short press (1002) is no longer possible.
The same applies to the pairing of the remote controls in the Phoscon app. Here I see that the Ikea Remote has been recognized, in the next step I should press the power button for 10 seconds ... After pairing, however, the short press 1001 is no longer recognized.

However, if I omit the 10 seconds press during the Phoscon app pairing process and close the popup window, but only then does the short press 1002 work. As soon as the long power button is pressed (1001) then the short press (1002) unfortunately no longer works.

readjust the process with all my 20 Ikea-Tradfri Remote to Control Sonos. Thank you guys

**Comment by moschnetwork** [comment] 2021-07-17 18:19
update to beta and now the 1001 Bug is fixed. Thank you guys ;)

**Comment by ChristianPorsche** [comment] 2021-07-17 18:31
> update to beta and now the 1001 Bug is fixed. Thank you guys ;)

@moschnetwork how did you installed the beta?

**Comment by SwoopX** [comment] 2021-07-17 18:34
Duplicate of #4900 and resolved.

**Closed by SwoopX** 2021-07-17 18:34 UTC
Labels: Bug report
