### ISSUE TITLE
Cannot rename Tuya Multipurpose device _TZ3000_yd2e749y in Phoscon or Deconz

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#6247] opened 2022-08-08 00:02 UTC
## Describe the bug
Cannot edit device name in Phoscon or DeConz
@manup remoted into my system to work on this device and create the DDF for it. At that time I was on deConz 17.1
Today I 18.0 and removed and re-added the device (2 actually) hoping it would work better... it does not. It shows the temp/humidity levels Phoscon will not allow me to edit the device name like I can all other devices. I change the name so my Home Automation system (Homeseer) recognizes unique names coming from deConz.

I included debug logs during the adding of the new device

## Steps to reproduce the behavior
Add new device

## Expected behavior
Should be able to edit name in Phoscon

## Screenshots
Attached 2: Phoscon and deConz
![Tuya_Phoscon](https://user-images.githubusercontent.com/1626802/183316289-43a03876-5811-485a-8dd0-802b1574e76c.JPG)
![Tuya_deConz](https://user-images.githubusercontent.com/1626802/183316290-a16b98b1-b403-41d3-b3f8-c6fd31087731.JPG)

## Environment
 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: Windows
 - Firmware version: 26390500, then updated to 26400500
 - deCONZ version: 2.18.0
 - Device: ConBee I
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
attached TXT file
[Tuya_deConzDebug.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9277820/Tuya_deConzDebug.txt)

**Comment by Mimiix** [comment] 2022-08-08 08:32
Hi There,

As this is not a bug report as described in #5113 i am closing this issue. Feel free to report bugs with Phoscon on the forums: https://forum.phoscon.de/c/phoscon/bug-reports/20

Kind regards,

**Closed by Mimiix** 2022-08-08 08:32 UTC
Labels: Bug report
