### ISSUE TITLE
Tuya Soil Sensor won't connect.

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/deconz-rest-plugin#7043] opened 2023-06-08 17:45 UTC
## Describe the bug
As in V2.22.0 the Tuya Soil ([Link to an example](https://smarthomescene.com/reviews/tuya-zigbee-plant-soil-sensor-gxm-01-review/)) sensor was added to deconz I bought two of them. And well, they won't connect to deconz. They are not even found as an unknown device.

## Expected behavior
It should be found as a sensor, but it is found nothing.

## Environment
Conbee II
Latest deconz 2.22.01 beta
Latest firmware 26780700

Running on raspberry OS.

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: (26780700)
 - deCONZ version: (2.22.01)
 - Device: ConBee II
 - Do you use an USB extension cable: yes 0.5m long, to gain distance to the Raspi, because of disturbance by USB3.0 
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment] 2023-06-08 18:21
You probably have another one (different chip) thus not whitelisted.

This is definitely not a bug and that's why im closing this issue.

For help ik debugging, please use the forums.

Kind regards, Dennis

**Closed by Mimiix** 2023-06-08 18:21 UTC
Labels: Bug report

**Comment by BabaIsYou** [comment] 2023-06-08 20:27
Or maybe just have a look to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6731#issuecomment-1556634769

**Comment by Maddinthebrain** [comment] 2023-06-23 07:14
the API indeed catches both of the values. Then at some point the value of the moisture gets lost

![api moisture](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/43421040/120408d6-8bdf-42c6-b902-389ebde86ec2)
![api temp](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/43421040/eec17d49-6920-4134-9d48-026e84017fe2)

**Comment by Maddinthebrain** [comment] 2023-07-06 11:38
The problem is in fhem. Fhem recieves the value correctly but it isn't processed correctly.
