### ISSUE TITLE
Xbee router and RaspBee. Communication problem!

### ISSUE THREAD

**Issue by VitoLeo92** [dresden-elektronik/deconz-rest-plugin#382] opened 2018-01-26 20:01 UTC
Hello everyone, 
I use deConz for the RaspBee Premium module (deRFmega256-23M12).

I want to make a communication between RaspBee (coordinator) and an Xbee module (router). On the router I have the firmware "0x23A7.elb". Which firmware ".bin.GCF" (or ".zigbee) can I carry out for my purpose?
Can a ".elb" file be converted to a ".bin.GCF" firmware file?

**Comment by manup** [comment] 2018-01-30 08:03
Closing the issue since it seems duplicate of this: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/380

**Closed by manup** 2018-01-30 08:03 UTC
