### ISSUE TITLE
Power measure with TH1124ZB

### ISSUE THREAD

**Issue by BabaIsYou** [dresden-elektronik/deconz-rest-plugin#5897] opened 2022-03-22 17:10 UTC
## Describe the bug

  The power attribute is reported once thru ZHAPower type and one using ZHAConsumption type. But the value in ZHAComsuption sensor is always 0

## Steps to reproduce the behavior

{
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "8b113721e336e023239a3098e8f88953",
  "lastannounced": null,
  "lastseen": "2022-03-22T16:33Z",
  "manufacturername": "Sinope Technologies",
  "modelid": "TH1124ZB",
  "name": "Puissance Salon",
  "state": {
    "current": 57064,
    "lastupdated": "2022-03-22T16:34:50.727",
    "power": 423,
    "voltage": 241
  },
  "swversion": "2007",
  "type": "ZHAPower",
  "uniqueid": "50:0b:91:40:00:02:ca:1c-01-0b04",
  "id": "19",
  "deviceclass": "sensors"
}
}
{
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "d858914b6c88548d35c65c9f276f783c",
  "lastannounced": null,
  "lastseen": "2022-03-22T16:34Z",
  "manufacturername": "Sinope Technologies",
  "modelid": "TH1124ZB",
  "name": "Consommation Salon",
  "state": {
    "consumption": 32117,
    "lastupdated": "2022-03-22T16:34:49.810",
    **"power": 0**
  },
  "swversion": "2007",
  "type": "ZHAConsumption",
  "uniqueid": "50:0b:91:40:00:02:ca:1c-01-0702",
  "id": "18",
  "deviceclass": "sensors"
}

## Expected behavior

 I expect to have the same value in both.

## Environment

ConBeeII Firmware : 0x26660700
Phoscon APP 2.14.01 06/02/2022

 - Host system: Raspberry Pi /
 - Running method: Raspbian
 - Firmware version:26660700
 - deCONZ version: 2.14.1
 - Device: ConBee II 
 - Do you use an USB extension cable:yes 
 - Is there any other USB or serial devices connected to the host system? yes (Dongle Z-Wave and RFXcomm)

## deCONZ Logs

 No log to produce at this step.

**Comment by Smanar** [comment] 2022-03-22 17:27
But it s you on domoticz forum too ?

I can purpose a PR to correct that, but in the actual situation I think it will be better to try using the DDF ?
Do you know how it work ? https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
As the device is already working the DDF can be almost complete (I think it will just miss the binding)

**Comment by Mimiix** [comment] 2022-03-22 18:18
Please use the respective device report to report these things. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2104

Closing this one.

**Closed by Mimiix** 2022-03-22 18:18 UTC
Labels: Bug report

**Comment by BabaIsYou** [comment] 2022-03-23 17:04
> But it s you on domoticz forum too ?
> 
> I think it s same on the node itself ? If you check on the cluster 0x0702 the value is 0 for the power ?
> 
> I can purpose a PR to correct that, but in the actual situation I think it will be better to try using the DDF. Do you know how it work ? https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet As the device is already working the DDF can be almost complete (I think it will just miss the binding)
> 
> If you can't finish it, just make a copy/paste here to have a base.

@Smanar As you can see the attribute are already defined the same manner in both cases...

![ZHAConsumption](https://user-images.githubusercontent.com/85300265/159755463-57f461da-59ed-41cc-8e72-bcb97c5bd441.jpg)
![ZHApower](https://user-images.githubusercontent.com/85300265/159755468-8c8338e9-d1de-45c8-9424-77b1b108b50d.jpg)

**Comment by BabaIsYou** [comment] 2022-03-23 17:07
> Please use the respective device report to report these things. #2104
> 
> Closing this one.

@Mimiix As the other one is also closed, that's looks like a "catch 22" ;-)

**Comment by Smanar** [comment] 2022-03-23 17:47
Don't worry, he is able to re open the other issue. And he is right, better to have one issue by device.
I will answer on the https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2104

**Comment by BabaIsYou** [comment] 2022-04-14 16:48
> Don't worry, he is able to re open the other issue. And he is right, better to have one issue by device. I will answer on the #2104

@Mimiix . Well, both of the issues are still closed but not solved ?!

**Comment by Mimiix** [comment] 2022-04-15 06:11
I can't reopen the other one because it doesn't comply with the template. As that issue contains all relevant information it makes sense to keep all talk there.

Is the "status" of an issue important for you? I mean, Smanar is helping out there afaik.

**Comment by BabaIsYou** [comment] 2022-04-15 10:21
You sent me to the other thread and at this time there was no mention to missing information to be compliant to a template for an issue that was already closed before than the device was fully supported as initially requested.

BTW what is missing ?

Le 15 avr. 2022 à 02:11, Dennis D ***@***.***> a écrit :

﻿

I can't reopen the other one because it doesn't comply with the template. As that issue contains all relevant information it makes sense to keep all talk there.

Is the "status" of an issue important for you? I mean, Smanar is helping out there afaik.

**Comment by Mimiix** [comment] 2022-04-15 10:29
We use templates for issues. a bot checks if theres headers in the original post. If they don't exist, the issue gets auto closed. Even on re-opening.

As the issue is quiet old, the template wasnt used. Either way, I am not sure why you are so eager to have it opened... It really doesn't change anything at this moment 😅

**Comment by BabaIsYou** [comment] 2022-04-15 11:20
You’re right it changes nothing at this moment. I mean nothing at all … i plugged the device, got errouneous value, trying to have some help to understand and correct this fact and the only clear answer is « you don’t it, then delete it, not an issue, keep closed ».

My point is : if this sensor is useless, please correct it’s creation process for everybody using it. Whatever the way is to correct it. If it’a  thru DDF then just tell me what to modify then I can do a PR once it’s corrected.

Letting the issue closed send the message that there is no more issue. But there is.

Le 15 avr. 2022 à 06:29, Dennis D ***@***.***> a écrit :

﻿

We use templates for issues. a bot checks if theres headers in the original post. If they don't exist, the issue gets auto closed. Even on re-opening.

As the issue is quiet old, the template wasnt used. Either way, I am not sure why you are so eager to have it opened... It really doesn't change anything at this moment 😅

**Comment by Mimiix** [comment] 2022-04-15 11:24
If it's that important to you, let me work around it.

It really makes not difference here at all in the end.

**Comment by Mimiix** [comment] 2022-04-15 11:25
Please continue in the other issue.

**Comment by BabaIsYou** [comment] 2022-10-11 08:33
Many thanks

Le 15 avr. 2022 à 07:26, Dennis D ***@***.***> a écrit :

﻿

Please continue in the other issue.
