### ISSUE TITLE
apt repository returns 404 on Ubuntu Kinetic

### ISSUE THREAD

**Issue by runerune** [dresden-elektronik/deconz-rest-plugin#6712] opened 2023-01-30 18:40 UTC
## Describe the bug

The apt repository listed in the docs returns HTTP 404 on Ubuntu Kinetic.

## Steps to reproduce the behavior

1. Follow installation steps listed on https://phoscon.de/en/conbee/install#ubuntu
2. Observe 404 Not Found, attached, in step 4.

## Expected behavior

Repository should be available.

## Screenshots

![403](https://user-images.githubusercontent.com/20373951/215565602-d6723ec7-f186-416d-bb7a-9fc1982b932b.png)

## Environment

 - Host system: Raspberry Pi 4
 - Running method:  Ubuntu kinetic (22.10)
 - Firmware version: n/a
 - deCONZ version: n/a
 - Device: ConBee II
 - Do you use an USB extension cable: n/a
 - Is there any other USB or serial devices connected to the host system? If so: Which? n/a

## deCONZ Logs

n/a

**Comment by Mimiix** [comment] 2023-01-30 19:14
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

Feel free to open a topic on the forums.

Kind regards,
Dennis

**Closed by Mimiix** 2023-01-30 19:14 UTC
Labels: Bug report
