### ISSUE TITLE
Frient Smart Plug SPLZB-132

### ISSUE THREAD

**Issue by chicamaxi** [dresden-elektronik/deconz-rest-plugin#6715] opened 2023-01-31 21:49 UTC
Hello, I use a lot of Frient Smart Plugs in my home, all of them are SPLZB-131 plugs (except the last one I bought this week) are working perfectly. They monitor my energy consumption and power. The last one I bought is a newer version, SPLZB-132. This plug works as a standard on/off plug but is not showing the consumption and power data via Rest-API, and the data is not available in HASS neither. The list of supported devices only shows SPLZB-131, are there any plans to also support the newer version of the plug?
Regards

**Comment by Mimiix** [comment] 2023-01-31 22:28
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

In your case you should open a device request.

Kind regards,

**Closed by Mimiix** 2023-01-31 22:28 UTC
