### ISSUE TITLE
Aqara Smart Plug SP-EUC01 shows 10 times to high values 

### ISSUE THREAD

**Issue by haz-69** [dresden-elektronik/deconz-rest-plugin#6430] opened 2022-10-17 13:24 UTC
## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment] 2022-10-17 15:57
Hi,

As this issue is not a bug report as described in #5113 , I am closing this issue.

Kind regards 
Dennis

**Closed by Mimiix** 2022-10-17 15:57 UTC
Labels: Bug report
