### ISSUE TITLE
deconz service unable to connect to new RasbBee II device

### ISSUE THREAD

**Issue by stefaanv** [dresden-elektronik/deconz-rest-plugin#5612] opened 2021-12-26 10:31 UTC
## Describe the bug

deconz service is not able to connect to the RaspBee II device over `/dev/ttyAMA0` (according to log file)
On the gateway page of the phoscon web app, information about the raspbee device is missing: Vendor=`unknown`, product=**empty**
DeCONZ is not descovering any Zigbee devices

## Steps to reproduce the behavior

- Fresh installation of `openhabian` on a new Respberry Pi 4b device.
- Followed installation steps from https://phoscon.de/en/raspbee2/install except for the installation of deconz which is already included on the `openhabian` image
- Disabled the console to serial in `raspi-config`

## Expected behavior

Zigbee device discovery

## Environment

 - Host system: **Raspberry Pi 4B**
 - Running method: **Raspbian** (openhabian) headless setup
 - Firmware version: **unknown**
 - deCONZ version: **2.13.04 / 12/18/2021**
 - Device:  **RaspBee II**
 - Do you use an USB extension cable: **NO**
 - Is there any other USB or serial devices connected to the host system? **RFXcom over USB**

## deCONZ Logs
Log file attached, problem starts at line 1050
[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7776850/deconz.log)

## Additional context

The RTC clock of the RaspBee is working fine, so I don't expect the device to be defect

**Comment by Mimiix** [comment] 2021-12-26 10:49
Hi,

As this is not a bug report as described in #5113, I am closing this issue.

Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2021-12-26 10:49 UTC
Labels: Bug report
