### ISSUE TITLE
XHK1-UE manufactured by Xfinity only showing up as Temp Sensor

### ISSUE THREAD

**Issue by MichaelRV82** [dresden-elektronik/deconz-rest-plugin#5696] opened 2022-01-22 16:20 UTC
## Describe the bug
 XHK1-UE manufactured by Xfinity is only showing up as temperature sensor

## Steps to reproduce the behavior
 adding the XHK1-UE manufactured by Xfinity to deconz

## Expected behavior
 full keypad support

## Screenshots
 
![0CFAA0EA-31B0-4498-825C-13A5BC1026A6](https://user-images.githubusercontent.com/92013548/150646755-e7c4fa97-c146-4f10-b32c-33bbd308339b.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26690700
 - deCONZ version: 2.13.04 / 18/12/2021
 - Device:  RaspBee II
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment] 2022-01-22 18:14
Hi

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum for help.

Or check this issue and ask there. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4560#issue-829119876

Kind regards,
Dennis

**Closed** 2022-01-22 18:14 UTC
Labels: Bug report
