### ISSUE TITLE
Philips Hue motion sensor not pairing

### ISSUE THREAD

**Issue by zbeez** [dresden-elektronik/deconz-rest-plugin#5774] opened 2022-02-09 12:38 UTC
Describe the issue you are experiencing here to communicate to the
  maintainers. Tell us what you were trying to do and what happened.
 
Tried to pair my new Philips hue motion sensor to my deconz (Conbee II) via the option "Philips" but it does not succeed to find any sensor. If I pair the sensor with choosing "Other", it works. 
Steps to pair that I followed. 
Long pressed the "setup" button on the sensor and searched for new sensor in Phoscon/deconz.
Sadly I miss the illuminance sensor with this option, therefor I'd like to ask for help.

 
## Expected behavior
 Pairing the Philips Hue motion sensor with the Philips option under sensors.

## Screenshots
 
![image](https://user-images.githubusercontent.com/63555234/153201726-7e884585-1ea5-4d35-86c1-df64cfe2246c.png)
![image](https://user-images.githubusercontent.com/63555234/153201842-22d1429f-a498-47bf-b85a-169f7f36b83a.png)

## Environment

 - Host system: (Raspberry Pi)
 - Running method: (Home Assistent deCONZ Add-on)
 - Firmware version: (26720700)
 - deCONZ version: (2.14.01)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) 
 - Is there any other USB or serial devices connected to the host system? (yes) - SSD drive with extension cable (working since a year).

**Comment by Mimiix** [comment] 2022-02-10 07:19
Hi,

As this is not a bug report as described in #5113  i am closing this issue. Feel free to open a topic on the forums.
https://forum.phoscon.de

Kind regards,

**Closed by Mimiix** 2022-02-10 07:19 UTC
Labels: Bug report
