### ISSUE TITLE
Zigbee Smart Door Window Sensor

### ISSUE THREAD

**Issue by JasonMask** [dresden-elektronik/deconz-rest-plugin#7995] opened 2024-10-25 19:39 UTC
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Zigbee Smart Door Window Sensor

### Manufacturer

eWeLink

### Model identifier

SNZB-04

### Device type to add

Sensor

### Node info

![image](https://github.com/user-attachments/assets/b4e6c64b-fb1b-413c-a808-fb04ddae970c)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/c3ee04a0-751a-44d4-bf8c-5d5271ffc7a8)

### Basic

![image](https://github.com/user-attachments/assets/198fb914-515e-4bef-bda2-7f2ece55539f)

### Power Configuration
![image](https://github.com/user-attachments/assets/004c9e98-0285-46e0-833a-c13fcad6881a)

### Any other cluster of relevance/interest
![image](https://github.com/user-attachments/assets/aa627b5d-f0de-4903-a0f4-69ca1e8a806b)
![image](https://github.com/user-attachments/assets/2497a36a-9805-4980-9b64-a29a256ba89b)
![image](https://github.com/user-attachments/assets/ac605a3f-5c5d-42e3-85bc-5999ac1cc76a)
![image](https://github.com/user-attachments/assets/be94e6a0-2244-438f-bbb6-bb226c995295)

this is a renew/reopen of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7563

**Comment by SwoopX** [comment] 2024-10-27 15:33
Duplicate of #7857 and #7563

**Closed by SwoopX** 2024-10-27 15:33 UTC
Labels: Device Request

**Comment by JasonMask** [comment] 2024-10-27 15:48
@SwoopX hi, you closed this issue for being a duplicate of an already closed ticket. That ticket has been closed for being stall, as the original reporter failed to reply with missing information.
How can I reopen that other ticket and provide the information there? 
Thanks for your reply. 
Best regards

**Comment by SwoopX** [comment] 2024-10-27 16:23
Hi. Pretty much the way you did, just ask 🙂 reopened the first mentioed, as it seemed to be almost complete.
