### ISSUE TITLE
Tuya / Aubess Smart Plug 20A EU Stecker

### ISSUE THREAD

**Issue by lViSoRl** [dresden-elektronik/deconz-rest-plugin#6741] opened 2023-02-11 10:58 UTC
Hey,

I bought the following device
https://de.aliexpress.com/item/1005004910203202.html
Tuya Aubess Smart Plug 20A EU Stecker

I found there is 2 Request closed  #5334 #5639 the difference is that they only have 16A and that has 20A.
I'm not sure maybe you should add this one or make a new one for 20A :)
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/neo/NAS-WR01B_TS011F.json

## Device
Product name: Tuya smart plug 20A
Manufacturer: _TZ3000_gvn91tmx
Model identifier: TS011F

Device type : Smart plug with power metering

## Screenshots
![Screenshot 2023-02-11 113857](https://user-images.githubusercontent.com/63469183/218254056-638f55b2-1a3e-43ea-ac91-de6785df9a56.png)

![Screenshot 2023-02-11 120709](https://user-images.githubusercontent.com/63469183/218254760-ccd5439b-385c-41d6-bbcc-d9acdda18c7a.png)
![Screenshot 2023-02-11 115339](https://user-images.githubusercontent.com/63469183/218254408-7193452e-4bd1-42d7-b103-43fdf96f6495.png)
![Screenshot 2023-02-11 115529](https://user-images.githubusercontent.com/63469183/218254409-2afec7c1-e47c-4650-9d14-1987c5565842.png)
![Screenshot 2023-02-11 115619](https://user-images.githubusercontent.com/63469183/218254411-0e6d35e0-df60-4661-ac15-d2b3b9046206.png)
![Screenshot 2023-02-11 115647](https://user-images.githubusercontent.com/63469183/218254413-2c0135a5-6e7c-4dc3-abfb-c5d4ce6f636d.png)

Big Thanks!

**Comment by Mimiix** [comment] 2023-02-11 12:44
Hi,

Duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6423

Closing this issue.

**Closed by Mimiix** 2023-02-11 12:44 UTC
Labels: Device Request
