### ISSUE TITLE
Xiaomi Aqara End Devices do not stay connected

### ISSUE THREAD

**Issue by Ar-eh** [dresden-elektronik/deconz-rest-plugin#5245] opened 2021-08-25 05:32 UTC
**Describe the bug**

I have 9 Aqara door/window sensors, 4 Aqara vibration sensors, and 1 Aqara multi-sensor. For many months they have been rock-solid and among my most reliable devices. In the past few weeks, they fail to remain connected to the Conbee II network. I have repeatedly deleted, and re-added the sensors in Phoscon and read all clusters, node descriptor, and simple descriptors in the deconz GUI. I have followed the directions at [Xiaomi: Lost devices or functional issues](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues) multiple times. The sensors will sometimes reconnect for a short time and then disconnect. When they disconnect, the cluster info in the Deconz GUI for the basic cluster is typically blank. I have also tried changing the zigbee channel from 11 to 25, but that did not resolve the issue.

**Steps to reproduce the behavior**

Add Aqara sensors to network using Phoscon and Deconz GUI and wait for them to lose connection to deconz.

**Expected behavior**

The sensors should stay connected to deconz.

**Screenshots**

**Environment**

Host system: Synology DS718+
Running method: Marthoc Docker container
Firmware version: 26720700
deCONZ version: 2.12.06 / 8/19/2021
Device: ConBee II
Do you use an USB extension cable: yes
Is there any other USB or serial devices connected to the host system? If so: Which? APC UPS
**deCONZ Logs**

Additional context

**Comment by Mimiix** [comment] 2021-08-25 05:40
Hi,

As this is not a bug, I am closing this issue. 

Feel free to post on the forums (https://forum.phoscon.de).

**Closed by Mimiix** 2021-08-25 05:40 UTC
