### ISSUE TITLE
Xiaomi Mi Smart Plug connection issues

### ISSUE THREAD

**Issue by JustNZ** [dresden-elektronik/deconz-rest-plugin#5482] opened 2021-11-13 14:48 UTC
## Describe the bug
My Xiaomi Mi Smart Plug loses connection after a certain time. Even over night where the plug is turned off I can see that it loses for several hours the connection

It is connected via a conbee2 and HA deCONZ

## Steps to reproduce the behavior
1. Connect the plug with deCONZ
2. wait some time
3. Plug gets unreachable

## Expected behavior
Simply works

## Screenshots
![image](https://user-images.githubusercontent.com/51332147/141648073-ed4374a0-d795-436c-9551-6a57eb1d36ef.png)

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.12.06
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: SSD

## deCONZ Logs

> 15:28:05:206 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 163 seconds ago
15:28:08:085 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 166 seconds ago
15:28:10:965 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 169 seconds ago
15:28:13:845 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 171 seconds ago
15:28:16:725 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 174 seconds ago
15:28:19:606 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 177 seconds ago
15:28:22:485 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 180 seconds ago
15:28:25:365 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 183 seconds ago
15:28:28:246 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 186 seconds ago
15:28:31:126 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 189 seconds ago
15:28:34:005 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 192 seconds ago
15:28:36:886 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 195 seconds ago
15:28:39:234 Device TTL 4919 s flags: 0x7
15:28:39:766 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 197 seconds ago
15:29:39:232 Device TTL 4859 s flags: 0x7
15:30:39:231 Device TTL 4799 s flags: 0x7
15:30:55:126 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 333 seconds ago
15:30:58:006 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 336 seconds ago
15:31:00:885 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 339 seconds ago
15:31:02:226 GW firmware version: 0x26660700
15:31:02:226 GW firmware version is up to date: 0x26660700
15:31:03:765 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 341 seconds ago
15:31:06:646 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 344 seconds ago
15:31:09:525 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 347 seconds ago
15:31:12:405 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 350 seconds ago
15:31:15:286 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 353 seconds ago
15:31:18:166 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 356 seconds ago
15:31:21:045 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 359 seconds ago
15:31:23:925 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 362 seconds ago
15:31:26:805 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 364 seconds ago
15:31:29:686 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 367 seconds ago
15:31:32:566 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 370 seconds ago
15:31:35:445 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 373 seconds ago
15:31:38:326 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 376 seconds ago
15:31:39:233 Device TTL 4739 s flags: 0x7
15:31:41:205 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 379 seconds ago
15:31:44:085 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 382 seconds ago
15:31:46:965 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 385 seconds ago
15:31:49:846 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 387 seconds ago
15:31:51:098 LightNode 1: Justin Station updated
15:31:51:101 ZCL attribute report 0x04CF8CDF3C8A38B7 for cluster: 0x000C, ep: 0x15, frame control: 0x18, mfcode: 0x0000 
15:31:51:845 reuse dead link (dead link container size now 0)
15:31:58:168 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:00:871 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:03:475 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:06:164 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:08:871 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:08:872 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 1 s
15:32:11:474 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:11:475 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 0 s
15:32:12:510 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:12:512 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 2 s
15:32:12:769 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 2 s
15:32:14:174 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:32:14:176 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 0 s
15:32:14:566 0x9320 seems to be a zombie recv errors 10
15:32:14:568 Node zombie state changed 0x04cf8cdf3c8a38b7
15:32:14:569 SensorNode id: 3 (Consumption 3) no longer available
15:32:14:573 SensorNode id: 2 (Power 2) no longer available
15:32:16:245 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 19 seconds ago
15:32:19:125 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 22 seconds ago
15:32:22:005 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 25 seconds ago
15:32:24:886 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 28 seconds ago
15:32:27:765 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 30 seconds ago
15:32:30:646 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 33 seconds ago
15:32:33:525 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 36 seconds ago
15:32:36:406 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 39 seconds ago
15:32:39:234 Device TTL 4678 s flags: 0x7
15:32:39:286 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 42 seconds ago
15:32:42:165 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 45 seconds ago
15:32:45:046 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 48 seconds ago
15:32:47:925 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 51 seconds ago
15:32:50:805 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 53 seconds ago
15:32:53:686 discovery for zombie 0x04cf8cdf3c8a38b7 dropped, last try was 56 seconds ago
15:33:39:234 Device TTL 4618 s flags: 0x7
15:34:32:409 LightNode 1: Justin Station updated
15:34:32:411 ZCL attribute report 0x04CF8CDF3C8A38B7 for cluster: 0x000C, ep: 0x15, frame control: 0x18, mfcode: 0x0000 
15:34:33:467 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:36:169 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:38:868 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:39:233 Device TTL 4558 s flags: 0x7
15:34:41:474 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:44:172 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:46:865 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:46:866 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 113 s
15:34:49:468 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:49:470 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 116 s
15:34:52:174 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:52:175 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 118 s
15:34:53:767 0x04CF8CDF3C8A38B7 error APSDE-DATA.confirm: 0xE9 on task
15:34:53:768 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 120 s
15:34:54:070 max transmit errors for node 0x04CF8CDF3C8A38B7, last seen by neighbors 120 s
15:34:54:406 0x9320 seems to be a zombie recv errors 10
15:34:54:407 Node zombie state changed 0x04cf8cdf3c8a38b7
15:34:54:408 SensorNode id: 3 (Consumption 3) no longer available
15:34:54:409 SensorNode id: 2 (Power 2) no longer available
15:35:02:226 GW firmware version: 0x26660700
15:35:02:227 GW firmware version is up to date: 0x26660700
15:35:39:232 Device TTL 4498 s flags: 0x7
15:36:39:232 Device TTL 4438 s flags: 0x7

**Comment by Mimiix** [comment] 2021-11-13 14:51
Hi,

As this is not a bug report as described in #5113, I am closing this issue. Feel free to open an topic on the forum 's.

Kind regards,

**Closed by Mimiix** 2021-11-13 14:51 UTC
Labels: Bug report
