### ISSUE TITLE
Tuya Single Gang Switch - _TZE200_amp6tsvy - TS0601

### ISSUE THREAD

**Issue by TheAlphaLaw** [dresden-elektronik/deconz-rest-plugin#6302] opened 2022-09-05 19:03 UTC
## Device

- Product name: [MOES ZigBee Smart Touch Wall Light Switch](https://www.amazon.com/gp/product/B08X3J9KLM/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)
- Manufacturer: _TZE200_amp6tsvy
- Model identifier: TS0601
- Device type : Switch

## Screenshots

**Node Info**
![image](https://user-images.githubusercontent.com/26587248/188502530-49baa2f3-01e6-447f-8347-eb9df67724d1.png)

### Basic
![image](https://user-images.githubusercontent.com/26587248/188502593-b2d3261e-b218-45ab-9ed4-3a9981eb2aa3.png)

### Groups
![image](https://user-images.githubusercontent.com/26587248/188502729-f7e47222-f135-41dd-ae10-7a5ed8b674af.png)
![image](https://user-images.githubusercontent.com/26587248/188502930-c9577971-9b50-4c84-9ca8-2b9506eea4a6.png)

### Scenes
![image](https://user-images.githubusercontent.com/26587248/188502751-f1defe82-ffef-49e5-9cff-e8ff4c317470.png)
![image](https://user-images.githubusercontent.com/26587248/188503008-c6907651-4562-496b-8b4f-eec8c2d20b3f.png)
![image](https://user-images.githubusercontent.com/26587248/188503071-a6975397-53c0-4d4d-a79c-4619b4fca78f.png)

### Tuya Specific
![image](https://user-images.githubusercontent.com/26587248/188502786-591bf97e-89fd-41ef-b5a3-b97162b794f5.png)

**Comment by Mimiix** [comment] 2022-09-05 19:28
Closing as it is a duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5505

Reopened that one.

**Closed by Mimiix** 2022-09-05 19:28 UTC
Labels: Device Request
