### ISSUE TITLE
DeConz 2.19.01 not communicating with PhosCon app or HomeSeer plugin

### ISSUE THREAD

**Issue by jeroengvv** [dresden-elektronik/deconz-rest-plugin#6468] opened 2022-10-25 21:20 UTC
## Describe the bug

Upgrading to DeConz 2.19.01 breaks communication with PhosCon app and HomeSeer plugin. Roll back to 2.18.02 solves the issue.

DeConz is running in minimal mode on a RaspBerry PI 4B, Raspbian GNU/Linux 10 (buster).
The ConBee 2 has firmware version 26780700.

## Steps to reproduce the behavior

Upgrade to DeConz 2.19.01
Try communicating

## Expected behavior

Communication with PhosCon app and/orHomeSeer plugin

## Environment

 - Host system: Raspberry Pi  4B
 - Running method: Raspbian GNU/Linux 10 (buster)
 - Firmware version: 26780700
 - deCONZ version: 2.19.01
 - Device:  ConBee II
 - Do you use an USB extension cable: yes -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? SSD device.

**Comment by Mimiix** [comment] 2022-10-25 22:06
Hi,

As this is not a bug report as described in #5113, i am closing this issue.

Feel free to open a topic on the forums .

Kind regards ,

Dennis

**Closed by Mimiix** 2022-10-25 22:06 UTC
Labels: Bug report
