### ISSUE TITLE
ORVIBO gaz detector SG21

### ISSUE THREAD

**Issue by alex15978** [dresden-elektronik/deconz-rest-plugin#4607] opened 2021-03-19 00:15 UTC
## Device
ORVIBO gaz detector SG21

- Product name: SG21
- Manufacturer: Orvibo
- Model identifier: 358e4e3e03c644709905034dae81433e
- Device type : 
  - Sensor
  - Siren
 

## Screenshots

Node Info
![SG21_node Info](https://user-images.githubusercontent.com/80794144/111713424-e0c91300-884f-11eb-8210-eb4b43892e24.png)

### Basic
![SG21_basic cluster](https://user-images.githubusercontent.com/80794144/111713300-a52e4900-884f-11eb-9adb-ea1f46832853.png)

### Identify
![SG21_identity](https://user-images.githubusercontent.com/80794144/111713317-aeb7b100-884f-11eb-963c-ef9373a09bed.png)

### Alarms
![SG21_alarms](https://user-images.githubusercontent.com/80794144/111713322-b1b2a180-884f-11eb-879f-c3a636efccdf.png)

### IAS Zone
![SG21_IAS_Zone](https://user-images.githubusercontent.com/80794144/111713802-985e2500-8850-11eb-9691-721e232a01a9.png)

### OTAU
![SG21_OTAU](https://user-images.githubusercontent.com/80794144/111713473-fa6a5a80-884f-11eb-9ca3-8b60c27a0835.png)

**Comment by SwoopX** [comment] 2021-03-26 23:34
Duplicate of #3763

**Closed by SwoopX** 2021-03-26 23:34 UTC
Labels: Device Request, Duplicate
