### ISSUE TITLE
Xiaomi Relay T1 does not work with latest firmware

### ISSUE THREAD

**Issue by aeklo** [dresden-elektronik/deconz-rest-plugin#5908] opened 2022-03-26 15:15 UTC
## Describe the bug

Xiaomi Single Switch Module T1 (lumi.switch.n0agl1) does not work after being added on latest Conbee 1 firmware (26400500). To be more specific: It is found and added, but can neither be controlled or read after adding. By downgrading to (26390500) before adding, it does work, even after uprading back to latest fw.

## Steps to reproduce the behavior

  1. Flash Conbee 1 with firmware 26400500.
  2. Include lumi.switch.n0agl1.
  3. Try to control the device, or read values.
  4. Appears dead.

## Expected behavior

Expect device to be controllable after including.

## Environment

 - Host system: Intel NUC
 - Running method: Home Assistant ZHA integration
 - Firmware version: 26400500
 - deCONZ version: n/a
 - Device: ConBee I
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? Yes: UZB0 (Zwave dongle)

## deCONZ Logs

n/a

**Comment by Mimiix** [comment] 2022-03-26 16:34
Hi,

This repository is only for usage with deconz software.

This is not a bug in deconz, so I am closing this issue.

A bit of advice : see what happens if you flash older firmware to it. I doubt it's the firmware as we never seen firmware updates cause this behavior.

Closing.

**Closed by Mimiix** 2022-03-26 16:34 UTC
Labels: Bug report
