### ISSUE TITLE
Jung ZLL 8 gang Wall Swicth is identified as Remote instead of WS_4f_J_1

### ISSUE THREAD

**Issue by Kienz** [dresden-elektronik/deconz-rest-plugin#5792] opened 2022-02-14 18:50 UTC
## Describe the bug
The Jung ZLL LS 5004 is identifed as "Remote" instead of "WS_4f_J_1".
My existing Jung 8 gang Wall Switches working fine - had to reset one and after adding it is identified wrong.

## Steps to reproduce the behavior
Pair a Jung ZLL 8 gang Wall Switch - it is displayed as "Remote" in Phoscon and deCONZ GUI.

## Expected behavior
See screenshot 2

## Screenshots
Wrong device:
![image](https://user-images.githubusercontent.com/954545/153926864-59857331-c651-4b77-b391-a2af1ff875cf.png)

Correct device (same type)
![image](https://user-images.githubusercontent.com/954545/153926948-c1cdf50c-7c13-4fd0-9f1d-2f22a2135c26.png)

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26720700
 - deCONZ version: 2.14.01
 - Device: RaspBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment] 2022-02-14 21:47
Can you show a screenshot of the basic cluster?

**Comment by Kienz** [comment] 2022-02-15 07:00
Correct device:
![image](https://user-images.githubusercontent.com/954545/154009273-f1cf9ad7-0f67-4d71-8e38-73ca840a73fe.png)

Wrong device:
![image](https://user-images.githubusercontent.com/954545/154009260-0254d118-7634-4960-955c-26adab5ccdac.png)

I added the device with the Phoscon Web app.

**Comment by Mimiix** [comment] 2022-02-15 07:25
They are not the same devices. The Manufacturer name and Model identifier is what the device is programmed for. Meaning: That's what it is. They can look the same, but the chip is different.  This is identifeid properly, in a way that this is what the device says he is.

If the device is working properly, you can ignore it. If it's not, you need to open an device request issue and supply all required screenshots and information there to get it supported. Be adviced of #5733.

Closing this issue as it's not a bug in deCONZ.

**Comment by Kienz** [comment] 2022-02-15 07:33
They are the same device - https://downloads.jung.de/public/de/pdf/bedienungsanleitungen/de_ZLLx5004M_32596233_20190703.pdf

And it worked - I added the device a year ago and it worked like my other Jung ZLLx5004 devices. Yesterday I have to reset this device and now I can't pair it right.

**Comment by Mimiix** [comment] 2022-02-15 07:36
Do they show the same clusters?

**Comment by Mimiix** [comment] 2022-02-15 07:38
Are you sure it worked before? You didn't do a firmware update?

**Comment by Kienz** [comment] 2022-02-15 07:43
Yes it worked - sure. I have 4 of this devices and all of them worked.
Some of them have the firmware 10023202 and some 10033202.
Here are some new screenshots of the Clusters:

Device which doesn't work:
![image](https://user-images.githubusercontent.com/954545/154015313-bc3a4130-2649-4760-9aef-8fa9339f343d.png)

Device with firmware 10023202:
![image](https://user-images.githubusercontent.com/954545/154015422-d505905b-a357-4cf8-a1cb-c44045be633e.png)

Device with firmware 10033202:
![image](https://user-images.githubusercontent.com/954545/154015406-a3edd44d-3f7c-4d23-91ed-d8791b54292c.png)

**Comment by Kienz** [comment] 2022-02-15 07:55
Why was this closed?

**Comment by Kienz** [comment] 2022-02-15 08:06
I downgraded to deCONZ 2.10.04 (deconz-2.10.04-qt5.deb) - now the pairing works correct.
Cluster Info:
![image](https://user-images.githubusercontent.com/954545/154018932-205ff5f0-7b18-40c0-844c-68fbe6a3bebc.png)

![image](https://user-images.githubusercontent.com/954545/154018995-3c79800b-cdad-452d-a364-8da04e34367b.png)

**Comment by Mimiix** [comment] 2022-02-15 08:40
This doesn't make any changes, but now we can classify it as a bug indeed :) Re-opening:)

**Comment by Kienz** [comment] 2022-02-15 11:42
The pairing process works correctly with 2.10.4 and 2.12.6.

**Comment by Eisenhauer1987** [comment] 2022-03-01 07:35
Same Problem here. 4 already paired devices working Fine, the new switch pairs worng and is Not working. Please fix

**Comment by Eisenhauer1987** [comment] 2022-03-14 06:24
Hi, Problem still existing. What can we do for help to fix?

**Comment by Mimiix** [comment] 2022-03-14 06:26
@manup

**Comment by manup** [comment] 2022-03-14 12:23
I've put it on my test list. There is some quirky code to detect the JUNG/GIRA switches (some MAC address magic if I remember correctly) which was likely broken somehow.

**Closed** 2022-03-16 16:35 UTC
Labels: Bug report
