### ISSUE TITLE
Conbee II shown as a Raspbee

### ISSUE THREAD

**Issue by MurphyB17** [dresden-elektronik/deconz-rest-plugin#6185] opened 2022-07-10 11:25 UTC
## Describe the bug
I'm having the same issues as: [#1221]  [#2579]
I am running on a Raspberry Pi through the Homebridge image, and the homebridge-deconz plugin. I have been having difficulties accessing my Conbee II through the Phoscon app pretty much since the beginning. I was able to access it through my phone earlier today, but Homebridge or my computer could not detect it. After re-imaging my Raspberry Pi SD card and reinstalling deconz, it now displays as a Raspbee and I can't even click on the gateway through the phoscon app. 
I had found similar issues , how can I change the device location through homebridge image on Raspberry Pi (sorry if obvious I am a newbie) 

<img width="513" alt="Screen Shot 2022-07-10 at 8 51 11 pm" src="https://user-images.githubusercontent.com/68230705/178142525-3b0a0696-49f6-45c0-ad62-9635cbd09d05.png">

<img width="559" alt="Screen Shot 2022-07-10 at 9 15 38 pm" src="https://user-images.githubusercontent.com/68230705/178142587-cb89b9e8-b1b3-4c64-b6e2-3793cd776535.png">

## Steps to reproduce the behavior

  I thought it may have been an issue with how I installed deconz - I was unable to update any firmware. So I reimaged the SD card and reinstalled everything. Now showing incorrect USB location.

## Environment

 - Host system: Raspberry Pi
 - Running method: HomeBridge deCONZ plugin
 - Firmware version: (26xxyy00) 
 - deCONZ version: (2.xx.yy)
 - Device: ConBee II 
 - Do you use an USB extension cable: No - have ordered one
 - Is there any other USB or serial devices connected to the host system? Yes, Broadlink-RM Pro

**Comment by Mimiix** [comment] 2022-07-10 13:00
Hi,

As this is not a bug report as described in #5113 I am closing this issue. Feel free to open an topic on the forum.

Kind regards,
Dennis

**Closed by Mimiix** 2022-07-10 13:00 UTC
Labels: Bug report
