### ISSUE TITLE
Deconz GUI service wont start on Debian 12 GNOME

### ISSUE THREAD

**Issue by olicooper** [dresden-elektronik/deconz-rest-plugin#7186] opened 2023-08-18 17:23 UTC
## Describe the bug

deconz GUI will not start when run as a service `sudo systemctl start deconz-gui` but the GUI starts okay if I run `/usr/bin/deCONZ` from the same terminal.

## Steps to reproduce the behavior

1. Install Debian 12 GNOME on amd64 PC (I used https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/)
2. Follow instructions on https://www.phoscon.de/en/conbee2/install#ubuntu to install deconz
3. Enable auto login so the GUI can start
4. `sudo systemctl enable deconz-gui`
5. `sudo systemctl disable deconz`

I also changed the `http-port` to 8081 in the service file `sudo systemctl edit deconz-gui`

## Expected behavior

Deconz should start and show GUI

## Environment

 - Host system: PC
 - Running method: Debian 12
 - Firmware version: 26720700
 - deCONZ version: 2.22.02
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? Wireless mouse

## deCONZ Logs

```log
Aug 18 17:30:27 lm700 systemd[1]: deconz-gui.service: Scheduled restart job, restart counter is at 1.
Aug 18 17:30:27 lm700 systemd[1]: Stopped deconz-gui.service - deCONZ: ZigBee gateway -- GUI/REST API.
Aug 18 17:30:28 lm700 systemd[1]: Started deconz-gui.service - deCONZ: ZigBee gateway -- GUI/REST API.
Aug 18 17:30:28 lm700 systemd[1]: Starting deconz-init.service - deCONZ: ZigBee gateway -- Initialisation...
Aug 18 17:30:28 lm700 deCONZ-init.sh[31735]: cat: /sys/block/mmcblk0/device/cid: No such file or directory
Aug 18 17:30:28 lm700 deCONZ[31727]: Authorization required, but no authorization protocol specified
Aug 18 17:30:28 lm700 deCONZ[31727]: qt.qpa.xcb: could not connect to display :0
Aug 18 17:30:28 lm700 deCONZ[31727]: qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
Aug 18 17:30:28 lm700 deCONZ[31727]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aug 18 17:30:28 lm700 deCONZ[31727]: Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
Aug 18 17:30:28 lm700 deCONZ-init.sh[31728]:  stopping deconz-wifi.service
Aug 18 17:30:28 lm700 systemd[1]: deconz-gui.service: Main process exited, code=killed, status=6/ABRT
Aug 18 17:30:28 lm700 systemd[1]: deconz-gui.service: Failed with result 'signal'.
Aug 18 17:30:28 lm700 systemd[1]: Reloading.
Aug 18 17:30:28 lm700 systemd[1]: deconz-init.service: Deactivated successfully.
Aug 18 17:30:28 lm700 systemd[1]: Finished deconz-init.service - deCONZ: ZigBee gateway -- Initialisation.
```

**Comment by Mimiix** [comment] 2023-08-18 18:02
Hi,

As this is not a bug report as described in #5113 I am closing this issus.

Please open an topic on the forums.

Kind regards,
Dennis

**Closed by Mimiix** 2023-08-18 18:02 UTC
Labels: Bug report
