### ISSUE TITLE
IKEA Tradfri Open/Close Remote E1766 - Stopped Working

### ISSUE THREAD

**Issue by jotzet79** [dresden-elektronik/deconz-rest-plugin#6950] opened 2023-05-05 10:20 UTC
## Describe the bug

- Pressing any button on the remote has no effect 
- Previously ("some" months ago) this was working correctly without further ado...

## Steps to reproduce the behavior

- I have 2 IKEA Fyjrtur Shades connected to deCONZ and the IKEA Tradfri Open/Close Remote. 
- In the deconz Legacy UI Tool I created the group which includes the 2 shades 
- Pressing any button on the remote has no effect 
- If I control the shades using Actions mapped to the Remote within Homebridge / HomeKit it works, meaning the Events seem to be triggered
- Deleting the remote from within deConz and Re-connecting it has also no effect

## Expected behavior

- All devices assigned to that group are controlled correctly

## Environment

 - Host system: Raspberry Pi 
 - Running method: Raspbian 
 - Firmware version: 0x26690700
 - deCONZ version: v2.21.2
 - Device: RaspBee II
 - Do you use an USB extension cable: n/a
 - Is there any other USB or serial devices connected to the host system? nope

## Additional context

![Screenshot 2023-05-05 at 12 19 18](https://user-images.githubusercontent.com/44292689/236433027-932da81d-e448-41d3-a1d1-02c6f6e208fd.png)

**Comment by Mimiix** [comment] 2023-05-05 10:22
Hi,

I have this one at home. Will test this afternoon.

**Comment by Mimiix** [comment] 2023-05-05 12:17
Hi,

I have tested on 2.21.1 and 2.22.0 ( can't test on 2.21.2 as i am on beta). On both occasions, it works as expected when i add it to the group:
![image](https://user-images.githubusercontent.com/43333120/236455504-543c56d0-530f-403f-b21d-2cea94a4c72a.png)

So i am not able to reproduce this.

**Comment by ebaauw** [comment] 2023-05-05 14:11
The remote no longer sends group commands with its latest firmware.  You should still be able to control the blinds directly, by creating unicast bindings from the remote to each blind.

Note that IKEA probably changed this, as it was stretching the Zigbee spec, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3881.

**Comment by jotzet79** [comment] 2023-05-05 20:14
@ebaauw Wow, Thank you - I will definitely look into this! 

@Mimiix, Can you check what is your firmware version, please? Just to rule out different things here...

Thanks,
Joachim

**Comment by Mimiix** [comment] 2023-05-05 20:23
> @ebaauw Wow, Thank you - I will definitely look into this!
> 
> @Mimiix, Can you check what is your firmware version, please? Just to rule out different things here...
> 
> Thanks, Joachim



> @ebaauw Wow, Thank you - I will definitely look into this!
> 
> @Mimiix, Can you check what is your firmware version, please? Just to rule out different things here...
> 
> Thanks, Joachim

I never updated it since I got it. Date code is 20190311 , application version is 34.

Anyway, as i can't reproduce and Ebaauw giving a possible explanation, i am closing this issue.

We can still discuss a bit.

**Closed by Mimiix** 2023-05-05 20:23 UTC
Labels: Bug report

**Comment by olemr** [comment] 2023-05-07 13:29
Is this what I'm seing here?
https://forum.phoscon.de/t/tradfri-open-close-switch-with-fw-2-3-079-fails-to-pair-with-blind/3518

**Comment by ebaauw** [comment] 2023-05-07 14:08
Yes, looks like.  If memory serves, the "association" in the old web app consists of adding the group bound to the controller (i.c. the open/close remote) to the actuator (i.c. the blind).

**Comment by olemr** [comment] 2023-05-07 17:54
IC. 
It is possible to do the association from somewhere else, and if so, how? (Have just used the Old Web App so far)

**Comment by ebaauw** [comment] 2023-05-07 18:29
The "association" is still there, but the open/close remote no longer sends group commands.  As I mentioned above, you could add unicast bindings from the remote to each blind individually, from the _Binding_ panel in the GUI.  See the user manual for details.
