### ISSUE TITLE
The system behaves nondeterministic sluggish with version > 2.23.2

### ISSUE THREAD

**Issue by lukicsl** [dresden-elektronik/deconz-rest-plugin#7543] opened 2024-01-21 14:07 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I have upgraded my system from 2.23.2 first to 2.24.2, following the 2.25.1 and finally the 2.24.3. At all of these versions, I am experiencing the same behavior of the system:
**The system behaves nondeterministic sluggish**

- Light react sometimes delayed to command, somethimes commands are lost
- Switches behave the same sometimes I see delays on my openhab chanel event, somethimes they are even lost
- From within the Phoscon  when acting on idividual lights or groups the response is somethime delyaed of is not executed at all.

I am running deconz as a container. Switching between container always delivers a perfect running 2.23.2 and malfunction higher versions. I did this cycle multiple times, to make sure it is not one time shot.

### Steps to reproduce the behavior

Upgrade the docker deconz installation from 2.23.2 to a higher version.
For sure having a similar device landscape as me.
Manipulation of light over the REST API, or Phoscon.
e.g. turning on a group, then the group is not turning immediately on and the individual lights change state extremely asynchronous (1-2s) to each other

### Expected behavior

as in version 2.23.2:
the lights shall follow the command fast. the group members shall act together synchronously. The switch channel events shall fire with a small delay.

### Environment

- Host system: (Raspberry Pi 4/8GB
- Running method: community Docker container 
- Firmware version: 26720700
- deCONZ version : as described
- Device: ConBee II 
- Do you use an USB extension cable: yes
- ssd usb disk connected

### deCONZ Logs

[deconz.2.23.2.log](https://gist.github.com/lukicsl/875f723d0bff6bb35c3ccea0d26ec5ad)
[deconz.2.24.3.log](https://gist.github.com/lukicsl/a6d4097d225348d5954f7e1e4f2cdfe2)

**Comment by Mimiix** [comment] 2024-01-21 14:18
Hi

As this is not a bug as described in #5113, I am closing this issue.

Please continue on the forums until we can find a clear bug.

**Closed by Mimiix** 2024-01-21 14:18 UTC
Labels: Bug report
