### ISSUE TITLE
Aqara motion sensors not consistent

### ISSUE THREAD

**Issue by benblb** [dresden-elektronik/deconz-rest-plugin#5438] opened 2021-11-02 18:11 UTC
## Describe the bug
Occasionally an Aqara motion sensor will not detect motion. It normally fixes itself 30s - 1m later and then triggers which causes me to believe there is an issue with the Aqara sensor... however they were working perfectly before I upgraded my HA server and restored deCONZ so I suspect there may be a deCONZ problem. Additional context at bottom has more info. 

## Steps to reproduce the behavior
- Setup Aqara motion sensor
- Use sensor and note that sometimes it misses detection

Happens several times a day, around once every hour if I walk by. 

## Expected behavior
Motion sensor should always detect and notify deCONZ

## Screenshots
N/A and no errors in logs. 

## Environment
 - Host system: NAS (Chromebox running Debian 11)
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.12.06 / 8/19/2021
 - Device: ConBee II
 - Do you use an USB extension cable: yes, USB 2.0
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
Only weird thing I see in logs is "...(lumi.sensor_motion.aq2): disable presence" (happened before I copied recent logs)

`172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/css/themes/de-default/theme.min.css?a5231b= HTTP/1.1" 200 176173 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/language/languages.js?fb6b37= HTTP/1.1" 200 104397 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/library/js/snap.svg-min.js?0b6a0f= HTTP/1.1" 200 82489 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/library/js/jquery-min.js?0baf29= HTTP/1.1" 200 86687 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/library/js/underscore-min.js?16058b= HTTP/1.1" 200 16422 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/library/js/backbone-min.js?e2b7ab= HTTP/1.1" 200 23335 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/library/bootstrap/original/js/bootstrap.min.js?430a44= HTTP/1.1" 200 37102 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/js/global.js?a83a9a= HTTP/1.1" 200 86632 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:03 -0700] "GET /pwa/library/js/interact.min.js?11e1c8= HTTP/1.1" 200 62930 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:04 -0700] "GET /pwa/js/main.js?71310e= HTTP/1.1" 200 34859 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:04 -0700] "GET /pwa/css/themes/slate/theme.min.css?c653fe= HTTP/1.1" 200 168834 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:04 -0700] "GET /pwa/library/font/Lato/fonts/Lato-Regular.woff2 HTTP/1.1" 200 182917 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/library/font/Lato/latofonts.css?e08de6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:04 -0700] "GET /pwa/login.html?1635875884406= HTTP/1.1" 200 27127 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:04 -0700] "GET /pwa/js/login.js?e98ba5= HTTP/1.1" 200 19686 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/login.html?1635875884406" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:04 -0700] "GET /api/config?_=1635875884824 HTTP/1.1" 200 261 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:05 -0700] "GET /api/config?_=1635875885021 HTTP/1.1" 200 261 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:05 -0700] "GET /api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/api/config?_=1635875885055 HTTP/1.1" 403 140 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:06 -0700] "GET /api/config HTTP/1.1" 200 261 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/login.html?1635875884406" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - delight [02/Nov/2021:10:58:09 -0700] "POST /api/ HTTP/1.1" 200 55 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/login.html?1635875884406" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
10:58:09:986 created username: 6A8144CDBC, devicetype: Phoscon#B1664x1279
172.30.32.2 - - [02/Nov/2021:10:58:10 -0700] "GET /api/6A8144CDBC/groups HTTP/1.1" 200 1196 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/login.html?1635875884406" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:10 -0700] "GET /pwa/index.html?1629404819000=&gwid=00212EFFFF0552B5 HTTP/1.1" 200 113247 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/login.html?1635875884406" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:10 -0700] "GET /api/6A8144CDBC/config?_=1635875890573 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:10 -0700] "GET /api/6A8144CDBC/config?_=1635875890574 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:10 -0700] "GET /api/6A8144CDBC/groups?_=1635875890575 HTTP/1.1" 200 1358 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:11 -0700] "GET /api/6A8144CDBC/lights?_=1635875890576 HTTP/1.1" 200 1111 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
2021/11/02 10:58:11 [warn] 1076#1076: *40 an upstream response is buffered to a temporary file /var/lib/nginx/proxy/1/00/0000000001 while reading upstream, client: 172.30.32.2, server: _, request: "GET /pwa/library/font/Lato/fonts/Lato-Italic.woff2 HTTP/1.1", upstream: "http://127.0.0.1:40850/pwa/library/font/Lato/fonts/Lato-Italic.woff2", host: "ben-ha.duckdns.org", referrer: "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/library/font/Lato/latofonts.css?e08de6"
172.30.32.2 - - [02/Nov/2021:10:58:11 -0700] "GET /pwa/library/font/Lato/fonts/Lato-Italic.woff2 HTTP/1.1" 200 195893 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/library/font/Lato/latofonts.css?e08de6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:11 -0700] "GET /api/6A8144CDBC/sensors?_=1635875890577 HTTP/1.1" 200 6121 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:11 -0700] "GET /api/6A8144CDBC/config?_=1635875890578 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
10:58:11:683 New websocket 127.0.0.1:36636 (state: 3) 
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5 HTTP/1.1" 200 54364 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/index.html?1629404819000&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /websocket HTTP/1.1" 101 4 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
10:58:13:450 Websocket disconnected 127.0.0.1:36636, state: 0, close-code: 1000, reason: 
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /pwa/library/js/moment.js?69ab16= HTTP/1.1" 200 53382 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /pwa/css/settings-gateway2.css?cd002c= HTTP/1.1" 200 24128 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
2021/11/02 10:58:13 [warn] 1076#1076: *18 an upstream response is buffered to a temporary file /var/lib/nginx/proxy/2/00/0000000002 while reading upstream, client: 172.30.32.2, server: _, request: "GET /pwa/library/js/moment-timezone-with-data.js?e60811= HTTP/1.1", upstream: "http://127.0.0.1:40850/pwa/library/js/moment-timezone-with-data.js?e60811=", host: "ben-ha.duckdns.org", referrer: "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5"
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /pwa/library/js/xstate.interpreter.js?567382= HTTP/1.1" 200 39765 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /pwa/library/js/xstate.js?218fe0= HTTP/1.1" 200 40359 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:13 -0700] "GET /pwa/library/js/moment-timezone-with-data.js?e60811= HTTP/1.1" 200 929590 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:14 -0700] "GET /api/6A8144CDBC/config?_=1635875893877 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:14 -0700] "GET /api/6A8144CDBC/config?_=1635875893879 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:14 -0700] "GET /api/6A8144CDBC/config?_=1635875893878 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
10:58:15:011 New websocket 127.0.0.1:36688 (state: 3) 
172.30.32.2 - - [02/Nov/2021:10:58:19 -0700] "GET /api/6A8144CDBC/config?_=1635875893880 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:19 -0700] "GET /api/6A8144CDBC/config?_=1635875893881 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:24 -0700] "GET /api/6A8144CDBC/config?_=1635875893882 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:29 -0700] "GET /api/6A8144CDBC/config?_=1635875893883 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:34 -0700] "GET /api/6A8144CDBC/config?_=1635875893884 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:39 -0700] "GET /api/6A8144CDBC/config?_=1635875893885 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:44 -0700] "GET /api/6A8144CDBC/config?_=1635875893886 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:10:58:49 -0700] "GET /api/6A8144CDBC/config?_=1635875893887 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
10:58:57:230 Device TTL 2698 s flags: 0x7
10:59:57:228 Device TTL 2638 s flags: 0x7
11:00:13:223 GW firmware version: 0x26660700
11:00:13:224 GW firmware version is up to date: 0x26660700
11:00:57:228 Device TTL 2578 s flags: 0x7
11:01:57:229 Device TTL 2517 s flags: 0x7
11:02:57:229 Device TTL 2457 s flags: 0x7
11:03:57:230 Device TTL 2397 s flags: 0x7
11:03:58:874 Announced to internet http://dresden-light.appspot.com/discover
11:04:13:223 GW firmware version: 0x26660700
11:04:13:224 GW firmware version is up to date: 0x26660700
11:04:57:229 Device TTL 2337 s flags: 0x7
11:05:22:099 ZCL attribute report 0x00158D0002528ECB for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
11:05:22:100 0x00158D0002528ECB extract Xiaomi special attribute 0xFF01
11:05:22:100 	01 battery 3005 (0x0BBD)
11:05:22:100 	03 Device temperature 25 °C
11:05:22:101 	04 unknown 17320 (0x43A8)
11:05:22:101 	05 RSSI dB (?) 7 (0x0007)
11:05:22:101 	06 LQI (?) 4294967296 (0x0100000000)
11:05:22:101 	0a Parent NWK 0 (0x0000)
11:05:22:102 	64 on/off 0
11:05:57:229 Device TTL 2277 s flags: 0x7
11:06:57:229 Device TTL 2217 s flags: 0x7
172.30.32.2 - - [02/Nov/2021:11:07:19 -0700] "GET /api/6A8144CDBC/config?_=1635875893888 HTTP/1.1" 200 8209 "https://ben-ha.duckdns.org/api/hassio_ingress/fLbYfDtvW92qdaMrr9yTPRD0QaqY2DmFA4A4zkOmNHQ/pwa/settings-gateway2.html?_v=31e61bb47af6840b284b99615a0d9eff80716958,10,2,10&gwid=00212EFFFF0552B5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
172.30.32.2 - - [02/Nov/2021:11:07:19 -0700] "GET /websocket HTTP/1.1" 101 9717 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
11:07:19:988 Websocket disconnected 127.0.0.1:36688, state: 0, close-code: 1000, reason: 
127.0.0.1: new handler Process
localhost - - [02/Nov/2021 11:07:30] "GET //websockify HTTP/1.1" 101 -
localhost - - [02/Nov/2021 11:07:30] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [02/Nov/2021 11:07:30] 127.0.0.1: Version hybi-13, base64: 'False'
localhost - - [02/Nov/2021 11:07:30] 127.0.0.1: Path: '//websockify'
localhost - - [02/Nov/2021 11:07:30] connecting to: 127.0.0.1:5900
11:07:34:223 Skip idle timer callback, too early: elapsed 942 msec
11:07:57:229 Device TTL 2157 s flags: 0x7
11:08:13:224 GW firmware version: 0x26660700
11:08:13:225 GW firmware version is up to date: 0x26660700
11:08:50:217 MS CORE_APS_IND (processPacked:966) took 0 ms
11:08:55:971 MS CORE_APS_IND (processPacked:966) took 0 ms
11:08:59:737 MS CORE_APS_IND (processPacked:966) took 0 ms
11:09:02:616 MS CORE_APS_IND (processPacked:966) took 0 ms
11:09:57:237 Device TTL 2037 s flags: 0x7
11:10:57:228 Device TTL 1977 s flags: 0x7
11:11:57:228 Device TTL 1917 s flags: 0x7
11:12:13:222 GW firmware version: 0x26660700
11:12:13:223 GW firmware version is up to date: 0x26660700
11:12:57:228 Device TTL 1857 s flags: 0x7
11:13:57:228 Device TTL 1797 s flags: 0x7
11:13:58:964 Announced to internet http://dresden-light.appspot.com/discover`

## Additional context
Troubleshooting has been completed.

- New batteries have been put into the 3 problem motion sensors
- Disabled all powered devices and re-paired motion sensors to ensure they are not using a router (all directly connected to Conbee II)
- Rebooted host system
- USB extension added (then another reboot)
- Verified nearby WiFi is not conflicting with Zigbee channel 25 (in use)

I do want to note that everything was working perfectly when I was running an "unsupported" Home Assistant install on Gallium OS (now Debian 11). I accidentally bricked that "NUC", so I swapped to one that is identical in every way *except* I upgraded the 16GB SSD to 128GB and this one has 8GB of RAM instead of 4. 
The old server and this went in the same spot in my closet and I restored my HA backup including deCONZ. 

It's possible this is not a deCONZ issue, but nothing had changed with the Aqara sensors before the problems began.

**Comment by Mimiix** [comment] 2021-11-02 19:09
Hi there,

As this is not a bug as described in #5113, i am closing this issue. Please use the forums for help/setup questions.

Kind regards,

**Closed by Mimiix** 2021-11-02 19:09 UTC
Labels: Bug report

**Comment by benblb** [comment] 2021-11-02 19:23
I am aware of the forums @Mimiix. How do you know for sure this is not a bug?

**Comment by Mimiix** [comment] 2021-11-02 20:37
For the same reason we can't be sure its a user specific issue: We want github to have issues that are 100% provable bugs.

**Comment by benblb** [comment] 2021-11-02 20:47
Ah, that's fair. Thanks very much.
