### ISSUE TITLE
Lidl/Silvercrest doorbell

### ISSUE THREAD

**Issue by palletodap** [dresden-elektronik/deconz-rest-plugin#4344] opened 2021-02-04 19:38 UTC
## Device

- Product name: Lidl/Silvercrest Doorbell
- Manufacturer: _TZ1800_ladpngdx
- Model identifier: TS0211
- Device type : Please remove all unrelated device types. 
  - Remote

## Screenshots

Screenshots taken from #4258 - closed becuase of no template

<img width="882" alt="105479279-9179c280-5ca4-11eb-98a2-01b62f75a280" src="https://user-images.githubusercontent.com/65086663/106945893-af293c00-6728-11eb-9103-85de2068ba33.png">
<img width="266" alt="105479312-976fa380-5ca4-11eb-954a-d699e05cb4b7" src="https://user-images.githubusercontent.com/65086663/106945896-afc1d280-6728-11eb-871c-9c1b00ebea37.png">

**Comment by palletodap** [comment] 2021-02-04 20:03
Just checked the screenshots with my own deconz, and all info is the same for me.

**Comment by SwoopX** [comment] 2021-02-04 22:05
Duplicate of #4260

**Closed by SwoopX** 2021-02-04 22:05 UTC
Labels: Device Request, Duplicate
