### ISSUE TITLE
Cannot set opening % on Bticino K4027C shutter switch

### ISSUE THREAD

**Issue by mariomaz87** [dresden-elektronik/deconz-rest-plugin#7388] opened 2023-11-27 08:58 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hi, I recently moved my K4027C shutter switch from Bticino Gateway to Deconz. I can control the device as expected only on Deconz Gui. From Phoscon or Home Assistant I can fully close or fully open the device, I can stop the movement and it will report the correct percentage, but I can't set it a to a specific % (as I can in Deconz Gui). The firmwares of the Bticino devices is 0x003643FF. Can you help me? Thanks!
I searched for similar issues but I couldn't find a viable solution, some are also mentioning issues with inverted controls but open and close work as expected in my case.

### Steps to reproduce the behavior

Set a % of opening on Home Assistant or Phoscon does not do anything. I can however fully open or fully close it (using the open\close buttons or the shutter %). 

### Expected behavior

In Deconz Gui I can issue the set to % command and it works as expected.

### Environment

- Host system: Raspberry Pi
- Running method: Raspbian
- Firmware version: 26780700
- deCONZ version (not Home assistant Addon version!): 2.24.2
- Device: ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? If so: Which? External HDD and external US card reader

**Comment by Mimiix** [comment] 2023-11-27 09:13
Hi,

Looks like this device is not properly supported in that case.

I recommend opening a new Device request so a DDF can be made, as there seems to be none yet.

As this is clearly not a bug, i am closing it.

Kind regards,

**Closed by Mimiix** 2023-11-27 09:13 UTC
Labels: Bug report
