### ISSUE TITLE
Sonoff ZBmini state return

### ISSUE THREAD

**Issue by nonome1** [dresden-elektronik/deconz-rest-plugin#4317] opened 2021-02-01 08:55 UTC
## Describe the bug
when the module is turned ON, the lamp comes on and there is no status feedback.  therefore it is no longer possible to switch off the lamp when switching to the OFF state.  to turn off the lamp, press the button on the module
  Describe the issue you are experiencing here to communicate to the
  maintainers. Tell us what you were trying to do and what happened.
In Homeassistant with the switch.turn.on and switch.turn.off service I can turn the light off and on but I have no status feedback
  Help us understand the issue by providing valuable context.
-->

## Environment

 - Host system: ( / PC /)
 - Running method: ( / Home Assistent deCONZ Add-on )
 - Firmware version: 26660700
 - deCONZ version: (2.07.01)
 - Device: (ConBee II )
 - Do you use an USB extension cable: (yes -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment] 2021-02-01 08:57
Hi,

Duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4016

Closing this one.

**Closed by Mimiix** 2021-02-01 08:57 UTC
Labels: Bug report
