### ISSUE TITLE
Aqara T1 with neutral wire and consuming report DLKZMK11LM 

### ISSUE THREAD

**Issue by MiAutomations** [dresden-elektronik/deconz-rest-plugin#3785] opened 2020-11-30 22:15 UTC
Hello Team this device is not reporting the measuring data, the device is detected and the switch is working as suppose.
Can you please add the measuring feature to this device? Thank you for your support   

- Product name: Aqara Single Switch Module T1 (With Neutral)
- Manufacturer: Lumi
- Model identifier: lumi.switch.n0agl1
- Device type : 
  - Switch

## Screenshots

![Image 001](https://user-images.githubusercontent.com/47602733/100671844-0988d380-3359-11eb-8914-cddd534b75d7.png)
![Image 002](https://user-images.githubusercontent.com/47602733/100671875-14436880-3359-11eb-8106-1c5eec55cd24.png)
![Image 003](https://user-images.githubusercontent.com/47602733/100671886-17d6ef80-3359-11eb-95be-e18b544d4e85.png)

**Comment by SwoopX** [comment] 2020-11-30 22:27
Can you please set up the bindings for simple metering and electrical measurement cluster as described here?

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-bind-server-clusters

Then, please turn the switch on and see if values are generated at all. I don't really trust the exposed clusters by the device, we've seen too many non-working over time. I'd like to ensure that first.

**Comment by MiAutomations** [comment] 2020-11-30 23:31
I executed the binding as described and the values keep in 0 

Please let me know if you need any more info from my side, and thank you for your support

**Comment by MiAutomations** [comment] 2020-12-15 09:36
Is there any update in this device? Do you need any further information?

**Comment by SwoopX** [comment] 2020-12-15 10:30
Sorry, this one drowned somehow. Can you double check the `Analog Input (Basic)` clusters? The values of interest are typically to be found in attribute 0x0055 present value.

Please also do me the favour to right click on the light and read the simple descriptors again. Would be interested to see if electrocal measurement and simple metering clusters disappear again.

**Comment by flopp999** [comment] 2020-12-15 19:20
check this issue #3380

**Comment by MiAutomations** [comment] 2020-12-18 09:04
I just have installed the new update for the plugin  deCONZ 6.6.1 available, and I still without data from the electricity report .
And I have removed the device and re added in order to verify ... Please let me know if you need more info from my side.
Thank you and best regards

**Comment by MiAutomations** [comment] 2020-12-22 10:04
> lso do me the favour to right click on the light and read the simple descriptors again.

Hello and once again thank you for your support 

Please let me know if is this that you need/request 

![image](https://user-images.githubusercontent.com/47602733/102876450-1de25c80-443d-11eb-8786-d9ea3f75d8eb.png)

**Comment by Mimiix** [comment] 2020-12-22 14:02
@MiAutomations This seems to be a duplicate of #3380. Closing this one, please continue there.

**Closed by Mimiix** 2020-12-22 14:02 UTC
Labels: Device Request

**Comment by MiAutomations** [comment] 2020-12-22 15:48
Ok and regarding the info that I share? Is also need to be posted in the open topic?
