### ISSUE TITLE
Deconz 2.05.52 lost Vimar/Hue Tap switches

### ISSUE THREAD

**Issue by rafuz** [dresden-elektronik/deconz-rest-plugin#1060] opened 2018-12-18 21:50 UTC
Installing the last version I have completely lost my switches again (as in 2.05.50), so I am stuck on 2.05.49
I only see them as groups and no output in the rest interface.
I am using the Vimar switches that I linked in the issue #1020 that should be seen as Hue Tap.

![schermata 2018-12-18 alle 22 39 32](https://user-images.githubusercontent.com/22271829/50184643-ef918a00-0315-11e9-912e-c3e5b6c513a5.png)

**Comment by manup** [comment] 2018-12-19 13:34
Damn the group device membership check was not complete.

Fixed already in the online version [http://dresden-elektronik.de/pwa](http://dresden-elektronik.de/pwa?19-12) and will be part of 2.05.53.

**Note:** This is only shown for former added switches, newly added switches won't show up on the main page.

ZigBee Green Power (ZGP) devices like Hue Tap, Vimar and Illumra don't control a own group directly, the group was added in the past by deCONZ with some default rules.

This was before the Switch Editor existed.

With recent versions (.51 and .52):
* No group and default rules will be created
* Instead the switch can control one or more normal light groups
* Also a light group can be controlled by multiple switches

We publish the related documentation very soon, hope it helps.

![image](https://user-images.githubusercontent.com/383386/50223061-6cfede00-039a-11e9-838a-0100b30da4ab.png)

With the Switch Editor custom actions can be assigned to the buttons.

**Comment by rafuz** [comment] 2018-12-19 14:17
Fine, I will check as soon Marthoc (https://github.com/marthoc/docker-deconz) bumps the version.

So to get rid of the groups I have to rejoin the switches?

**Comment by manup** [comment] 2018-12-19 14:20
> So to get rid of the groups I have to rejoin the switches?

Or just delete the groups, but only do this if they aren't used or have lights assigned.

**Comment by rafuz** [comment] 2018-12-22 00:11
I have checked the online version and I see all the vimar switches as philips tap switches. This means that when I update my local PWA it will be the same?

**Comment by manup** [comment] 2018-12-22 09:19
Yes, basically the local version is just a copy which is updated with each release.

I've seen that the switches support more features like dimming. Looking forward to support these with a own implementation in early 2019. However the `buttonevents` and `modelid` might be different from the Hue tap.

**Comment by rafuz** [comment] 2018-12-22 11:55
To be honest I am using them only capturing their buttonevents in the REST interface for activating lights in Home Assistant. In deconz their buttonevents do not match Philips Tap of Friends of Hue switches so they need a custom integration. 
Anyway if you will implement them properly it will be very nice, they also cost less than their Friend of Hue counterparts.

**Comment by manup** [comment] 2018-12-22 12:04
>In deconz their buttonevents do not match Philips Tap of Friends of Hue switches so they need a custom integration.

Yes I guess so, do you know the button events for the Friends of Hue switches used by the Hue bridge? The Philips documentation hasn't been updated yet.

Digging deeper into ZGP land, I've just sniffed the ZigBee traffic of the Hue bridge when a Tap is paired. Since the Hue bulbs (and likely other ZigBee 3.0 devices) support ZigBee Green Power, the Hue bridge does setup them so they repeat the Hue Tap messages through the mesh.

Currently deCONZ doesn't support this, so the ZGP switches need to be in signal range of the gateway. I'm planning to implement the ZGP commissioning via mesh soon, so the switches can be placed anywhere near the mesh.

**Comment by rafuz** [comment] 2018-12-22 12:13
> Yes I guess so, do you know the button events for the Friends of Hue switches used by the Hue bridge? The Philips documentation hasn't been updated yet.

No, unfortunately I don't know the buttonevents for Friends of Hue (Vimar 03906). I can only find the buttonevents for the generic ones I have (Vimar 03905)

Currently I have to put Deconz in the center of my house to avoid to loose button presses from these wall switches. I have some smart plugs that could route that events in the mesh so it is a much needed feature.

**Comment by manup** [comment] 2018-12-22 13:35
>I can only find the buttonevents for the generic ones I have (Vimar 03905)

Seems to use the PTM-215ZE-DA module.

https://www.zigbee.org/zigbee-products-2/#zigbeecertifiedproducts/productdetails3/58a567c06b774f4349e1fe42/

**Comment by rafuz** [comment] 2018-12-22 13:53
yes, it is exactly this

**Comment by rafuz** [comment] 2019-01-08 19:59
Just update to the latest phoscon 2.05.54 and I have lost again all my Vimar switches again :(
Last version working is still 2.05.49. The strange thing is that the online version of PWA seems to work.

[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2738253/deconz.log)

![schermata 2019-01-08 alle 20 46 32](https://user-images.githubusercontent.com/22271829/50855265-a5854c80-1387-11e9-9941-ac3fed5f4cba.png)

![schermata 2019-01-08 alle 20 46 50](https://user-images.githubusercontent.com/22271829/50855273-aa4a0080-1387-11e9-8884-6f1718b1b62e.png)

![schermata 2019-01-08 alle 20 47 03](https://user-images.githubusercontent.com/22271829/50855283-afa74b00-1387-11e9-8993-a4750695bbd4.png)

**Comment by manup** [comment] 2019-01-09 12:40
:/ I don't understand why this happens, can you please send me a backup to mpi@dresden-elektronik.de 
I'll try to load the config here and look why they don't show up.

**Comment by rafuz** [comment] 2019-01-09 13:55
I will send you the current backup (2.05.49) this evening.

**Comment by manup** [comment] 2019-01-14 08:46
Hi, yes I've checked the file the switches are there and all have a assigned group. So from this side it looks good. The Phoscon App should already check exactly this to show the switches on the main page.

I wonder why they are missing on the *Menu > Devices > Switches* page. Here I need to do some more tests with your backup file. But it should be fixed in 2.05.55 if I can find anything.

**Comment by rafuz** [comment] 2019-01-14 09:20
Not only they are missing in the Menu > Devices > Switches page but I also do not get any output from them in the REST interface. If I can't get output from REST when I operate the switches I can't use them to fire events in HomeAssistant.

**Comment by manup** [comment] 2019-01-14 09:49
Found the cause, the commit 280cceacbf5f9d2c2bfbaa4527db1dfee063e2f8 prevents ZGPSwitch resources from loading.

**Comment by rafuz** [comment] 2019-01-14 09:55
Great to hear :-)
Will it be fixed in 2.05.55?

**Comment by manup** [comment] 2019-01-14 09:55
Yes :)

**Comment by rafuz** [comment] 2019-01-14 10:02
Good, when I will report back when I will be able to test it.

**Comment by rafuz** [comment] 2019-01-15 23:55
I can confirm it is fixed in 2.05.55, this can be closed.
I hope for future support for Vimar ZGPSwitches :-)

**Closed** 2019-01-15 23:56 UTC

**Comment by manup** [comment] 2019-01-16 07:38
>I can confirm it is fixed in 2.05.55, this can be closed.
I hope for future support for Vimar ZGPSwitches :-)

Cool, yes the Friends of Hue switches will be fully supported. :)
