### ISSUE TITLE
IKEA TRÅDFRI Remote left / right button (<>) without funktion

### ISSUE THREAD

**Issue by TobiasH2010** [dresden-elektronik/deconz-rest-plugin#4815] opened 2021-04-26 12:48 UTC
## Describe the bug
IKEA TRÅDFRI Fernbedienung lässt sich nicht richtig anlernen.

Das System und die Konfiguration läuft eigentlich super, ich hatte auch schon eine IKEA TRÅDFRI Fernbedienung (Rund, 5 Tasten) seit langem in Betrieb ohne Probleme. Jetzt wollte ich eine weitere anlernen und bekomme jedoch nur 3 Tasten in IoBroker angezeigt. Die rechts links Taste wird nicht erkannt. Schon x mal gelöscht und neu angelernt ohne Erfolg. Auch mit der Beta Oberfläche funktioniert es nicht.

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

Fernbedienung wie beschrieben anlernen

## Expected behavior

  Alle 5 Tasten sollten erkannt werden. Teilweise auch mit langem Tastendruck

## Screenshots

 könne bei bedarf erstellt werden

## Environment

 - Host system: MSI Cubi 3 Silent mit ConBee II
 - Running method: Debian Headless in Proxmox
 - Firmware version: 26680700
 - deCONZ version: 2.11.01 / 14.3.2021
 - Device: ConBee II
 - Do you use an USB extension cable: yes

**Comment by jan666** [comment] 2021-04-26 12:54
Try removing the battery for 10 seconds and re-insert it. I can't remember if I had the same issue but it fixed something related to the <> buttons for me. Just give it a try :)

**Comment by TobiasH2010** [comment] 2021-04-26 12:58
I've tried it several times without effect. The system also will not recognize a long press of the middle button... At the moment it won't even show the firmware of the remote. But I checked before and it was the latest

**Comment by Mimiix** [comment] 2021-04-26 17:13
Hi,

Can you please translate to English? This is a English git.

**Comment by Verteo** [comment] 2021-04-26 18:23
I have the same problem with the Tradfri Remote. The < and > buttons no longer work with 2.11.01, the button presses - neither short or long - show up in the logs. They were still working with 2.11.00.

**Comment by ebaauw** [comment] 2021-04-26 18:44
I can confirm.  The left and right buttons of the STYRBAR (Remote Control N2) don't work either.

**Comment by Mimiix** [comment] 2021-04-26 18:50
@ebaauw please remain from adding labels. We have guidelines for issues and one of them is that they should be in English.

**Comment by ebaauw** [comment] 2021-04-26 18:51
Ok you go fix it

**Comment by Mimiix** [comment] 2021-04-26 19:48
@ebaauw I think it's for the best if we solve the issue you have with me in discord.

@TobiasH2010 my first request is the same: please translate your issue to English.

**Comment by jazza1234567** [comment] 2021-04-27 07:55
have the same issues, I am more than glad to provide any information needed to help out, Just need to be told what I can provide to help team :)

**Comment by jazza1234567** [comment] 2021-04-27 09:28
## Describe the bug


## Steps to reproduce the behavior


## Expected behavior


## Screenshots


## Environment


 - Host system: NAS
 - Running method: Marthoc Docker container but this links through to my home assistant platform
 - Firmware version: 26660700
 - deCONZ version: 2.11.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs


## Additional context

**Comment by Mimiix** [comment] 2021-04-28 07:31
@jazza1234567 It's a nice gesture, but i'd rather have the opening post from @TobiasH2010 to be in english...

**Comment by jazza1234567** [comment] 2021-04-28 07:36
> @jazza1234567 It's a nice gesture, but i'd rather have the opening post from @TobiasH2010 to be in english...

As much as it is a gesture, its also due to self-interest - because it will be handy for me to have fixed 😂

**Comment by Mimiix** [comment] 2021-04-28 07:41
@jazza1234567 Feel free to open a seperate issue and copy paste your report in there. I'll close this one then.

**Comment by jazza1234567** [comment] 2021-04-28 07:55
> @jazza1234567 Feel free to open a seperate issue and copy paste your report in there. I'll close this one then.

Done 🙂 ill be around for a few hours should you need any troubleshooting on my end

**Comment by Mimiix** [comment] 2021-04-28 08:18
Closing this one, moving on in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4821.

**Closed by Mimiix** 2021-04-28 08:18 UTC
Labels: Incomplete issue, User Question, Waiting on Info
