### ISSUE TITLE
RaspBee not recognized on RPi3 Bullseye

### ISSUE THREAD

**Issue by brown78** [dresden-elektronik/deconz-rest-plugin#7515] opened 2024-01-05 09:34 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I have a Raspberry 3 with RaspBee on it. With an SD-Card flashed with Stretch all works pretty well. I set up a second SD-Card with Bullseye and installed deCONZ-latest-beta.deb - with the latest stable the deCONZ-gui didn't work.
The GUI now works but can't connect to the RaspBee. In the /boot/config.txt I added "dtoverlay=miniuart-bt" and Bluetooth is off after a reboot. Still the RaspBee is not found. The command "GCFFlasher_internal l" showed that no device was found. Is there something more I can try to make it work?

### Steps to reproduce the behavior

Boot Raspberry
deCONZ-GUI is starting
No connection to RaspBee is established

### Expected behavior

Connecting to RaspBee

### Environment

- Host system: (Raspberry Pi 3B)
- Running method: (Raspbian Bullseye)
- Firmware version: (26350500)
- deCONZ version (not Home assistant Addon version!): (2.05.67)
- Device: (RaspBee I)
- Do you use an USB extension cable: (no)
- Is there any other USB or serial devices connected to the ho system? If so: Which? 433MHz Dongle, HMMOD on USBtoI2C

**Comment by Mimiix** [comment] 2024-01-05 09:42
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

Please open a forum post for help.

Closing.

**Closed by Mimiix** 2024-01-05 09:42 UTC
Labels: Bug report
