### ISSUE TITLE
DDF inheritance broken, custom DDF partially gets overwritten

### ISSUE THREAD

**Issue by bluemoehre** [dresden-elektronik/deconz-rest-plugin#7954] opened 2024-10-01 18:26 UTC
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

My custom DDF gets partially overruled by a generic item definition, causing wrong values being displayed.
Actually this was hard to find, since the Product Name of my custom DDF is displayed correctly, but the value calculation comes from the generic files.

In my case from this one:
[/devices/generic/items/state_power_item.json](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/2b890eeebe6d998331415adbb955bb7cb8956022/devices/generic/items/state_power_item.json#L4)

### Steps to reproduce the behavior

I have a deCONZ Docker including these files:

Custom `/opt/deCONZ/devices/lumi.plug.maeu01.json` _(matches >= v42)_:
<details>
<summary>JSON</summary>

```json
{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.plug.maeu01",
  "vendor": "Xiaomi Aqara v45",
  "product": "Smart plug (SP-EUC01)",
  "sleeper": false,
  "status": "Gold",
  "comment": "DDF for device firmwares at least at 0.0.0_0045, paired with xBee I fw 0x26400500 / xBee II fw 0x266f0700 and above",
  "matchexpr": "(R.endpoints.indexOf(0x15) === -1) && (R.endpoints.indexOf(0x1F) === -1);",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": ["$address.ext", "0x01"],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "at": "0x00F7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 10
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": ["$address.ext", "0x15", "0x000c"],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x15",
        "in": ["0x000C"]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "at": "0x00F7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/temperature"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 10,
          "read": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 0,
            "eval": "if (Attr.val != -32768 && Attr.val != 32768) { Item.val = Attr.val / 10; }"
          }
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": ["$address.ext", "0x01", "0x0702"],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": ["0x0000", "0x0702"]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "at": "0x00F7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/temperature"
        },
        {
          "name": "state/consumption",
          "description": "The measured consumption (in Wh).",
          "refresh.interval": 300,
          "read": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "eval": "Item.val = Attr.val / 1000"
          },
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

</details>

Default from deCONZ `/usr/share/deCONZ/devices/xiaomi/xiaomi_sp-euc01_smart_plug.json` _(matches <= v41)_

<details>
<summary>JSON</summary>

```json
{
  "schema": "devcap1.schema.json",
  "uuid": "711cfee9-6235-4db7-be0e-52b5a976a231",
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.plug.maeu01",
  "vendor": "Xiaomi Aqara",
  "product": "Smart plug (SP-EUC01)",
  "sleeper": false,
  "status": "Gold",
  "comment": "DDF for device firmwares at least above 0.0.0_0022, paired with xBee I fw 0x26400500 / xBee II fw 0x266f0700 and above",
  "matchexpr": "(R.endpoints.indexOf(0x15) !== -1) && (R.endpoints.indexOf(0x1F) !== -1);",
  "md:known_issues": [ "xiaomi_known_issues_firmware_update.md" ],
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "at": "0x00F7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x15",
        "0x000C"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x15",
        "in": [
          "0x000C"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "at": "0x00F7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/temperature"
        },
        {
          "name": "state/current",
          "parse": {
            "at": "0x00F7",
            "eval": "Item.val = Math.round(Attr.val);",
            "fn": "xiaomi:special",
            "idx": "0x97"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 10,
          "read": {
            "at": "0x0055",
            "cl": "0x000C",
            "ep": 21,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0055",
            "cl": "0x000C",
            "ep": 21,
            "eval": "Item.val = Math.round(Attr.val);"
          }
        },
        {
          "name": "state/voltage",
          "parse": {
            "at": "0x00F7",
            "eval": "Item.val = Math.round(Attr.val / 10);",
            "fn": "xiaomi:special",
            "idx": "0x96"
          },
          "read": {
            "fn": "none"
          }
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x1F",
        "0x000C"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x1F",
        "in": [
          "0x000C"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "at": "0x00F7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/temperature"
        },
        {
          "name": "state/consumption",
          "refresh.interval": 300,
          "read": {
            "at": "0x0055",
            "cl": "0x000C",
            "ep": 31,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0055",
            "cl": "0x000C",
            "ep": 31,
            "eval": "Item.val = Math.round(Attr.val * 1000);"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

</details>

### Expected behavior

My custom DDF is loaded for a v45 device and all custom definitions take place over the generic ones.
As a final result all power values should be divided by 10.

### Screenshots

![image](https://github.com/user-attachments/assets/9b14fe6a-ec73-4a45-885d-37f94d9bebe9)

### Environment

- Host system: PC / Ubuntu
- Running method: deconz-docker container
- Firmware version: 0x26780700
- deCONZ version (not Home assistant Addon version!): 2.28.1
- Device: ConBee II & RaspBee II
- Do you use an USB extension cable: no
- Is there any other USB or serial devices connected to the host system? no

### Additional context

I can also double-check this behavior by changing the contents of `/devices/generic/items/state_power_item.json`.
Just change the corresponding line to `"eval": "Item.val = 999;"` in that file. 

After hot-reloading the DDF this value is immediately applied.

**Comment by SwoopX** [comment] 2024-10-01 20:42
Hi,

thanks for taking the effort, but unfortunately I have to say there's no notable bug taking the somehow limited information and log data into account. The highlighted sensor in the log is not part of any DDF mentioned here and hence, a DDF change has no notable effect. However, changing the generic item has an effect, as the sensor obviously used the default item definition.

On a side note, the device is incorrectly set up and is apparently exposing or using clusters it is not supposed to use (0x0b04). The continued usage of such clusters is technically not a bug, but as I learned intended behavior. I highlighted that earlier already, as I personally do not fully agree with those mechanics and observed some nonsense behavior of other devices under unfavorable conditions.

**Comment by bluemoehre** [comment] 2024-10-02 12:29
@SwoopX you have seen the device name in DDF editor as well as the path of the DDF in use?

**Comment by SwoopX** [comment] 2024-10-02 18:06
@bluemoehre yes, I've indeed seen what you mean and understand what you mean in your previous post. And yes, your understanding is correct: the shown DDF is the active one. I haven't said anything different up there, have I? 🤔 

Not sure, but maybe you missed my key sentence above, or mis-interpreted it?

> The highlighted sensor in the log is not part of any DDF mentioned here and hence, a DDF change has no notable effect.

**Comment by SwoopX** [comment] 2024-10-03 12:21
Yes, you are correct.

Happy to elaborate a bit. So, as you might have seen, each sensor defined in a DDF gets its parent cluster assigned in the `uuid`, which is a of course also part of the debug logs. Your referenced DDFs above do not hold the designated and highlighted example cluster `0x0b04`, concluding the sensor is not coming from or considered by any DDF.

```"type": "$TYPE_LIGHT_LEVEL_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0400"
      ]
```

Now, there's apparently a legacy sensor `0x0b04` which got activated by the code and presumably fed by forced data pollings. This sensor could have been created either before a DDF was available or due to an inappropriate pairing.

The real kicker here is that subdevices or sensors a device is comprised of, a smart plug in your case, are not marked holistically with DDF support, but individually. This detail leads to the fact that a non DDF supported sensor gets a) loaded and b) fed with data and have the DDF support guards fail, if I recall the respective spot in the code correctly. Technically, everything's in order here.

As mentioned earlier, I experienced the very same while adding support for the Aqara socket outlet.

**Comment by bluemoehre** [comment] 2024-10-03 12:46
> Your referenced DDFs above do not hold the designated and highlighted example cluster 0x0b04, [...]

Mmh, but my custom DDF (lumi.plug.maeu01.json) does hold the cluster in line 124 !?

Maybe my workflow of creating the custom DDF was wrong this time?

- I re-added the device after firmware upgrade
- no DDF was assigned anymore
- I force-read all descriptors / endpoints
- then I opened the DDF editor, which already contained some autogenerated Draft
- I compared the config the the other plugs still having old firmware with that new one
- then just removed entries which had no cluster or endpoint matches anymore

**Comment by SwoopX** [comment] 2024-10-03 13:07
> Mmh, but my custom DDF (lumi.plug.maeu01.json) does hold the cluster in line 124 !?

That is a resource item, not a subdevice and therefore irrelevant. The cluster in the light/sensor uid determines when to react, not in the resource item.

As we're not discussing a bug here, I'm closing the issue now. Let's jump over to the forum for finding out what might have happened.

**Closed by SwoopX** 2024-10-03 13:07 UTC
Labels: Bug report
